/* You can edit. 
   But this file will be translated to .mk,
   and the .mk in turn can be translated back to an equivalent file, without comments, reordered, to untangle the #ifdef structure.
 */

#ifndef __SMP8734R1_H__
#define __SMP8734R1_H__ 1

#include "rmchip_common.h"

#define AD_BORDER 0x800ea2f0
#define AD_CRC32_TAB 0x800e9d2c
#define AD_HEAP_MALLOC 0x800e8144
#define AUDIO_DM_SIZE 0xf000
#define AUDIO_PM_SIZE 0x8000
#define CORTEX_TARGET_FASTMODEL 6
#define CORTEX_TARGET_PALLADIUM 4
#define CORTEX_TARGET_PANDA 2
#define CORTEX_TARGET_SIGMA_SILICON 0
#define CORTEX_TARGET_SIMU 1
#define CORTEX_TARGET_TEGRA2 3
#define CORTEX_TARGET_ZEBU 5
#define DEMUX_DM_SIZE 0x8000
#define DEMUX_PM_SIZE 0x8000
#define FG_SIZE 0x5000
#define IOSVA_TEXT 0xddc00000
#define LOG2_IOS 0x15
#define MAIN_MIXER_CHANNEL_COUNT 8
#define MPEG_DM_SIZE 0x3000
#define MPEG_PM_SIZE 0x4000
#define H265_PM_SIZE 0x6000
#define RMCHIP_AUDIO_ENGINE_COUNT 1
#undef RMCHIP_AUDIO_ENGINE_VERSION
#define RMCHIP_AUDIO_ENGINE_VERSION 2
#define RMCHIP_CPU_ARCH 0x3e8
#define RMCHIP_DEMUX_ENGINE_COUNT 1
#define RMCHIP_DISPLAY_BLOCK_VERSION 2
#define RMCHIP_DISPLAY_DFE_VERSION 2
#define RMCHIP_DISPLAY_HAS_VIDSRC1_PSO 1
#define RMCHIP_BVP_DISPLAY_VERSION 3     // DFD 0,1,2,4,11 support 10 bit decompression needed for H265
#define RMCHIP_DRAM_CONTROLLER_COUNT 2
#define RMCHIP_GPU_ARCH 0x7d2
#define RMCHIP_L2_CACHE_PRESENT 1
#define RMCHIP_OTP_PRESENT 1
#define RMCHIP_REVISION 1
#define RMCHIP_VIDEO_ENGINE_COUNT 2
#define RMFEATURE_HAS_VIDEO_ENGINE_1 1
#define RMCHIP_VIDEO_ENGINE_H265_INDEX 1    // index of video engine that supports only H265
#define RMCHIP_VIDEO_ENGINE_VERSION 11      // version of video engine supporting legacy codecs
#define RMCHIP_VIDEO_ENGINE_H265_VERSION 12 // version of video engine supporting only H265
#define RMFEATURE_CPUSPI_S_BIT_IS_BUSY 1
#define RMFEATURE_DISPLAY_HAS_ACE_RGB_SUPPORT 1
#define RMFEATURE_DISPLAY_HAS_FIRMWARE_FILMMODE_DETECT 1
#define RMFEATURE_DemuxEngine_HAS_C2_CIPHER 1
#define RMFEATURE_DemuxEngine_HAS_KEY_LADDER_CIPHER_BLOCK 1
#define RMFEATURE_DemuxEngine_HAS_PrivateEmmEcmFilter 1
#define RMFEATURE_DemuxEngine_HAS_RC4_CIPHER 1
#define RMFEATURE_DemuxEngine_HAS_DVBCSAv3_CIPHER 1
#define RMFEATURE_DemuxEngine_MVC_GROUP 1
#define RMFEATURE_DemuxEngine_TSOUT_SPI_COUNT 0
#define RMFEATURE_DemuxEngine_TSOUT_SSI_COUNT 0
#define RMFEATURE_DemuxEngine_TS_IN_SPI_COUNT 1
#define RMFEATURE_DemuxEngine_TS_IN_SSI_COUNT 4
#define RMFEATURE_EZBOOT_SUPPORT_CPUSPI 1
#define RMFEATURE_EZBOOT_SUPPORT_GPIOSPI 1
#define RMFEATURE_EZBOOT_SUPPORT_HOSTSPI 1
#define RMFEATURE_EZBOOT_SUPPORT_MLCNAND 1
#define RMFEATURE_EZBOOT_SUPPORT_PFLASH 1
#define RMFEATURE_HAS_DDR3 1
#define RMFEATURE_HAS_DRAM_CONTROLLER_1 1
#define RMFEATURE_HAS_HWSHA256 1
#define RMFEATURE_HAS_PLLRAMPING 1
#define RMFEATURE_HAS_TANGO4_GBUS_MAP 1
#define RMFEATURE_HAS_GACC_V2 1
#define RMFEATURE_ROMOF52KB 1
#define RMFEATURE_UART0_IS_IN_SYSTEM_BLOCK 1
#define RMFEATURE_USE_POST_65NM_PLL 1
#define RMFEATURE_VideoDecoder_HAS_SCALE_PIC 1
#define RMFEATURE_uCode_audio__kernel_audio_transfer_asm_MBUS_VERSION 2
#define RMFEATURE_uCode_audio__DTSMA 1
#define XBOOT3_VERSION 0xcd
#define RMFEATURE_ROM_BDL_DISABLE_UART 1
#define RMFEATURE_XBOOT3_NAGRA_CUSTOM 1
#define RMCHIP_ROM_SPI_SUPPORT 1
#define RMCHIP_ROM_SATA_SUPPORT 1
#define RMCHIP_ROM_EMMC_SUPPORT 1
#define RMCHIP_ROM_EMMC_DRIVER_VERSION 2
#define RMFEATURE_MLC_GF15 1
#define RMFEATURE_WITH_UART_SYNC 1
#define RMFEATURE_VideoDecoder_HAS_DRAM_MUX_FOR_MOTION_COMP 1

#endif /* __SMP8734R1_H__ */
