/* autogenerated with parsecfg: do not edit. */

union vmbus_maskReg {
 struct { uint32_t

 /* sorting 1 */
#define vmbus_mask_vmbus_mask_data_SHIFT 0
#define vmbus_mask_vmbus_mask_data_WIDTH 16

 vmbus_mask_data:16, /*[15:0]  */
 hole0:16;
 } bits;

 uint32_t value;
};

union vmbus_configReg {
 struct { uint32_t

 /* sorting 1 */
#define vmbus_config_vmbus_config_data_SHIFT 0
#define vmbus_config_vmbus_config_data_WIDTH 16

 vmbus_config_data:16, /*[15:0]  */
 hole0:16;
 } bits;

 uint32_t value;
};

union io_maskReg {
 struct { uint32_t

 /* sorting 1 */
#define io_mask_io_mask_data_SHIFT 0
#define io_mask_io_mask_data_WIDTH 16

 io_mask_data:16, /*[15:0]  */
 hole0:16;
 } bits;

 uint32_t value;
};

struct audio_io_irq {
 uint32_t io_status; /* +0x00000000 ,RO */
 union io_maskReg io_mask; /* +0x00000004  */
 uint32_t io_clear; /* +0x00000008 ,NO_TEST */
 uint32_t vmbus_status; /* +0x0000000c ,RO */
 union vmbus_maskReg vmbus_mask; /* +0x00000010  */
 uint32_t vmbus_clear; /* +0x00000014 ,NO_TEST */
 union vmbus_configReg vmbus_config; /* +0x00000018  */
};
