/* autogenerated with parsecfg: do not edit. */

union weight_3_9Reg {
 struct { uint32_t

 /* sorting 1 */
#define weight_3_9_weight_3_9_value_SHIFT 0
#define weight_3_9_weight_3_9_value_WIDTH 24

 weight_3_9_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union weight_3_8Reg {
 struct { uint32_t

 /* sorting 1 */
#define weight_3_8_weight_3_8_value_SHIFT 0
#define weight_3_8_weight_3_8_value_WIDTH 24

 weight_3_8_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union weight_3_7Reg {
 struct { uint32_t

 /* sorting 1 */
#define weight_3_7_weight_3_7_value_SHIFT 0
#define weight_3_7_weight_3_7_value_WIDTH 24

 weight_3_7_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union weight_3_6Reg {
 struct { uint32_t

 /* sorting 1 */
#define weight_3_6_weight_3_6_value_SHIFT 0
#define weight_3_6_weight_3_6_value_WIDTH 24

 weight_3_6_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union weight_3_5Reg {
 struct { uint32_t

 /* sorting 1 */
#define weight_3_5_weight_3_5_value_SHIFT 0
#define weight_3_5_weight_3_5_value_WIDTH 24

 weight_3_5_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union weight_3_4Reg {
 struct { uint32_t

 /* sorting 1 */
#define weight_3_4_weight_3_4_value_SHIFT 0
#define weight_3_4_weight_3_4_value_WIDTH 24

 weight_3_4_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union weight_3_3Reg {
 struct { uint32_t

 /* sorting 1 */
#define weight_3_3_weight_3_3_value_SHIFT 0
#define weight_3_3_weight_3_3_value_WIDTH 24

 weight_3_3_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union weight_3_2Reg {
 struct { uint32_t

 /* sorting 1 */
#define weight_3_2_weight_3_2_value_SHIFT 0
#define weight_3_2_weight_3_2_value_WIDTH 24

 weight_3_2_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union weight_3_11Reg {
 struct { uint32_t

 /* sorting 1 */
#define weight_3_11_weight_3_11_value_SHIFT 0
#define weight_3_11_weight_3_11_value_WIDTH 24

 weight_3_11_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union weight_3_10Reg {
 struct { uint32_t

 /* sorting 1 */
#define weight_3_10_weight_3_10_value_SHIFT 0
#define weight_3_10_weight_3_10_value_WIDTH 24

 weight_3_10_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union weight_3_1Reg {
 struct { uint32_t

 /* sorting 1 */
#define weight_3_1_weight_3_1_value_SHIFT 0
#define weight_3_1_weight_3_1_value_WIDTH 24

 weight_3_1_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union weight_3_0Reg {
 struct { uint32_t

 /* sorting 1 */
#define weight_3_0_weight_3_0_value_SHIFT 0
#define weight_3_0_weight_3_0_value_WIDTH 24

 weight_3_0_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union weight_2_9Reg {
 struct { uint32_t

 /* sorting 1 */
#define weight_2_9_weight_2_9_value_SHIFT 0
#define weight_2_9_weight_2_9_value_WIDTH 24

 weight_2_9_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union weight_2_8Reg {
 struct { uint32_t

 /* sorting 1 */
#define weight_2_8_weight_2_8_value_SHIFT 0
#define weight_2_8_weight_2_8_value_WIDTH 24

 weight_2_8_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union weight_2_7Reg {
 struct { uint32_t

 /* sorting 1 */
#define weight_2_7_weight_2_7_value_SHIFT 0
#define weight_2_7_weight_2_7_value_WIDTH 24

 weight_2_7_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union weight_2_6Reg {
 struct { uint32_t

 /* sorting 1 */
#define weight_2_6_weight_2_6_value_SHIFT 0
#define weight_2_6_weight_2_6_value_WIDTH 24

 weight_2_6_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union weight_2_5Reg {
 struct { uint32_t

 /* sorting 1 */
#define weight_2_5_weight_2_5_value_SHIFT 0
#define weight_2_5_weight_2_5_value_WIDTH 24

 weight_2_5_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union weight_2_4Reg {
 struct { uint32_t

 /* sorting 1 */
#define weight_2_4_weight_2_4_value_SHIFT 0
#define weight_2_4_weight_2_4_value_WIDTH 24

 weight_2_4_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union weight_2_3Reg {
 struct { uint32_t

 /* sorting 1 */
#define weight_2_3_weight_2_3_value_SHIFT 0
#define weight_2_3_weight_2_3_value_WIDTH 24

 weight_2_3_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union weight_2_2Reg {
 struct { uint32_t

 /* sorting 1 */
#define weight_2_2_weight_2_2_value_SHIFT 0
#define weight_2_2_weight_2_2_value_WIDTH 24

 weight_2_2_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union weight_2_11Reg {
 struct { uint32_t

 /* sorting 1 */
#define weight_2_11_weight_2_11_value_SHIFT 0
#define weight_2_11_weight_2_11_value_WIDTH 24

 weight_2_11_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union weight_2_10Reg {
 struct { uint32_t

 /* sorting 1 */
#define weight_2_10_weight_2_10_value_SHIFT 0
#define weight_2_10_weight_2_10_value_WIDTH 24

 weight_2_10_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union weight_2_1Reg {
 struct { uint32_t

 /* sorting 1 */
#define weight_2_1_weight_2_1_value_SHIFT 0
#define weight_2_1_weight_2_1_value_WIDTH 24

 weight_2_1_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union weight_2_0Reg {
 struct { uint32_t

 /* sorting 1 */
#define weight_2_0_weight_2_0_value_SHIFT 0
#define weight_2_0_weight_2_0_value_WIDTH 24

 weight_2_0_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union weight_1_9Reg {
 struct { uint32_t

 /* sorting 1 */
#define weight_1_9_weight_1_9_value_SHIFT 0
#define weight_1_9_weight_1_9_value_WIDTH 24

 weight_1_9_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union weight_1_8Reg {
 struct { uint32_t

 /* sorting 1 */
#define weight_1_8_weight_1_8_value_SHIFT 0
#define weight_1_8_weight_1_8_value_WIDTH 24

 weight_1_8_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union weight_1_7Reg {
 struct { uint32_t

 /* sorting 1 */
#define weight_1_7_weight_1_7_value_SHIFT 0
#define weight_1_7_weight_1_7_value_WIDTH 24

 weight_1_7_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union weight_1_6Reg {
 struct { uint32_t

 /* sorting 1 */
#define weight_1_6_weight_1_6_value_SHIFT 0
#define weight_1_6_weight_1_6_value_WIDTH 24

 weight_1_6_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union weight_1_5Reg {
 struct { uint32_t

 /* sorting 1 */
#define weight_1_5_weight_1_5_value_SHIFT 0
#define weight_1_5_weight_1_5_value_WIDTH 24

 weight_1_5_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union weight_1_4Reg {
 struct { uint32_t

 /* sorting 1 */
#define weight_1_4_weight_1_4_value_SHIFT 0
#define weight_1_4_weight_1_4_value_WIDTH 24

 weight_1_4_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union weight_1_3Reg {
 struct { uint32_t

 /* sorting 1 */
#define weight_1_3_weight_1_3_value_SHIFT 0
#define weight_1_3_weight_1_3_value_WIDTH 24

 weight_1_3_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union weight_1_2Reg {
 struct { uint32_t

 /* sorting 1 */
#define weight_1_2_weight_1_2_value_SHIFT 0
#define weight_1_2_weight_1_2_value_WIDTH 24

 weight_1_2_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union weight_1_11Reg {
 struct { uint32_t

 /* sorting 1 */
#define weight_1_11_weight_1_11_value_SHIFT 0
#define weight_1_11_weight_1_11_value_WIDTH 24

 weight_1_11_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union weight_1_10Reg {
 struct { uint32_t

 /* sorting 1 */
#define weight_1_10_weight_1_10_value_SHIFT 0
#define weight_1_10_weight_1_10_value_WIDTH 24

 weight_1_10_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union weight_1_1Reg {
 struct { uint32_t

 /* sorting 1 */
#define weight_1_1_weight_1_1_value_SHIFT 0
#define weight_1_1_weight_1_1_value_WIDTH 24

 weight_1_1_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union weight_1_0Reg {
 struct { uint32_t

 /* sorting 1 */
#define weight_1_0_weight_1_0_value_SHIFT 0
#define weight_1_0_weight_1_0_value_WIDTH 24

 weight_1_0_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union weight_0_9Reg {
 struct { uint32_t

 /* sorting 1 */
#define weight_0_9_weight_0_9_value_SHIFT 0
#define weight_0_9_weight_0_9_value_WIDTH 24

 weight_0_9_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union weight_0_8Reg {
 struct { uint32_t

 /* sorting 1 */
#define weight_0_8_weight_0_8_value_SHIFT 0
#define weight_0_8_weight_0_8_value_WIDTH 24

 weight_0_8_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union weight_0_7Reg {
 struct { uint32_t

 /* sorting 1 */
#define weight_0_7_weight_0_7_value_SHIFT 0
#define weight_0_7_weight_0_7_value_WIDTH 24

 weight_0_7_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union weight_0_6Reg {
 struct { uint32_t

 /* sorting 1 */
#define weight_0_6_weight_0_6_value_SHIFT 0
#define weight_0_6_weight_0_6_value_WIDTH 24

 weight_0_6_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union weight_0_5Reg {
 struct { uint32_t

 /* sorting 1 */
#define weight_0_5_weight_0_5_value_SHIFT 0
#define weight_0_5_weight_0_5_value_WIDTH 24

 weight_0_5_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union weight_0_4Reg {
 struct { uint32_t

 /* sorting 1 */
#define weight_0_4_weight_0_4_value_SHIFT 0
#define weight_0_4_weight_0_4_value_WIDTH 24

 weight_0_4_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union weight_0_3Reg {
 struct { uint32_t

 /* sorting 1 */
#define weight_0_3_weight_0_3_value_SHIFT 0
#define weight_0_3_weight_0_3_value_WIDTH 24

 weight_0_3_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union weight_0_2Reg {
 struct { uint32_t

 /* sorting 1 */
#define weight_0_2_weight_0_2_value_SHIFT 0
#define weight_0_2_weight_0_2_value_WIDTH 24

 weight_0_2_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union weight_0_11Reg {
 struct { uint32_t

 /* sorting 1 */
#define weight_0_11_weight_0_11_value_SHIFT 0
#define weight_0_11_weight_0_11_value_WIDTH 24

 weight_0_11_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union weight_0_10Reg {
 struct { uint32_t

 /* sorting 1 */
#define weight_0_10_weight_0_10_value_SHIFT 0
#define weight_0_10_weight_0_10_value_WIDTH 24

 weight_0_10_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union weight_0_1Reg {
 struct { uint32_t

 /* sorting 1 */
#define weight_0_1_weight_0_1_value_SHIFT 0
#define weight_0_1_weight_0_1_value_WIDTH 24

 weight_0_1_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union weight_0_0Reg {
 struct { uint32_t

 /* sorting 1 */
#define weight_0_0_weight_0_0_value_SHIFT 0
#define weight_0_0_weight_0_0_value_WIDTH 24

 weight_0_0_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union active_channels_3Reg {
 struct { uint32_t

 /* sorting 1 */
#define active_channels_3_active_channels_3_value_SHIFT 0
#define active_channels_3_active_channels_3_value_WIDTH 12

 active_channels_3_value:12, /*[11:0]  */
 hole0:20;
 } bits;

 uint32_t value;
};

union active_channels_2Reg {
 struct { uint32_t

 /* sorting 1 */
#define active_channels_2_active_channels_2_value_SHIFT 0
#define active_channels_2_active_channels_2_value_WIDTH 12

 active_channels_2_value:12, /*[11:0]  */
 hole0:20;
 } bits;

 uint32_t value;
};

union active_channels_1Reg {
 struct { uint32_t

 /* sorting 1 */
#define active_channels_1_active_channels_1_value_SHIFT 0
#define active_channels_1_active_channels_1_value_WIDTH 12

 active_channels_1_value:12, /*[11:0]  */
 hole0:20;
 } bits;

 uint32_t value;
};

union active_channels_0Reg {
 struct { uint32_t

 /* sorting 1 */
#define active_channels_0_active_channels_0_value_SHIFT 0
#define active_channels_0_active_channels_0_value_WIDTH 12

 active_channels_0_value:12, /*[11:0]  */
 hole0:20;
 } bits;

 uint32_t value;
};

struct audio_mixer {
 union active_channels_0Reg active_channels_0; /* +0x00000000  */
 union active_channels_1Reg active_channels_1; /* +0x00000004  */
 union active_channels_2Reg active_channels_2; /* +0x00000008  */
 union active_channels_3Reg active_channels_3; /* +0x0000000c  */
 union weight_0_0Reg weight_0_0; /* +0x00000010  */
 union weight_0_1Reg weight_0_1; /* +0x00000014  */
 union weight_0_2Reg weight_0_2; /* +0x00000018  */
 union weight_0_3Reg weight_0_3; /* +0x0000001c  */
 union weight_0_4Reg weight_0_4; /* +0x00000020  */
 union weight_0_5Reg weight_0_5; /* +0x00000024  */
 union weight_0_6Reg weight_0_6; /* +0x00000028  */
 union weight_0_7Reg weight_0_7; /* +0x0000002c  */
 union weight_0_8Reg weight_0_8; /* +0x00000030  */
 union weight_0_9Reg weight_0_9; /* +0x00000034  */
 union weight_0_10Reg weight_0_10; /* +0x00000038  */
 union weight_0_11Reg weight_0_11; /* +0x0000003c  */
 union weight_1_0Reg weight_1_0; /* +0x00000040  */
 union weight_1_1Reg weight_1_1; /* +0x00000044  */
 union weight_1_2Reg weight_1_2; /* +0x00000048  */
 union weight_1_3Reg weight_1_3; /* +0x0000004c  */
 union weight_1_4Reg weight_1_4; /* +0x00000050  */
 union weight_1_5Reg weight_1_5; /* +0x00000054  */
 union weight_1_6Reg weight_1_6; /* +0x00000058  */
 union weight_1_7Reg weight_1_7; /* +0x0000005c  */
 union weight_1_8Reg weight_1_8; /* +0x00000060  */
 union weight_1_9Reg weight_1_9; /* +0x00000064  */
 union weight_1_10Reg weight_1_10; /* +0x00000068  */
 union weight_1_11Reg weight_1_11; /* +0x0000006c  */
 union weight_2_0Reg weight_2_0; /* +0x00000070  */
 union weight_2_1Reg weight_2_1; /* +0x00000074  */
 union weight_2_2Reg weight_2_2; /* +0x00000078  */
 union weight_2_3Reg weight_2_3; /* +0x0000007c  */
 union weight_2_4Reg weight_2_4; /* +0x00000080  */
 union weight_2_5Reg weight_2_5; /* +0x00000084  */
 union weight_2_6Reg weight_2_6; /* +0x00000088  */
 union weight_2_7Reg weight_2_7; /* +0x0000008c  */
 union weight_2_8Reg weight_2_8; /* +0x00000090  */
 union weight_2_9Reg weight_2_9; /* +0x00000094  */
 union weight_2_10Reg weight_2_10; /* +0x00000098  */
 union weight_2_11Reg weight_2_11; /* +0x0000009c  */
 union weight_3_0Reg weight_3_0; /* +0x000000a0  */
 union weight_3_1Reg weight_3_1; /* +0x000000a4  */
 union weight_3_2Reg weight_3_2; /* +0x000000a8  */
 union weight_3_3Reg weight_3_3; /* +0x000000ac  */
 union weight_3_4Reg weight_3_4; /* +0x000000b0  */
 union weight_3_5Reg weight_3_5; /* +0x000000b4  */
 union weight_3_6Reg weight_3_6; /* +0x000000b8  */
 union weight_3_7Reg weight_3_7; /* +0x000000bc  */
 union weight_3_8Reg weight_3_8; /* +0x000000c0  */
 union weight_3_9Reg weight_3_9; /* +0x000000c4  */
 union weight_3_10Reg weight_3_10; /* +0x000000c8  */
 union weight_3_11Reg weight_3_11; /* +0x000000cc  */
};
