/* autogenerated with parsecfg: do not edit. */

union voip_pad_ctrlReg {
 struct { uint32_t

 /* sorting 1 */
#define voip_pad_ctrl_voip_pad_ground_SHIFT 0
#define voip_pad_ctrl_voip_pad_ground_WIDTH 5

 voip_pad_ground:5, /*[4:0]  */
 hole0:27;
 } bits;

 uint32_t value;
};

union spdif_out_pad_ctrlReg {
 struct { uint32_t

 /* sorting 2 */
#define spdif_out_pad_ctrl_ground_SHIFT 0
#define spdif_out_pad_ctrl_ground_WIDTH 1
#define spdif_out_pad_ctrl_mux_SHIFT 16
#define spdif_out_pad_ctrl_mux_WIDTH 3

 ground:1, /*[0:0]  */
 hole0:15,
 mux:3, /*[18:16]  */
 hole1:13;
 } bits;

 uint32_t value;
};

union spdif_hdmitx0_pad_ctrlReg {
 struct { uint32_t

 /* sorting 2 */
#define spdif_hdmitx0_pad_ctrl_ground_SHIFT 0
#define spdif_hdmitx0_pad_ctrl_ground_WIDTH 1
#define spdif_hdmitx0_pad_ctrl_mux_SHIFT 16
#define spdif_hdmitx0_pad_ctrl_mux_WIDTH 3

 ground:1, /*[0:0]  */
 hole0:15,
 mux:3, /*[18:16]  */
 hole1:13;
 } bits;

 uint32_t value;
};

union i2s_seco_pad_ctrlReg {
 struct { uint32_t

 /* sorting 2 */
#define i2s_seco_pad_ctrl_ground_SHIFT 0
#define i2s_seco_pad_ctrl_ground_WIDTH 4
#define i2s_seco_pad_ctrl_mux_SHIFT 16
#define i2s_seco_pad_ctrl_mux_WIDTH 3

 ground:4, /*[3:0]  */
 hole0:12,
 mux:3, /*[18:16]  */
 hole1:13;
 } bits;

 uint32_t value;
};

union i2s_main_pad_ctrlReg {
 struct { uint32_t

 /* sorting 2 */
#define i2s_main_pad_ctrl_ground_SHIFT 0
#define i2s_main_pad_ctrl_ground_WIDTH 9
#define i2s_main_pad_ctrl_mux_SHIFT 16
#define i2s_main_pad_ctrl_mux_WIDTH 3

 ground:9, /*[8:0]  */
 hole0:7,
 mux:3, /*[18:16]  */
 hole1:13;
 } bits;

 uint32_t value;
};

union i2s_hdmitx0_pad_ctrlReg {
 struct { uint32_t

 /* sorting 2 */
#define i2s_hdmitx0_pad_ctrl_ground_SHIFT 0
#define i2s_hdmitx0_pad_ctrl_ground_WIDTH 7
#define i2s_hdmitx0_pad_ctrl_mux_SHIFT 16
#define i2s_hdmitx0_pad_ctrl_mux_WIDTH 3

 ground:7, /*[6:0]  */
 hole0:9,
 mux:3, /*[18:16]  */
 hole1:13;
 } bits;

 uint32_t value;
};

struct audio_io_misc {
 uint32_t reset0; /* +0x00000000 ,NO_TEST */
 uint32_t reset1; /* +0x00000004 ,NO_TEST */
 uint32_t input_instance_map; /* +0x00000008 ,RO */
 uint32_t output_instance_map; /* +0x0000000c ,RO */
 union i2s_main_pad_ctrlReg i2s_main_pad_ctrl; /* +0x00000010  */
 union i2s_seco_pad_ctrlReg i2s_seco_pad_ctrl; /* +0x00000014  */
 union i2s_hdmitx0_pad_ctrlReg i2s_hdmitx0_pad_ctrl; /* +0x00000018  */
 union spdif_hdmitx0_pad_ctrlReg spdif_hdmitx0_pad_ctrl; /* +0x0000001c  */
 union spdif_out_pad_ctrlReg spdif_out_pad_ctrl; /* +0x00000020  */
 union voip_pad_ctrlReg voip_pad_ctrl; /* +0x00000024  */
 uint32_t pad0[0x0018/4];
 uint32_t reset_run; /* +0x00000040 ,NO_TEST */
 uint32_t reset_datapath; /* +0x00000044 ,NO_TEST */
 uint32_t reset_timing; /* +0x00000048 ,NO_TEST */
 uint32_t reset_config; /* +0x0000004c ,NO_TEST */
 uint32_t reset_unused; /* +0x00000050 ,NO_TEST */
 uint32_t reset_mode_0; /* +0x00000054 ,NO_TEST */
 uint32_t reset_mode_1; /* +0x00000058 ,NO_TEST */
};
