/* autogenerated with parsecfg: do not edit. */

/* gotta drop misc_dsp_remap0_ro@misc_remap_control: 0x0000ffff [0:0] */
/* gotta drop misc_dsp_remap1_ro@misc_remap_control: 0x0000ffff [5:5] */
/* gotta drop misc_dsp_remap2_ro@misc_remap_control: 0x0000ffff [10:10] */
/* gotta drop misc_dsp_remap3_ro@misc_remap_control: 0x0000ffff [15:15] */
union misc_tombus_dma_statusReg {
 struct { uint32_t

 /* sorting 2 */
#define misc_tombus_dma_status_done_SHIFT 0
#define misc_tombus_dma_status_done_WIDTH 1
#define misc_tombus_dma_status_size_SHIFT 8
#define misc_tombus_dma_status_size_WIDTH 18

 done:1, /*[0:0]  */
 hole0:7,
 size:18, /*[25:8]  */
 hole1:6;
 } bits;

 uint32_t value;
};

union misc_tombus_dma_intrReg {
 struct { uint32_t

 /* sorting 2 */
#define misc_tombus_dma_intr_address_skip_SHIFT 0
#define misc_tombus_dma_intr_address_skip_WIDTH 16
#define misc_tombus_dma_intr_interlaced_ycnt_SHIFT 16
#define misc_tombus_dma_intr_interlaced_ycnt_WIDTH 16

 address_skip:16, /*[15:0]  */
 interlaced_ycnt:16; /*[31:16]  */
 } bits;

 uint32_t value;
};

union misc_tombus_dma_controlReg {
 struct { uint32_t

 /* sorting 2 */
#define misc_tombus_dma_control_start_size_SHIFT 0
#define misc_tombus_dma_control_start_size_WIDTH 18
#define misc_tombus_dma_control_mode_SHIFT 24
#define misc_tombus_dma_control_mode_WIDTH 4

 start_size:18, /*[17:0]  */
 hole0:6,
 mode:4, /*[27:24]  */
 hole1:4;
 } bits;

 uint32_t value;
};

union misc_tombus_dma_addReg {
 struct { uint32_t

 /* sorting 1 */
#define misc_tombus_dma_add_misc_tombus_dma_start_read_add_SHIFT 0
#define misc_tombus_dma_add_misc_tombus_dma_start_read_add_WIDTH 19

 misc_tombus_dma_start_read_add:19, /*[18:0]  */
 hole0:13;
 } bits;

 uint32_t value;
};

union misc_remap_controlReg {
 struct { uint32_t

 /* sorting 1 */
#define misc_remap_control_misc_dsp_remap_SHIFT 0
#define misc_remap_control_misc_dsp_remap_WIDTH 16

 misc_dsp_remap:16, /*[15:0]  */
 hole0:16;
 } bits;

 uint32_t value;
};

union misc_intra_dma_waddReg {
 struct { uint32_t

 /* sorting 1 */
#define misc_intra_dma_wadd_misc_intra_dma_start_write_add_SHIFT 0
#define misc_intra_dma_wadd_misc_intra_dma_start_write_add_WIDTH 19

 misc_intra_dma_start_write_add:19, /*[18:0]  */
 hole0:13;
 } bits;

 uint32_t value;
};

union misc_intra_dma_statusReg {
 struct { uint32_t

 /* sorting 2 */
#define misc_intra_dma_status_done_SHIFT 0
#define misc_intra_dma_status_done_WIDTH 1
#define misc_intra_dma_status_size_SHIFT 8
#define misc_intra_dma_status_size_WIDTH 18

 done:1, /*[0:0]  */
 hole0:7,
 size:18, /*[25:8]  */
 hole1:6;
 } bits;

 uint32_t value;
};

union misc_intra_dma_raddReg {
 struct { uint32_t

 /* sorting 1 */
#define misc_intra_dma_radd_misc_intra_dma_start_read_add_SHIFT 0
#define misc_intra_dma_radd_misc_intra_dma_start_read_add_WIDTH 19

 misc_intra_dma_start_read_add:19, /*[18:0]  */
 hole0:13;
 } bits;

 uint32_t value;
};

union misc_intra_dma_controlReg {
 struct { uint32_t

 /* sorting 2 */
#define misc_intra_dma_control_start_size_SHIFT 0
#define misc_intra_dma_control_start_size_WIDTH 18
#define misc_intra_dma_control_mode_SHIFT 24
#define misc_intra_dma_control_mode_WIDTH 2

 start_size:18, /*[17:0]  */
 hole0:6,
 mode:2, /*[25:24]  */
 hole1:6;
 } bits;

 uint32_t value;
};

union misc_frommbus_dma_statusReg {
 struct { uint32_t

 /* sorting 2 */
#define misc_frommbus_dma_status_done_SHIFT 0
#define misc_frommbus_dma_status_done_WIDTH 1
#define misc_frommbus_dma_status_size_SHIFT 8
#define misc_frommbus_dma_status_size_WIDTH 18

 done:1, /*[0:0]  */
 hole0:7,
 size:18, /*[25:8]  */
 hole1:6;
 } bits;

 uint32_t value;
};

union misc_frommbus_dma_intrReg {
 struct { uint32_t

 /* sorting 2 */
#define misc_frommbus_dma_intr_address_skip_SHIFT 0
#define misc_frommbus_dma_intr_address_skip_WIDTH 16
#define misc_frommbus_dma_intr_interlaced_ycnt_SHIFT 16
#define misc_frommbus_dma_intr_interlaced_ycnt_WIDTH 16

 address_skip:16, /*[15:0]  */
 interlaced_ycnt:16; /*[31:16]  */
 } bits;

 uint32_t value;
};

union misc_frommbus_dma_controlReg {
 struct { uint32_t

 /* sorting 2 */
#define misc_frommbus_dma_control_start_size_SHIFT 0
#define misc_frommbus_dma_control_start_size_WIDTH 18
#define misc_frommbus_dma_control_mode_SHIFT 24
#define misc_frommbus_dma_control_mode_WIDTH 4

 start_size:18, /*[17:0]  */
 hole0:6,
 mode:4, /*[27:24]  */
 hole1:4;
 } bits;

 uint32_t value;
};

union misc_frommbus_dma_addReg {
 struct { uint32_t

 /* sorting 1 */
#define misc_frommbus_dma_add_misc_frommbus_dma_start_write_add_SHIFT 0
#define misc_frommbus_dma_add_misc_frommbus_dma_start_write_add_WIDTH 19

 misc_frommbus_dma_start_write_add:19, /*[18:0]  */
 hole0:13;
 } bits;

 uint32_t value;
};

union misc_flag_mask_3Reg {
 struct { uint32_t

 /* sorting 1 */
#define misc_flag_mask_3_dsp3_flag_mask_SHIFT 0
#define misc_flag_mask_3_dsp3_flag_mask_WIDTH 30

 dsp3_flag_mask:30, /*[29:0]  */
 hole0:2;
 } bits;

 uint32_t value;
};

union misc_flag_mask_2Reg {
 struct { uint32_t

 /* sorting 1 */
#define misc_flag_mask_2_dsp2_flag_mask_SHIFT 0
#define misc_flag_mask_2_dsp2_flag_mask_WIDTH 30

 dsp2_flag_mask:30, /*[29:0]  */
 hole0:2;
 } bits;

 uint32_t value;
};

union misc_flag_mask_1Reg {
 struct { uint32_t

 /* sorting 1 */
#define misc_flag_mask_1_dsp1_flag_mask_SHIFT 0
#define misc_flag_mask_1_dsp1_flag_mask_WIDTH 30

 dsp1_flag_mask:30, /*[29:0]  */
 hole0:2;
 } bits;

 uint32_t value;
};

union misc_flag_mask_0Reg {
 struct { uint32_t

 /* sorting 1 */
#define misc_flag_mask_0_dsp0_flag_mask_SHIFT 0
#define misc_flag_mask_0_dsp0_flag_mask_WIDTH 30

 dsp0_flag_mask:30, /*[29:0]  */
 hole0:2;
 } bits;

 uint32_t value;
};

union misc_dma_loop_backReg {
 struct { uint32_t

 /* sorting 1 */
#define misc_dma_loop_back_misc_dma_loop_back0_SHIFT 0
#define misc_dma_loop_back_misc_dma_loop_back0_WIDTH 1

 misc_dma_loop_back0:1, /*[0:0]  */
 hole0:31;
 } bits;

 uint32_t value;
};

struct audio_misc {
 uint32_t misc_resets; /* +0x00000000 ,NO_TEST */
 uint32_t misc_interrupts; /* +0x00000004 ,NO_MEM */
 uint32_t misc_version_revision; /* +0x00000008 ,RO */
 union misc_dma_loop_backReg misc_dma_loop_back; /* +0x0000000c  */
 union misc_tombus_dma_controlReg misc_tombus_dma_control; /* +0x00000010 ,NO_TEST */
 union misc_tombus_dma_addReg misc_tombus_dma_add; /* +0x00000014  */
 union misc_tombus_dma_intrReg misc_tombus_dma_intr; /* +0x00000018  */
 union misc_tombus_dma_statusReg misc_tombus_dma_status; /* +0x0000001c ,NO_TEST */
 union misc_frommbus_dma_controlReg misc_frommbus_dma_control; /* +0x00000020 ,NO_TEST */
 union misc_frommbus_dma_addReg misc_frommbus_dma_add; /* +0x00000024  */
 union misc_frommbus_dma_intrReg misc_frommbus_dma_intr; /* +0x00000028  */
 union misc_frommbus_dma_statusReg misc_frommbus_dma_status; /* +0x0000002c ,NO_TEST */
 union misc_intra_dma_controlReg misc_intra_dma_control; /* +0x00000030 ,NO_TEST */
 union misc_intra_dma_raddReg misc_intra_dma_radd; /* +0x00000034  */
 union misc_intra_dma_waddReg misc_intra_dma_wadd; /* +0x00000038  */
 union misc_intra_dma_statusReg misc_intra_dma_status; /* +0x0000003c ,NO_TEST */
 uint32_t misc_dsp_reset_level; /* +0x00000040 ,NO_TEST */
 uint32_t misc_timer_div0; /* +0x00000044 ,NO_MEM */
 uint32_t misc_timer_cnt0; /* +0x00000048 ,NO_MEM */
 uint32_t misc_timer_div1; /* +0x0000004c ,NO_MEM */
 uint32_t misc_timer_cnt1; /* +0x00000050 ,NO_MEM */
 uint32_t misc_timer_div2; /* +0x00000054 ,NO_MEM */
 uint32_t misc_timer_cnt2; /* +0x00000058 ,NO_MEM */
 uint32_t misc_timer_div3; /* +0x0000005c ,NO_MEM */
 uint32_t misc_timer_cnt3; /* +0x00000060 ,NO_MEM */
 uint32_t misc_semaphore0; /* +0x00000064 ,NO_TEST */
 uint32_t misc_semaphore1; /* +0x00000068 ,NO_TEST */
 uint32_t misc_semaphore2; /* +0x0000006c ,NO_TEST */
 uint32_t misc_semaphore3; /* +0x00000070 ,NO_TEST */
 uint32_t misc_semaphore4; /* +0x00000074 ,NO_TEST */
 uint32_t misc_semaphore5; /* +0x00000078 ,NO_TEST */
 uint32_t misc_semaphore6; /* +0x0000007c ,NO_TEST */
 uint32_t misc_semaphore7; /* +0x00000080 ,NO_TEST */
 uint32_t misc_semaphore8; /* +0x00000084 ,NO_TEST */
 uint32_t misc_semaphore9; /* +0x00000088 ,NO_TEST */
 uint32_t misc_semaphore10; /* +0x0000008c ,NO_TEST */
 uint32_t misc_semaphore11; /* +0x00000090 ,NO_TEST */
 uint32_t misc_semaphore12; /* +0x00000094 ,NO_TEST */
 uint32_t misc_semaphore13; /* +0x00000098 ,NO_TEST */
 uint32_t misc_semaphore14; /* +0x0000009c ,NO_TEST */
 uint32_t misc_semaphore15; /* +0x000000a0 ,NO_TEST */
 union misc_remap_controlReg misc_remap_control; /* +0x000000a4  */
 uint32_t misc_irq_vector; /* +0x000000a8 ,NO_MEM */
 uint32_t misc_irq_mask_0; /* +0x000000ac  */
 uint32_t misc_irq_mask_1; /* +0x000000b0  */
 uint32_t misc_irq_mask_2; /* +0x000000b4  */
 uint32_t misc_irq_mask_3; /* +0x000000b8  */
 uint32_t misc_flag_vector; /* +0x000000bc ,NO_MEM */
 union misc_flag_mask_0Reg misc_flag_mask_0; /* +0x000000c0  */
 union misc_flag_mask_1Reg misc_flag_mask_1; /* +0x000000c4  */
 union misc_flag_mask_2Reg misc_flag_mask_2; /* +0x000000c8  */
 union misc_flag_mask_3Reg misc_flag_mask_3; /* +0x000000cc  */
 uint32_t pad0[0x0010/4];
 uint32_t misc_reset_run; /* +0x000000e0 ,NO_TEST */
 uint32_t misc_reset_datapath; /* +0x000000e4 ,NO_TEST */
 uint32_t misc_reset_timing; /* +0x000000e8 ,NO_TEST */
 uint32_t misc_reset_config; /* +0x000000ec ,NO_TEST */
 uint32_t misc_reset_unused; /* +0x000000f0 ,NO_TEST */
 uint32_t misc_reset_mode_0; /* +0x000000f4 ,NO_TEST */
 uint32_t misc_reset_mode_1; /* +0x000000f8 ,NO_TEST */
 uint32_t misc_reset_mbus_flush; /* +0x000000fc ,NO_TEST */
};
