/* autogenerated with parsecfg: do not edit. */

union statusReg {
 struct { uint32_t

 /* sorting 2 */
#define status_eft_padding_SHIFT 0
#define status_eft_padding_WIDTH 8
#define status_ast_carry_SHIFT 8
#define status_ast_carry_WIDTH 1

 eft_padding:8, /*[7:0] ,RO */
 ast_carry:1, /*[8:8] ,RO */
 hole0:23;
 } bits;

 uint32_t value;
};

union scale_factorReg {
 struct { uint32_t

 /* sorting 2 */
#define scale_factor_fract_scale_SHIFT 0
#define scale_factor_fract_scale_WIDTH 27
#define scale_factor_int_scale_SHIFT 27
#define scale_factor_int_scale_WIDTH 5

 fract_scale:27, /*[26:0]  */
 int_scale:5; /*[31:27]  */
 } bits;

 uint32_t value;
};

union out_sizeReg {
 struct { uint32_t

 /* sorting 1 */
#define out_size_out_size_value_SHIFT 0
#define out_size_out_size_value_WIDTH 14

 out_size_value:14, /*[13:0]  */
 hole0:18;
 } bits;

 uint32_t value;
};

union init_phaseReg {
 struct { uint32_t

 /* sorting 1 */
#define init_phase_init_phase_value_SHIFT 0
#define init_phase_init_phase_value_WIDTH 27

 init_phase_value:27, /*[26:0]  */
 hole0:5;
 } bits;

 uint32_t value;
};

union configReg {
 struct { uint32_t

 /* sorting 4 */
#define config_taps_minus1_SHIFT 0
#define config_taps_minus1_WIDTH 7
#define config_phase_minus1_SHIFT 8
#define config_phase_minus1_WIDTH 5
#define config_channel_minus1_SHIFT 16
#define config_channel_minus1_WIDTH 4
#define config_shift_SHIFT 24
#define config_shift_WIDTH 8

 taps_minus1:7, /*[6:0]  */
 hole0:1,
 phase_minus1:5, /*[12:8]  */
 hole1:3,
 channel_minus1:4, /*[19:16]  */
 hole2:4,
 shift:8; /*[31:24]  */
 } bits;

 uint32_t value;
};

union coeff99Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff99_coeff99_value_SHIFT 0
#define coeff99_coeff99_value_WIDTH 24

 coeff99_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff98Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff98_coeff98_value_SHIFT 0
#define coeff98_coeff98_value_WIDTH 24

 coeff98_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff97Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff97_coeff97_value_SHIFT 0
#define coeff97_coeff97_value_WIDTH 24

 coeff97_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff96Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff96_coeff96_value_SHIFT 0
#define coeff96_coeff96_value_WIDTH 24

 coeff96_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff95Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff95_coeff95_value_SHIFT 0
#define coeff95_coeff95_value_WIDTH 24

 coeff95_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff94Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff94_coeff94_value_SHIFT 0
#define coeff94_coeff94_value_WIDTH 24

 coeff94_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff93Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff93_coeff93_value_SHIFT 0
#define coeff93_coeff93_value_WIDTH 24

 coeff93_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff92Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff92_coeff92_value_SHIFT 0
#define coeff92_coeff92_value_WIDTH 24

 coeff92_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff91Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff91_coeff91_value_SHIFT 0
#define coeff91_coeff91_value_WIDTH 24

 coeff91_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff90Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff90_coeff90_value_SHIFT 0
#define coeff90_coeff90_value_WIDTH 24

 coeff90_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff9Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff9_coeff9_value_SHIFT 0
#define coeff9_coeff9_value_WIDTH 24

 coeff9_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff89Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff89_coeff89_value_SHIFT 0
#define coeff89_coeff89_value_WIDTH 24

 coeff89_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff88Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff88_coeff88_value_SHIFT 0
#define coeff88_coeff88_value_WIDTH 24

 coeff88_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff87Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff87_coeff87_value_SHIFT 0
#define coeff87_coeff87_value_WIDTH 24

 coeff87_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff86Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff86_coeff86_value_SHIFT 0
#define coeff86_coeff86_value_WIDTH 24

 coeff86_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff85Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff85_coeff85_value_SHIFT 0
#define coeff85_coeff85_value_WIDTH 24

 coeff85_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff84Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff84_coeff84_value_SHIFT 0
#define coeff84_coeff84_value_WIDTH 24

 coeff84_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff83Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff83_coeff83_value_SHIFT 0
#define coeff83_coeff83_value_WIDTH 24

 coeff83_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff82Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff82_coeff82_value_SHIFT 0
#define coeff82_coeff82_value_WIDTH 24

 coeff82_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff81Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff81_coeff81_value_SHIFT 0
#define coeff81_coeff81_value_WIDTH 24

 coeff81_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff80Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff80_coeff80_value_SHIFT 0
#define coeff80_coeff80_value_WIDTH 24

 coeff80_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff8Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff8_coeff8_value_SHIFT 0
#define coeff8_coeff8_value_WIDTH 24

 coeff8_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff79Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff79_coeff79_value_SHIFT 0
#define coeff79_coeff79_value_WIDTH 24

 coeff79_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff78Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff78_coeff78_value_SHIFT 0
#define coeff78_coeff78_value_WIDTH 24

 coeff78_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff77Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff77_coeff77_value_SHIFT 0
#define coeff77_coeff77_value_WIDTH 24

 coeff77_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff76Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff76_coeff76_value_SHIFT 0
#define coeff76_coeff76_value_WIDTH 24

 coeff76_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff75Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff75_coeff75_value_SHIFT 0
#define coeff75_coeff75_value_WIDTH 24

 coeff75_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff74Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff74_coeff74_value_SHIFT 0
#define coeff74_coeff74_value_WIDTH 24

 coeff74_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff73Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff73_coeff73_value_SHIFT 0
#define coeff73_coeff73_value_WIDTH 24

 coeff73_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff72Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff72_coeff72_value_SHIFT 0
#define coeff72_coeff72_value_WIDTH 24

 coeff72_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff71Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff71_coeff71_value_SHIFT 0
#define coeff71_coeff71_value_WIDTH 24

 coeff71_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff70Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff70_coeff70_value_SHIFT 0
#define coeff70_coeff70_value_WIDTH 24

 coeff70_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff7Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff7_coeff7_value_SHIFT 0
#define coeff7_coeff7_value_WIDTH 24

 coeff7_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff69Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff69_coeff69_value_SHIFT 0
#define coeff69_coeff69_value_WIDTH 24

 coeff69_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff68Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff68_coeff68_value_SHIFT 0
#define coeff68_coeff68_value_WIDTH 24

 coeff68_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff67Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff67_coeff67_value_SHIFT 0
#define coeff67_coeff67_value_WIDTH 24

 coeff67_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff66Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff66_coeff66_value_SHIFT 0
#define coeff66_coeff66_value_WIDTH 24

 coeff66_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff65Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff65_coeff65_value_SHIFT 0
#define coeff65_coeff65_value_WIDTH 24

 coeff65_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff64Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff64_coeff64_value_SHIFT 0
#define coeff64_coeff64_value_WIDTH 24

 coeff64_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff63Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff63_coeff63_value_SHIFT 0
#define coeff63_coeff63_value_WIDTH 24

 coeff63_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff62Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff62_coeff62_value_SHIFT 0
#define coeff62_coeff62_value_WIDTH 24

 coeff62_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff61Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff61_coeff61_value_SHIFT 0
#define coeff61_coeff61_value_WIDTH 24

 coeff61_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff60Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff60_coeff60_value_SHIFT 0
#define coeff60_coeff60_value_WIDTH 24

 coeff60_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff6Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff6_coeff6_value_SHIFT 0
#define coeff6_coeff6_value_WIDTH 24

 coeff6_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff59Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff59_coeff59_value_SHIFT 0
#define coeff59_coeff59_value_WIDTH 24

 coeff59_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff58Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff58_coeff58_value_SHIFT 0
#define coeff58_coeff58_value_WIDTH 24

 coeff58_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff57Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff57_coeff57_value_SHIFT 0
#define coeff57_coeff57_value_WIDTH 24

 coeff57_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff56Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff56_coeff56_value_SHIFT 0
#define coeff56_coeff56_value_WIDTH 24

 coeff56_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff55Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff55_coeff55_value_SHIFT 0
#define coeff55_coeff55_value_WIDTH 24

 coeff55_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff54Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff54_coeff54_value_SHIFT 0
#define coeff54_coeff54_value_WIDTH 24

 coeff54_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff53Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff53_coeff53_value_SHIFT 0
#define coeff53_coeff53_value_WIDTH 24

 coeff53_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff52Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff52_coeff52_value_SHIFT 0
#define coeff52_coeff52_value_WIDTH 24

 coeff52_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff51Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff51_coeff51_value_SHIFT 0
#define coeff51_coeff51_value_WIDTH 24

 coeff51_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff50Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff50_coeff50_value_SHIFT 0
#define coeff50_coeff50_value_WIDTH 24

 coeff50_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff5Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff5_coeff5_value_SHIFT 0
#define coeff5_coeff5_value_WIDTH 24

 coeff5_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff49Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff49_coeff49_value_SHIFT 0
#define coeff49_coeff49_value_WIDTH 24

 coeff49_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff48Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff48_coeff48_value_SHIFT 0
#define coeff48_coeff48_value_WIDTH 24

 coeff48_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff47Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff47_coeff47_value_SHIFT 0
#define coeff47_coeff47_value_WIDTH 24

 coeff47_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff46Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff46_coeff46_value_SHIFT 0
#define coeff46_coeff46_value_WIDTH 24

 coeff46_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff45Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff45_coeff45_value_SHIFT 0
#define coeff45_coeff45_value_WIDTH 24

 coeff45_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff44Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff44_coeff44_value_SHIFT 0
#define coeff44_coeff44_value_WIDTH 24

 coeff44_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff43Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff43_coeff43_value_SHIFT 0
#define coeff43_coeff43_value_WIDTH 24

 coeff43_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff42Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff42_coeff42_value_SHIFT 0
#define coeff42_coeff42_value_WIDTH 24

 coeff42_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff41Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff41_coeff41_value_SHIFT 0
#define coeff41_coeff41_value_WIDTH 24

 coeff41_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff40Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff40_coeff40_value_SHIFT 0
#define coeff40_coeff40_value_WIDTH 24

 coeff40_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff4Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff4_coeff4_value_SHIFT 0
#define coeff4_coeff4_value_WIDTH 24

 coeff4_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff39Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff39_coeff39_value_SHIFT 0
#define coeff39_coeff39_value_WIDTH 24

 coeff39_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff38Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff38_coeff38_value_SHIFT 0
#define coeff38_coeff38_value_WIDTH 24

 coeff38_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff37Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff37_coeff37_value_SHIFT 0
#define coeff37_coeff37_value_WIDTH 24

 coeff37_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff36Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff36_coeff36_value_SHIFT 0
#define coeff36_coeff36_value_WIDTH 24

 coeff36_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff35Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff35_coeff35_value_SHIFT 0
#define coeff35_coeff35_value_WIDTH 24

 coeff35_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff34Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff34_coeff34_value_SHIFT 0
#define coeff34_coeff34_value_WIDTH 24

 coeff34_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff33Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff33_coeff33_value_SHIFT 0
#define coeff33_coeff33_value_WIDTH 24

 coeff33_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff32Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff32_coeff32_value_SHIFT 0
#define coeff32_coeff32_value_WIDTH 24

 coeff32_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff31Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff31_coeff31_value_SHIFT 0
#define coeff31_coeff31_value_WIDTH 24

 coeff31_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff30Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff30_coeff30_value_SHIFT 0
#define coeff30_coeff30_value_WIDTH 24

 coeff30_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff3Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff3_coeff3_value_SHIFT 0
#define coeff3_coeff3_value_WIDTH 24

 coeff3_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff29Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff29_coeff29_value_SHIFT 0
#define coeff29_coeff29_value_WIDTH 24

 coeff29_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff28Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff28_coeff28_value_SHIFT 0
#define coeff28_coeff28_value_WIDTH 24

 coeff28_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff27Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff27_coeff27_value_SHIFT 0
#define coeff27_coeff27_value_WIDTH 24

 coeff27_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff26Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff26_coeff26_value_SHIFT 0
#define coeff26_coeff26_value_WIDTH 24

 coeff26_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff255Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff255_coeff255_value_SHIFT 0
#define coeff255_coeff255_value_WIDTH 24

 coeff255_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff254Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff254_coeff254_value_SHIFT 0
#define coeff254_coeff254_value_WIDTH 24

 coeff254_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff253Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff253_coeff253_value_SHIFT 0
#define coeff253_coeff253_value_WIDTH 24

 coeff253_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff252Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff252_coeff252_value_SHIFT 0
#define coeff252_coeff252_value_WIDTH 24

 coeff252_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff251Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff251_coeff251_value_SHIFT 0
#define coeff251_coeff251_value_WIDTH 24

 coeff251_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff250Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff250_coeff250_value_SHIFT 0
#define coeff250_coeff250_value_WIDTH 24

 coeff250_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff25Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff25_coeff25_value_SHIFT 0
#define coeff25_coeff25_value_WIDTH 24

 coeff25_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff249Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff249_coeff249_value_SHIFT 0
#define coeff249_coeff249_value_WIDTH 24

 coeff249_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff248Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff248_coeff248_value_SHIFT 0
#define coeff248_coeff248_value_WIDTH 24

 coeff248_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff247Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff247_coeff247_value_SHIFT 0
#define coeff247_coeff247_value_WIDTH 24

 coeff247_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff246Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff246_coeff246_value_SHIFT 0
#define coeff246_coeff246_value_WIDTH 24

 coeff246_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff245Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff245_coeff245_value_SHIFT 0
#define coeff245_coeff245_value_WIDTH 24

 coeff245_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff244Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff244_coeff244_value_SHIFT 0
#define coeff244_coeff244_value_WIDTH 24

 coeff244_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff243Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff243_coeff243_value_SHIFT 0
#define coeff243_coeff243_value_WIDTH 24

 coeff243_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff242Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff242_coeff242_value_SHIFT 0
#define coeff242_coeff242_value_WIDTH 24

 coeff242_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff241Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff241_coeff241_value_SHIFT 0
#define coeff241_coeff241_value_WIDTH 24

 coeff241_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff240Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff240_coeff240_value_SHIFT 0
#define coeff240_coeff240_value_WIDTH 24

 coeff240_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff24Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff24_coeff24_value_SHIFT 0
#define coeff24_coeff24_value_WIDTH 24

 coeff24_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff239Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff239_coeff239_value_SHIFT 0
#define coeff239_coeff239_value_WIDTH 24

 coeff239_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff238Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff238_coeff238_value_SHIFT 0
#define coeff238_coeff238_value_WIDTH 24

 coeff238_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff237Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff237_coeff237_value_SHIFT 0
#define coeff237_coeff237_value_WIDTH 24

 coeff237_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff236Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff236_coeff236_value_SHIFT 0
#define coeff236_coeff236_value_WIDTH 24

 coeff236_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff235Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff235_coeff235_value_SHIFT 0
#define coeff235_coeff235_value_WIDTH 24

 coeff235_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff234Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff234_coeff234_value_SHIFT 0
#define coeff234_coeff234_value_WIDTH 24

 coeff234_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff233Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff233_coeff233_value_SHIFT 0
#define coeff233_coeff233_value_WIDTH 24

 coeff233_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff232Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff232_coeff232_value_SHIFT 0
#define coeff232_coeff232_value_WIDTH 24

 coeff232_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff231Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff231_coeff231_value_SHIFT 0
#define coeff231_coeff231_value_WIDTH 24

 coeff231_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff230Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff230_coeff230_value_SHIFT 0
#define coeff230_coeff230_value_WIDTH 24

 coeff230_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff23Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff23_coeff23_value_SHIFT 0
#define coeff23_coeff23_value_WIDTH 24

 coeff23_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff229Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff229_coeff229_value_SHIFT 0
#define coeff229_coeff229_value_WIDTH 24

 coeff229_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff228Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff228_coeff228_value_SHIFT 0
#define coeff228_coeff228_value_WIDTH 24

 coeff228_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff227Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff227_coeff227_value_SHIFT 0
#define coeff227_coeff227_value_WIDTH 24

 coeff227_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff226Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff226_coeff226_value_SHIFT 0
#define coeff226_coeff226_value_WIDTH 24

 coeff226_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff225Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff225_coeff225_value_SHIFT 0
#define coeff225_coeff225_value_WIDTH 24

 coeff225_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff224Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff224_coeff224_value_SHIFT 0
#define coeff224_coeff224_value_WIDTH 24

 coeff224_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff223Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff223_coeff223_value_SHIFT 0
#define coeff223_coeff223_value_WIDTH 24

 coeff223_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff222Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff222_coeff222_value_SHIFT 0
#define coeff222_coeff222_value_WIDTH 24

 coeff222_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff221Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff221_coeff221_value_SHIFT 0
#define coeff221_coeff221_value_WIDTH 24

 coeff221_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff220Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff220_coeff220_value_SHIFT 0
#define coeff220_coeff220_value_WIDTH 24

 coeff220_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff22Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff22_coeff22_value_SHIFT 0
#define coeff22_coeff22_value_WIDTH 24

 coeff22_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff219Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff219_coeff219_value_SHIFT 0
#define coeff219_coeff219_value_WIDTH 24

 coeff219_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff218Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff218_coeff218_value_SHIFT 0
#define coeff218_coeff218_value_WIDTH 24

 coeff218_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff217Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff217_coeff217_value_SHIFT 0
#define coeff217_coeff217_value_WIDTH 24

 coeff217_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff216Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff216_coeff216_value_SHIFT 0
#define coeff216_coeff216_value_WIDTH 24

 coeff216_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff215Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff215_coeff215_value_SHIFT 0
#define coeff215_coeff215_value_WIDTH 24

 coeff215_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff214Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff214_coeff214_value_SHIFT 0
#define coeff214_coeff214_value_WIDTH 24

 coeff214_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff213Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff213_coeff213_value_SHIFT 0
#define coeff213_coeff213_value_WIDTH 24

 coeff213_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff212Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff212_coeff212_value_SHIFT 0
#define coeff212_coeff212_value_WIDTH 24

 coeff212_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff211Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff211_coeff211_value_SHIFT 0
#define coeff211_coeff211_value_WIDTH 24

 coeff211_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff210Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff210_coeff210_value_SHIFT 0
#define coeff210_coeff210_value_WIDTH 24

 coeff210_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff21Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff21_coeff21_value_SHIFT 0
#define coeff21_coeff21_value_WIDTH 24

 coeff21_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff209Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff209_coeff209_value_SHIFT 0
#define coeff209_coeff209_value_WIDTH 24

 coeff209_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff208Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff208_coeff208_value_SHIFT 0
#define coeff208_coeff208_value_WIDTH 24

 coeff208_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff207Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff207_coeff207_value_SHIFT 0
#define coeff207_coeff207_value_WIDTH 24

 coeff207_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff206Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff206_coeff206_value_SHIFT 0
#define coeff206_coeff206_value_WIDTH 24

 coeff206_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff205Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff205_coeff205_value_SHIFT 0
#define coeff205_coeff205_value_WIDTH 24

 coeff205_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff204Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff204_coeff204_value_SHIFT 0
#define coeff204_coeff204_value_WIDTH 24

 coeff204_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff203Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff203_coeff203_value_SHIFT 0
#define coeff203_coeff203_value_WIDTH 24

 coeff203_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff202Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff202_coeff202_value_SHIFT 0
#define coeff202_coeff202_value_WIDTH 24

 coeff202_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff201Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff201_coeff201_value_SHIFT 0
#define coeff201_coeff201_value_WIDTH 24

 coeff201_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff200Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff200_coeff200_value_SHIFT 0
#define coeff200_coeff200_value_WIDTH 24

 coeff200_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff20Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff20_coeff20_value_SHIFT 0
#define coeff20_coeff20_value_WIDTH 24

 coeff20_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff2Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff2_coeff2_value_SHIFT 0
#define coeff2_coeff2_value_WIDTH 24

 coeff2_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff199Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff199_coeff199_value_SHIFT 0
#define coeff199_coeff199_value_WIDTH 24

 coeff199_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff198Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff198_coeff198_value_SHIFT 0
#define coeff198_coeff198_value_WIDTH 24

 coeff198_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff197Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff197_coeff197_value_SHIFT 0
#define coeff197_coeff197_value_WIDTH 24

 coeff197_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff196Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff196_coeff196_value_SHIFT 0
#define coeff196_coeff196_value_WIDTH 24

 coeff196_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff195Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff195_coeff195_value_SHIFT 0
#define coeff195_coeff195_value_WIDTH 24

 coeff195_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff194Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff194_coeff194_value_SHIFT 0
#define coeff194_coeff194_value_WIDTH 24

 coeff194_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff193Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff193_coeff193_value_SHIFT 0
#define coeff193_coeff193_value_WIDTH 24

 coeff193_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff192Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff192_coeff192_value_SHIFT 0
#define coeff192_coeff192_value_WIDTH 24

 coeff192_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff191Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff191_coeff191_value_SHIFT 0
#define coeff191_coeff191_value_WIDTH 24

 coeff191_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff190Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff190_coeff190_value_SHIFT 0
#define coeff190_coeff190_value_WIDTH 24

 coeff190_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff19Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff19_coeff19_value_SHIFT 0
#define coeff19_coeff19_value_WIDTH 24

 coeff19_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff189Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff189_coeff189_value_SHIFT 0
#define coeff189_coeff189_value_WIDTH 24

 coeff189_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff188Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff188_coeff188_value_SHIFT 0
#define coeff188_coeff188_value_WIDTH 24

 coeff188_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff187Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff187_coeff187_value_SHIFT 0
#define coeff187_coeff187_value_WIDTH 24

 coeff187_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff186Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff186_coeff186_value_SHIFT 0
#define coeff186_coeff186_value_WIDTH 24

 coeff186_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff185Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff185_coeff185_value_SHIFT 0
#define coeff185_coeff185_value_WIDTH 24

 coeff185_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff184Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff184_coeff184_value_SHIFT 0
#define coeff184_coeff184_value_WIDTH 24

 coeff184_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff183Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff183_coeff183_value_SHIFT 0
#define coeff183_coeff183_value_WIDTH 24

 coeff183_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff182Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff182_coeff182_value_SHIFT 0
#define coeff182_coeff182_value_WIDTH 24

 coeff182_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff181Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff181_coeff181_value_SHIFT 0
#define coeff181_coeff181_value_WIDTH 24

 coeff181_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff180Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff180_coeff180_value_SHIFT 0
#define coeff180_coeff180_value_WIDTH 24

 coeff180_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff18Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff18_coeff18_value_SHIFT 0
#define coeff18_coeff18_value_WIDTH 24

 coeff18_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff179Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff179_coeff179_value_SHIFT 0
#define coeff179_coeff179_value_WIDTH 24

 coeff179_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff178Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff178_coeff178_value_SHIFT 0
#define coeff178_coeff178_value_WIDTH 24

 coeff178_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff177Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff177_coeff177_value_SHIFT 0
#define coeff177_coeff177_value_WIDTH 24

 coeff177_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff176Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff176_coeff176_value_SHIFT 0
#define coeff176_coeff176_value_WIDTH 24

 coeff176_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff175Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff175_coeff175_value_SHIFT 0
#define coeff175_coeff175_value_WIDTH 24

 coeff175_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff174Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff174_coeff174_value_SHIFT 0
#define coeff174_coeff174_value_WIDTH 24

 coeff174_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff173Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff173_coeff173_value_SHIFT 0
#define coeff173_coeff173_value_WIDTH 24

 coeff173_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff172Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff172_coeff172_value_SHIFT 0
#define coeff172_coeff172_value_WIDTH 24

 coeff172_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff171Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff171_coeff171_value_SHIFT 0
#define coeff171_coeff171_value_WIDTH 24

 coeff171_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff170Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff170_coeff170_value_SHIFT 0
#define coeff170_coeff170_value_WIDTH 24

 coeff170_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff17Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff17_coeff17_value_SHIFT 0
#define coeff17_coeff17_value_WIDTH 24

 coeff17_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff169Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff169_coeff169_value_SHIFT 0
#define coeff169_coeff169_value_WIDTH 24

 coeff169_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff168Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff168_coeff168_value_SHIFT 0
#define coeff168_coeff168_value_WIDTH 24

 coeff168_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff167Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff167_coeff167_value_SHIFT 0
#define coeff167_coeff167_value_WIDTH 24

 coeff167_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff166Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff166_coeff166_value_SHIFT 0
#define coeff166_coeff166_value_WIDTH 24

 coeff166_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff165Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff165_coeff165_value_SHIFT 0
#define coeff165_coeff165_value_WIDTH 24

 coeff165_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff164Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff164_coeff164_value_SHIFT 0
#define coeff164_coeff164_value_WIDTH 24

 coeff164_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff163Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff163_coeff163_value_SHIFT 0
#define coeff163_coeff163_value_WIDTH 24

 coeff163_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff162Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff162_coeff162_value_SHIFT 0
#define coeff162_coeff162_value_WIDTH 24

 coeff162_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff161Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff161_coeff161_value_SHIFT 0
#define coeff161_coeff161_value_WIDTH 24

 coeff161_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff160Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff160_coeff160_value_SHIFT 0
#define coeff160_coeff160_value_WIDTH 24

 coeff160_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff16Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff16_coeff16_value_SHIFT 0
#define coeff16_coeff16_value_WIDTH 24

 coeff16_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff159Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff159_coeff159_value_SHIFT 0
#define coeff159_coeff159_value_WIDTH 24

 coeff159_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff158Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff158_coeff158_value_SHIFT 0
#define coeff158_coeff158_value_WIDTH 24

 coeff158_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff157Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff157_coeff157_value_SHIFT 0
#define coeff157_coeff157_value_WIDTH 24

 coeff157_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff156Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff156_coeff156_value_SHIFT 0
#define coeff156_coeff156_value_WIDTH 24

 coeff156_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff155Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff155_coeff155_value_SHIFT 0
#define coeff155_coeff155_value_WIDTH 24

 coeff155_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff154Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff154_coeff154_value_SHIFT 0
#define coeff154_coeff154_value_WIDTH 24

 coeff154_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff153Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff153_coeff153_value_SHIFT 0
#define coeff153_coeff153_value_WIDTH 24

 coeff153_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff152Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff152_coeff152_value_SHIFT 0
#define coeff152_coeff152_value_WIDTH 24

 coeff152_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff151Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff151_coeff151_value_SHIFT 0
#define coeff151_coeff151_value_WIDTH 24

 coeff151_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff150Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff150_coeff150_value_SHIFT 0
#define coeff150_coeff150_value_WIDTH 24

 coeff150_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff15Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff15_coeff15_value_SHIFT 0
#define coeff15_coeff15_value_WIDTH 24

 coeff15_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff149Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff149_coeff149_value_SHIFT 0
#define coeff149_coeff149_value_WIDTH 24

 coeff149_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff148Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff148_coeff148_value_SHIFT 0
#define coeff148_coeff148_value_WIDTH 24

 coeff148_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff147Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff147_coeff147_value_SHIFT 0
#define coeff147_coeff147_value_WIDTH 24

 coeff147_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff146Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff146_coeff146_value_SHIFT 0
#define coeff146_coeff146_value_WIDTH 24

 coeff146_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff145Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff145_coeff145_value_SHIFT 0
#define coeff145_coeff145_value_WIDTH 24

 coeff145_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff144Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff144_coeff144_value_SHIFT 0
#define coeff144_coeff144_value_WIDTH 24

 coeff144_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff143Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff143_coeff143_value_SHIFT 0
#define coeff143_coeff143_value_WIDTH 24

 coeff143_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff142Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff142_coeff142_value_SHIFT 0
#define coeff142_coeff142_value_WIDTH 24

 coeff142_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff141Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff141_coeff141_value_SHIFT 0
#define coeff141_coeff141_value_WIDTH 24

 coeff141_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff140Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff140_coeff140_value_SHIFT 0
#define coeff140_coeff140_value_WIDTH 24

 coeff140_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff14Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff14_coeff14_value_SHIFT 0
#define coeff14_coeff14_value_WIDTH 24

 coeff14_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff139Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff139_coeff139_value_SHIFT 0
#define coeff139_coeff139_value_WIDTH 24

 coeff139_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff138Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff138_coeff138_value_SHIFT 0
#define coeff138_coeff138_value_WIDTH 24

 coeff138_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff137Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff137_coeff137_value_SHIFT 0
#define coeff137_coeff137_value_WIDTH 24

 coeff137_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff136Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff136_coeff136_value_SHIFT 0
#define coeff136_coeff136_value_WIDTH 24

 coeff136_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff135Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff135_coeff135_value_SHIFT 0
#define coeff135_coeff135_value_WIDTH 24

 coeff135_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff134Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff134_coeff134_value_SHIFT 0
#define coeff134_coeff134_value_WIDTH 24

 coeff134_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff133Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff133_coeff133_value_SHIFT 0
#define coeff133_coeff133_value_WIDTH 24

 coeff133_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff132Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff132_coeff132_value_SHIFT 0
#define coeff132_coeff132_value_WIDTH 24

 coeff132_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff131Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff131_coeff131_value_SHIFT 0
#define coeff131_coeff131_value_WIDTH 24

 coeff131_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff130Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff130_coeff130_value_SHIFT 0
#define coeff130_coeff130_value_WIDTH 24

 coeff130_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff13Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff13_coeff13_value_SHIFT 0
#define coeff13_coeff13_value_WIDTH 24

 coeff13_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff129Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff129_coeff129_value_SHIFT 0
#define coeff129_coeff129_value_WIDTH 24

 coeff129_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff128Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff128_coeff128_value_SHIFT 0
#define coeff128_coeff128_value_WIDTH 24

 coeff128_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff127Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff127_coeff127_value_SHIFT 0
#define coeff127_coeff127_value_WIDTH 24

 coeff127_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff126Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff126_coeff126_value_SHIFT 0
#define coeff126_coeff126_value_WIDTH 24

 coeff126_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff125Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff125_coeff125_value_SHIFT 0
#define coeff125_coeff125_value_WIDTH 24

 coeff125_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff124Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff124_coeff124_value_SHIFT 0
#define coeff124_coeff124_value_WIDTH 24

 coeff124_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff123Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff123_coeff123_value_SHIFT 0
#define coeff123_coeff123_value_WIDTH 24

 coeff123_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff122Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff122_coeff122_value_SHIFT 0
#define coeff122_coeff122_value_WIDTH 24

 coeff122_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff121Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff121_coeff121_value_SHIFT 0
#define coeff121_coeff121_value_WIDTH 24

 coeff121_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff120Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff120_coeff120_value_SHIFT 0
#define coeff120_coeff120_value_WIDTH 24

 coeff120_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff12Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff12_coeff12_value_SHIFT 0
#define coeff12_coeff12_value_WIDTH 24

 coeff12_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff119Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff119_coeff119_value_SHIFT 0
#define coeff119_coeff119_value_WIDTH 24

 coeff119_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff118Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff118_coeff118_value_SHIFT 0
#define coeff118_coeff118_value_WIDTH 24

 coeff118_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff117Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff117_coeff117_value_SHIFT 0
#define coeff117_coeff117_value_WIDTH 24

 coeff117_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff116Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff116_coeff116_value_SHIFT 0
#define coeff116_coeff116_value_WIDTH 24

 coeff116_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff115Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff115_coeff115_value_SHIFT 0
#define coeff115_coeff115_value_WIDTH 24

 coeff115_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff114Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff114_coeff114_value_SHIFT 0
#define coeff114_coeff114_value_WIDTH 24

 coeff114_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff113Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff113_coeff113_value_SHIFT 0
#define coeff113_coeff113_value_WIDTH 24

 coeff113_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff112Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff112_coeff112_value_SHIFT 0
#define coeff112_coeff112_value_WIDTH 24

 coeff112_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff111Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff111_coeff111_value_SHIFT 0
#define coeff111_coeff111_value_WIDTH 24

 coeff111_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff110Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff110_coeff110_value_SHIFT 0
#define coeff110_coeff110_value_WIDTH 24

 coeff110_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff11Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff11_coeff11_value_SHIFT 0
#define coeff11_coeff11_value_WIDTH 24

 coeff11_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff109Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff109_coeff109_value_SHIFT 0
#define coeff109_coeff109_value_WIDTH 24

 coeff109_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff108Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff108_coeff108_value_SHIFT 0
#define coeff108_coeff108_value_WIDTH 24

 coeff108_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff107Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff107_coeff107_value_SHIFT 0
#define coeff107_coeff107_value_WIDTH 24

 coeff107_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff106Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff106_coeff106_value_SHIFT 0
#define coeff106_coeff106_value_WIDTH 24

 coeff106_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff105Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff105_coeff105_value_SHIFT 0
#define coeff105_coeff105_value_WIDTH 24

 coeff105_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff104Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff104_coeff104_value_SHIFT 0
#define coeff104_coeff104_value_WIDTH 24

 coeff104_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff103Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff103_coeff103_value_SHIFT 0
#define coeff103_coeff103_value_WIDTH 24

 coeff103_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff102Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff102_coeff102_value_SHIFT 0
#define coeff102_coeff102_value_WIDTH 24

 coeff102_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff101Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff101_coeff101_value_SHIFT 0
#define coeff101_coeff101_value_WIDTH 24

 coeff101_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff100Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff100_coeff100_value_SHIFT 0
#define coeff100_coeff100_value_WIDTH 24

 coeff100_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff10Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff10_coeff10_value_SHIFT 0
#define coeff10_coeff10_value_WIDTH 24

 coeff10_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff1Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff1_coeff1_value_SHIFT 0
#define coeff1_coeff1_value_WIDTH 24

 coeff1_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

union coeff0Reg {
 struct { uint32_t

 /* sorting 1 */
#define coeff0_coeff0_value_SHIFT 0
#define coeff0_coeff0_value_WIDTH 24

 coeff0_value:24, /*[23:0]  */
 hole0:8;
 } bits;

 uint32_t value;
};

struct audio_resampler {
 union coeff0Reg coeff0; /* +0x00000000  */
 union coeff1Reg coeff1; /* +0x00000004  */
 union coeff2Reg coeff2; /* +0x00000008  */
 union coeff3Reg coeff3; /* +0x0000000c  */
 union coeff4Reg coeff4; /* +0x00000010  */
 union coeff5Reg coeff5; /* +0x00000014  */
 union coeff6Reg coeff6; /* +0x00000018  */
 union coeff7Reg coeff7; /* +0x0000001c  */
 union coeff8Reg coeff8; /* +0x00000020  */
 union coeff9Reg coeff9; /* +0x00000024  */
 union coeff10Reg coeff10; /* +0x00000028  */
 union coeff11Reg coeff11; /* +0x0000002c  */
 union coeff12Reg coeff12; /* +0x00000030  */
 union coeff13Reg coeff13; /* +0x00000034  */
 union coeff14Reg coeff14; /* +0x00000038  */
 union coeff15Reg coeff15; /* +0x0000003c  */
 union coeff16Reg coeff16; /* +0x00000040  */
 union coeff17Reg coeff17; /* +0x00000044  */
 union coeff18Reg coeff18; /* +0x00000048  */
 union coeff19Reg coeff19; /* +0x0000004c  */
 union coeff20Reg coeff20; /* +0x00000050  */
 union coeff21Reg coeff21; /* +0x00000054  */
 union coeff22Reg coeff22; /* +0x00000058  */
 union coeff23Reg coeff23; /* +0x0000005c  */
 union coeff24Reg coeff24; /* +0x00000060  */
 union coeff25Reg coeff25; /* +0x00000064  */
 union coeff26Reg coeff26; /* +0x00000068  */
 union coeff27Reg coeff27; /* +0x0000006c  */
 union coeff28Reg coeff28; /* +0x00000070  */
 union coeff29Reg coeff29; /* +0x00000074  */
 union coeff30Reg coeff30; /* +0x00000078  */
 union coeff31Reg coeff31; /* +0x0000007c  */
 union coeff32Reg coeff32; /* +0x00000080  */
 union coeff33Reg coeff33; /* +0x00000084  */
 union coeff34Reg coeff34; /* +0x00000088  */
 union coeff35Reg coeff35; /* +0x0000008c  */
 union coeff36Reg coeff36; /* +0x00000090  */
 union coeff37Reg coeff37; /* +0x00000094  */
 union coeff38Reg coeff38; /* +0x00000098  */
 union coeff39Reg coeff39; /* +0x0000009c  */
 union coeff40Reg coeff40; /* +0x000000a0  */
 union coeff41Reg coeff41; /* +0x000000a4  */
 union coeff42Reg coeff42; /* +0x000000a8  */
 union coeff43Reg coeff43; /* +0x000000ac  */
 union coeff44Reg coeff44; /* +0x000000b0  */
 union coeff45Reg coeff45; /* +0x000000b4  */
 union coeff46Reg coeff46; /* +0x000000b8  */
 union coeff47Reg coeff47; /* +0x000000bc  */
 union coeff48Reg coeff48; /* +0x000000c0  */
 union coeff49Reg coeff49; /* +0x000000c4  */
 union coeff50Reg coeff50; /* +0x000000c8  */
 union coeff51Reg coeff51; /* +0x000000cc  */
 union coeff52Reg coeff52; /* +0x000000d0  */
 union coeff53Reg coeff53; /* +0x000000d4  */
 union coeff54Reg coeff54; /* +0x000000d8  */
 union coeff55Reg coeff55; /* +0x000000dc  */
 union coeff56Reg coeff56; /* +0x000000e0  */
 union coeff57Reg coeff57; /* +0x000000e4  */
 union coeff58Reg coeff58; /* +0x000000e8  */
 union coeff59Reg coeff59; /* +0x000000ec  */
 union coeff60Reg coeff60; /* +0x000000f0  */
 union coeff61Reg coeff61; /* +0x000000f4  */
 union coeff62Reg coeff62; /* +0x000000f8  */
 union coeff63Reg coeff63; /* +0x000000fc  */
 union coeff64Reg coeff64; /* +0x00000100  */
 union coeff65Reg coeff65; /* +0x00000104  */
 union coeff66Reg coeff66; /* +0x00000108  */
 union coeff67Reg coeff67; /* +0x0000010c  */
 union coeff68Reg coeff68; /* +0x00000110  */
 union coeff69Reg coeff69; /* +0x00000114  */
 union coeff70Reg coeff70; /* +0x00000118  */
 union coeff71Reg coeff71; /* +0x0000011c  */
 union coeff72Reg coeff72; /* +0x00000120  */
 union coeff73Reg coeff73; /* +0x00000124  */
 union coeff74Reg coeff74; /* +0x00000128  */
 union coeff75Reg coeff75; /* +0x0000012c  */
 union coeff76Reg coeff76; /* +0x00000130  */
 union coeff77Reg coeff77; /* +0x00000134  */
 union coeff78Reg coeff78; /* +0x00000138  */
 union coeff79Reg coeff79; /* +0x0000013c  */
 union coeff80Reg coeff80; /* +0x00000140  */
 union coeff81Reg coeff81; /* +0x00000144  */
 union coeff82Reg coeff82; /* +0x00000148  */
 union coeff83Reg coeff83; /* +0x0000014c  */
 union coeff84Reg coeff84; /* +0x00000150  */
 union coeff85Reg coeff85; /* +0x00000154  */
 union coeff86Reg coeff86; /* +0x00000158  */
 union coeff87Reg coeff87; /* +0x0000015c  */
 union coeff88Reg coeff88; /* +0x00000160  */
 union coeff89Reg coeff89; /* +0x00000164  */
 union coeff90Reg coeff90; /* +0x00000168  */
 union coeff91Reg coeff91; /* +0x0000016c  */
 union coeff92Reg coeff92; /* +0x00000170  */
 union coeff93Reg coeff93; /* +0x00000174  */
 union coeff94Reg coeff94; /* +0x00000178  */
 union coeff95Reg coeff95; /* +0x0000017c  */
 union coeff96Reg coeff96; /* +0x00000180  */
 union coeff97Reg coeff97; /* +0x00000184  */
 union coeff98Reg coeff98; /* +0x00000188  */
 union coeff99Reg coeff99; /* +0x0000018c  */
 union coeff100Reg coeff100; /* +0x00000190  */
 union coeff101Reg coeff101; /* +0x00000194  */
 union coeff102Reg coeff102; /* +0x00000198  */
 union coeff103Reg coeff103; /* +0x0000019c  */
 union coeff104Reg coeff104; /* +0x000001a0  */
 union coeff105Reg coeff105; /* +0x000001a4  */
 union coeff106Reg coeff106; /* +0x000001a8  */
 union coeff107Reg coeff107; /* +0x000001ac  */
 union coeff108Reg coeff108; /* +0x000001b0  */
 union coeff109Reg coeff109; /* +0x000001b4  */
 union coeff110Reg coeff110; /* +0x000001b8  */
 union coeff111Reg coeff111; /* +0x000001bc  */
 union coeff112Reg coeff112; /* +0x000001c0  */
 union coeff113Reg coeff113; /* +0x000001c4  */
 union coeff114Reg coeff114; /* +0x000001c8  */
 union coeff115Reg coeff115; /* +0x000001cc  */
 union coeff116Reg coeff116; /* +0x000001d0  */
 union coeff117Reg coeff117; /* +0x000001d4  */
 union coeff118Reg coeff118; /* +0x000001d8  */
 union coeff119Reg coeff119; /* +0x000001dc  */
 union coeff120Reg coeff120; /* +0x000001e0  */
 union coeff121Reg coeff121; /* +0x000001e4  */
 union coeff122Reg coeff122; /* +0x000001e8  */
 union coeff123Reg coeff123; /* +0x000001ec  */
 union coeff124Reg coeff124; /* +0x000001f0  */
 union coeff125Reg coeff125; /* +0x000001f4  */
 union coeff126Reg coeff126; /* +0x000001f8  */
 union coeff127Reg coeff127; /* +0x000001fc  */
 union coeff128Reg coeff128; /* +0x00000200  */
 union coeff129Reg coeff129; /* +0x00000204  */
 union coeff130Reg coeff130; /* +0x00000208  */
 union coeff131Reg coeff131; /* +0x0000020c  */
 union coeff132Reg coeff132; /* +0x00000210  */
 union coeff133Reg coeff133; /* +0x00000214  */
 union coeff134Reg coeff134; /* +0x00000218  */
 union coeff135Reg coeff135; /* +0x0000021c  */
 union coeff136Reg coeff136; /* +0x00000220  */
 union coeff137Reg coeff137; /* +0x00000224  */
 union coeff138Reg coeff138; /* +0x00000228  */
 union coeff139Reg coeff139; /* +0x0000022c  */
 union coeff140Reg coeff140; /* +0x00000230  */
 union coeff141Reg coeff141; /* +0x00000234  */
 union coeff142Reg coeff142; /* +0x00000238  */
 union coeff143Reg coeff143; /* +0x0000023c  */
 union coeff144Reg coeff144; /* +0x00000240  */
 union coeff145Reg coeff145; /* +0x00000244  */
 union coeff146Reg coeff146; /* +0x00000248  */
 union coeff147Reg coeff147; /* +0x0000024c  */
 union coeff148Reg coeff148; /* +0x00000250  */
 union coeff149Reg coeff149; /* +0x00000254  */
 union coeff150Reg coeff150; /* +0x00000258  */
 union coeff151Reg coeff151; /* +0x0000025c  */
 union coeff152Reg coeff152; /* +0x00000260  */
 union coeff153Reg coeff153; /* +0x00000264  */
 union coeff154Reg coeff154; /* +0x00000268  */
 union coeff155Reg coeff155; /* +0x0000026c  */
 union coeff156Reg coeff156; /* +0x00000270  */
 union coeff157Reg coeff157; /* +0x00000274  */
 union coeff158Reg coeff158; /* +0x00000278  */
 union coeff159Reg coeff159; /* +0x0000027c  */
 union coeff160Reg coeff160; /* +0x00000280  */
 union coeff161Reg coeff161; /* +0x00000284  */
 union coeff162Reg coeff162; /* +0x00000288  */
 union coeff163Reg coeff163; /* +0x0000028c  */
 union coeff164Reg coeff164; /* +0x00000290  */
 union coeff165Reg coeff165; /* +0x00000294  */
 union coeff166Reg coeff166; /* +0x00000298  */
 union coeff167Reg coeff167; /* +0x0000029c  */
 union coeff168Reg coeff168; /* +0x000002a0  */
 union coeff169Reg coeff169; /* +0x000002a4  */
 union coeff170Reg coeff170; /* +0x000002a8  */
 union coeff171Reg coeff171; /* +0x000002ac  */
 union coeff172Reg coeff172; /* +0x000002b0  */
 union coeff173Reg coeff173; /* +0x000002b4  */
 union coeff174Reg coeff174; /* +0x000002b8  */
 union coeff175Reg coeff175; /* +0x000002bc  */
 union coeff176Reg coeff176; /* +0x000002c0  */
 union coeff177Reg coeff177; /* +0x000002c4  */
 union coeff178Reg coeff178; /* +0x000002c8  */
 union coeff179Reg coeff179; /* +0x000002cc  */
 union coeff180Reg coeff180; /* +0x000002d0  */
 union coeff181Reg coeff181; /* +0x000002d4  */
 union coeff182Reg coeff182; /* +0x000002d8  */
 union coeff183Reg coeff183; /* +0x000002dc  */
 union coeff184Reg coeff184; /* +0x000002e0  */
 union coeff185Reg coeff185; /* +0x000002e4  */
 union coeff186Reg coeff186; /* +0x000002e8  */
 union coeff187Reg coeff187; /* +0x000002ec  */
 union coeff188Reg coeff188; /* +0x000002f0  */
 union coeff189Reg coeff189; /* +0x000002f4  */
 union coeff190Reg coeff190; /* +0x000002f8  */
 union coeff191Reg coeff191; /* +0x000002fc  */
 union coeff192Reg coeff192; /* +0x00000300  */
 union coeff193Reg coeff193; /* +0x00000304  */
 union coeff194Reg coeff194; /* +0x00000308  */
 union coeff195Reg coeff195; /* +0x0000030c  */
 union coeff196Reg coeff196; /* +0x00000310  */
 union coeff197Reg coeff197; /* +0x00000314  */
 union coeff198Reg coeff198; /* +0x00000318  */
 union coeff199Reg coeff199; /* +0x0000031c  */
 union coeff200Reg coeff200; /* +0x00000320  */
 union coeff201Reg coeff201; /* +0x00000324  */
 union coeff202Reg coeff202; /* +0x00000328  */
 union coeff203Reg coeff203; /* +0x0000032c  */
 union coeff204Reg coeff204; /* +0x00000330  */
 union coeff205Reg coeff205; /* +0x00000334  */
 union coeff206Reg coeff206; /* +0x00000338  */
 union coeff207Reg coeff207; /* +0x0000033c  */
 union coeff208Reg coeff208; /* +0x00000340  */
 union coeff209Reg coeff209; /* +0x00000344  */
 union coeff210Reg coeff210; /* +0x00000348  */
 union coeff211Reg coeff211; /* +0x0000034c  */
 union coeff212Reg coeff212; /* +0x00000350  */
 union coeff213Reg coeff213; /* +0x00000354  */
 union coeff214Reg coeff214; /* +0x00000358  */
 union coeff215Reg coeff215; /* +0x0000035c  */
 union coeff216Reg coeff216; /* +0x00000360  */
 union coeff217Reg coeff217; /* +0x00000364  */
 union coeff218Reg coeff218; /* +0x00000368  */
 union coeff219Reg coeff219; /* +0x0000036c  */
 union coeff220Reg coeff220; /* +0x00000370  */
 union coeff221Reg coeff221; /* +0x00000374  */
 union coeff222Reg coeff222; /* +0x00000378  */
 union coeff223Reg coeff223; /* +0x0000037c  */
 union coeff224Reg coeff224; /* +0x00000380  */
 union coeff225Reg coeff225; /* +0x00000384  */
 union coeff226Reg coeff226; /* +0x00000388  */
 union coeff227Reg coeff227; /* +0x0000038c  */
 union coeff228Reg coeff228; /* +0x00000390  */
 union coeff229Reg coeff229; /* +0x00000394  */
 union coeff230Reg coeff230; /* +0x00000398  */
 union coeff231Reg coeff231; /* +0x0000039c  */
 union coeff232Reg coeff232; /* +0x000003a0  */
 union coeff233Reg coeff233; /* +0x000003a4  */
 union coeff234Reg coeff234; /* +0x000003a8  */
 union coeff235Reg coeff235; /* +0x000003ac  */
 union coeff236Reg coeff236; /* +0x000003b0  */
 union coeff237Reg coeff237; /* +0x000003b4  */
 union coeff238Reg coeff238; /* +0x000003b8  */
 union coeff239Reg coeff239; /* +0x000003bc  */
 union coeff240Reg coeff240; /* +0x000003c0  */
 union coeff241Reg coeff241; /* +0x000003c4  */
 union coeff242Reg coeff242; /* +0x000003c8  */
 union coeff243Reg coeff243; /* +0x000003cc  */
 union coeff244Reg coeff244; /* +0x000003d0  */
 union coeff245Reg coeff245; /* +0x000003d4  */
 union coeff246Reg coeff246; /* +0x000003d8  */
 union coeff247Reg coeff247; /* +0x000003dc  */
 union coeff248Reg coeff248; /* +0x000003e0  */
 union coeff249Reg coeff249; /* +0x000003e4  */
 union coeff250Reg coeff250; /* +0x000003e8  */
 union coeff251Reg coeff251; /* +0x000003ec  */
 union coeff252Reg coeff252; /* +0x000003f0  */
 union coeff253Reg coeff253; /* +0x000003f4  */
 union coeff254Reg coeff254; /* +0x000003f8  */
 union coeff255Reg coeff255; /* +0x000003fc  */
 union configReg config; /* +0x00000400  */
 union scale_factorReg scale_factor; /* +0x00000404  */
 union init_phaseReg init_phase; /* +0x00000408  */
 union out_sizeReg out_size; /* +0x0000040c  */
 union statusReg status; /* +0x00000410  */
};
