/* autogenerated with parsecfg: do not edit. */

union voip_clk_ctrlReg {
 struct { uint32_t

 /* sorting 1 */
#define voip_clk_ctrl_voip_clk_en_SHIFT 0
#define voip_clk_ctrl_voip_clk_en_WIDTH 1

 voip_clk_en:1, /*[0:0]  */
 hole0:31;
 } bits;

 uint32_t value;
};

union clk_mux_ctrlReg {
 struct { uint32_t

 /* sorting 2 */
#define clk_mux_ctrl_value_SHIFT 0
#define clk_mux_ctrl_value_WIDTH 6
#define clk_mux_ctrl_ext_SHIFT 6
#define clk_mux_ctrl_ext_WIDTH 2

 value:6, /*[5:0]  */
 ext:2, /*[7:6]  */
 hole0:24;
 } bits;

 uint32_t value;
};

struct audio_io_clk_gen_clk {
 union clk_mux_ctrlReg clk_mux_ctrl; /* +0x00000000  */
 uint32_t aux_clk_count; /* +0x00000004  */
 union voip_clk_ctrlReg voip_clk_ctrl; /* +0x00000008 ,NO_TEST */
 uint32_t voip_clk_hi; /* +0x0000000c ,NO_TEST */
 uint32_t voip_clk_low; /* +0x00000010 ,NO_TEST */
};
