/* autogenerated with parsecfg: do not edit. */

union spdif_in_irq_countReg {
 struct { uint32_t

 /* sorting 1 */
#define spdif_in_irq_count_spdif_in_irq_count16_SHIFT 0
#define spdif_in_irq_count_spdif_in_irq_count16_WIDTH 16

 spdif_in_irq_count16:16, /*[15:0]  */
 hole0:16;
 } bits;

 uint32_t value;
};

union spdif_in_data_ctrlReg {
 struct { uint32_t

 /* sorting 4 */
#define spdif_in_data_ctrl_data_en_SHIFT 0
#define spdif_in_data_ctrl_data_en_WIDTH 2
#define spdif_in_data_ctrl_clk_ctrl_SHIFT 2
#define spdif_in_data_ctrl_clk_ctrl_WIDTH 2
#define spdif_in_data_ctrl_drop_invalid_SHIFT 4
#define spdif_in_data_ctrl_drop_invalid_WIDTH 1
#define spdif_in_data_ctrl_data_format_SHIFT 5
#define spdif_in_data_ctrl_data_format_WIDTH 2

 data_en:2, /*[1:0] ,NO_TEST */
 clk_ctrl:2, /*[3:2]  */
 drop_invalid:1, /*[4:4]  */
 data_format:2, /*[6:5]  */
 hole0:25;
 } bits;

 uint32_t value;
};

union spdif_in_clk_recover_ctrlReg {
 struct { uint32_t

 /* sorting 2 */
#define spdif_in_clk_recover_ctrl_lsb_SHIFT 0
#define spdif_in_clk_recover_ctrl_lsb_WIDTH 10
#define spdif_in_clk_recover_ctrl_msb_SHIFT 16
#define spdif_in_clk_recover_ctrl_msb_WIDTH 10

 lsb:10, /*[9:0]  */
 hole0:6,
 msb:10, /*[25:16]  */
 hole1:6;
 } bits;

 uint32_t value;
};

struct audio_io_spdif_in {
 union spdif_in_data_ctrlReg spdif_in_data_ctrl; /* +0x00000000  */
 uint32_t spdif_in_irq_ctrl; /* +0x00000004 ,NO_TEST */
 uint32_t spdif_in_clk_status0; /* +0x00000008 ,RO */
 uint32_t spdif_in_clk_status1; /* +0x0000000c ,RO */
 union spdif_in_clk_recover_ctrlReg spdif_in_clk_recover_ctrl; /* +0x00000010  */
 uint32_t spdif_in_count; /* +0x00000014  */
 union spdif_in_irq_countReg spdif_in_irq_count; /* +0x00000018  */
};
