/* autogenerated with parsemap: do not edit. */
struct audio_io_lbus_address_decoder_mem {
                              uint32_t pad0[1036288/4];
#define audio_io_lbus_address_decoder_mem_dispatch_OFF 0x000fd000
/* [0x000fd000,0x000fd400[ */ struct { struct dispatch_det d; uint32_t w[(0x00000400-sizeof(struct dispatch_det))/4]; } _dispatch;
#define audio_io_lbus_address_decoder_mem_in_sbox_OFF 0x000fd400
/* [0x000fd400,0x000fd600[ */ struct { struct in_sbox_det d; uint32_t w[(0x00000200-sizeof(struct in_sbox_det))/4]; } _in_sbox;
#define audio_io_lbus_address_decoder_mem_out_sbox_OFF 0x000fd600
/* [0x000fd600,0x000fd800[ */ struct { struct out_sbox_det d; uint32_t w[(0x00000200-sizeof(struct out_sbox_det))/4]; } _out_sbox;
#define audio_io_lbus_address_decoder_mem_volume_OFF 0x000fd800
/* [0x000fd800,0x000fda00[ */ struct { struct volume_det d; uint32_t w[(0x00000200-sizeof(struct volume_det))/4]; } _volume;
#define audio_io_lbus_address_decoder_mem_io_misc_OFF 0x000fda00
/* [0x000fda00,0x000fda60[ */ struct { struct io_misc_det d; uint32_t w[(0x00000060-sizeof(struct io_misc_det))/4]; } _io_misc;
                              uint32_t pad1[32/4];
#define audio_io_lbus_address_decoder_mem_irq_ctrl_OFF 0x000fda80
/* [0x000fda80,0x000fdaa0[ */ struct { struct irq_ctrl_det d; uint32_t w[(0x00000020-sizeof(struct irq_ctrl_det))/4]; } _irq_ctrl;
                              uint32_t pad2[96/4];
#define audio_io_lbus_address_decoder_mem_clk_gen_OFF 0x000fdb00
/* [0x000fdb00,0x000fdb80[ */ struct { struct clk_gen_det d; uint32_t w[(0x00000080-sizeof(struct clk_gen_det))/4]; } _clk_gen;
                              uint32_t pad3[128/4];
#define audio_io_lbus_address_decoder_mem_out_i2s_main_OFF 0x000fdc00
/* [0x000fdc00,0x000fdc40[ */ struct { struct out_i2s_main_det d; uint32_t w[(0x00000040-sizeof(struct out_i2s_main_det))/4]; } _out_i2s_main;
#define audio_io_lbus_address_decoder_mem_out_i2s_seco_OFF 0x000fdc40
/* [0x000fdc40,0x000fdc80[ */ struct { struct out_i2s_seco_det d; uint32_t w[(0x00000040-sizeof(struct out_i2s_seco_det))/4]; } _out_i2s_seco;
#define audio_io_lbus_address_decoder_mem_out_i2s_hdmitx0_OFF 0x000fdc80
/* [0x000fdc80,0x000fdcc0[ */ struct { struct out_i2s_hdmitx0_det d; uint32_t w[(0x00000040-sizeof(struct out_i2s_hdmitx0_det))/4]; } _out_i2s_hdmitx0;
#define audio_io_lbus_address_decoder_mem_out_spdif_OFF 0x000fdcc0
/* [0x000fdcc0,0x000fdd00[ */ struct { struct out_spdif_det d; uint32_t w[(0x00000040-sizeof(struct out_spdif_det))/4]; } _out_spdif;
#define audio_io_lbus_address_decoder_mem_out_i2s_voip_OFF 0x000fdd00
/* [0x000fdd00,0x000fdd40[ */ struct { struct out_i2s_voip_det d; uint32_t w[(0x00000040-sizeof(struct out_i2s_voip_det))/4]; } _out_i2s_voip;
                              uint32_t pad4[192/4];
#define audio_io_lbus_address_decoder_mem_in_i2s_main_OFF 0x000fde00
/* [0x000fde00,0x000fde40[ */ struct { struct in_i2s_main_det d; uint32_t w[(0x00000040-sizeof(struct in_i2s_main_det))/4]; } _in_i2s_main;
#define audio_io_lbus_address_decoder_mem_in_i2s_hdmirx0_OFF 0x000fde40
/* [0x000fde40,0x000fde80[ */ struct { struct in_i2s_hdmirx0_det d; uint32_t w[(0x00000040-sizeof(struct in_i2s_hdmirx0_det))/4]; } _in_i2s_hdmirx0;
#define audio_io_lbus_address_decoder_mem_in_spdif_hdmirx0_OFF 0x000fde80
/* [0x000fde80,0x000fdec0[ */ struct { struct in_spdif_hdmirx0_det d; uint32_t w[(0x00000040-sizeof(struct in_spdif_hdmirx0_det))/4]; } _in_spdif_hdmirx0;
#define audio_io_lbus_address_decoder_mem_in_i2s_hdmirx1_OFF 0x000fdec0
/* [0x000fdec0,0x000fdf00[ */ struct { struct in_i2s_hdmirx1_det d; uint32_t w[(0x00000040-sizeof(struct in_i2s_hdmirx1_det))/4]; } _in_i2s_hdmirx1;
#define audio_io_lbus_address_decoder_mem_in_spdif_hdmirx1_OFF 0x000fdf00
/* [0x000fdf00,0x000fdf40[ */ struct { struct in_spdif_hdmirx1_det d; uint32_t w[(0x00000040-sizeof(struct in_spdif_hdmirx1_det))/4]; } _in_spdif_hdmirx1;
#define audio_io_lbus_address_decoder_mem_in_spdif_OFF 0x000fdf40
/* [0x000fdf40,0x000fdf80[ */ struct { struct in_spdif_det d; uint32_t w[(0x00000040-sizeof(struct in_spdif_det))/4]; } _in_spdif;
#define audio_io_lbus_address_decoder_mem_in_i2s_voip_OFF 0x000fdf80
/* [0x000fdf80,0x000fdfc0[ */ struct { struct in_i2s_voip_det d; uint32_t w[(0x00000040-sizeof(struct in_i2s_voip_det))/4]; } _in_i2s_voip;
};
