/* autogenerated with parsecfg: do not edit. */

struct bvo_reset {
 uint32_t bvo_reset_run_0; /* +0x00000000  */
 uint32_t bvo_reset_datapath_0; /* +0x00000004  */
 uint32_t bvo_reset_timing_0; /* +0x00000008  */
 uint32_t bvo_reset_config_0; /* +0x0000000c  */
 uint32_t pad0[0x0004/4];
 uint32_t bvo_reset_mode_0_0; /* +0x00000014  */
 uint32_t bvo_reset_mode_1_0; /* +0x00000018  */
 uint32_t bvo_reset_vbus_flush; /* +0x0000001c  */
 uint32_t bvo_reset_mbus_flush; /* +0x00000020  */
 uint32_t pad1[0x001c/4];
 uint32_t bvo_reset_run_1; /* +0x00000040  */
 uint32_t bvo_reset_datapath_1; /* +0x00000044  */
 uint32_t bvo_reset_timing_1; /* +0x00000048  */
 uint32_t bvo_reset_config_1; /* +0x0000004c  */
 uint32_t pad2[0x0004/4];
 uint32_t bvo_reset_mode_0_1; /* +0x00000054  */
 uint32_t bvo_reset_mode_1_1; /* +0x00000058  */
};
