/* autogenerated with parsecfg: do not edit. */

union bvo_teletext_ram_configReg {
 struct { uint32_t

 /* sorting 1 */
#define bvo_teletext_ram_config_bvo_teletext_ram_output_nb_SHIFT 0
#define bvo_teletext_ram_config_bvo_teletext_ram_output_nb_WIDTH 1

 bvo_teletext_ram_output_nb:1, /*[0:0]  */
 hole0:31;
 } bits;

 uint32_t value;
};

struct bvo_teletext_ram {
 union bvo_teletext_ram_configReg bvo_teletext_ram_config; /* +0x00000000  */
};
