/* autogenerated with parsecfg: do not edit. */

union bvo_pads_digital_hdmi_out_delay_limitsReg {
 struct { uint32_t

 /* sorting 4 */
#define bvo_pads_digital_hdmi_out_delay_limits_s0_SHIFT 0
#define bvo_pads_digital_hdmi_out_delay_limits_s0_WIDTH 6
#define bvo_pads_digital_hdmi_out_delay_limits_s1_SHIFT 8
#define bvo_pads_digital_hdmi_out_delay_limits_s1_WIDTH 6
#define bvo_pads_digital_hdmi_out_delay_limits_s2_SHIFT 16
#define bvo_pads_digital_hdmi_out_delay_limits_s2_WIDTH 6
#define bvo_pads_digital_hdmi_out_delay_limits_s3_SHIFT 24
#define bvo_pads_digital_hdmi_out_delay_limits_s3_WIDTH 6

 s0:6, /*[5:0]  */
 hole0:2,
 s1:6, /*[13:8]  */
 hole1:2,
 s2:6, /*[21:16]  */
 hole2:2,
 s3:6, /*[29:24]  */
 hole3:2;
 } bits;

 uint32_t value;
};

union bvo_pads_digital_hdmi_dll_configReg {
 struct { uint32_t

 /* sorting 2 */
#define bvo_pads_digital_hdmi_dll_config_g0_SHIFT 0
#define bvo_pads_digital_hdmi_dll_config_g0_WIDTH 3
#define bvo_pads_digital_hdmi_dll_config_g1_SHIFT 8
#define bvo_pads_digital_hdmi_dll_config_g1_WIDTH 1

 g0:3, /*[2:0]  */
 hole0:5,
 g1:1, /*[8:8]  */
 hole1:23;
 } bits;

 uint32_t value;
};

union bvo_pads_digital_hdmi_configReg {
 struct { uint32_t

 /* sorting 1 */
#define bvo_pads_digital_hdmi_config_bvo_pads_digital_hdmi_cfg_SHIFT 0
#define bvo_pads_digital_hdmi_config_bvo_pads_digital_hdmi_cfg_WIDTH 12

 bvo_pads_digital_hdmi_cfg:12, /*[11:0]  */
 hole0:20;
 } bits;

 uint32_t value;
};

struct bvo_pads_digital_hdmi {
 union bvo_pads_digital_hdmi_configReg bvo_pads_digital_hdmi_config; /* +0x00000000  */
 union bvo_pads_digital_hdmi_out_delay_limitsReg bvo_pads_digital_hdmi_out_delay_limits; /* +0x00000004  */
 uint32_t bvo_pads_digital_hdmi_ref_delay_limits; /* +0x00000008  */
 uint32_t bvo_pads_digital_hdmi_ref_delay_init; /* +0x0000000c  */
 union bvo_pads_digital_hdmi_dll_configReg bvo_pads_digital_hdmi_dll_config; /* +0x00000010  */
 uint32_t bvo_pads_digital_hdmi_ref_delay_sync; /* +0x00000014  */
 uint32_t bvo_pads_digital_hdmi_delay_sync; /* +0x00000018  */
};
