/* autogenerated with parsecfg: do not edit. */

union bvo_digital_out_vt_syncReg {
 struct { uint32_t

 /* sorting 3 */
#define bvo_digital_out_vt_sync_er_total_size_SHIFT 0
#define bvo_digital_out_vt_sync_er_total_size_WIDTH 12
#define bvo_digital_out_vt_sync_sync_width_SHIFT 16
#define bvo_digital_out_vt_sync_sync_width_WIDTH 13
#define bvo_digital_out_vt_sync_p_SHIFT 31
#define bvo_digital_out_vt_sync_p_WIDTH 1

 er_total_size:12, /*[11:0]  */
 hole0:4,
 sync_width:13, /*[28:16]  */
 hole1:2,
 p:1; /*[31:31]  */
 } bits;

 uint32_t value;
};

union bvo_digital_out_vsync_coordReg {
 struct { uint32_t

 /* sorting 2 */
#define bvo_digital_out_vsync_coord_vsync_fine_adjust_SHIFT 0
#define bvo_digital_out_vsync_coord_vsync_fine_adjust_WIDTH 16
#define bvo_digital_out_vsync_coord_top_field_height_SHIFT 16
#define bvo_digital_out_vsync_coord_top_field_height_WIDTH 13

 vsync_fine_adjust:16, /*[15:0]  */
 top_field_height:13, /*[28:16]  */
 hole0:3;
 } bits;

 uint32_t value;
};

union bvo_digital_out_tv_starv_default_val2Reg {
 struct { uint32_t

 /* sorting 2 */
#define bvo_digital_out_tv_starv_default_val2_low_SHIFT 0
#define bvo_digital_out_tv_starv_default_val2_low_WIDTH 12
#define bvo_digital_out_tv_starv_default_val2_middle_SHIFT 16
#define bvo_digital_out_tv_starv_default_val2_middle_WIDTH 12

 low:12, /*[11:0]  */
 hole0:4,
 middle:12, /*[27:16]  */
 hole1:4;
 } bits;

 uint32_t value;
};

union bvo_digital_out_tv_starv_default_val1Reg {
 struct { uint32_t

 /* sorting 1 */
#define bvo_digital_out_tv_starv_default_val1_bvo_digital_out_tv_starv_default_high_SHIFT 0
#define bvo_digital_out_tv_starv_default_val1_bvo_digital_out_tv_starv_default_high_WIDTH 12

 bvo_digital_out_tv_starv_default_high:12, /*[11:0]  */
 hole0:20;
 } bits;

 uint32_t value;
};

union bvo_digital_out_tv_starv_configReg {
 struct { uint32_t

 /* sorting 4 */
#define bvo_digital_out_tv_starv_config_xsize_SHIFT 0
#define bvo_digital_out_tv_starv_config_xsize_WIDTH 12
#define bvo_digital_out_tv_starv_config_ysize_SHIFT 12
#define bvo_digital_out_tv_starv_config_ysize_WIDTH 12
#define bvo_digital_out_tv_starv_config_status_SHIFT 27
#define bvo_digital_out_tv_starv_config_status_WIDTH 4
#define bvo_digital_out_tv_starv_config_enable_SHIFT 31
#define bvo_digital_out_tv_starv_config_enable_WIDTH 1

 xsize:12, /*[11:0]  */
 ysize:12, /*[23:12]  */
 hole0:3,
 status:4, /*[30:27]  */
 enable:1; /*[31:31]  */
 } bits;

 uint32_t value;
};

union bvo_digital_out_sync_ext_sync_2Reg {
 struct { uint32_t

 /* sorting 3 */
#define bvo_digital_out_sync_ext_sync_2_pel_delay2_SHIFT 0
#define bvo_digital_out_sync_ext_sync_2_pel_delay2_WIDTH 8
#define bvo_digital_out_sync_ext_sync_2_line_delay2_SHIFT 16
#define bvo_digital_out_sync_ext_sync_2_line_delay2_WIDTH 6
#define bvo_digital_out_sync_ext_sync_2_line_er2_SHIFT 31
#define bvo_digital_out_sync_ext_sync_2_line_er2_WIDTH 1

 pel_delay2:8, /*[7:0]  */
 hole0:8,
 line_delay2:6, /*[21:16]  */
 hole1:9,
 line_er2:1; /*[31:31]  */
 } bits;

 uint32_t value;
};

union bvo_digital_out_sync_ext_sync_1Reg {
 struct { uint32_t

 /* sorting 3 */
#define bvo_digital_out_sync_ext_sync_1_pel_delay1_SHIFT 0
#define bvo_digital_out_sync_ext_sync_1_pel_delay1_WIDTH 8
#define bvo_digital_out_sync_ext_sync_1_line_delay1_SHIFT 16
#define bvo_digital_out_sync_ext_sync_1_line_delay1_WIDTH 6
#define bvo_digital_out_sync_ext_sync_1_line_er1_SHIFT 31
#define bvo_digital_out_sync_ext_sync_1_line_er1_WIDTH 1

 pel_delay1:8, /*[7:0]  */
 hole0:8,
 line_delay1:6, /*[21:16]  */
 hole1:9,
 line_er1:1; /*[31:31]  */
 } bits;

 uint32_t value;
};

union bvo_digital_out_sync_ext_sync_0Reg {
 struct { uint32_t

 /* sorting 3 */
#define bvo_digital_out_sync_ext_sync_0_pel_delay0_SHIFT 0
#define bvo_digital_out_sync_ext_sync_0_pel_delay0_WIDTH 8
#define bvo_digital_out_sync_ext_sync_0_line_delay0_SHIFT 16
#define bvo_digital_out_sync_ext_sync_0_line_delay0_WIDTH 6
#define bvo_digital_out_sync_ext_sync_0_line_er0_SHIFT 31
#define bvo_digital_out_sync_ext_sync_0_line_er0_WIDTH 1

 pel_delay0:8, /*[7:0]  */
 hole0:8,
 line_delay0:6, /*[21:16]  */
 hole1:9,
 line_er0:1; /*[31:31]  */
 } bits;

 uint32_t value;
};

union bvo_digital_out_hz_syncReg {
 struct { uint32_t

 /* sorting 3 */
#define bvo_digital_out_hz_sync_or_total_size_SHIFT 0
#define bvo_digital_out_hz_sync_or_total_size_WIDTH 12
#define bvo_digital_out_hz_sync_sync_width_SHIFT 16
#define bvo_digital_out_hz_sync_sync_width_WIDTH 12
#define bvo_digital_out_hz_sync_p_SHIFT 31
#define bvo_digital_out_hz_sync_p_WIDTH 1

 or_total_size:12, /*[11:0]  */
 hole0:4,
 sync_width:12, /*[27:16]  */
 hole1:3,
 p:1; /*[31:31]  */
 } bits;

 uint32_t value;
};

union bvo_digital_out_formatReg {
 struct { uint32_t

 /* sorting 19 */
#define bvo_digital_out_format__bus_size_SHIFT 0
#define bvo_digital_out_format__bus_size_WIDTH 2
#define bvo_digital_out_format__chroma_format_SHIFT 2
#define bvo_digital_out_format__chroma_format_WIDTH 1
#define bvo_digital_out_format__gamma_SHIFT 4
#define bvo_digital_out_format__gamma_WIDTH 1
#define bvo_digital_out_format__temperature_SHIFT 5
#define bvo_digital_out_format__temperature_WIDTH 1
#define bvo_digital_out_format__resolution_SHIFT 6
#define bvo_digital_out_format__resolution_WIDTH 1
#define bvo_digital_out_format__cs_SHIFT 7
#define bvo_digital_out_format__cs_WIDTH 1
#define bvo_digital_out_format__clip_level_SHIFT 8
#define bvo_digital_out_format__clip_level_WIDTH 1
#define bvo_digital_out_format__vip_20_SHIFT 9
#define bvo_digital_out_format__vip_20_WIDTH 1
#define bvo_digital_out_format__601_656_SHIFT 10
#define bvo_digital_out_format__601_656_WIDTH 1
#define bvo_digital_out_format__clip_enable_SHIFT 11
#define bvo_digital_out_format__clip_enable_WIDTH 1
#define bvo_digital_out_format__component_order_SHIFT 12
#define bvo_digital_out_format__component_order_WIDTH 1
#define bvo_digital_out_format__sync_source_SHIFT 13
#define bvo_digital_out_format__sync_source_WIDTH 3
#define bvo_digital_out_format__pixel_lost_SHIFT 17
#define bvo_digital_out_format__pixel_lost_WIDTH 1
#define bvo_digital_out_format__double_rate_SHIFT 21
#define bvo_digital_out_format__double_rate_WIDTH 1
#define bvo_digital_out_format__div_ctrl_SHIFT 22
#define bvo_digital_out_format__div_ctrl_WIDTH 2
#define bvo_digital_out_format__trailing_edge_SHIFT 24
#define bvo_digital_out_format__trailing_edge_WIDTH 1
#define bvo_digital_out_format__vsync_delay_SHIFT 26
#define bvo_digital_out_format__vsync_delay_WIDTH 1
#define bvo_digital_out_format__sync_control_SHIFT 27
#define bvo_digital_out_format__sync_control_WIDTH 2
#define bvo_digital_out_format__pads_control_SHIFT 29
#define bvo_digital_out_format__pads_control_WIDTH 3

 _bus_size:2, /*[1:0]  */
 _chroma_format:1, /*[2:2]  */
 hole0:1,
 _gamma:1, /*[4:4]  */
 _temperature:1, /*[5:5]  */
 _resolution:1, /*[6:6]  */
 _cs:1, /*[7:7]  */
 _clip_level:1, /*[8:8]  */
 _vip_20:1, /*[9:9]  */
 _601_656:1, /*[10:10]  */
 _clip_enable:1, /*[11:11]  */
 _component_order:1, /*[12:12]  */
 _sync_source:3, /*[15:13]  */
 hole1:1,
 _pixel_lost:1, /*[17:17]  */
 hole2:3,
 _double_rate:1, /*[21:21]  */
 _div_ctrl:2, /*[23:22]  */
 _trailing_edge:1, /*[24:24]  */
 hole3:1,
 _vsync_delay:1, /*[26:26]  */
 _sync_control:2, /*[28:27]  */
 _pads_control:3; /*[31:29]  */
 } bits;

 uint32_t value;
};

union bvo_digital_out_conv5Reg {
 struct { uint32_t

 /* sorting 2 */
#define bvo_digital_out_conv5_c1_SHIFT 0
#define bvo_digital_out_conv5_c1_WIDTH 16
#define bvo_digital_out_conv5_c2_SHIFT 16
#define bvo_digital_out_conv5_c2_WIDTH 16

 c1:16, /*[15:0]  */
 c2:16; /*[31:16]  */
 } bits;

 uint32_t value;
};

union bvo_digital_out_conv4Reg {
 struct { uint32_t

 /* sorting 2 */
#define bvo_digital_out_conv4_m22_SHIFT 0
#define bvo_digital_out_conv4_m22_WIDTH 16
#define bvo_digital_out_conv4_c0_SHIFT 16
#define bvo_digital_out_conv4_c0_WIDTH 16

 m22:16, /*[15:0]  */
 c0:16; /*[31:16]  */
 } bits;

 uint32_t value;
};

union bvo_digital_out_conv3Reg {
 struct { uint32_t

 /* sorting 2 */
#define bvo_digital_out_conv3_m20_SHIFT 0
#define bvo_digital_out_conv3_m20_WIDTH 16
#define bvo_digital_out_conv3_m21_SHIFT 16
#define bvo_digital_out_conv3_m21_WIDTH 16

 m20:16, /*[15:0]  */
 m21:16; /*[31:16]  */
 } bits;

 uint32_t value;
};

union bvo_digital_out_conv2Reg {
 struct { uint32_t

 /* sorting 2 */
#define bvo_digital_out_conv2_m11_SHIFT 0
#define bvo_digital_out_conv2_m11_WIDTH 16
#define bvo_digital_out_conv2_m12_SHIFT 16
#define bvo_digital_out_conv2_m12_WIDTH 16

 m11:16, /*[15:0]  */
 m12:16; /*[31:16]  */
 } bits;

 uint32_t value;
};

union bvo_digital_out_conv1Reg {
 struct { uint32_t

 /* sorting 2 */
#define bvo_digital_out_conv1_m02_SHIFT 0
#define bvo_digital_out_conv1_m02_WIDTH 16
#define bvo_digital_out_conv1_m10_SHIFT 16
#define bvo_digital_out_conv1_m10_WIDTH 16

 m02:16, /*[15:0]  */
 m10:16; /*[31:16]  */
 } bits;

 uint32_t value;
};

union bvo_digital_out_conv0Reg {
 struct { uint32_t

 /* sorting 2 */
#define bvo_digital_out_conv0_m00_SHIFT 0
#define bvo_digital_out_conv0_m00_WIDTH 16
#define bvo_digital_out_conv0_m01_SHIFT 16
#define bvo_digital_out_conv0_m01_WIDTH 16

 m00:16, /*[15:0]  */
 m01:16; /*[31:16]  */
 } bits;

 uint32_t value;
};

union bvo_digital_out_color_depthReg {
 struct { uint32_t

 /* sorting 2 */
#define bvo_digital_out_color_depth_dith_ctrl_SHIFT 0
#define bvo_digital_out_color_depth_dith_ctrl_WIDTH 2
#define bvo_digital_out_color_depth_cd_ctrl_SHIFT 2
#define bvo_digital_out_color_depth_cd_ctrl_WIDTH 4

 dith_ctrl:2, /*[1:0]  */
 cd_ctrl:4, /*[5:2]  */
 hole0:26;
 } bits;

 uint32_t value;
};

union bvo_digital_out_YoffsetReg {
 struct { uint32_t

 /* sorting 2 */
#define bvo_digital_out_Yoffset_top_SHIFT 0
#define bvo_digital_out_Yoffset_top_WIDTH 12
#define bvo_digital_out_Yoffset_bot_SHIFT 16
#define bvo_digital_out_Yoffset_bot_WIDTH 12

 top:12, /*[11:0]  */
 hole0:4,
 bot:12, /*[27:16]  */
 hole1:4;
 } bits;

 uint32_t value;
};

union bvo_digital_out_XoffsetReg {
 struct { uint32_t

 /* sorting 1 */
#define bvo_digital_out_Xoffset_bvo_digital_out_xoffset_SHIFT 0
#define bvo_digital_out_Xoffset_bvo_digital_out_xoffset_WIDTH 12

 bvo_digital_out_xoffset:12, /*[11:0]  */
 hole0:20;
 } bits;

 uint32_t value;
};

struct bvo_digital_out {
 union bvo_digital_out_conv0Reg bvo_digital_out_conv0; /* +0x00000000  */
 union bvo_digital_out_conv1Reg bvo_digital_out_conv1; /* +0x00000004  */
 union bvo_digital_out_conv2Reg bvo_digital_out_conv2; /* +0x00000008  */
 union bvo_digital_out_conv3Reg bvo_digital_out_conv3; /* +0x0000000c  */
 union bvo_digital_out_conv4Reg bvo_digital_out_conv4; /* +0x00000010  */
 union bvo_digital_out_conv5Reg bvo_digital_out_conv5; /* +0x00000014  */
 uint32_t pad0[0x0008/4];
 union bvo_digital_out_formatReg bvo_digital_out_format; /* +0x00000020  */
 union bvo_digital_out_XoffsetReg bvo_digital_out_Xoffset; /* +0x00000024  */
 union bvo_digital_out_YoffsetReg bvo_digital_out_Yoffset; /* +0x00000028  */
 union bvo_digital_out_hz_syncReg bvo_digital_out_hz_sync; /* +0x0000002c  */
 union bvo_digital_out_vt_syncReg bvo_digital_out_vt_sync; /* +0x00000030  */
 union bvo_digital_out_vsync_coordReg bvo_digital_out_vsync_coord; /* +0x00000034  */
 uint32_t pad1[0x0004/4];
 union bvo_digital_out_color_depthReg bvo_digital_out_color_depth; /* +0x0000003c  */
 union bvo_digital_out_sync_ext_sync_0Reg bvo_digital_out_sync_ext_sync_0; /* +0x00000040  */
 union bvo_digital_out_sync_ext_sync_1Reg bvo_digital_out_sync_ext_sync_1; /* +0x00000044  */
 union bvo_digital_out_sync_ext_sync_2Reg bvo_digital_out_sync_ext_sync_2; /* +0x00000048  */
 uint32_t pad2[0x0004/4];
 union bvo_digital_out_tv_starv_configReg bvo_digital_out_tv_starv_config; /* +0x00000050  */
 union bvo_digital_out_tv_starv_default_val1Reg bvo_digital_out_tv_starv_default_val1; /* +0x00000054  */
 union bvo_digital_out_tv_starv_default_val2Reg bvo_digital_out_tv_starv_default_val2; /* +0x00000058  */
};
