/* autogenerated with parsecfg: do not edit. */

union ha_ipu_l3c_ctrlReg {
 struct { uint32_t

 /* sorting 1 */
#define ha_ipu_l3c_ctrl_ha_ipu_l3c_uncached_SHIFT 0
#define ha_ipu_l3c_ctrl_ha_ipu_l3c_uncached_WIDTH 1

 ha_ipu_l3c_uncached:1, /*[0:0]  */
 hole0:31;
 } bits;

 uint32_t value;
};

struct ha_ipu {
 uint32_t ha_ipu_rom_base; /* +0x00000000 ,RO */
 uint32_t pad0[0x08fc/4];
 uint32_t ha_ipu_ver_rev; /* +0x00000900 ,RO */
 union ha_ipu_l3c_ctrlReg ha_ipu_l3c_ctrl; /* +0x00000904  */
};
