/* autogenerated with parsecfg: do not edit. */

union hc_dc_cache_unit_wcache_rwlevel_4567Reg {
 struct { uint32_t

 /* sorting 4 */
#define hc_dc_cache_unit_wcache_rwlevel_4567__4_SHIFT 0
#define hc_dc_cache_unit_wcache_rwlevel_4567__4_WIDTH 8
#define hc_dc_cache_unit_wcache_rwlevel_4567__5_SHIFT 8
#define hc_dc_cache_unit_wcache_rwlevel_4567__5_WIDTH 8
#define hc_dc_cache_unit_wcache_rwlevel_4567__6_SHIFT 16
#define hc_dc_cache_unit_wcache_rwlevel_4567__6_WIDTH 8
#define hc_dc_cache_unit_wcache_rwlevel_4567__7_SHIFT 24
#define hc_dc_cache_unit_wcache_rwlevel_4567__7_WIDTH 8

 _4:8, /*[7:0]  */
 _5:8, /*[15:8]  */
 _6:8, /*[23:16]  */
 _7:8; /*[31:24]  */
 } bits;

 uint32_t value;
};

union hc_dc_cache_unit_wcache_rwlevel_0123Reg {
 struct { uint32_t

 /* sorting 4 */
#define hc_dc_cache_unit_wcache_rwlevel_0123__0_SHIFT 0
#define hc_dc_cache_unit_wcache_rwlevel_0123__0_WIDTH 8
#define hc_dc_cache_unit_wcache_rwlevel_0123__1_SHIFT 8
#define hc_dc_cache_unit_wcache_rwlevel_0123__1_WIDTH 8
#define hc_dc_cache_unit_wcache_rwlevel_0123__2_SHIFT 16
#define hc_dc_cache_unit_wcache_rwlevel_0123__2_WIDTH 8
#define hc_dc_cache_unit_wcache_rwlevel_0123__3_SHIFT 24
#define hc_dc_cache_unit_wcache_rwlevel_0123__3_WIDTH 8

 _0:8, /*[7:0]  */
 _1:8, /*[15:8]  */
 _2:8, /*[23:16]  */
 _3:8; /*[31:24]  */
 } bits;

 uint32_t value;
};

union hc_dc_cache_unit_wcache_level_4567Reg {
 struct { uint32_t

 /* sorting 4 */
#define hc_dc_cache_unit_wcache_level_4567__4_SHIFT 0
#define hc_dc_cache_unit_wcache_level_4567__4_WIDTH 8
#define hc_dc_cache_unit_wcache_level_4567__5_SHIFT 8
#define hc_dc_cache_unit_wcache_level_4567__5_WIDTH 8
#define hc_dc_cache_unit_wcache_level_4567__6_SHIFT 16
#define hc_dc_cache_unit_wcache_level_4567__6_WIDTH 8
#define hc_dc_cache_unit_wcache_level_4567__7_SHIFT 24
#define hc_dc_cache_unit_wcache_level_4567__7_WIDTH 8

 _4:8, /*[7:0]  */
 _5:8, /*[15:8]  */
 _6:8, /*[23:16]  */
 _7:8; /*[31:24]  */
 } bits;

 uint32_t value;
};

union hc_dc_cache_unit_wcache_level_0123Reg {
 struct { uint32_t

 /* sorting 4 */
#define hc_dc_cache_unit_wcache_level_0123__0_SHIFT 0
#define hc_dc_cache_unit_wcache_level_0123__0_WIDTH 8
#define hc_dc_cache_unit_wcache_level_0123__1_SHIFT 8
#define hc_dc_cache_unit_wcache_level_0123__1_WIDTH 8
#define hc_dc_cache_unit_wcache_level_0123__2_SHIFT 16
#define hc_dc_cache_unit_wcache_level_0123__2_WIDTH 8
#define hc_dc_cache_unit_wcache_level_0123__3_SHIFT 24
#define hc_dc_cache_unit_wcache_level_0123__3_WIDTH 8

 _0:8, /*[7:0]  */
 _1:8, /*[15:8]  */
 _2:8, /*[23:16]  */
 _3:8; /*[31:24]  */
 } bits;

 uint32_t value;
};

union hc_dc_cache_unit_rcache_rwlevel2Reg {
 struct { uint32_t

 /* sorting 2 */
#define hc_dc_cache_unit_rcache_rwlevel2_threshold_SHIFT 2
#define hc_dc_cache_unit_rcache_rwlevel2_threshold_WIDTH 8
#define hc_dc_cache_unit_rcache_rwlevel2_inc_SHIFT 26
#define hc_dc_cache_unit_rcache_rwlevel2_inc_WIDTH 5

 hole0:2,
 threshold:8, /*[9:2]  */
 hole1:16,
 inc:5, /*[30:26]  */
 hole2:1;
 } bits;

 uint32_t value;
};

union hc_dc_cache_unit_rcache_rwlevel1Reg {
 struct { uint32_t

 /* sorting 2 */
#define hc_dc_cache_unit_rcache_rwlevel1_threshold_SHIFT 2
#define hc_dc_cache_unit_rcache_rwlevel1_threshold_WIDTH 8
#define hc_dc_cache_unit_rcache_rwlevel1_inc_SHIFT 26
#define hc_dc_cache_unit_rcache_rwlevel1_inc_WIDTH 5

 hole0:2,
 threshold:8, /*[9:2]  */
 hole1:16,
 inc:5, /*[30:26]  */
 hole2:1;
 } bits;

 uint32_t value;
};

union hc_dc_cache_unit_rcache_rwlevel0Reg {
 struct { uint32_t

 /* sorting 2 */
#define hc_dc_cache_unit_rcache_rwlevel0_threshold_SHIFT 2
#define hc_dc_cache_unit_rcache_rwlevel0_threshold_WIDTH 8
#define hc_dc_cache_unit_rcache_rwlevel0_inc_SHIFT 26
#define hc_dc_cache_unit_rcache_rwlevel0_inc_WIDTH 5

 hole0:2,
 threshold:8, /*[9:2]  */
 hole1:16,
 inc:5, /*[30:26]  */
 hole2:1;
 } bits;

 uint32_t value;
};

union hc_dc_cache_unit_bandwidthReg {
 struct { uint32_t

 /* sorting 2 */
#define hc_dc_cache_unit_bandwidth_dc_cache_unit_bw_ghub_SHIFT 0
#define hc_dc_cache_unit_bandwidth_dc_cache_unit_bw_ghub_WIDTH 5
#define hc_dc_cache_unit_bandwidth_cd_cache_unit_rcache_cmd_level_SHIFT 16
#define hc_dc_cache_unit_bandwidth_cd_cache_unit_rcache_cmd_level_WIDTH 8

 dc_cache_unit_bw_ghub:5, /*[4:0]  */
 hole0:11,
 cd_cache_unit_rcache_cmd_level:8, /*[23:16]  */
 hole1:8;
 } bits;

 uint32_t value;
};

struct hc_dc_cache_unit_common {
 union hc_dc_cache_unit_bandwidthReg hc_dc_cache_unit_bandwidth; /* +0x00000000  */
 union hc_dc_cache_unit_rcache_rwlevel0Reg hc_dc_cache_unit_rcache_rwlevel0; /* +0x00000004  */
 union hc_dc_cache_unit_rcache_rwlevel1Reg hc_dc_cache_unit_rcache_rwlevel1; /* +0x00000008  */
 union hc_dc_cache_unit_rcache_rwlevel2Reg hc_dc_cache_unit_rcache_rwlevel2; /* +0x0000000c  */
 union hc_dc_cache_unit_wcache_rwlevel_0123Reg hc_dc_cache_unit_wcache_rwlevel_0123; /* +0x00000010  */
 union hc_dc_cache_unit_wcache_rwlevel_4567Reg hc_dc_cache_unit_wcache_rwlevel_4567; /* +0x00000014  */
 uint32_t pad0[0x0008/4];
 union hc_dc_cache_unit_wcache_level_0123Reg hc_dc_cache_unit_wcache_level_0123; /* +0x00000020  */
 union hc_dc_cache_unit_wcache_level_4567Reg hc_dc_cache_unit_wcache_level_4567; /* +0x00000024  */
 uint32_t pad1[0x0008/4];
 uint32_t hc_dc_cache_unit_write_flush_abort_counter; /* +0x00000030  */
 uint32_t hc_dc_cache_unit_ghub_hit_counter; /* +0x00000034  */
 uint32_t hc_dc_cache_unit_ghub_miss_counter; /* +0x00000038  */
 uint32_t hc_dc_cache_unit_ghub_write_cmd_counter; /* +0x0000003c  */
 uint32_t hc_dc_cache_unit_gpu_hit_counter; /* +0x00000040  */
 uint32_t hc_dc_cache_unit_gpu_miss_counter; /* +0x00000044  */
 uint32_t hc_dc_cache_unit_gpu_write_cmd_counter; /* +0x00000048  */
};
