/* autogenerated with parsecfg: do not edit. */

union hc_dram_controller_rw_time_cfgReg {
 struct { uint32_t

 /* sorting 4 */
#define hc_dram_controller_rw_time_cfg_time_limit_w_r_SHIFT 0
#define hc_dram_controller_rw_time_cfg_time_limit_w_r_WIDTH 6
#define hc_dram_controller_rw_time_cfg_time_limit_r_w_SHIFT 8
#define hc_dram_controller_rw_time_cfg_time_limit_r_w_WIDTH 6
#define hc_dram_controller_rw_time_cfg_cnt_from_0_SHIFT 30
#define hc_dram_controller_rw_time_cfg_cnt_from_0_WIDTH 1
#define hc_dram_controller_rw_time_cfg_enable_cnt_SHIFT 31
#define hc_dram_controller_rw_time_cfg_enable_cnt_WIDTH 1

 time_limit_w_r:6, /*[5:0]  */
 hole0:2,
 time_limit_r_w:6, /*[13:8]  */
 hole1:16,
 cnt_from_0:1, /*[30:30]  */
 enable_cnt:1; /*[31:31]  */
 } bits;

 uint32_t value;
};

union hc_dram_controller_rw_range_cfgReg {
 struct { uint32_t

 /* sorting 5 */
#define hc_dram_controller_rw_range_cfg_level_range0_SHIFT 0
#define hc_dram_controller_rw_range_cfg_level_range0_WIDTH 8
#define hc_dram_controller_rw_range_cfg_level_range1_SHIFT 8
#define hc_dram_controller_rw_range_cfg_level_range1_WIDTH 8
#define hc_dram_controller_rw_range_cfg_range01_transition_SHIFT 16
#define hc_dram_controller_rw_range_cfg_range01_transition_WIDTH 8
#define hc_dram_controller_rw_range_cfg_range_min_dly_SHIFT 24
#define hc_dram_controller_rw_range_cfg_range_min_dly_WIDTH 6
#define hc_dram_controller_rw_range_cfg_range_en_SHIFT 31
#define hc_dram_controller_rw_range_cfg_range_en_WIDTH 1

 level_range0:8, /*[7:0]  */
 level_range1:8, /*[15:8]  */
 range01_transition:8, /*[23:16]  */
 range_min_dly:6, /*[29:24]  */
 hole0:1,
 range_en:1; /*[31:31]  */
 } bits;

 uint32_t value;
};

union hc_dram_controller_illegal_statReg {
 struct { uint32_t

 /* sorting 2 */
#define hc_dram_controller_illegal_stat_did_SHIFT 0
#define hc_dram_controller_illegal_stat_did_WIDTH 12
#define hc_dram_controller_illegal_stat_err_SHIFT 31
#define hc_dram_controller_illegal_stat_err_WIDTH 1

 did:12, /*[11:0] ,RO */
 hole0:19,
 err:1; /*[31:31] ,RO */
 } bits;

 uint32_t value;
};

union hc_dram_controller_dram_prot5Reg {
 struct { uint32_t

 /* sorting 3 */
#define hc_dram_controller_dram_prot5_dram_boundary5_SHIFT 0
#define hc_dram_controller_dram_prot5_dram_boundary5_WIDTH 16
#define hc_dram_controller_dram_prot5_gbus_dram_privilege5_SHIFT 16
#define hc_dram_controller_dram_prot5_gbus_dram_privilege5_WIDTH 8
#define hc_dram_controller_dram_prot5_mbus_dram_privilege5_SHIFT 24
#define hc_dram_controller_dram_prot5_mbus_dram_privilege5_WIDTH 8

 dram_boundary5:16, /*[15:0]  */
 gbus_dram_privilege5:8, /*[23:16]  */
 mbus_dram_privilege5:8; /*[31:24]  */
 } bits;

 uint32_t value;
};

union hc_dram_controller_dram_prot4Reg {
 struct { uint32_t

 /* sorting 3 */
#define hc_dram_controller_dram_prot4_dram_boundary4_SHIFT 0
#define hc_dram_controller_dram_prot4_dram_boundary4_WIDTH 16
#define hc_dram_controller_dram_prot4_gbus_dram_privilege4_SHIFT 16
#define hc_dram_controller_dram_prot4_gbus_dram_privilege4_WIDTH 8
#define hc_dram_controller_dram_prot4_mbus_dram_privilege4_SHIFT 24
#define hc_dram_controller_dram_prot4_mbus_dram_privilege4_WIDTH 8

 dram_boundary4:16, /*[15:0]  */
 gbus_dram_privilege4:8, /*[23:16]  */
 mbus_dram_privilege4:8; /*[31:24]  */
 } bits;

 uint32_t value;
};

union hc_dram_controller_dram_prot3Reg {
 struct { uint32_t

 /* sorting 3 */
#define hc_dram_controller_dram_prot3_dram_boundary3_SHIFT 0
#define hc_dram_controller_dram_prot3_dram_boundary3_WIDTH 16
#define hc_dram_controller_dram_prot3_gbus_dram_privilege3_SHIFT 16
#define hc_dram_controller_dram_prot3_gbus_dram_privilege3_WIDTH 8
#define hc_dram_controller_dram_prot3_mbus_dram_privilege3_SHIFT 24
#define hc_dram_controller_dram_prot3_mbus_dram_privilege3_WIDTH 8

 dram_boundary3:16, /*[15:0]  */
 gbus_dram_privilege3:8, /*[23:16]  */
 mbus_dram_privilege3:8; /*[31:24]  */
 } bits;

 uint32_t value;
};

union hc_dram_controller_dram_prot2Reg {
 struct { uint32_t

 /* sorting 3 */
#define hc_dram_controller_dram_prot2_dram_boundary2_SHIFT 0
#define hc_dram_controller_dram_prot2_dram_boundary2_WIDTH 16
#define hc_dram_controller_dram_prot2_gbus_dram_privilege2_SHIFT 16
#define hc_dram_controller_dram_prot2_gbus_dram_privilege2_WIDTH 8
#define hc_dram_controller_dram_prot2_mbus_dram_privilege2_SHIFT 24
#define hc_dram_controller_dram_prot2_mbus_dram_privilege2_WIDTH 8

 dram_boundary2:16, /*[15:0]  */
 gbus_dram_privilege2:8, /*[23:16]  */
 mbus_dram_privilege2:8; /*[31:24]  */
 } bits;

 uint32_t value;
};

union hc_dram_controller_dram_prot1Reg {
 struct { uint32_t

 /* sorting 3 */
#define hc_dram_controller_dram_prot1_dram_boundary1_SHIFT 0
#define hc_dram_controller_dram_prot1_dram_boundary1_WIDTH 16
#define hc_dram_controller_dram_prot1_gbus_dram_privilege1_SHIFT 16
#define hc_dram_controller_dram_prot1_gbus_dram_privilege1_WIDTH 8
#define hc_dram_controller_dram_prot1_mbus_dram_privilege1_SHIFT 24
#define hc_dram_controller_dram_prot1_mbus_dram_privilege1_WIDTH 8

 dram_boundary1:16, /*[15:0]  */
 gbus_dram_privilege1:8, /*[23:16]  */
 mbus_dram_privilege1:8; /*[31:24]  */
 } bits;

 uint32_t value;
};

union hc_dram_controller_dram_prot0Reg {
 struct { uint32_t

 /* sorting 3 */
#define hc_dram_controller_dram_prot0_dram_boundary0_SHIFT 0
#define hc_dram_controller_dram_prot0_dram_boundary0_WIDTH 16
#define hc_dram_controller_dram_prot0_gbus_dram_privilege0_SHIFT 16
#define hc_dram_controller_dram_prot0_gbus_dram_privilege0_WIDTH 8
#define hc_dram_controller_dram_prot0_mbus_dram_privilege0_SHIFT 24
#define hc_dram_controller_dram_prot0_mbus_dram_privilege0_WIDTH 8

 dram_boundary0:16, /*[15:0]  */
 gbus_dram_privilege0:8, /*[23:16]  */
 mbus_dram_privilege0:8; /*[31:24]  */
 } bits;

 uint32_t value;
};

union hc_dram_controller_bw_modeReg {
 struct { uint32_t

 /* sorting 2 */
#define hc_dram_controller_bw_mode_interrupt_on_SHIFT 0
#define hc_dram_controller_bw_mode_interrupt_on_WIDTH 5
#define hc_dram_controller_bw_mode_add_boundary_on_SHIFT 8
#define hc_dram_controller_bw_mode_add_boundary_on_WIDTH 5

 interrupt_on:5, /*[4:0]  */
 hole0:3,
 add_boundary_on:5, /*[12:8]  */
 hole1:19;
 } bits;

 uint32_t value;
};

union hc_dram_controller_bw_low_addReg {
 struct { uint32_t

 /* sorting 2 */
#define hc_dram_controller_bw_low_add__30_3_SHIFT 3
#define hc_dram_controller_bw_low_add__30_3_WIDTH 28
#define hc_dram_controller_bw_low_add__31_SHIFT 31
#define hc_dram_controller_bw_low_add__31_WIDTH 1

 hole0:3,
 _30_3:28, /*[30:3]  */
 _31:1; /*[31:31] ,RO */
 } bits;

 uint32_t value;
};

union hc_dram_controller_bw_int_res_masterReg {
 struct { uint32_t

 /* sorting 5 */
#define hc_dram_controller_bw_int_res_master_thread_id_SHIFT 0
#define hc_dram_controller_bw_int_res_master_thread_id_WIDTH 6
#define hc_dram_controller_bw_int_res_master_thread_rwb_SHIFT 6
#define hc_dram_controller_bw_int_res_master_thread_rwb_WIDTH 1
#define hc_dram_controller_bw_int_res_master_ring_id_SHIFT 8
#define hc_dram_controller_bw_int_res_master_ring_id_WIDTH 2
#define hc_dram_controller_bw_int_res_master_gbus_SHIFT 16
#define hc_dram_controller_bw_int_res_master_gbus_WIDTH 1
#define hc_dram_controller_bw_int_res_master_vld_SHIFT 31
#define hc_dram_controller_bw_int_res_master_vld_WIDTH 1

 thread_id:6, /*[5:0]  */
 thread_rwb:1, /*[6:6]  */
 hole0:1,
 ring_id:2, /*[9:8]  */
 hole1:6,
 gbus:1, /*[16:16]  */
 hole2:14,
 vld:1; /*[31:31]  */
 } bits;

 uint32_t value;
};

union hc_dram_controller_bw_int_res_addReg {
 struct { uint32_t

 /* sorting 1 */
#define hc_dram_controller_bw_int_res_add_hc_dram_controller_bw_int_res_add_reg_SHIFT 3
#define hc_dram_controller_bw_int_res_add_hc_dram_controller_bw_int_res_add_reg_WIDTH 29

 hole0:3,
 hc_dram_controller_bw_int_res_add_reg:29; /*[31:3] ,RO */
 } bits;

 uint32_t value;
};

union hc_dram_controller_bw_high_addReg {
 struct { uint32_t

 /* sorting 2 */
#define hc_dram_controller_bw_high_add__30_3_SHIFT 3
#define hc_dram_controller_bw_high_add__30_3_WIDTH 28
#define hc_dram_controller_bw_high_add__31_SHIFT 31
#define hc_dram_controller_bw_high_add__31_WIDTH 1

 hole0:3,
 _30_3:28, /*[30:3]  */
 _31:1; /*[31:31] ,RO */
 } bits;

 uint32_t value;
};

union hc_dram_controller_bw_counter_4_selector_1Reg {
 struct { uint32_t

 /* sorting 12 */
#define hc_dram_controller_bw_counter_4_selector_1_thread_0_SHIFT 0
#define hc_dram_controller_bw_counter_4_selector_1_thread_0_WIDTH 6
#define hc_dram_controller_bw_counter_4_selector_1_rwb_0_SHIFT 6
#define hc_dram_controller_bw_counter_4_selector_1_rwb_0_WIDTH 1
#define hc_dram_controller_bw_counter_4_selector_1_tmode_0_SHIFT 7
#define hc_dram_controller_bw_counter_4_selector_1_tmode_0_WIDTH 1
#define hc_dram_controller_bw_counter_4_selector_1_thread_1_SHIFT 8
#define hc_dram_controller_bw_counter_4_selector_1_thread_1_WIDTH 6
#define hc_dram_controller_bw_counter_4_selector_1_rwb_1_SHIFT 14
#define hc_dram_controller_bw_counter_4_selector_1_rwb_1_WIDTH 1
#define hc_dram_controller_bw_counter_4_selector_1_tmode_1_SHIFT 15
#define hc_dram_controller_bw_counter_4_selector_1_tmode_1_WIDTH 1
#define hc_dram_controller_bw_counter_4_selector_1_thread_2_SHIFT 16
#define hc_dram_controller_bw_counter_4_selector_1_thread_2_WIDTH 6
#define hc_dram_controller_bw_counter_4_selector_1_rwb_2_SHIFT 22
#define hc_dram_controller_bw_counter_4_selector_1_rwb_2_WIDTH 1
#define hc_dram_controller_bw_counter_4_selector_1_tmode_2_SHIFT 23
#define hc_dram_controller_bw_counter_4_selector_1_tmode_2_WIDTH 1
#define hc_dram_controller_bw_counter_4_selector_1_thread_3_SHIFT 24
#define hc_dram_controller_bw_counter_4_selector_1_thread_3_WIDTH 6
#define hc_dram_controller_bw_counter_4_selector_1_rwb_3_SHIFT 30
#define hc_dram_controller_bw_counter_4_selector_1_rwb_3_WIDTH 1
#define hc_dram_controller_bw_counter_4_selector_1_tmode_3_SHIFT 31
#define hc_dram_controller_bw_counter_4_selector_1_tmode_3_WIDTH 1

 thread_0:6, /*[5:0]  */
 rwb_0:1, /*[6:6]  */
 tmode_0:1, /*[7:7]  */
 thread_1:6, /*[13:8]  */
 rwb_1:1, /*[14:14]  */
 tmode_1:1, /*[15:15]  */
 thread_2:6, /*[21:16]  */
 rwb_2:1, /*[22:22]  */
 tmode_2:1, /*[23:23]  */
 thread_3:6, /*[29:24]  */
 rwb_3:1, /*[30:30]  */
 tmode_3:1; /*[31:31]  */
 } bits;

 uint32_t value;
};

union hc_dram_controller_bw_counter_4_selector_0Reg {
 struct { uint32_t

 /* sorting 4 */
#define hc_dram_controller_bw_counter_4_selector_0_gbus_mode_SHIFT 0
#define hc_dram_controller_bw_counter_4_selector_0_gbus_mode_WIDTH 2
#define hc_dram_controller_bw_counter_4_selector_0_mbus_mode_SHIFT 8
#define hc_dram_controller_bw_counter_4_selector_0_mbus_mode_WIDTH 2
#define hc_dram_controller_bw_counter_4_selector_0_block_id_SHIFT 16
#define hc_dram_controller_bw_counter_4_selector_0_block_id_WIDTH 8
#define hc_dram_controller_bw_counter_4_selector_0_ring_id_SHIFT 24
#define hc_dram_controller_bw_counter_4_selector_0_ring_id_WIDTH 2

 gbus_mode:2, /*[1:0]  */
 hole0:6,
 mbus_mode:2, /*[9:8]  */
 hole1:6,
 block_id:8, /*[23:16]  */
 ring_id:2, /*[25:24]  */
 hole2:6;
 } bits;

 uint32_t value;
};

union hc_dram_controller_bw_counter_3_selector_1Reg {
 struct { uint32_t

 /* sorting 12 */
#define hc_dram_controller_bw_counter_3_selector_1_thread_0_SHIFT 0
#define hc_dram_controller_bw_counter_3_selector_1_thread_0_WIDTH 6
#define hc_dram_controller_bw_counter_3_selector_1_rwb_0_SHIFT 6
#define hc_dram_controller_bw_counter_3_selector_1_rwb_0_WIDTH 1
#define hc_dram_controller_bw_counter_3_selector_1_tmode_0_SHIFT 7
#define hc_dram_controller_bw_counter_3_selector_1_tmode_0_WIDTH 1
#define hc_dram_controller_bw_counter_3_selector_1_thread_1_SHIFT 8
#define hc_dram_controller_bw_counter_3_selector_1_thread_1_WIDTH 6
#define hc_dram_controller_bw_counter_3_selector_1_rwb_1_SHIFT 14
#define hc_dram_controller_bw_counter_3_selector_1_rwb_1_WIDTH 1
#define hc_dram_controller_bw_counter_3_selector_1_tmode_1_SHIFT 15
#define hc_dram_controller_bw_counter_3_selector_1_tmode_1_WIDTH 1
#define hc_dram_controller_bw_counter_3_selector_1_thread_2_SHIFT 16
#define hc_dram_controller_bw_counter_3_selector_1_thread_2_WIDTH 6
#define hc_dram_controller_bw_counter_3_selector_1_rwb_2_SHIFT 22
#define hc_dram_controller_bw_counter_3_selector_1_rwb_2_WIDTH 1
#define hc_dram_controller_bw_counter_3_selector_1_tmode_2_SHIFT 23
#define hc_dram_controller_bw_counter_3_selector_1_tmode_2_WIDTH 1
#define hc_dram_controller_bw_counter_3_selector_1_thread_3_SHIFT 24
#define hc_dram_controller_bw_counter_3_selector_1_thread_3_WIDTH 6
#define hc_dram_controller_bw_counter_3_selector_1_rwb_3_SHIFT 30
#define hc_dram_controller_bw_counter_3_selector_1_rwb_3_WIDTH 1
#define hc_dram_controller_bw_counter_3_selector_1_tmode_3_SHIFT 31
#define hc_dram_controller_bw_counter_3_selector_1_tmode_3_WIDTH 1

 thread_0:6, /*[5:0]  */
 rwb_0:1, /*[6:6]  */
 tmode_0:1, /*[7:7]  */
 thread_1:6, /*[13:8]  */
 rwb_1:1, /*[14:14]  */
 tmode_1:1, /*[15:15]  */
 thread_2:6, /*[21:16]  */
 rwb_2:1, /*[22:22]  */
 tmode_2:1, /*[23:23]  */
 thread_3:6, /*[29:24]  */
 rwb_3:1, /*[30:30]  */
 tmode_3:1; /*[31:31]  */
 } bits;

 uint32_t value;
};

union hc_dram_controller_bw_counter_3_selector_0Reg {
 struct { uint32_t

 /* sorting 4 */
#define hc_dram_controller_bw_counter_3_selector_0_gbus_mode_SHIFT 0
#define hc_dram_controller_bw_counter_3_selector_0_gbus_mode_WIDTH 2
#define hc_dram_controller_bw_counter_3_selector_0_mbus_mode_SHIFT 8
#define hc_dram_controller_bw_counter_3_selector_0_mbus_mode_WIDTH 2
#define hc_dram_controller_bw_counter_3_selector_0_block_id_SHIFT 16
#define hc_dram_controller_bw_counter_3_selector_0_block_id_WIDTH 8
#define hc_dram_controller_bw_counter_3_selector_0_ring_id_SHIFT 24
#define hc_dram_controller_bw_counter_3_selector_0_ring_id_WIDTH 2

 gbus_mode:2, /*[1:0]  */
 hole0:6,
 mbus_mode:2, /*[9:8]  */
 hole1:6,
 block_id:8, /*[23:16]  */
 ring_id:2, /*[25:24]  */
 hole2:6;
 } bits;

 uint32_t value;
};

union hc_dram_controller_bw_counter_2_selector_1Reg {
 struct { uint32_t

 /* sorting 12 */
#define hc_dram_controller_bw_counter_2_selector_1_thread_0_SHIFT 0
#define hc_dram_controller_bw_counter_2_selector_1_thread_0_WIDTH 6
#define hc_dram_controller_bw_counter_2_selector_1_rwb_0_SHIFT 6
#define hc_dram_controller_bw_counter_2_selector_1_rwb_0_WIDTH 1
#define hc_dram_controller_bw_counter_2_selector_1_tmode_0_SHIFT 7
#define hc_dram_controller_bw_counter_2_selector_1_tmode_0_WIDTH 1
#define hc_dram_controller_bw_counter_2_selector_1_thread_1_SHIFT 8
#define hc_dram_controller_bw_counter_2_selector_1_thread_1_WIDTH 6
#define hc_dram_controller_bw_counter_2_selector_1_rwb_1_SHIFT 14
#define hc_dram_controller_bw_counter_2_selector_1_rwb_1_WIDTH 1
#define hc_dram_controller_bw_counter_2_selector_1_tmode_1_SHIFT 15
#define hc_dram_controller_bw_counter_2_selector_1_tmode_1_WIDTH 1
#define hc_dram_controller_bw_counter_2_selector_1_thread_2_SHIFT 16
#define hc_dram_controller_bw_counter_2_selector_1_thread_2_WIDTH 6
#define hc_dram_controller_bw_counter_2_selector_1_rwb_2_SHIFT 22
#define hc_dram_controller_bw_counter_2_selector_1_rwb_2_WIDTH 1
#define hc_dram_controller_bw_counter_2_selector_1_tmode_2_SHIFT 23
#define hc_dram_controller_bw_counter_2_selector_1_tmode_2_WIDTH 1
#define hc_dram_controller_bw_counter_2_selector_1_thread_3_SHIFT 24
#define hc_dram_controller_bw_counter_2_selector_1_thread_3_WIDTH 6
#define hc_dram_controller_bw_counter_2_selector_1_rwb_3_SHIFT 30
#define hc_dram_controller_bw_counter_2_selector_1_rwb_3_WIDTH 1
#define hc_dram_controller_bw_counter_2_selector_1_tmode_3_SHIFT 31
#define hc_dram_controller_bw_counter_2_selector_1_tmode_3_WIDTH 1

 thread_0:6, /*[5:0]  */
 rwb_0:1, /*[6:6]  */
 tmode_0:1, /*[7:7]  */
 thread_1:6, /*[13:8]  */
 rwb_1:1, /*[14:14]  */
 tmode_1:1, /*[15:15]  */
 thread_2:6, /*[21:16]  */
 rwb_2:1, /*[22:22]  */
 tmode_2:1, /*[23:23]  */
 thread_3:6, /*[29:24]  */
 rwb_3:1, /*[30:30]  */
 tmode_3:1; /*[31:31]  */
 } bits;

 uint32_t value;
};

union hc_dram_controller_bw_counter_2_selector_0Reg {
 struct { uint32_t

 /* sorting 4 */
#define hc_dram_controller_bw_counter_2_selector_0_gbus_mode_SHIFT 0
#define hc_dram_controller_bw_counter_2_selector_0_gbus_mode_WIDTH 2
#define hc_dram_controller_bw_counter_2_selector_0_mbus_mode_SHIFT 8
#define hc_dram_controller_bw_counter_2_selector_0_mbus_mode_WIDTH 2
#define hc_dram_controller_bw_counter_2_selector_0_block_id_SHIFT 16
#define hc_dram_controller_bw_counter_2_selector_0_block_id_WIDTH 8
#define hc_dram_controller_bw_counter_2_selector_0_ring_id_SHIFT 24
#define hc_dram_controller_bw_counter_2_selector_0_ring_id_WIDTH 2

 gbus_mode:2, /*[1:0]  */
 hole0:6,
 mbus_mode:2, /*[9:8]  */
 hole1:6,
 block_id:8, /*[23:16]  */
 ring_id:2, /*[25:24]  */
 hole2:6;
 } bits;

 uint32_t value;
};

union hc_dram_controller_bw_counter_1_selector_1Reg {
 struct { uint32_t

 /* sorting 12 */
#define hc_dram_controller_bw_counter_1_selector_1_thread_0_SHIFT 0
#define hc_dram_controller_bw_counter_1_selector_1_thread_0_WIDTH 6
#define hc_dram_controller_bw_counter_1_selector_1_rwb_0_SHIFT 6
#define hc_dram_controller_bw_counter_1_selector_1_rwb_0_WIDTH 1
#define hc_dram_controller_bw_counter_1_selector_1_tmode_0_SHIFT 7
#define hc_dram_controller_bw_counter_1_selector_1_tmode_0_WIDTH 1
#define hc_dram_controller_bw_counter_1_selector_1_thread_1_SHIFT 8
#define hc_dram_controller_bw_counter_1_selector_1_thread_1_WIDTH 6
#define hc_dram_controller_bw_counter_1_selector_1_rwb_1_SHIFT 14
#define hc_dram_controller_bw_counter_1_selector_1_rwb_1_WIDTH 1
#define hc_dram_controller_bw_counter_1_selector_1_tmode_1_SHIFT 15
#define hc_dram_controller_bw_counter_1_selector_1_tmode_1_WIDTH 1
#define hc_dram_controller_bw_counter_1_selector_1_thread_2_SHIFT 16
#define hc_dram_controller_bw_counter_1_selector_1_thread_2_WIDTH 6
#define hc_dram_controller_bw_counter_1_selector_1_rwb_2_SHIFT 22
#define hc_dram_controller_bw_counter_1_selector_1_rwb_2_WIDTH 1
#define hc_dram_controller_bw_counter_1_selector_1_tmode_2_SHIFT 23
#define hc_dram_controller_bw_counter_1_selector_1_tmode_2_WIDTH 1
#define hc_dram_controller_bw_counter_1_selector_1_thread_3_SHIFT 24
#define hc_dram_controller_bw_counter_1_selector_1_thread_3_WIDTH 6
#define hc_dram_controller_bw_counter_1_selector_1_rwb_3_SHIFT 30
#define hc_dram_controller_bw_counter_1_selector_1_rwb_3_WIDTH 1
#define hc_dram_controller_bw_counter_1_selector_1_tmode_3_SHIFT 31
#define hc_dram_controller_bw_counter_1_selector_1_tmode_3_WIDTH 1

 thread_0:6, /*[5:0]  */
 rwb_0:1, /*[6:6]  */
 tmode_0:1, /*[7:7]  */
 thread_1:6, /*[13:8]  */
 rwb_1:1, /*[14:14]  */
 tmode_1:1, /*[15:15]  */
 thread_2:6, /*[21:16]  */
 rwb_2:1, /*[22:22]  */
 tmode_2:1, /*[23:23]  */
 thread_3:6, /*[29:24]  */
 rwb_3:1, /*[30:30]  */
 tmode_3:1; /*[31:31]  */
 } bits;

 uint32_t value;
};

union hc_dram_controller_bw_counter_1_selector_0Reg {
 struct { uint32_t

 /* sorting 4 */
#define hc_dram_controller_bw_counter_1_selector_0_gbus_mode_SHIFT 0
#define hc_dram_controller_bw_counter_1_selector_0_gbus_mode_WIDTH 2
#define hc_dram_controller_bw_counter_1_selector_0_mbus_mode_SHIFT 8
#define hc_dram_controller_bw_counter_1_selector_0_mbus_mode_WIDTH 2
#define hc_dram_controller_bw_counter_1_selector_0_block_id_SHIFT 16
#define hc_dram_controller_bw_counter_1_selector_0_block_id_WIDTH 8
#define hc_dram_controller_bw_counter_1_selector_0_ring_id_SHIFT 24
#define hc_dram_controller_bw_counter_1_selector_0_ring_id_WIDTH 2

 gbus_mode:2, /*[1:0]  */
 hole0:6,
 mbus_mode:2, /*[9:8]  */
 hole1:6,
 block_id:8, /*[23:16]  */
 ring_id:2, /*[25:24]  */
 hole2:6;
 } bits;

 uint32_t value;
};

struct hc_dram_controller {
 union hc_dram_controller_dram_prot0Reg hc_dram_controller_dram_prot0; /* +0x00000000  */
 union hc_dram_controller_dram_prot1Reg hc_dram_controller_dram_prot1; /* +0x00000004  */
 union hc_dram_controller_dram_prot2Reg hc_dram_controller_dram_prot2; /* +0x00000008  */
 union hc_dram_controller_dram_prot3Reg hc_dram_controller_dram_prot3; /* +0x0000000c  */
 union hc_dram_controller_dram_prot4Reg hc_dram_controller_dram_prot4; /* +0x00000010  */
 union hc_dram_controller_dram_prot5Reg hc_dram_controller_dram_prot5; /* +0x00000014  */
 uint32_t pad0[0x0008/4];
 union hc_dram_controller_rw_range_cfgReg hc_dram_controller_rw_range_cfg; /* +0x00000020  */
 union hc_dram_controller_rw_time_cfgReg hc_dram_controller_rw_time_cfg; /* +0x00000024  */
 union hc_dram_controller_illegal_statReg hc_dram_controller_illegal_stat; /* +0x00000028 ,RO */
 uint32_t hc_dram_controller_illegal_add; /* +0x0000002c ,RO */
 union hc_dram_controller_bw_low_addReg hc_dram_controller_bw_low_add; /* +0x00000030  */
 union hc_dram_controller_bw_high_addReg hc_dram_controller_bw_high_add; /* +0x00000034  */
 union hc_dram_controller_bw_modeReg hc_dram_controller_bw_mode; /* +0x00000038  */
 union hc_dram_controller_bw_int_res_masterReg hc_dram_controller_bw_int_res_master; /* +0x0000003c ,NO_TEST */
 union hc_dram_controller_bw_int_res_addReg hc_dram_controller_bw_int_res_add; /* +0x00000040  */
 uint32_t pad1[0x0008/4];
 uint32_t hc_dram_controller_bw_counter_all; /* +0x0000004c ,NO_TEST */
 union hc_dram_controller_bw_counter_1_selector_0Reg hc_dram_controller_bw_counter_1_selector_0; /* +0x00000050  */
 union hc_dram_controller_bw_counter_1_selector_1Reg hc_dram_controller_bw_counter_1_selector_1; /* +0x00000054  */
 uint32_t pad2[0x0004/4];
 uint32_t hc_dram_controller_bw_counter_1_counter; /* +0x0000005c ,NO_TEST */
 union hc_dram_controller_bw_counter_2_selector_0Reg hc_dram_controller_bw_counter_2_selector_0; /* +0x00000060  */
 union hc_dram_controller_bw_counter_2_selector_1Reg hc_dram_controller_bw_counter_2_selector_1; /* +0x00000064  */
 uint32_t pad3[0x0004/4];
 uint32_t hc_dram_controller_bw_counter_2_counter; /* +0x0000006c ,NO_TEST */
 union hc_dram_controller_bw_counter_3_selector_0Reg hc_dram_controller_bw_counter_3_selector_0; /* +0x00000070  */
 union hc_dram_controller_bw_counter_3_selector_1Reg hc_dram_controller_bw_counter_3_selector_1; /* +0x00000074  */
 uint32_t pad4[0x0004/4];
 uint32_t hc_dram_controller_bw_counter_3_counter; /* +0x0000007c ,NO_TEST */
 union hc_dram_controller_bw_counter_4_selector_0Reg hc_dram_controller_bw_counter_4_selector_0; /* +0x00000080  */
 union hc_dram_controller_bw_counter_4_selector_1Reg hc_dram_controller_bw_counter_4_selector_1; /* +0x00000084  */
 uint32_t pad5[0x0004/4];
 uint32_t hc_dram_controller_bw_counter_4_counter; /* +0x0000008c ,NO_TEST */
};
