/* autogenerated with parsecfg: do not edit. */

struct hc_iv_ram {
 uint32_t load_iv_0_[4]; /* +0x00000000 [127:0] */
 uint32_t load_iv_1_[4]; /* +0x00000010 [127:0] */
 uint32_t load_iv_2_[4]; /* +0x00000020 [127:0] */
 uint32_t load_iv_3_[4]; /* +0x00000030 [127:0] */
 uint32_t load_iv_4_[4]; /* +0x00000040 [127:0] */
 uint32_t load_iv_5_[4]; /* +0x00000050 [127:0] */
 uint32_t load_iv_6_[4]; /* +0x00000060 [127:0] */
 uint32_t load_iv_7_[4]; /* +0x00000070 [127:0] */
 uint32_t load_iv_8_[4]; /* +0x00000080 [127:0] */
 uint32_t load_iv_9_[4]; /* +0x00000090 [127:0] */
 uint32_t load_iv_10_[4]; /* +0x000000a0 [127:0] */
 uint32_t load_iv_11_[4]; /* +0x000000b0 [127:0] */
 uint32_t load_iv_12_[4]; /* +0x000000c0 [127:0] */
 uint32_t load_iv_13_[4]; /* +0x000000d0 [127:0] */
 uint32_t load_iv_14_[4]; /* +0x000000e0 [127:0] */
 uint32_t load_iv_15_[4]; /* +0x000000f0 [127:0] */
 uint32_t load_iv_16_[4]; /* +0x00000100 [127:0] */
 uint32_t load_iv_17_[4]; /* +0x00000110 [127:0] */
 uint32_t load_iv_18_[4]; /* +0x00000120 [127:0] */
 uint32_t load_iv_19_[4]; /* +0x00000130 [127:0] */
 uint32_t load_iv_20_[4]; /* +0x00000140 [127:0] */
 uint32_t load_iv_21_[4]; /* +0x00000150 [127:0] */
 uint32_t load_iv_22_[4]; /* +0x00000160 [127:0] */
 uint32_t load_iv_23_[4]; /* +0x00000170 [127:0] */
};
