/* autogenerated with parsecfg: do not edit. */

union r2r_aes_msc_regReg {
 struct { uint32_t

 /* sorting 2 */
#define r2r_aes_msc_reg_msc_bytes_SHIFT 0
#define r2r_aes_msc_reg_msc_bytes_WIDTH 8
#define r2r_aes_msc_reg_pkt_length_SHIFT 8
#define r2r_aes_msc_reg_pkt_length_WIDTH 8

 msc_bytes:8, /*[7:0]  */
 pkt_length:8, /*[15:8]  */
 hole0:16;
 } bits;

 uint32_t value;
};

union r2r_aes_config_regReg {
 struct { uint32_t

 /* sorting 5 */
#define r2r_aes_config_reg_mode_SHIFT 4
#define r2r_aes_config_reg_mode_WIDTH 4
#define r2r_aes_config_reg_unused_SHIFT 8
#define r2r_aes_config_reg_unused_WIDTH 16
#define r2r_aes_config_reg_key_index_SHIFT 24
#define r2r_aes_config_reg_key_index_WIDTH 4
#define r2r_aes_config_reg_cpu_access_err_SHIFT 30
#define r2r_aes_config_reg_cpu_access_err_WIDTH 1
#define r2r_aes_config_reg_end_SHIFT 31
#define r2r_aes_config_reg_end_WIDTH 1

 hole0:4,
 mode:4, /*[7:4] ,NO_MEM */
 unused:16, /*[23:8] ,RO */
 key_index:4, /*[27:24] ,NO_MEM */
 hole1:2,
 cpu_access_err:1, /*[30:30] ,NO_MEM */
 end:1; /*[31:31] ,RO */
 } bits;

 uint32_t value;
};

union r2r_aes_access_regReg {
 struct { uint32_t

 /* sorting 2 */
#define r2r_aes_access_reg_residual_bytes_SHIFT 0
#define r2r_aes_access_reg_residual_bytes_WIDTH 4
#define r2r_aes_access_reg_counter_cycles_SHIFT 4
#define r2r_aes_access_reg_counter_cycles_WIDTH 20

 residual_bytes:4, /*[3:0]  */
 counter_cycles:20, /*[23:4]  */
 hole0:8;
 } bits;

 uint32_t value;
};

struct hc_r2r_aes {
 uint32_t r2r_aes_IV[4]; /* +0x00000000 [127:0],ENDIANBIG,RO */
 union r2r_aes_config_regReg r2r_aes_config_reg; /* +0x00000010  */
 union r2r_aes_msc_regReg r2r_aes_msc_reg; /* +0x00000014 ,NO_TEST */
 union r2r_aes_access_regReg r2r_aes_access_reg; /* +0x00000018 ,NO_TEST */
};
