/* autogenerated with parsecfg: do not edit. */

union r2r_des_config_regReg {
 struct { uint32_t

 /* sorting 8 */
#define r2r_des_config_reg_tdes_desn_SHIFT 0
#define r2r_des_config_reg_tdes_desn_WIDTH 1
#define r2r_des_config_reg_des_decryption_SHIFT 1
#define r2r_des_config_reg_des_decryption_WIDTH 1
#define r2r_des_config_reg_des_ofb_mode_SHIFT 2
#define r2r_des_config_reg_des_ofb_mode_WIDTH 1
#define r2r_des_config_reg_des_cbc_mode_SHIFT 3
#define r2r_des_config_reg_des_cbc_mode_WIDTH 1
#define r2r_des_config_reg_des_cts_mode_SHIFT 4
#define r2r_des_config_reg_des_cts_mode_WIDTH 1
#define r2r_des_config_reg_des_key_index_SHIFT 16
#define r2r_des_config_reg_des_key_index_WIDTH 4
#define r2r_des_config_reg_des_cpu_access_err_SHIFT 30
#define r2r_des_config_reg_des_cpu_access_err_WIDTH 1
#define r2r_des_config_reg_des_end_SHIFT 31
#define r2r_des_config_reg_des_end_WIDTH 1

 tdes_desn:1, /*[0:0] ,NO_MEM */
 des_decryption:1, /*[1:1] ,NO_MEM */
 des_ofb_mode:1, /*[2:2] ,NO_MEM */
 des_cbc_mode:1, /*[3:3] ,NO_MEM */
 des_cts_mode:1, /*[4:4] ,NO_MEM */
 hole0:11,
 des_key_index:4, /*[19:16] ,NO_MEM */
 hole1:10,
 des_cpu_access_err:1, /*[30:30] ,RO */
 des_end:1; /*[31:31] ,RO */
 } bits;

 uint32_t value;
};

union r2r_des_access_regReg {
 struct { uint32_t

 /* sorting 2 */
#define r2r_des_access_reg_residual_bytes_SHIFT 0
#define r2r_des_access_reg_residual_bytes_WIDTH 3
#define r2r_des_access_reg_counter_cycles_SHIFT 3
#define r2r_des_access_reg_counter_cycles_WIDTH 21

 residual_bytes:3, /*[2:0]  */
 counter_cycles:21, /*[23:3]  */
 hole0:8;
 } bits;

 uint32_t value;
};

struct hc_r2r_des {
 uint32_t r2r_des_IV[2]; /* +0x00000000 [127:64],RO */
 union r2r_des_config_regReg r2r_des_config_reg; /* +0x00000008  */
 union r2r_des_access_regReg r2r_des_access_reg; /* +0x0000000c ,NO_TEST */
};
