/* autogenerated with parsecfg: do not edit. */

union hc_sysids_revision_idReg {
 struct { uint32_t

 /* sorting 1 */
#define hc_sysids_revision_id_hc_sysids_revision_id_value_SHIFT 0
#define hc_sysids_revision_id_hc_sysids_revision_id_value_WIDTH 8

 hc_sysids_revision_id_value:8, /*[7:0] ,RO */
 hole0:24;
 } bits;

 uint32_t value;
};

union hc_sysids_featuresReg {
 struct { uint32_t

 /* sorting 1 */
#define hc_sysids_features_hc_sysids_features_value_SHIFT 0
#define hc_sysids_features_hc_sysids_features_value_WIDTH 8

 hc_sysids_features_value:8, /*[7:0]  */
 hole0:24;
 } bits;

 uint32_t value;
};

union hc_sysids_device_idReg {
 struct { uint32_t

 /* sorting 2 */
#define hc_sysids_device_id_device_id_value_SHIFT 0
#define hc_sysids_device_id_device_id_value_WIDTH 16
#define hc_sysids_device_id_arch_id_value_SHIFT 24
#define hc_sysids_device_id_arch_id_value_WIDTH 8

 device_id_value:16, /*[15:0] ,RO */
 hole0:8,
 arch_id_value:8; /*[31:24] ,RO */
 } bits;

 uint32_t value;
};

struct hc_system_ids {
 union hc_sysids_device_idReg hc_sysids_device_id; /* +0x00000000  */
 union hc_sysids_revision_idReg hc_sysids_revision_id; /* +0x00000004  */
 uint32_t hc_sysids_jtag_idcode; /* +0x00000008  */
 union hc_sysids_featuresReg hc_sysids_features; /* +0x0000000c  */
};
