/* autogenerated with parsecfg: do not edit. */

union ha_pll_ctrl_3Reg {
 struct { uint32_t

 /* sorting 6 */
#define ha_pll_ctrl_3_F_SHIFT 0
#define ha_pll_ctrl_3_F_WIDTH 7
#define ha_pll_ctrl_3_Q_SHIFT 13
#define ha_pll_ctrl_3_Q_WIDTH 3
#define ha_pll_ctrl_3_R_SHIFT 16
#define ha_pll_ctrl_3_R_WIDTH 3
#define ha_pll_ctrl_3_bypass_SHIFT 29
#define ha_pll_ctrl_3_bypass_WIDTH 1
#define ha_pll_ctrl_3_reset_SHIFT 30
#define ha_pll_ctrl_3_reset_WIDTH 1
#define ha_pll_ctrl_3_busy_SHIFT 31
#define ha_pll_ctrl_3_busy_WIDTH 1

 f:7, /*[6:0] ,NO_MEM */
 hole0:6,
 q:3, /*[15:13] ,NO_MEM */
 r:3, /*[18:16] ,NO_MEM */
 hole1:10,
 bypass:1, /*[29:29] ,NO_MEM */
 reset:1, /*[30:30] ,NO_MEM */
 busy:1; /*[31:31] ,RO */
 } bits;

 uint32_t value;
};

union ha_pll_ctrl_2Reg {
 struct { uint32_t

 /* sorting 6 */
#define ha_pll_ctrl_2_F_SHIFT 0
#define ha_pll_ctrl_2_F_WIDTH 7
#define ha_pll_ctrl_2_Q_SHIFT 13
#define ha_pll_ctrl_2_Q_WIDTH 3
#define ha_pll_ctrl_2_R_SHIFT 16
#define ha_pll_ctrl_2_R_WIDTH 3
#define ha_pll_ctrl_2_bypass_SHIFT 29
#define ha_pll_ctrl_2_bypass_WIDTH 1
#define ha_pll_ctrl_2_reset_SHIFT 30
#define ha_pll_ctrl_2_reset_WIDTH 1
#define ha_pll_ctrl_2_busy_SHIFT 31
#define ha_pll_ctrl_2_busy_WIDTH 1

 f:7, /*[6:0] ,NO_MEM */
 hole0:6,
 q:3, /*[15:13] ,NO_MEM */
 r:3, /*[18:16] ,NO_MEM */
 hole1:10,
 bypass:1, /*[29:29] ,NO_MEM */
 reset:1, /*[30:30] ,NO_MEM */
 busy:1; /*[31:31] ,RO */
 } bits;

 uint32_t value;
};

union ha_pll_ctrl_1Reg {
 struct { uint32_t

 /* sorting 6 */
#define ha_pll_ctrl_1_F_SHIFT 0
#define ha_pll_ctrl_1_F_WIDTH 7
#define ha_pll_ctrl_1_Q_SHIFT 13
#define ha_pll_ctrl_1_Q_WIDTH 3
#define ha_pll_ctrl_1_R_SHIFT 16
#define ha_pll_ctrl_1_R_WIDTH 3
#define ha_pll_ctrl_1_bypass_SHIFT 29
#define ha_pll_ctrl_1_bypass_WIDTH 1
#define ha_pll_ctrl_1_reset_SHIFT 30
#define ha_pll_ctrl_1_reset_WIDTH 1
#define ha_pll_ctrl_1_busy_SHIFT 31
#define ha_pll_ctrl_1_busy_WIDTH 1

 f:7, /*[6:0] ,NO_MEM */
 hole0:6,
 q:3, /*[15:13] ,NO_MEM */
 r:3, /*[18:16] ,NO_MEM */
 hole1:10,
 bypass:1, /*[29:29] ,NO_MEM */
 reset:1, /*[30:30] ,NO_MEM */
 busy:1; /*[31:31] ,RO */
 } bits;

 uint32_t value;
};

union ha_pll_ctrl_0Reg {
 struct { uint32_t

 /* sorting 6 */
#define ha_pll_ctrl_0_F_SHIFT 0
#define ha_pll_ctrl_0_F_WIDTH 7
#define ha_pll_ctrl_0_Q_SHIFT 13
#define ha_pll_ctrl_0_Q_WIDTH 3
#define ha_pll_ctrl_0_R_SHIFT 16
#define ha_pll_ctrl_0_R_WIDTH 3
#define ha_pll_ctrl_0_bypass_SHIFT 29
#define ha_pll_ctrl_0_bypass_WIDTH 1
#define ha_pll_ctrl_0_reset_SHIFT 30
#define ha_pll_ctrl_0_reset_WIDTH 1
#define ha_pll_ctrl_0_busy_SHIFT 31
#define ha_pll_ctrl_0_busy_WIDTH 1

 f:7, /*[6:0] ,NO_MEM */
 hole0:6,
 q:3, /*[15:13] ,NO_MEM */
 r:3, /*[18:16] ,NO_MEM */
 hole1:10,
 bypass:1, /*[29:29] ,NO_MEM */
 reset:1, /*[30:30] ,NO_MEM */
 busy:1; /*[31:31] ,RO */
 } bits;

 uint32_t value;
};

union ha_clkgen_ctrl_8Reg {
 struct { uint32_t

 /* sorting 7 */
#define ha_clkgen_ctrl_8_ramp_div_SHIFT 4
#define ha_clkgen_ctrl_8_ramp_div_WIDTH 12
#define ha_clkgen_ctrl_8_pll_mux_SHIFT 16
#define ha_clkgen_ctrl_8_pll_mux_WIDTH 4
#define ha_clkgen_ctrl_8_ramp_mode_SHIFT 26
#define ha_clkgen_ctrl_8_ramp_mode_WIDTH 2
#define ha_clkgen_ctrl_8_int_div_bypass_SHIFT 28
#define ha_clkgen_ctrl_8_int_div_bypass_WIDTH 1
#define ha_clkgen_ctrl_8_xtal_sel_SHIFT 29
#define ha_clkgen_ctrl_8_xtal_sel_WIDTH 1
#define ha_clkgen_ctrl_8_icg_SHIFT 30
#define ha_clkgen_ctrl_8_icg_WIDTH 1
#define ha_clkgen_ctrl_8_busy_SHIFT 31
#define ha_clkgen_ctrl_8_busy_WIDTH 1

 hole0:4,
 ramp_div:12, /*[15:4] ,NO_MEM */
 pll_mux:4, /*[19:16] ,NO_MEM */
 hole1:6,
 ramp_mode:2, /*[27:26] ,NO_MEM */
 int_div_bypass:1, /*[28:28] ,NO_MEM */
 xtal_sel:1, /*[29:29] ,NO_MEM */
 icg:1, /*[30:30] ,NO_MEM */
 busy:1; /*[31:31] ,NO_MEM */
 } bits;

 uint32_t value;
};

union ha_clkgen_ctrl_7Reg {
 struct { uint32_t

 /* sorting 7 */
#define ha_clkgen_ctrl_7_ramp_div_SHIFT 4
#define ha_clkgen_ctrl_7_ramp_div_WIDTH 12
#define ha_clkgen_ctrl_7_pll_mux_SHIFT 16
#define ha_clkgen_ctrl_7_pll_mux_WIDTH 4
#define ha_clkgen_ctrl_7_ramp_mode_SHIFT 26
#define ha_clkgen_ctrl_7_ramp_mode_WIDTH 2
#define ha_clkgen_ctrl_7_int_div_bypass_SHIFT 28
#define ha_clkgen_ctrl_7_int_div_bypass_WIDTH 1
#define ha_clkgen_ctrl_7_xtal_sel_SHIFT 29
#define ha_clkgen_ctrl_7_xtal_sel_WIDTH 1
#define ha_clkgen_ctrl_7_icg_SHIFT 30
#define ha_clkgen_ctrl_7_icg_WIDTH 1
#define ha_clkgen_ctrl_7_busy_SHIFT 31
#define ha_clkgen_ctrl_7_busy_WIDTH 1

 hole0:4,
 ramp_div:12, /*[15:4] ,NO_MEM */
 pll_mux:4, /*[19:16] ,NO_MEM */
 hole1:6,
 ramp_mode:2, /*[27:26] ,NO_MEM */
 int_div_bypass:1, /*[28:28] ,NO_MEM */
 xtal_sel:1, /*[29:29] ,NO_MEM */
 icg:1, /*[30:30] ,NO_MEM */
 busy:1; /*[31:31] ,NO_MEM */
 } bits;

 uint32_t value;
};

union ha_clkgen_ctrl_6Reg {
 struct { uint32_t

 /* sorting 7 */
#define ha_clkgen_ctrl_6_ramp_div_SHIFT 4
#define ha_clkgen_ctrl_6_ramp_div_WIDTH 12
#define ha_clkgen_ctrl_6_pll_mux_SHIFT 16
#define ha_clkgen_ctrl_6_pll_mux_WIDTH 4
#define ha_clkgen_ctrl_6_ramp_mode_SHIFT 26
#define ha_clkgen_ctrl_6_ramp_mode_WIDTH 2
#define ha_clkgen_ctrl_6_int_div_bypass_SHIFT 28
#define ha_clkgen_ctrl_6_int_div_bypass_WIDTH 1
#define ha_clkgen_ctrl_6_xtal_sel_SHIFT 29
#define ha_clkgen_ctrl_6_xtal_sel_WIDTH 1
#define ha_clkgen_ctrl_6_icg_SHIFT 30
#define ha_clkgen_ctrl_6_icg_WIDTH 1
#define ha_clkgen_ctrl_6_busy_SHIFT 31
#define ha_clkgen_ctrl_6_busy_WIDTH 1

 hole0:4,
 ramp_div:12, /*[15:4] ,NO_MEM */
 pll_mux:4, /*[19:16] ,NO_MEM */
 hole1:6,
 ramp_mode:2, /*[27:26] ,NO_MEM */
 int_div_bypass:1, /*[28:28] ,NO_MEM */
 xtal_sel:1, /*[29:29] ,NO_MEM */
 icg:1, /*[30:30] ,NO_MEM */
 busy:1; /*[31:31] ,NO_MEM */
 } bits;

 uint32_t value;
};

union ha_clkgen_ctrl_5Reg {
 struct { uint32_t

 /* sorting 7 */
#define ha_clkgen_ctrl_5_ramp_div_SHIFT 4
#define ha_clkgen_ctrl_5_ramp_div_WIDTH 12
#define ha_clkgen_ctrl_5_pll_mux_SHIFT 16
#define ha_clkgen_ctrl_5_pll_mux_WIDTH 4
#define ha_clkgen_ctrl_5_ramp_mode_SHIFT 26
#define ha_clkgen_ctrl_5_ramp_mode_WIDTH 2
#define ha_clkgen_ctrl_5_int_div_bypass_SHIFT 28
#define ha_clkgen_ctrl_5_int_div_bypass_WIDTH 1
#define ha_clkgen_ctrl_5_xtal_sel_SHIFT 29
#define ha_clkgen_ctrl_5_xtal_sel_WIDTH 1
#define ha_clkgen_ctrl_5_icg_SHIFT 30
#define ha_clkgen_ctrl_5_icg_WIDTH 1
#define ha_clkgen_ctrl_5_busy_SHIFT 31
#define ha_clkgen_ctrl_5_busy_WIDTH 1

 hole0:4,
 ramp_div:12, /*[15:4] ,NO_MEM */
 pll_mux:4, /*[19:16] ,NO_MEM */
 hole1:6,
 ramp_mode:2, /*[27:26] ,NO_MEM */
 int_div_bypass:1, /*[28:28] ,NO_MEM */
 xtal_sel:1, /*[29:29] ,NO_MEM */
 icg:1, /*[30:30] ,NO_MEM */
 busy:1; /*[31:31] ,NO_MEM */
 } bits;

 uint32_t value;
};

union ha_clkgen_ctrl_4Reg {
 struct { uint32_t

 /* sorting 7 */
#define ha_clkgen_ctrl_4_ramp_div_SHIFT 4
#define ha_clkgen_ctrl_4_ramp_div_WIDTH 12
#define ha_clkgen_ctrl_4_pll_mux_SHIFT 16
#define ha_clkgen_ctrl_4_pll_mux_WIDTH 4
#define ha_clkgen_ctrl_4_ramp_mode_SHIFT 26
#define ha_clkgen_ctrl_4_ramp_mode_WIDTH 2
#define ha_clkgen_ctrl_4_int_div_bypass_SHIFT 28
#define ha_clkgen_ctrl_4_int_div_bypass_WIDTH 1
#define ha_clkgen_ctrl_4_xtal_sel_SHIFT 29
#define ha_clkgen_ctrl_4_xtal_sel_WIDTH 1
#define ha_clkgen_ctrl_4_icg_SHIFT 30
#define ha_clkgen_ctrl_4_icg_WIDTH 1
#define ha_clkgen_ctrl_4_busy_SHIFT 31
#define ha_clkgen_ctrl_4_busy_WIDTH 1

 hole0:4,
 ramp_div:12, /*[15:4] ,NO_MEM */
 pll_mux:4, /*[19:16] ,NO_MEM */
 hole1:6,
 ramp_mode:2, /*[27:26] ,NO_MEM */
 int_div_bypass:1, /*[28:28] ,NO_MEM */
 xtal_sel:1, /*[29:29] ,NO_MEM */
 icg:1, /*[30:30] ,NO_MEM */
 busy:1; /*[31:31] ,NO_MEM */
 } bits;

 uint32_t value;
};

union ha_clkgen_ctrl_3Reg {
 struct { uint32_t

 /* sorting 7 */
#define ha_clkgen_ctrl_3_ramp_div_SHIFT 4
#define ha_clkgen_ctrl_3_ramp_div_WIDTH 12
#define ha_clkgen_ctrl_3_pll_mux_SHIFT 16
#define ha_clkgen_ctrl_3_pll_mux_WIDTH 4
#define ha_clkgen_ctrl_3_ramp_mode_SHIFT 26
#define ha_clkgen_ctrl_3_ramp_mode_WIDTH 2
#define ha_clkgen_ctrl_3_int_div_bypass_SHIFT 28
#define ha_clkgen_ctrl_3_int_div_bypass_WIDTH 1
#define ha_clkgen_ctrl_3_xtal_sel_SHIFT 29
#define ha_clkgen_ctrl_3_xtal_sel_WIDTH 1
#define ha_clkgen_ctrl_3_icg_SHIFT 30
#define ha_clkgen_ctrl_3_icg_WIDTH 1
#define ha_clkgen_ctrl_3_busy_SHIFT 31
#define ha_clkgen_ctrl_3_busy_WIDTH 1

 hole0:4,
 ramp_div:12, /*[15:4] ,NO_MEM */
 pll_mux:4, /*[19:16] ,NO_MEM */
 hole1:6,
 ramp_mode:2, /*[27:26] ,NO_MEM */
 int_div_bypass:1, /*[28:28] ,NO_MEM */
 xtal_sel:1, /*[29:29] ,NO_MEM */
 icg:1, /*[30:30] ,NO_MEM */
 busy:1; /*[31:31] ,NO_MEM */
 } bits;

 uint32_t value;
};

union ha_clkgen_ctrl_2Reg {
 struct { uint32_t

 /* sorting 7 */
#define ha_clkgen_ctrl_2_ramp_div_SHIFT 4
#define ha_clkgen_ctrl_2_ramp_div_WIDTH 12
#define ha_clkgen_ctrl_2_pll_mux_SHIFT 16
#define ha_clkgen_ctrl_2_pll_mux_WIDTH 4
#define ha_clkgen_ctrl_2_ramp_mode_SHIFT 26
#define ha_clkgen_ctrl_2_ramp_mode_WIDTH 2
#define ha_clkgen_ctrl_2_int_div_bypass_SHIFT 28
#define ha_clkgen_ctrl_2_int_div_bypass_WIDTH 1
#define ha_clkgen_ctrl_2_xtal_sel_SHIFT 29
#define ha_clkgen_ctrl_2_xtal_sel_WIDTH 1
#define ha_clkgen_ctrl_2_icg_SHIFT 30
#define ha_clkgen_ctrl_2_icg_WIDTH 1
#define ha_clkgen_ctrl_2_busy_SHIFT 31
#define ha_clkgen_ctrl_2_busy_WIDTH 1

 hole0:4,
 ramp_div:12, /*[15:4] ,NO_MEM */
 pll_mux:4, /*[19:16] ,NO_MEM */
 hole1:6,
 ramp_mode:2, /*[27:26] ,NO_MEM */
 int_div_bypass:1, /*[28:28] ,NO_MEM */
 xtal_sel:1, /*[29:29] ,NO_MEM */
 icg:1, /*[30:30] ,NO_MEM */
 busy:1; /*[31:31] ,NO_MEM */
 } bits;

 uint32_t value;
};

union ha_clkgen_ctrl_1Reg {
 struct { uint32_t

 /* sorting 7 */
#define ha_clkgen_ctrl_1_ramp_div_SHIFT 4
#define ha_clkgen_ctrl_1_ramp_div_WIDTH 12
#define ha_clkgen_ctrl_1_pll_mux_SHIFT 16
#define ha_clkgen_ctrl_1_pll_mux_WIDTH 4
#define ha_clkgen_ctrl_1_ramp_mode_SHIFT 26
#define ha_clkgen_ctrl_1_ramp_mode_WIDTH 2
#define ha_clkgen_ctrl_1_int_div_bypass_SHIFT 28
#define ha_clkgen_ctrl_1_int_div_bypass_WIDTH 1
#define ha_clkgen_ctrl_1_xtal_sel_SHIFT 29
#define ha_clkgen_ctrl_1_xtal_sel_WIDTH 1
#define ha_clkgen_ctrl_1_icg_SHIFT 30
#define ha_clkgen_ctrl_1_icg_WIDTH 1
#define ha_clkgen_ctrl_1_busy_SHIFT 31
#define ha_clkgen_ctrl_1_busy_WIDTH 1

 hole0:4,
 ramp_div:12, /*[15:4] ,NO_MEM */
 pll_mux:4, /*[19:16] ,NO_MEM */
 hole1:6,
 ramp_mode:2, /*[27:26] ,NO_MEM */
 int_div_bypass:1, /*[28:28] ,NO_MEM */
 xtal_sel:1, /*[29:29] ,NO_MEM */
 icg:1, /*[30:30] ,NO_MEM */
 busy:1; /*[31:31] ,NO_MEM */
 } bits;

 uint32_t value;
};

union ha_clkgen_ctrl_0Reg {
 struct { uint32_t

 /* sorting 7 */
#define ha_clkgen_ctrl_0_ramp_div_SHIFT 4
#define ha_clkgen_ctrl_0_ramp_div_WIDTH 12
#define ha_clkgen_ctrl_0_pll_mux_SHIFT 16
#define ha_clkgen_ctrl_0_pll_mux_WIDTH 4
#define ha_clkgen_ctrl_0_ramp_mode_SHIFT 26
#define ha_clkgen_ctrl_0_ramp_mode_WIDTH 2
#define ha_clkgen_ctrl_0_int_div_bypass_SHIFT 28
#define ha_clkgen_ctrl_0_int_div_bypass_WIDTH 1
#define ha_clkgen_ctrl_0_xtal_sel_SHIFT 29
#define ha_clkgen_ctrl_0_xtal_sel_WIDTH 1
#define ha_clkgen_ctrl_0_icg_SHIFT 30
#define ha_clkgen_ctrl_0_icg_WIDTH 1
#define ha_clkgen_ctrl_0_busy_SHIFT 31
#define ha_clkgen_ctrl_0_busy_WIDTH 1

 hole0:4,
 ramp_div:12, /*[15:4] ,NO_MEM */
 pll_mux:4, /*[19:16] ,NO_MEM */
 hole1:6,
 ramp_mode:2, /*[27:26] ,NO_MEM */
 int_div_bypass:1, /*[28:28] ,NO_MEM */
 xtal_sel:1, /*[29:29] ,NO_MEM */
 icg:1, /*[30:30] ,NO_MEM */
 busy:1; /*[31:31] ,NO_MEM */
 } bits;

 uint32_t value;
};

struct hcc {
 union ha_pll_ctrl_0Reg ha_pll_ctrl_0; /* +0x00000000  */
 union ha_pll_ctrl_1Reg ha_pll_ctrl_1; /* +0x00000004  */
 union ha_pll_ctrl_2Reg ha_pll_ctrl_2; /* +0x00000008  */
 union ha_pll_ctrl_3Reg ha_pll_ctrl_3; /* +0x0000000c  */
 uint32_t pad0[0x0030/4];
 uint32_t ha_life_clk_cnt_lsb; /* +0x00000040 ,NO_TEST */
 uint32_t ha_life_clk_cnt_msb; /* +0x00000044 ,NO_TEST */
 uint32_t ha_system_clk_cnt; /* +0x00000048 ,NO_TEST */
 uint32_t ha_random_clk_cnt; /* +0x0000004c ,NO_TEST */
 uint32_t ha_xtal_clk_cnt; /* +0x00000050 ,NO_TEST */
 uint32_t ha_pll_0_cnt; /* +0x00000054 ,NO_TEST */
 uint32_t ha_pll_1_cnt; /* +0x00000058 ,NO_TEST */
 uint32_t ha_pll_2_cnt; /* +0x0000005c ,NO_TEST */
 uint32_t ha_pll_3_cnt; /* +0x00000060 ,NO_TEST */
 uint32_t ha_oclk_0_cnt; /* +0x00000064 ,NO_TEST */
 uint32_t ha_oclk_1_cnt; /* +0x00000068 ,NO_TEST */
 uint32_t ha_oclk_2_cnt; /* +0x0000006c ,NO_TEST */
 uint32_t ha_oclk_3_cnt; /* +0x00000070 ,NO_TEST */
 uint32_t ha_oclk_4_cnt; /* +0x00000074 ,NO_TEST */
 uint32_t ha_oclk_5_cnt; /* +0x00000078 ,NO_TEST */
 uint32_t ha_oclk_6_cnt; /* +0x0000007c ,NO_TEST */
 uint32_t ha_oclk_7_cnt; /* +0x00000080 ,NO_TEST */
 uint32_t pad1[0x007c/4];
 union ha_clkgen_ctrl_0Reg ha_clkgen_ctrl_0; /* +0x00000100  */
 union ha_clkgen_ctrl_1Reg ha_clkgen_ctrl_1; /* +0x00000104  */
 union ha_clkgen_ctrl_2Reg ha_clkgen_ctrl_2; /* +0x00000108  */
 union ha_clkgen_ctrl_3Reg ha_clkgen_ctrl_3; /* +0x0000010c  */
 union ha_clkgen_ctrl_4Reg ha_clkgen_ctrl_4; /* +0x00000110  */
 union ha_clkgen_ctrl_5Reg ha_clkgen_ctrl_5; /* +0x00000114  */
 union ha_clkgen_ctrl_6Reg ha_clkgen_ctrl_6; /* +0x00000118  */
 union ha_clkgen_ctrl_7Reg ha_clkgen_ctrl_7; /* +0x0000011c  */
 union ha_clkgen_ctrl_8Reg ha_clkgen_ctrl_8; /* +0x00000120  */
};
