/* autogenerated with parsecfg: do not edit. */

struct host_switchbox {
 uint32_t sbox_connect; /* +0x00000000 ,NO_MEM */
 uint32_t sbox_disconnect; /* +0x00000004 ,NO_MEM */
 uint32_t mbus_ch0_sbox_connection; /* +0x00000008 ,RO */
 uint32_t mbus_ch1_sbox_connection; /* +0x0000000c ,RO */
 uint32_t mlc_flash0_sbox_connection; /* +0x00000010 ,RO */
 uint32_t mlc_flash1_sbox_connection; /* +0x00000014 ,RO */
 uint32_t pbus0_sbox_connection; /* +0x00000018 ,RO */
 uint32_t pbus1_sbox_connection; /* +0x0000001c ,RO */
 uint32_t pad0[0x0068/4];
 uint32_t sbox_mbus_ch0_connection; /* +0x00000088 ,RO */
 uint32_t sbox_mbus_ch1_connection; /* +0x0000008c ,RO */
 uint32_t sbox_mlc_flash0_connection; /* +0x00000090 ,RO */
 uint32_t sbox_mlc_flash1_connection; /* +0x00000094 ,RO */
 uint32_t sbox_pbus0_connection; /* +0x00000098 ,RO */
 uint32_t sbox_pbus1_connection; /* +0x0000009c ,RO */
};
