/* autogenerated with parsemap: do not edit. */
struct host_lbus_address_decoder_mem {
                              uint32_t pad0[4096/4];
#define host_lbus_address_decoder_mem_sdio0_OFF 0x00001000
/* [0x00001000,0x00001200[ */ struct { struct sdio0_det d; uint32_t w[(0x00000200-sizeof(struct sdio0_det))/4]; } _sdio0;
                              uint32_t pad1[512/4];
#define host_lbus_address_decoder_mem_clean_div_OFF 0x00001400
/* [0x00001400,0x00001420[ */ struct { struct clean_div_det d; uint32_t w[(0x00000020-sizeof(struct clean_div_det))/4]; } _clean_div;
                              uint32_t pad2[7136/4];
#define host_lbus_address_decoder_mem_sata_0_1_OFF 0x00003000
/* [0x00003000,0x00004000[ */ struct { struct sata_0_1_det d; uint32_t w[(0x00001000-sizeof(struct sata_0_1_det))/4]; } _sata_0_1;
#define host_lbus_address_decoder_mem_sata_misc_OFF 0x00004000
/* [0x00004000,0x00004040[ */ struct { struct sata_misc_det d; uint32_t w[(0x00000040-sizeof(struct sata_misc_det))/4]; } _sata_misc;
                              uint32_t pad3[4032/4];
#define host_lbus_address_decoder_mem_cipher_OFF 0x00005000
/* [0x00005000,0x00005340[ */ struct { struct cipher_det d; uint32_t w[(0x00000340-sizeof(struct cipher_det))/4]; } _cipher;
                              uint32_t pad4[3264/4];
#define host_lbus_address_decoder_mem_eth0_OFF 0x00006000
/* [0x00006000,0x00006400[ */ struct { struct eth0_det d; uint32_t w[(0x00000400-sizeof(struct eth0_det))/4]; } _eth0;
#define host_lbus_address_decoder_mem_eth_gpio0_OFF 0x00006400
/* [0x00006400,0x00006500[ */ struct { struct eth_gpio0_det d; uint32_t w[(0x00000100-sizeof(struct eth_gpio0_det))/4]; } _eth_gpio0;
                              uint32_t pad5[768/4];
#define host_lbus_address_decoder_mem_eth1_OFF 0x00006800
/* [0x00006800,0x00006c00[ */ struct { struct eth1_det d; uint32_t w[(0x00000400-sizeof(struct eth1_det))/4]; } _eth1;
#define host_lbus_address_decoder_mem_eth_gpio1_OFF 0x00006c00
/* [0x00006c00,0x00006d00[ */ struct { struct eth_gpio1_det d; uint32_t w[(0x00000100-sizeof(struct eth_gpio1_det))/4]; } _eth_gpio1;
                              uint32_t pad6[768/4];
#define host_lbus_address_decoder_mem_eth0_ipf_OFF 0x00007000
/* [0x00007000,0x00007800[ */ struct { struct eth0_ipf_det d; uint32_t w[(0x00000800-sizeof(struct eth0_ipf_det))/4]; } _eth0_ipf;
#define host_lbus_address_decoder_mem_eth1_ipf_OFF 0x00007800
/* [0x00007800,0x00008000[ */ struct { struct eth1_ipf_det d; uint32_t w[(0x00000800-sizeof(struct eth1_ipf_det))/4]; } _eth1_ipf;
#define host_lbus_address_decoder_mem_eth0_tx_hmux_ram_OFF 0x00008000
/* [0x00008000,0x00008800[ */ struct { struct eth0_tx_hmux_ram_det d; uint32_t w[(0x00000800-sizeof(struct eth0_tx_hmux_ram_det))/4]; } _eth0_tx_hmux_ram;
#define host_lbus_address_decoder_mem_eth1_tx_hmux_ram_OFF 0x00008800
/* [0x00008800,0x00009000[ */ struct { struct eth1_tx_hmux_ram_det d; uint32_t w[(0x00000800-sizeof(struct eth1_tx_hmux_ram_det))/4]; } _eth1_tx_hmux_ram;
                              uint32_t pad7[2048/4];
#define host_lbus_address_decoder_mem_crc32_OFF 0x00009800
/* [0x00009800,0x00009810[ */ struct { struct crc32_det d; uint32_t w[(0x00000010-sizeof(struct crc32_det))/4]; } _crc32;
                              uint32_t pad8[6128/4];
#define host_lbus_address_decoder_mem_mbusm_OFF 0x0000b000
/* [0x0000b000,0x0000b100[ */ struct { struct mbusm_det d; uint32_t w[(0x00000100-sizeof(struct mbusm_det))/4]; } _mbusm;
                              uint32_t pad9[3840/4];
#define host_lbus_address_decoder_mem_eth_sw_OFF 0x0000c000
/* [0x0000c000,0x00010000[ */ struct { struct eth_sw_det d; uint32_t w[(0x00004000-sizeof(struct eth_sw_det))/4]; } _eth_sw;
};
