/* autogenerated with parsecfg: do not edit. */

struct lib_gbus_master16 {
 uint32_t main_gbus_master_dword0_low; /* +0x00000000  */
 uint32_t main_gbus_master_dword0_high; /* +0x00000004  */
 uint32_t main_gbus_master_dword1_low; /* +0x00000008  */
 uint32_t main_gbus_master_dword1_high; /* +0x0000000c  */
 uint32_t main_gbus_master_dword2_low; /* +0x00000010  */
 uint32_t main_gbus_master_dword2_high; /* +0x00000014  */
 uint32_t main_gbus_master_dword3_low; /* +0x00000018  */
 uint32_t main_gbus_master_dword3_high; /* +0x0000001c  */
 uint32_t main_gbus_master_dword4_low; /* +0x00000020  */
 uint32_t main_gbus_master_dword4_high; /* +0x00000024  */
 uint32_t main_gbus_master_dword5_low; /* +0x00000028  */
 uint32_t main_gbus_master_dword5_high; /* +0x0000002c  */
 uint32_t main_gbus_master_dword6_low; /* +0x00000030  */
 uint32_t main_gbus_master_dword6_high; /* +0x00000034  */
 uint32_t main_gbus_master_dword7_low; /* +0x00000038  */
 uint32_t main_gbus_master_dword7_high; /* +0x0000003c  */
 uint32_t main_gbus_master_word; /* +0x00000040  */
 uint32_t pad0[0x0004/4];
 uint32_t main_gbus_master_byte; /* +0x00000048  */
 uint32_t pad1[0x0004/4];
 uint32_t main_gbus_master_be_low; /* +0x00000050  */
 uint32_t main_gbus_master_be_high; /* +0x00000054  */
 uint32_t main_gbus_master_add_low; /* +0x00000058  */
 uint32_t main_gbus_master_add_high; /* +0x0000005c  */
 uint32_t main_gbus_master_cmd_low; /* +0x00000060  */
 uint32_t main_gbus_master_cmd_high; /* +0x00000064  */
 uint32_t main_gbus_master_arch_low; /* +0x00000068  */
 uint32_t main_gbus_master_arch_high; /* +0x0000006c  */
 uint32_t pad2[0x0010/4];
 uint32_t isr_gbus_master_dword0_low; /* +0x00000080  */
 uint32_t isr_gbus_master_dword0_high; /* +0x00000084  */
 uint32_t isr_gbus_master_dword1_low; /* +0x00000088  */
 uint32_t isr_gbus_master_dword1_high; /* +0x0000008c  */
 uint32_t isr_gbus_master_dword2_low; /* +0x00000090  */
 uint32_t isr_gbus_master_dword2_high; /* +0x00000094  */
 uint32_t isr_gbus_master_dword3_low; /* +0x00000098  */
 uint32_t isr_gbus_master_dword3_high; /* +0x0000009c  */
 uint32_t isr_gbus_master_dword4_low; /* +0x000000a0  */
 uint32_t isr_gbus_master_dword4_high; /* +0x000000a4  */
 uint32_t isr_gbus_master_dword5_low; /* +0x000000a8  */
 uint32_t isr_gbus_master_dword5_high; /* +0x000000ac  */
 uint32_t isr_gbus_master_dword6_low; /* +0x000000b0  */
 uint32_t isr_gbus_master_dword6_high; /* +0x000000b4  */
 uint32_t isr_gbus_master_dword7_low; /* +0x000000b8  */
 uint32_t isr_gbus_master_dword7_high; /* +0x000000bc  */
 uint32_t isr_gbus_master_word; /* +0x000000c0  */
 uint32_t pad3[0x0004/4];
 uint32_t isr_gbus_master_byte; /* +0x000000c8  */
 uint32_t pad4[0x0004/4];
 uint32_t isr_gbus_master_be_low; /* +0x000000d0  */
 uint32_t isr_gbus_master_be_high; /* +0x000000d4  */
 uint32_t isr_gbus_master_add_low; /* +0x000000d8  */
 uint32_t isr_gbus_master_add_high; /* +0x000000dc  */
 uint32_t isr_gbus_master_cmd_low; /* +0x000000e0  */
 uint32_t isr_gbus_master_cmd_high; /* +0x000000e4  */
 uint32_t isr_gbus_master_arch_low; /* +0x000000e8  */
 uint32_t isr_gbus_master_arch_high; /* +0x000000ec  */
};
