/* autogenerated with parsecfg: do not edit. */

union remap8Reg {
 struct { uint32_t

 /* sorting 1 */
#define remap8_remap8_val_SHIFT 26
#define remap8_remap8_val_WIDTH 6

 hole0:26,
 remap8_val:6; /*[31:26]  */
 } bits;

 uint32_t value;
};

union remap7Reg {
 struct { uint32_t

 /* sorting 1 */
#define remap7_remap7_val_SHIFT 26
#define remap7_remap7_val_WIDTH 6

 hole0:26,
 remap7_val:6; /*[31:26]  */
 } bits;

 uint32_t value;
};

union remap6Reg {
 struct { uint32_t

 /* sorting 1 */
#define remap6_remap6_val_SHIFT 26
#define remap6_remap6_val_WIDTH 6

 hole0:26,
 remap6_val:6; /*[31:26]  */
 } bits;

 uint32_t value;
};

union remap5Reg {
 struct { uint32_t

 /* sorting 1 */
#define remap5_remap5_val_SHIFT 26
#define remap5_remap5_val_WIDTH 6

 hole0:26,
 remap5_val:6; /*[31:26]  */
 } bits;

 uint32_t value;
};

union remap4Reg {
 struct { uint32_t

 /* sorting 1 */
#define remap4_remap4_val_SHIFT 26
#define remap4_remap4_val_WIDTH 6

 hole0:26,
 remap4_val:6; /*[31:26]  */
 } bits;

 uint32_t value;
};

union remap3Reg {
 struct { uint32_t

 /* sorting 1 */
#define remap3_remap3_val_SHIFT 26
#define remap3_remap3_val_WIDTH 6

 hole0:26,
 remap3_val:6; /*[31:26]  */
 } bits;

 uint32_t value;
};

union remap2Reg {
 struct { uint32_t

 /* sorting 1 */
#define remap2_remap2_val_SHIFT 26
#define remap2_remap2_val_WIDTH 6

 hole0:26,
 remap2_val:6; /*[31:26]  */
 } bits;

 uint32_t value;
};

union remap11Reg {
 struct { uint32_t

 /* sorting 1 */
#define remap11_remap11_val_SHIFT 22
#define remap11_remap11_val_WIDTH 10

 hole0:22,
 remap11_val:10; /*[31:22]  */
 } bits;

 uint32_t value;
};

union remap10Reg {
 struct { uint32_t

 /* sorting 1 */
#define remap10_remap10_val_SHIFT 22
#define remap10_remap10_val_WIDTH 10

 hole0:22,
 remap10_val:10; /*[31:22]  */
 } bits;

 uint32_t value;
};

union remap0Reg {
 struct { uint32_t

 /* sorting 1 */
#define remap0_remap0_val_SHIFT 16
#define remap0_remap0_val_WIDTH 16

 hole0:16,
 remap0_val:16; /*[31:16]  */
 } bits;

 uint32_t value;
};

struct lib_mips_remap {
 union remap0Reg remap0; /* +0x00000000  */
 union remap2Reg remap2; /* +0x00000004  */
 union remap3Reg remap3; /* +0x00000008  */
 union remap4Reg remap4; /* +0x0000000c  */
 union remap5Reg remap5; /* +0x00000010  */
 union remap6Reg remap6; /* +0x00000014  */
 union remap7Reg remap7; /* +0x00000018  */
 union remap8Reg remap8; /* +0x0000001c  */
 union remap10Reg remap10; /* +0x00000020  */
 union remap11Reg remap11; /* +0x00000024  */
};
