/* autogenerated with parsecfg: do not edit. */

/* gotta drop vert_i2@cnt: 0xffff7fff [31:31] */
/* gotta drop vert_i1@cnt: 0xffff7fff [30:30] */
/* gotta drop vert_vcnt1@cnt: 0xffff7fff [22:16] */
/* gotta drop vert_vcnt2@cnt: 0xffff7fff [29:23] */
/* gotta drop vert_outer_cnt@cnt: 0xffffffff [14:0] */
/* gotta drop vert_stride1@strides: 0x03ff03ff [9:0] */
 /* workaround clash with C language: void */
/* gotta drop vert_stride2@strides: 0x03ff03ff [25:16] */
union stridesReg {
 struct { uint32_t

 /* sorting 2 */
#define strides_s0_SHIFT 0
#define strides_s0_WIDTH 10
#define strides_s1_SHIFT 16
#define strides_s1_WIDTH 10

 s0:10, /*[9:0]  */
 hole0:6,
 s1:10, /*[25:16] ,NO_MEM */
 hole1:6;
 } bits;

 uint32_t value;
};

union skip2Reg {
 struct { uint32_t

 /* sorting 1 */
#define skip2_skipB_val_SHIFT 0
#define skip2_skipB_val_WIDTH 26

 skipb_val:26, /*[25:0] ,NO_MEM */
 hole0:6;
 } bits;

 uint32_t value;
};

union skipReg {
 struct { uint32_t

 /* sorting 3 */
#define skip_col2_SHIFT 0
#define skip_col2_WIDTH 2
#define skip_w2_SHIFT 2
#define skip_w2_WIDTH 1
#define skip_add2_SHIFT 3
#define skip_add2_WIDTH 28

 col2:2, /*[1:0]  */
 w2:1, /*[2:2]  */
 add2:28, /*[30:3]  */
 hole0:1;
 } bits;

 uint32_t value;
};

union cnt2Reg {
 struct { uint32_t

 /* sorting 2 */
#define cnt2_xcntB_SHIFT 0
#define cnt2_xcntB_WIDTH 15
#define cnt2_ycntB_SHIFT 16
#define cnt2_ycntB_WIDTH 15

 xcntb:15, /*[14:0] ,NO_MEM */
 hole0:1,
 ycntb:15, /*[30:16] ,NO_MEM */
 hole1:1;
 } bits;

 uint32_t value;
};

union cntReg {
 struct { uint32_t

 /* sorting 3 */
#define cnt_xcnt_SHIFT 0
#define cnt_xcnt_WIDTH 15
#define cnt_vert_rev_SHIFT 15
#define cnt_vert_rev_WIDTH 1
#define cnt_ycnt_SHIFT 16
#define cnt_ycnt_WIDTH 16

 xcnt:15, /*[14:0]  */
 vert_rev:1, /*[15:15] ,NO_MEM */
 ycnt:16; /*[31:16]  */
 } bits;

 uint32_t value;
};

union cmdReg {
 struct { uint32_t

 /* sorting 4 */
#define cmd_Void_SHIFT 0
#define cmd_Void_WIDTH 1
#define cmd_op_SHIFT 1
#define cmd_op_WIDTH 3
#define cmd_tiled_SHIFT 13
#define cmd_tiled_WIDTH 1
#define cmd_bpp_SHIFT 14
#define cmd_bpp_WIDTH 2

 Void:1, /*[0:0]  */
 op:3, /*[3:1]  */
 hole0:9,
 tiled:1, /*[13:13]  */
 bpp:2, /*[15:14]  */
 hole1:16;
 } bits;

 uint32_t value;
};

union add2Reg {
 struct { uint32_t

 /* sorting 1 */
#define add2_addressB_one_SHIFT 31
#define add2_addressB_one_WIDTH 1

 hole0:31,
 addressb_one:1; /*[31:31] ,NO_MEM */
 } bits;

 uint32_t value;
};

union addReg {
 struct { uint32_t

 /* sorting 4 */
#define add_vert_col1_SHIFT 0
#define add_vert_col1_WIDTH 2
#define add_vert_w1_SHIFT 2
#define add_vert_w1_WIDTH 1
#define add_vert_add_SHIFT 3
#define add_vert_add_WIDTH 28
#define add_address_one_SHIFT 31
#define add_address_one_WIDTH 1

 vert_col1:2, /*[1:0]  */
 vert_w1:1, /*[2:2]  */
 vert_add:28, /*[30:3]  */
 address_one:1; /*[31:31] ,RO */
 } bits;

 uint32_t value;
};

struct mbus_regs_32b {
 union addReg add; /* +0x00000000  */
 union cntReg cnt; /* +0x00000004  */
 union skipReg skip; /* +0x00000008  */
 union add2Reg add2; /* +0x0000000c  */
 union cnt2Reg cnt2; /* +0x00000010  */
 union skip2Reg skip2; /* +0x00000014  */
 union stridesReg strides; /* +0x00000018  */
 union cmdReg cmd; /* +0x0000001c ,NO_TEST */
};
