/* autogenerated with parsecfg: do not edit. */

union tango_lib_gpio_interrupt1Reg {
 struct { uint32_t

 /* sorting 4 */
#define tango_lib_gpio_interrupt1_l0_SHIFT 0
#define tango_lib_gpio_interrupt1_l0_WIDTH 6
#define tango_lib_gpio_interrupt1_l1_SHIFT 8
#define tango_lib_gpio_interrupt1_l1_WIDTH 6
#define tango_lib_gpio_interrupt1_l2_SHIFT 16
#define tango_lib_gpio_interrupt1_l2_WIDTH 6
#define tango_lib_gpio_interrupt1_l3_SHIFT 24
#define tango_lib_gpio_interrupt1_l3_WIDTH 6

 l0:6, /*[5:0]  */
 hole0:2,
 l1:6, /*[13:8]  */
 hole1:2,
 l2:6, /*[21:16]  */
 hole2:2,
 l3:6, /*[29:24]  */
 hole3:2;
 } bits;

 uint32_t value;
};

union tango_lib_gpio_interrupt0Reg {
 struct { uint32_t

 /* sorting 4 */
#define tango_lib_gpio_interrupt0_l0_SHIFT 0
#define tango_lib_gpio_interrupt0_l0_WIDTH 6
#define tango_lib_gpio_interrupt0_l1_SHIFT 8
#define tango_lib_gpio_interrupt0_l1_WIDTH 6
#define tango_lib_gpio_interrupt0_l2_SHIFT 16
#define tango_lib_gpio_interrupt0_l2_WIDTH 6
#define tango_lib_gpio_interrupt0_l3_SHIFT 24
#define tango_lib_gpio_interrupt0_l3_WIDTH 6

 l0:6, /*[5:0]  */
 hole0:2,
 l1:6, /*[13:8]  */
 hole1:2,
 l2:6, /*[21:16]  */
 hole2:2,
 l3:6, /*[29:24]  */
 hole3:2;
 } bits;

 uint32_t value;
};

union tango_lib_gpio_enable3Reg {
 struct { uint32_t

 /* sorting 2 */
#define tango_lib_gpio_enable3_bits_SHIFT 0
#define tango_lib_gpio_enable3_bits_WIDTH 16
#define tango_lib_gpio_enable3_mask_SHIFT 16
#define tango_lib_gpio_enable3_mask_WIDTH 16

 bits:16, /*[15:0]  */
 mask:16; /*[31:16]  */
 } bits;

 uint32_t value;
};

union tango_lib_gpio_enable2Reg {
 struct { uint32_t

 /* sorting 2 */
#define tango_lib_gpio_enable2_bits_SHIFT 0
#define tango_lib_gpio_enable2_bits_WIDTH 16
#define tango_lib_gpio_enable2_mask_SHIFT 16
#define tango_lib_gpio_enable2_mask_WIDTH 16

 bits:16, /*[15:0]  */
 mask:16; /*[31:16]  */
 } bits;

 uint32_t value;
};

union tango_lib_gpio_enable1Reg {
 struct { uint32_t

 /* sorting 2 */
#define tango_lib_gpio_enable1_bits_SHIFT 0
#define tango_lib_gpio_enable1_bits_WIDTH 16
#define tango_lib_gpio_enable1_mask_SHIFT 16
#define tango_lib_gpio_enable1_mask_WIDTH 16

 bits:16, /*[15:0]  */
 mask:16; /*[31:16]  */
 } bits;

 uint32_t value;
};

union tango_lib_gpio_enable0Reg {
 struct { uint32_t

 /* sorting 2 */
#define tango_lib_gpio_enable0_bits_SHIFT 0
#define tango_lib_gpio_enable0_bits_WIDTH 16
#define tango_lib_gpio_enable0_mask_SHIFT 16
#define tango_lib_gpio_enable0_mask_WIDTH 16

 bits:16, /*[15:0]  */
 mask:16; /*[31:16]  */
 } bits;

 uint32_t value;
};

union tango_lib_gpio_direction3Reg {
 struct { uint32_t

 /* sorting 2 */
#define tango_lib_gpio_direction3_bits_SHIFT 0
#define tango_lib_gpio_direction3_bits_WIDTH 16
#define tango_lib_gpio_direction3_mask_SHIFT 16
#define tango_lib_gpio_direction3_mask_WIDTH 16

 bits:16, /*[15:0]  */
 mask:16; /*[31:16]  */
 } bits;

 uint32_t value;
};

union tango_lib_gpio_direction2Reg {
 struct { uint32_t

 /* sorting 2 */
#define tango_lib_gpio_direction2_bits_SHIFT 0
#define tango_lib_gpio_direction2_bits_WIDTH 16
#define tango_lib_gpio_direction2_mask_SHIFT 16
#define tango_lib_gpio_direction2_mask_WIDTH 16

 bits:16, /*[15:0]  */
 mask:16; /*[31:16]  */
 } bits;

 uint32_t value;
};

union tango_lib_gpio_direction1Reg {
 struct { uint32_t

 /* sorting 2 */
#define tango_lib_gpio_direction1_bits_SHIFT 0
#define tango_lib_gpio_direction1_bits_WIDTH 16
#define tango_lib_gpio_direction1_mask_SHIFT 16
#define tango_lib_gpio_direction1_mask_WIDTH 16

 bits:16, /*[15:0]  */
 mask:16; /*[31:16]  */
 } bits;

 uint32_t value;
};

union tango_lib_gpio_direction0Reg {
 struct { uint32_t

 /* sorting 2 */
#define tango_lib_gpio_direction0_bits_SHIFT 0
#define tango_lib_gpio_direction0_bits_WIDTH 16
#define tango_lib_gpio_direction0_mask_SHIFT 16
#define tango_lib_gpio_direction0_mask_WIDTH 16

 bits:16, /*[15:0]  */
 mask:16; /*[31:16]  */
 } bits;

 uint32_t value;
};

union tango_lib_gpio_data3Reg {
 struct { uint32_t

 /* sorting 2 */
#define tango_lib_gpio_data3_bits_SHIFT 0
#define tango_lib_gpio_data3_bits_WIDTH 16
#define tango_lib_gpio_data3_mask_SHIFT 16
#define tango_lib_gpio_data3_mask_WIDTH 16

 bits:16, /*[15:0]  */
 mask:16; /*[31:16]  */
 } bits;

 uint32_t value;
};

union tango_lib_gpio_data2Reg {
 struct { uint32_t

 /* sorting 2 */
#define tango_lib_gpio_data2_bits_SHIFT 0
#define tango_lib_gpio_data2_bits_WIDTH 16
#define tango_lib_gpio_data2_mask_SHIFT 16
#define tango_lib_gpio_data2_mask_WIDTH 16

 bits:16, /*[15:0]  */
 mask:16; /*[31:16]  */
 } bits;

 uint32_t value;
};

union tango_lib_gpio_data1Reg {
 struct { uint32_t

 /* sorting 2 */
#define tango_lib_gpio_data1_bits_SHIFT 0
#define tango_lib_gpio_data1_bits_WIDTH 16
#define tango_lib_gpio_data1_mask_SHIFT 16
#define tango_lib_gpio_data1_mask_WIDTH 16

 bits:16, /*[15:0]  */
 mask:16; /*[31:16]  */
 } bits;

 uint32_t value;
};

union tango_lib_gpio_data0Reg {
 struct { uint32_t

 /* sorting 2 */
#define tango_lib_gpio_data0_bits_SHIFT 0
#define tango_lib_gpio_data0_bits_WIDTH 16
#define tango_lib_gpio_data0_mask_SHIFT 16
#define tango_lib_gpio_data0_mask_WIDTH 16

 bits:16, /*[15:0]  */
 mask:16; /*[31:16]  */
 } bits;

 uint32_t value;
};

struct tango_lib_gpio_interface {
 union tango_lib_gpio_direction0Reg tango_lib_gpio_direction0; /* +0x00000000  */
 union tango_lib_gpio_data0Reg tango_lib_gpio_data0; /* +0x00000004  */
 union tango_lib_gpio_enable0Reg tango_lib_gpio_enable0; /* +0x00000008  */
 union tango_lib_gpio_direction1Reg tango_lib_gpio_direction1; /* +0x0000000c  */
 union tango_lib_gpio_data1Reg tango_lib_gpio_data1; /* +0x00000010  */
 union tango_lib_gpio_enable1Reg tango_lib_gpio_enable1; /* +0x00000014  */
 union tango_lib_gpio_direction2Reg tango_lib_gpio_direction2; /* +0x00000018  */
 union tango_lib_gpio_data2Reg tango_lib_gpio_data2; /* +0x0000001c  */
 union tango_lib_gpio_enable2Reg tango_lib_gpio_enable2; /* +0x00000020  */
 union tango_lib_gpio_direction3Reg tango_lib_gpio_direction3; /* +0x00000024  */
 union tango_lib_gpio_data3Reg tango_lib_gpio_data3; /* +0x00000028  */
 union tango_lib_gpio_enable3Reg tango_lib_gpio_enable3; /* +0x0000002c  */
 union tango_lib_gpio_interrupt0Reg tango_lib_gpio_interrupt0; /* +0x00000030  */
 union tango_lib_gpio_interrupt1Reg tango_lib_gpio_interrupt1; /* +0x00000034  */
};
