/* autogenerated with parsemap: do not edit. */
struct top_block_lbusadddec_lbus_address_decoder_mem {
#define top_block_lbusadddec_lbus_address_decoder_mem_ram_OFF 0x00000000
/* [0x00000000,0x00008000[ */ struct { struct ram_det d; uint32_t w[(0x00008000-sizeof(struct ram_det))/4]; } _ram;
                              uint32_t pad0[16384/4];
#define top_block_lbusadddec_lbus_address_decoder_mem_int_test_OFF 0x0000c000
/* [0x0000c000,0x0000d000[ */ struct { struct int_test_det d; uint32_t w[(0x00001000-sizeof(struct int_test_det))/4]; } _int_test;
#define top_block_lbusadddec_lbus_address_decoder_mem_completion_OFF 0x0000d000
/* [0x0000d000,0x0000d800[ */ struct { struct completion_det d; uint32_t w[(0x00000800-sizeof(struct completion_det))/4]; } _completion;
};
