/* autogenerated with parsecfg: do not edit. */

union vdec_cs_widthReg {
 struct { uint32_t

 /* sorting 1 */
#define vdec_cs_width_vdec_cs_width_value_SHIFT 0
#define vdec_cs_width_vdec_cs_width_value_WIDTH 13

 vdec_cs_width_value:13, /*[12:0]  */
 hole0:19;
 } bits;

 uint32_t value;
};

union vdec_cs_top_statusReg {
 struct { uint32_t

 /* sorting 1 */
#define vdec_cs_top_status_vdec_cs_top_status_value_SHIFT 0
#define vdec_cs_top_status_vdec_cs_top_status_value_WIDTH 16

 vdec_cs_top_status_value:16, /*[15:0]  */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_setupReg {
 struct { uint32_t

 /* sorting 1 */
#define vdec_cs_setup_vdec_cs_setup_value_SHIFT 0
#define vdec_cs_setup_vdec_cs_setup_value_WIDTH 16

 vdec_cs_setup_value:16, /*[15:0]  */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_rreserved_1Reg {
 struct { uint32_t

 /* sorting 1 */
#define vdec_cs_rreserved_1_vdec_cs_rreserved_1_value_SHIFT 0
#define vdec_cs_rreserved_1_vdec_cs_rreserved_1_value_WIDTH 16

 vdec_cs_rreserved_1_value:16, /*[15:0] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_rreserved_0Reg {
 struct { uint32_t

 /* sorting 1 */
#define vdec_cs_rreserved_0_vdec_cs_rreserved_0_value_SHIFT 0
#define vdec_cs_rreserved_0_vdec_cs_rreserved_0_value_WIDTH 16

 vdec_cs_rreserved_0_value:16, /*[15:0] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_pred_wait_idctReg {
 struct { uint32_t

 /* sorting 1 */
#define vdec_cs_pred_wait_idct_vdec_cs_pred_wait_idct_value_SHIFT 0
#define vdec_cs_pred_wait_idct_vdec_cs_pred_wait_idct_value_WIDTH 16

 vdec_cs_pred_wait_idct_value:16, /*[15:0]  */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_no_allocateReg {
 struct { uint32_t

 /* sorting 2 */
#define vdec_cs_no_allocate__value_SHIFT 0
#define vdec_cs_no_allocate__value_WIDTH 1
#define vdec_cs_no_allocate__SHIFT 1
#define vdec_cs_no_allocate__WIDTH 1

 _value:1, /*[0:0]  */
 :1, /*[1:1]  */
 hole0:30;
 } bits;

 uint32_t value;
};

union vdec_cs_lwidth_9Reg {
 struct { uint32_t

 /* sorting 3 */
#define vdec_cs_lwidth_9_stride_SHIFT 0
#define vdec_cs_lwidth_9_stride_WIDTH 10
#define vdec_cs_lwidth_9_prep_SHIFT 14
#define vdec_cs_lwidth_9_prep_WIDTH 1
#define vdec_cs_lwidth_9_pad_SHIFT 15
#define vdec_cs_lwidth_9_pad_WIDTH 1

 stride:10, /*[9:0]  */
 hole0:4,
 prep:1, /*[14:14]  */
 pad:1, /*[15:15]  */
 hole1:16;
 } bits;

 uint32_t value;
};

union vdec_cs_lwidth_8Reg {
 struct { uint32_t

 /* sorting 3 */
#define vdec_cs_lwidth_8_stride_SHIFT 0
#define vdec_cs_lwidth_8_stride_WIDTH 10
#define vdec_cs_lwidth_8_prep_SHIFT 14
#define vdec_cs_lwidth_8_prep_WIDTH 1
#define vdec_cs_lwidth_8_pad_SHIFT 15
#define vdec_cs_lwidth_8_pad_WIDTH 1

 stride:10, /*[9:0]  */
 hole0:4,
 prep:1, /*[14:14]  */
 pad:1, /*[15:15]  */
 hole1:16;
 } bits;

 uint32_t value;
};

union vdec_cs_lwidth_7Reg {
 struct { uint32_t

 /* sorting 3 */
#define vdec_cs_lwidth_7_stride_SHIFT 0
#define vdec_cs_lwidth_7_stride_WIDTH 10
#define vdec_cs_lwidth_7_prep_SHIFT 14
#define vdec_cs_lwidth_7_prep_WIDTH 1
#define vdec_cs_lwidth_7_pad_SHIFT 15
#define vdec_cs_lwidth_7_pad_WIDTH 1

 stride:10, /*[9:0]  */
 hole0:4,
 prep:1, /*[14:14]  */
 pad:1, /*[15:15]  */
 hole1:16;
 } bits;

 uint32_t value;
};

union vdec_cs_lwidth_6Reg {
 struct { uint32_t

 /* sorting 3 */
#define vdec_cs_lwidth_6_stride_SHIFT 0
#define vdec_cs_lwidth_6_stride_WIDTH 10
#define vdec_cs_lwidth_6_prep_SHIFT 14
#define vdec_cs_lwidth_6_prep_WIDTH 1
#define vdec_cs_lwidth_6_pad_SHIFT 15
#define vdec_cs_lwidth_6_pad_WIDTH 1

 stride:10, /*[9:0]  */
 hole0:4,
 prep:1, /*[14:14]  */
 pad:1, /*[15:15]  */
 hole1:16;
 } bits;

 uint32_t value;
};

union vdec_cs_lwidth_5Reg {
 struct { uint32_t

 /* sorting 3 */
#define vdec_cs_lwidth_5_stride_SHIFT 0
#define vdec_cs_lwidth_5_stride_WIDTH 10
#define vdec_cs_lwidth_5_prep_SHIFT 14
#define vdec_cs_lwidth_5_prep_WIDTH 1
#define vdec_cs_lwidth_5_pad_SHIFT 15
#define vdec_cs_lwidth_5_pad_WIDTH 1

 stride:10, /*[9:0]  */
 hole0:4,
 prep:1, /*[14:14]  */
 pad:1, /*[15:15]  */
 hole1:16;
 } bits;

 uint32_t value;
};

union vdec_cs_lwidth_4Reg {
 struct { uint32_t

 /* sorting 3 */
#define vdec_cs_lwidth_4_stride_SHIFT 0
#define vdec_cs_lwidth_4_stride_WIDTH 10
#define vdec_cs_lwidth_4_prep_SHIFT 14
#define vdec_cs_lwidth_4_prep_WIDTH 1
#define vdec_cs_lwidth_4_pad_SHIFT 15
#define vdec_cs_lwidth_4_pad_WIDTH 1

 stride:10, /*[9:0]  */
 hole0:4,
 prep:1, /*[14:14]  */
 pad:1, /*[15:15]  */
 hole1:16;
 } bits;

 uint32_t value;
};

union vdec_cs_lwidth_3Reg {
 struct { uint32_t

 /* sorting 3 */
#define vdec_cs_lwidth_3_stride_SHIFT 0
#define vdec_cs_lwidth_3_stride_WIDTH 10
#define vdec_cs_lwidth_3_prep_SHIFT 14
#define vdec_cs_lwidth_3_prep_WIDTH 1
#define vdec_cs_lwidth_3_pad_SHIFT 15
#define vdec_cs_lwidth_3_pad_WIDTH 1

 stride:10, /*[9:0]  */
 hole0:4,
 prep:1, /*[14:14]  */
 pad:1, /*[15:15]  */
 hole1:16;
 } bits;

 uint32_t value;
};

union vdec_cs_lwidth_2Reg {
 struct { uint32_t

 /* sorting 3 */
#define vdec_cs_lwidth_2_stride_SHIFT 0
#define vdec_cs_lwidth_2_stride_WIDTH 10
#define vdec_cs_lwidth_2_prep_SHIFT 14
#define vdec_cs_lwidth_2_prep_WIDTH 1
#define vdec_cs_lwidth_2_pad_SHIFT 15
#define vdec_cs_lwidth_2_pad_WIDTH 1

 stride:10, /*[9:0]  */
 hole0:4,
 prep:1, /*[14:14]  */
 pad:1, /*[15:15]  */
 hole1:16;
 } bits;

 uint32_t value;
};

union vdec_cs_lwidth_16Reg {
 struct { uint32_t

 /* sorting 3 */
#define vdec_cs_lwidth_16_stride_SHIFT 0
#define vdec_cs_lwidth_16_stride_WIDTH 10
#define vdec_cs_lwidth_16_prep_SHIFT 14
#define vdec_cs_lwidth_16_prep_WIDTH 1
#define vdec_cs_lwidth_16_pad_SHIFT 15
#define vdec_cs_lwidth_16_pad_WIDTH 1

 stride:10, /*[9:0]  */
 hole0:4,
 prep:1, /*[14:14]  */
 pad:1, /*[15:15]  */
 hole1:16;
 } bits;

 uint32_t value;
};

union vdec_cs_lwidth_15Reg {
 struct { uint32_t

 /* sorting 3 */
#define vdec_cs_lwidth_15_stride_SHIFT 0
#define vdec_cs_lwidth_15_stride_WIDTH 10
#define vdec_cs_lwidth_15_prep_SHIFT 14
#define vdec_cs_lwidth_15_prep_WIDTH 1
#define vdec_cs_lwidth_15_pad_SHIFT 15
#define vdec_cs_lwidth_15_pad_WIDTH 1

 stride:10, /*[9:0]  */
 hole0:4,
 prep:1, /*[14:14]  */
 pad:1, /*[15:15]  */
 hole1:16;
 } bits;

 uint32_t value;
};

union vdec_cs_lwidth_14Reg {
 struct { uint32_t

 /* sorting 3 */
#define vdec_cs_lwidth_14_stride_SHIFT 0
#define vdec_cs_lwidth_14_stride_WIDTH 10
#define vdec_cs_lwidth_14_prep_SHIFT 14
#define vdec_cs_lwidth_14_prep_WIDTH 1
#define vdec_cs_lwidth_14_pad_SHIFT 15
#define vdec_cs_lwidth_14_pad_WIDTH 1

 stride:10, /*[9:0]  */
 hole0:4,
 prep:1, /*[14:14]  */
 pad:1, /*[15:15]  */
 hole1:16;
 } bits;

 uint32_t value;
};

union vdec_cs_lwidth_13Reg {
 struct { uint32_t

 /* sorting 3 */
#define vdec_cs_lwidth_13_stride_SHIFT 0
#define vdec_cs_lwidth_13_stride_WIDTH 10
#define vdec_cs_lwidth_13_prep_SHIFT 14
#define vdec_cs_lwidth_13_prep_WIDTH 1
#define vdec_cs_lwidth_13_pad_SHIFT 15
#define vdec_cs_lwidth_13_pad_WIDTH 1

 stride:10, /*[9:0]  */
 hole0:4,
 prep:1, /*[14:14]  */
 pad:1, /*[15:15]  */
 hole1:16;
 } bits;

 uint32_t value;
};

union vdec_cs_lwidth_12Reg {
 struct { uint32_t

 /* sorting 3 */
#define vdec_cs_lwidth_12_stride_SHIFT 0
#define vdec_cs_lwidth_12_stride_WIDTH 10
#define vdec_cs_lwidth_12_prep_SHIFT 14
#define vdec_cs_lwidth_12_prep_WIDTH 1
#define vdec_cs_lwidth_12_pad_SHIFT 15
#define vdec_cs_lwidth_12_pad_WIDTH 1

 stride:10, /*[9:0]  */
 hole0:4,
 prep:1, /*[14:14]  */
 pad:1, /*[15:15]  */
 hole1:16;
 } bits;

 uint32_t value;
};

union vdec_cs_lwidth_11Reg {
 struct { uint32_t

 /* sorting 3 */
#define vdec_cs_lwidth_11_stride_SHIFT 0
#define vdec_cs_lwidth_11_stride_WIDTH 10
#define vdec_cs_lwidth_11_prep_SHIFT 14
#define vdec_cs_lwidth_11_prep_WIDTH 1
#define vdec_cs_lwidth_11_pad_SHIFT 15
#define vdec_cs_lwidth_11_pad_WIDTH 1

 stride:10, /*[9:0]  */
 hole0:4,
 prep:1, /*[14:14]  */
 pad:1, /*[15:15]  */
 hole1:16;
 } bits;

 uint32_t value;
};

union vdec_cs_lwidth_10Reg {
 struct { uint32_t

 /* sorting 3 */
#define vdec_cs_lwidth_10_stride_SHIFT 0
#define vdec_cs_lwidth_10_stride_WIDTH 10
#define vdec_cs_lwidth_10_prep_SHIFT 14
#define vdec_cs_lwidth_10_prep_WIDTH 1
#define vdec_cs_lwidth_10_pad_SHIFT 15
#define vdec_cs_lwidth_10_pad_WIDTH 1

 stride:10, /*[9:0]  */
 hole0:4,
 prep:1, /*[14:14]  */
 pad:1, /*[15:15]  */
 hole1:16;
 } bits;

 uint32_t value;
};

union vdec_cs_lwidth_1Reg {
 struct { uint32_t

 /* sorting 3 */
#define vdec_cs_lwidth_1_stride_SHIFT 0
#define vdec_cs_lwidth_1_stride_WIDTH 10
#define vdec_cs_lwidth_1_prep_SHIFT 14
#define vdec_cs_lwidth_1_prep_WIDTH 1
#define vdec_cs_lwidth_1_pad_SHIFT 15
#define vdec_cs_lwidth_1_pad_WIDTH 1

 stride:10, /*[9:0]  */
 hole0:4,
 prep:1, /*[14:14]  */
 pad:1, /*[15:15]  */
 hole1:16;
 } bits;

 uint32_t value;
};

union vdec_cs_lwidth_0Reg {
 struct { uint32_t

 /* sorting 3 */
#define vdec_cs_lwidth_0_stride_SHIFT 0
#define vdec_cs_lwidth_0_stride_WIDTH 10
#define vdec_cs_lwidth_0_prep_SHIFT 14
#define vdec_cs_lwidth_0_prep_WIDTH 1
#define vdec_cs_lwidth_0_pad_SHIFT 15
#define vdec_cs_lwidth_0_pad_WIDTH 1

 stride:10, /*[9:0]  */
 hole0:4,
 prep:1, /*[14:14]  */
 pad:1, /*[15:15]  */
 hole1:16;
 } bits;

 uint32_t value;
};

union vdec_cs_luma_intensity_buffer_3Reg {
 struct { uint32_t

 /* sorting 1 */
#define vdec_cs_luma_intensity_buffer_3_vdec_cs_intensity_1_top_2_SHIFT 0
#define vdec_cs_luma_intensity_buffer_3_vdec_cs_intensity_1_top_2_WIDTH 16

 vdec_cs_intensity_1_top_2:16, /*[15:0]  */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_luma_intensity_buffer_2Reg {
 struct { uint32_t

 /* sorting 1 */
#define vdec_cs_luma_intensity_buffer_2_vdec_cs_intensity_0_top_2_SHIFT 0
#define vdec_cs_luma_intensity_buffer_2_vdec_cs_intensity_0_top_2_WIDTH 16

 vdec_cs_intensity_0_top_2:16, /*[15:0]  */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_luma_intensity_buffer_1Reg {
 struct { uint32_t

 /* sorting 1 */
#define vdec_cs_luma_intensity_buffer_1_vdec_cs_intensity_1_top_1_SHIFT 0
#define vdec_cs_luma_intensity_buffer_1_vdec_cs_intensity_1_top_1_WIDTH 16

 vdec_cs_intensity_1_top_1:16, /*[15:0]  */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_luma_intensity_buffer_0Reg {
 struct { uint32_t

 /* sorting 1 */
#define vdec_cs_luma_intensity_buffer_0_vdec_cs_intensity_0_top_1_SHIFT 0
#define vdec_cs_luma_intensity_buffer_0_vdec_cs_intensity_0_top_1_WIDTH 16

 vdec_cs_intensity_0_top_1:16, /*[15:0]  */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_lstartlow_9Reg {
 struct { uint32_t

 /* sorting 2 */
#define vdec_cs_lstartlow_9_x_offset_SHIFT 4
#define vdec_cs_lstartlow_9_x_offset_WIDTH 4
#define vdec_cs_lstartlow_9_tile_SHIFT 8
#define vdec_cs_lstartlow_9_tile_WIDTH 8

 hole0:4,
 x_offset:4, /*[7:4]  */
 tile:8, /*[15:8]  */
 hole1:16;
 } bits;

 uint32_t value;
};

union vdec_cs_lstartlow_8Reg {
 struct { uint32_t

 /* sorting 2 */
#define vdec_cs_lstartlow_8_x_offset_SHIFT 4
#define vdec_cs_lstartlow_8_x_offset_WIDTH 4
#define vdec_cs_lstartlow_8_tile_SHIFT 8
#define vdec_cs_lstartlow_8_tile_WIDTH 8

 hole0:4,
 x_offset:4, /*[7:4]  */
 tile:8, /*[15:8]  */
 hole1:16;
 } bits;

 uint32_t value;
};

union vdec_cs_lstartlow_7Reg {
 struct { uint32_t

 /* sorting 2 */
#define vdec_cs_lstartlow_7_x_offset_SHIFT 4
#define vdec_cs_lstartlow_7_x_offset_WIDTH 4
#define vdec_cs_lstartlow_7_tile_SHIFT 8
#define vdec_cs_lstartlow_7_tile_WIDTH 8

 hole0:4,
 x_offset:4, /*[7:4]  */
 tile:8, /*[15:8]  */
 hole1:16;
 } bits;

 uint32_t value;
};

union vdec_cs_lstartlow_6Reg {
 struct { uint32_t

 /* sorting 2 */
#define vdec_cs_lstartlow_6_x_offset_SHIFT 4
#define vdec_cs_lstartlow_6_x_offset_WIDTH 4
#define vdec_cs_lstartlow_6_tile_SHIFT 8
#define vdec_cs_lstartlow_6_tile_WIDTH 8

 hole0:4,
 x_offset:4, /*[7:4]  */
 tile:8, /*[15:8]  */
 hole1:16;
 } bits;

 uint32_t value;
};

union vdec_cs_lstartlow_5Reg {
 struct { uint32_t

 /* sorting 2 */
#define vdec_cs_lstartlow_5_x_offset_SHIFT 4
#define vdec_cs_lstartlow_5_x_offset_WIDTH 4
#define vdec_cs_lstartlow_5_tile_SHIFT 8
#define vdec_cs_lstartlow_5_tile_WIDTH 8

 hole0:4,
 x_offset:4, /*[7:4]  */
 tile:8, /*[15:8]  */
 hole1:16;
 } bits;

 uint32_t value;
};

union vdec_cs_lstartlow_4Reg {
 struct { uint32_t

 /* sorting 2 */
#define vdec_cs_lstartlow_4_x_offset_SHIFT 4
#define vdec_cs_lstartlow_4_x_offset_WIDTH 4
#define vdec_cs_lstartlow_4_tile_SHIFT 8
#define vdec_cs_lstartlow_4_tile_WIDTH 8

 hole0:4,
 x_offset:4, /*[7:4]  */
 tile:8, /*[15:8]  */
 hole1:16;
 } bits;

 uint32_t value;
};

union vdec_cs_lstartlow_3Reg {
 struct { uint32_t

 /* sorting 2 */
#define vdec_cs_lstartlow_3_x_offset_SHIFT 4
#define vdec_cs_lstartlow_3_x_offset_WIDTH 4
#define vdec_cs_lstartlow_3_tile_SHIFT 8
#define vdec_cs_lstartlow_3_tile_WIDTH 8

 hole0:4,
 x_offset:4, /*[7:4]  */
 tile:8, /*[15:8]  */
 hole1:16;
 } bits;

 uint32_t value;
};

union vdec_cs_lstartlow_2Reg {
 struct { uint32_t

 /* sorting 2 */
#define vdec_cs_lstartlow_2_x_offset_SHIFT 4
#define vdec_cs_lstartlow_2_x_offset_WIDTH 4
#define vdec_cs_lstartlow_2_tile_SHIFT 8
#define vdec_cs_lstartlow_2_tile_WIDTH 8

 hole0:4,
 x_offset:4, /*[7:4]  */
 tile:8, /*[15:8]  */
 hole1:16;
 } bits;

 uint32_t value;
};

union vdec_cs_lstartlow_16Reg {
 struct { uint32_t

 /* sorting 2 */
#define vdec_cs_lstartlow_16_x_offset_SHIFT 4
#define vdec_cs_lstartlow_16_x_offset_WIDTH 4
#define vdec_cs_lstartlow_16_tile_SHIFT 8
#define vdec_cs_lstartlow_16_tile_WIDTH 8

 hole0:4,
 x_offset:4, /*[7:4]  */
 tile:8, /*[15:8]  */
 hole1:16;
 } bits;

 uint32_t value;
};

union vdec_cs_lstartlow_15Reg {
 struct { uint32_t

 /* sorting 2 */
#define vdec_cs_lstartlow_15_x_offset_SHIFT 4
#define vdec_cs_lstartlow_15_x_offset_WIDTH 4
#define vdec_cs_lstartlow_15_tile_SHIFT 8
#define vdec_cs_lstartlow_15_tile_WIDTH 8

 hole0:4,
 x_offset:4, /*[7:4]  */
 tile:8, /*[15:8]  */
 hole1:16;
 } bits;

 uint32_t value;
};

union vdec_cs_lstartlow_14Reg {
 struct { uint32_t

 /* sorting 2 */
#define vdec_cs_lstartlow_14_x_offset_SHIFT 4
#define vdec_cs_lstartlow_14_x_offset_WIDTH 4
#define vdec_cs_lstartlow_14_tile_SHIFT 8
#define vdec_cs_lstartlow_14_tile_WIDTH 8

 hole0:4,
 x_offset:4, /*[7:4]  */
 tile:8, /*[15:8]  */
 hole1:16;
 } bits;

 uint32_t value;
};

union vdec_cs_lstartlow_13Reg {
 struct { uint32_t

 /* sorting 2 */
#define vdec_cs_lstartlow_13_x_offset_SHIFT 4
#define vdec_cs_lstartlow_13_x_offset_WIDTH 4
#define vdec_cs_lstartlow_13_tile_SHIFT 8
#define vdec_cs_lstartlow_13_tile_WIDTH 8

 hole0:4,
 x_offset:4, /*[7:4]  */
 tile:8, /*[15:8]  */
 hole1:16;
 } bits;

 uint32_t value;
};

union vdec_cs_lstartlow_12Reg {
 struct { uint32_t

 /* sorting 2 */
#define vdec_cs_lstartlow_12_x_offset_SHIFT 4
#define vdec_cs_lstartlow_12_x_offset_WIDTH 4
#define vdec_cs_lstartlow_12_tile_SHIFT 8
#define vdec_cs_lstartlow_12_tile_WIDTH 8

 hole0:4,
 x_offset:4, /*[7:4]  */
 tile:8, /*[15:8]  */
 hole1:16;
 } bits;

 uint32_t value;
};

union vdec_cs_lstartlow_11Reg {
 struct { uint32_t

 /* sorting 2 */
#define vdec_cs_lstartlow_11_x_offset_SHIFT 4
#define vdec_cs_lstartlow_11_x_offset_WIDTH 4
#define vdec_cs_lstartlow_11_tile_SHIFT 8
#define vdec_cs_lstartlow_11_tile_WIDTH 8

 hole0:4,
 x_offset:4, /*[7:4]  */
 tile:8, /*[15:8]  */
 hole1:16;
 } bits;

 uint32_t value;
};

union vdec_cs_lstartlow_10Reg {
 struct { uint32_t

 /* sorting 2 */
#define vdec_cs_lstartlow_10_x_offset_SHIFT 4
#define vdec_cs_lstartlow_10_x_offset_WIDTH 4
#define vdec_cs_lstartlow_10_tile_SHIFT 8
#define vdec_cs_lstartlow_10_tile_WIDTH 8

 hole0:4,
 x_offset:4, /*[7:4]  */
 tile:8, /*[15:8]  */
 hole1:16;
 } bits;

 uint32_t value;
};

union vdec_cs_lstartlow_1Reg {
 struct { uint32_t

 /* sorting 2 */
#define vdec_cs_lstartlow_1_x_offset_SHIFT 4
#define vdec_cs_lstartlow_1_x_offset_WIDTH 4
#define vdec_cs_lstartlow_1_tile_SHIFT 8
#define vdec_cs_lstartlow_1_tile_WIDTH 8

 hole0:4,
 x_offset:4, /*[7:4]  */
 tile:8, /*[15:8]  */
 hole1:16;
 } bits;

 uint32_t value;
};

union vdec_cs_lstartlow_0Reg {
 struct { uint32_t

 /* sorting 2 */
#define vdec_cs_lstartlow_0_x_offset_SHIFT 4
#define vdec_cs_lstartlow_0_x_offset_WIDTH 4
#define vdec_cs_lstartlow_0_tile_SHIFT 8
#define vdec_cs_lstartlow_0_tile_WIDTH 8

 hole0:4,
 x_offset:4, /*[7:4]  */
 tile:8, /*[15:8]  */
 hole1:16;
 } bits;

 uint32_t value;
};

union vdec_cs_lstarthigh_9Reg {
 struct { uint32_t

 /* sorting 2 */
#define vdec_cs_lstarthigh_9_tile_SHIFT 0
#define vdec_cs_lstarthigh_9_tile_WIDTH 15
#define vdec_cs_lstarthigh_9_msb_SHIFT 15
#define vdec_cs_lstarthigh_9_msb_WIDTH 1

 tile:15, /*[14:0]  */
 msb:1, /*[15:15] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_lstarthigh_8Reg {
 struct { uint32_t

 /* sorting 2 */
#define vdec_cs_lstarthigh_8_tile_SHIFT 0
#define vdec_cs_lstarthigh_8_tile_WIDTH 15
#define vdec_cs_lstarthigh_8_msb_SHIFT 15
#define vdec_cs_lstarthigh_8_msb_WIDTH 1

 tile:15, /*[14:0]  */
 msb:1, /*[15:15] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_lstarthigh_7Reg {
 struct { uint32_t

 /* sorting 2 */
#define vdec_cs_lstarthigh_7_tile_SHIFT 0
#define vdec_cs_lstarthigh_7_tile_WIDTH 15
#define vdec_cs_lstarthigh_7_msb_SHIFT 15
#define vdec_cs_lstarthigh_7_msb_WIDTH 1

 tile:15, /*[14:0]  */
 msb:1, /*[15:15] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_lstarthigh_6Reg {
 struct { uint32_t

 /* sorting 2 */
#define vdec_cs_lstarthigh_6_tile_SHIFT 0
#define vdec_cs_lstarthigh_6_tile_WIDTH 15
#define vdec_cs_lstarthigh_6_msb_SHIFT 15
#define vdec_cs_lstarthigh_6_msb_WIDTH 1

 tile:15, /*[14:0]  */
 msb:1, /*[15:15] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_lstarthigh_5Reg {
 struct { uint32_t

 /* sorting 2 */
#define vdec_cs_lstarthigh_5_tile_SHIFT 0
#define vdec_cs_lstarthigh_5_tile_WIDTH 15
#define vdec_cs_lstarthigh_5_msb_SHIFT 15
#define vdec_cs_lstarthigh_5_msb_WIDTH 1

 tile:15, /*[14:0]  */
 msb:1, /*[15:15] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_lstarthigh_4Reg {
 struct { uint32_t

 /* sorting 2 */
#define vdec_cs_lstarthigh_4_tile_SHIFT 0
#define vdec_cs_lstarthigh_4_tile_WIDTH 15
#define vdec_cs_lstarthigh_4_msb_SHIFT 15
#define vdec_cs_lstarthigh_4_msb_WIDTH 1

 tile:15, /*[14:0]  */
 msb:1, /*[15:15] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_lstarthigh_3Reg {
 struct { uint32_t

 /* sorting 2 */
#define vdec_cs_lstarthigh_3_tile_SHIFT 0
#define vdec_cs_lstarthigh_3_tile_WIDTH 15
#define vdec_cs_lstarthigh_3_msb_SHIFT 15
#define vdec_cs_lstarthigh_3_msb_WIDTH 1

 tile:15, /*[14:0]  */
 msb:1, /*[15:15] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_lstarthigh_2Reg {
 struct { uint32_t

 /* sorting 2 */
#define vdec_cs_lstarthigh_2_tile_SHIFT 0
#define vdec_cs_lstarthigh_2_tile_WIDTH 15
#define vdec_cs_lstarthigh_2_msb_SHIFT 15
#define vdec_cs_lstarthigh_2_msb_WIDTH 1

 tile:15, /*[14:0]  */
 msb:1, /*[15:15] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_lstarthigh_16Reg {
 struct { uint32_t

 /* sorting 2 */
#define vdec_cs_lstarthigh_16_tile_SHIFT 0
#define vdec_cs_lstarthigh_16_tile_WIDTH 15
#define vdec_cs_lstarthigh_16_msb_SHIFT 15
#define vdec_cs_lstarthigh_16_msb_WIDTH 1

 tile:15, /*[14:0]  */
 msb:1, /*[15:15] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_lstarthigh_15Reg {
 struct { uint32_t

 /* sorting 2 */
#define vdec_cs_lstarthigh_15_tile_SHIFT 0
#define vdec_cs_lstarthigh_15_tile_WIDTH 15
#define vdec_cs_lstarthigh_15_msb_SHIFT 15
#define vdec_cs_lstarthigh_15_msb_WIDTH 1

 tile:15, /*[14:0]  */
 msb:1, /*[15:15] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_lstarthigh_14Reg {
 struct { uint32_t

 /* sorting 2 */
#define vdec_cs_lstarthigh_14_tile_SHIFT 0
#define vdec_cs_lstarthigh_14_tile_WIDTH 15
#define vdec_cs_lstarthigh_14_msb_SHIFT 15
#define vdec_cs_lstarthigh_14_msb_WIDTH 1

 tile:15, /*[14:0]  */
 msb:1, /*[15:15] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_lstarthigh_13Reg {
 struct { uint32_t

 /* sorting 2 */
#define vdec_cs_lstarthigh_13_tile_SHIFT 0
#define vdec_cs_lstarthigh_13_tile_WIDTH 15
#define vdec_cs_lstarthigh_13_msb_SHIFT 15
#define vdec_cs_lstarthigh_13_msb_WIDTH 1

 tile:15, /*[14:0]  */
 msb:1, /*[15:15] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_lstarthigh_12Reg {
 struct { uint32_t

 /* sorting 2 */
#define vdec_cs_lstarthigh_12_tile_SHIFT 0
#define vdec_cs_lstarthigh_12_tile_WIDTH 15
#define vdec_cs_lstarthigh_12_msb_SHIFT 15
#define vdec_cs_lstarthigh_12_msb_WIDTH 1

 tile:15, /*[14:0]  */
 msb:1, /*[15:15] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_lstarthigh_11Reg {
 struct { uint32_t

 /* sorting 2 */
#define vdec_cs_lstarthigh_11_tile_SHIFT 0
#define vdec_cs_lstarthigh_11_tile_WIDTH 15
#define vdec_cs_lstarthigh_11_msb_SHIFT 15
#define vdec_cs_lstarthigh_11_msb_WIDTH 1

 tile:15, /*[14:0]  */
 msb:1, /*[15:15] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_lstarthigh_10Reg {
 struct { uint32_t

 /* sorting 2 */
#define vdec_cs_lstarthigh_10_tile_SHIFT 0
#define vdec_cs_lstarthigh_10_tile_WIDTH 15
#define vdec_cs_lstarthigh_10_msb_SHIFT 15
#define vdec_cs_lstarthigh_10_msb_WIDTH 1

 tile:15, /*[14:0]  */
 msb:1, /*[15:15] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_lstarthigh_1Reg {
 struct { uint32_t

 /* sorting 2 */
#define vdec_cs_lstarthigh_1_tile_SHIFT 0
#define vdec_cs_lstarthigh_1_tile_WIDTH 15
#define vdec_cs_lstarthigh_1_msb_SHIFT 15
#define vdec_cs_lstarthigh_1_msb_WIDTH 1

 tile:15, /*[14:0]  */
 msb:1, /*[15:15] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_lstarthigh_0Reg {
 struct { uint32_t

 /* sorting 2 */
#define vdec_cs_lstarthigh_0_tile_SHIFT 0
#define vdec_cs_lstarthigh_0_tile_WIDTH 15
#define vdec_cs_lstarthigh_0_msb_SHIFT 15
#define vdec_cs_lstarthigh_0_msb_WIDTH 1

 tile:15, /*[14:0]  */
 msb:1, /*[15:15] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_lreserved_9Reg {
 struct { uint32_t

 /* sorting 1 */
#define vdec_cs_lreserved_9_vdec_cs_lreserved_9_value_SHIFT 0
#define vdec_cs_lreserved_9_vdec_cs_lreserved_9_value_WIDTH 16

 vdec_cs_lreserved_9_value:16, /*[15:0] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_lreserved_8Reg {
 struct { uint32_t

 /* sorting 1 */
#define vdec_cs_lreserved_8_vdec_cs_lreserved_8_value_SHIFT 0
#define vdec_cs_lreserved_8_vdec_cs_lreserved_8_value_WIDTH 16

 vdec_cs_lreserved_8_value:16, /*[15:0] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_lreserved_7Reg {
 struct { uint32_t

 /* sorting 1 */
#define vdec_cs_lreserved_7_vdec_cs_lreserved_7_value_SHIFT 0
#define vdec_cs_lreserved_7_vdec_cs_lreserved_7_value_WIDTH 16

 vdec_cs_lreserved_7_value:16, /*[15:0] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_lreserved_6Reg {
 struct { uint32_t

 /* sorting 1 */
#define vdec_cs_lreserved_6_vdec_cs_lreserved_6_value_SHIFT 0
#define vdec_cs_lreserved_6_vdec_cs_lreserved_6_value_WIDTH 16

 vdec_cs_lreserved_6_value:16, /*[15:0] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_lreserved_5Reg {
 struct { uint32_t

 /* sorting 1 */
#define vdec_cs_lreserved_5_vdec_cs_lreserved_5_value_SHIFT 0
#define vdec_cs_lreserved_5_vdec_cs_lreserved_5_value_WIDTH 16

 vdec_cs_lreserved_5_value:16, /*[15:0] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_lreserved_4Reg {
 struct { uint32_t

 /* sorting 1 */
#define vdec_cs_lreserved_4_vdec_cs_lreserved_4_value_SHIFT 0
#define vdec_cs_lreserved_4_vdec_cs_lreserved_4_value_WIDTH 16

 vdec_cs_lreserved_4_value:16, /*[15:0] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_lreserved_3Reg {
 struct { uint32_t

 /* sorting 1 */
#define vdec_cs_lreserved_3_vdec_cs_lreserved_3_value_SHIFT 0
#define vdec_cs_lreserved_3_vdec_cs_lreserved_3_value_WIDTH 16

 vdec_cs_lreserved_3_value:16, /*[15:0] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_lreserved_2Reg {
 struct { uint32_t

 /* sorting 1 */
#define vdec_cs_lreserved_2_vdec_cs_lreserved_2_value_SHIFT 0
#define vdec_cs_lreserved_2_vdec_cs_lreserved_2_value_WIDTH 16

 vdec_cs_lreserved_2_value:16, /*[15:0] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_lreserved_16Reg {
 struct { uint32_t

 /* sorting 1 */
#define vdec_cs_lreserved_16_vdec_cs_lreserved_16_value_SHIFT 0
#define vdec_cs_lreserved_16_vdec_cs_lreserved_16_value_WIDTH 16

 vdec_cs_lreserved_16_value:16, /*[15:0] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_lreserved_15Reg {
 struct { uint32_t

 /* sorting 1 */
#define vdec_cs_lreserved_15_vdec_cs_lreserved_15_value_SHIFT 0
#define vdec_cs_lreserved_15_vdec_cs_lreserved_15_value_WIDTH 16

 vdec_cs_lreserved_15_value:16, /*[15:0] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_lreserved_14Reg {
 struct { uint32_t

 /* sorting 1 */
#define vdec_cs_lreserved_14_vdec_cs_lreserved_14_value_SHIFT 0
#define vdec_cs_lreserved_14_vdec_cs_lreserved_14_value_WIDTH 16

 vdec_cs_lreserved_14_value:16, /*[15:0] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_lreserved_13Reg {
 struct { uint32_t

 /* sorting 1 */
#define vdec_cs_lreserved_13_vdec_cs_lreserved_13_value_SHIFT 0
#define vdec_cs_lreserved_13_vdec_cs_lreserved_13_value_WIDTH 16

 vdec_cs_lreserved_13_value:16, /*[15:0] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_lreserved_12Reg {
 struct { uint32_t

 /* sorting 1 */
#define vdec_cs_lreserved_12_vdec_cs_lreserved_12_value_SHIFT 0
#define vdec_cs_lreserved_12_vdec_cs_lreserved_12_value_WIDTH 16

 vdec_cs_lreserved_12_value:16, /*[15:0] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_lreserved_11Reg {
 struct { uint32_t

 /* sorting 1 */
#define vdec_cs_lreserved_11_vdec_cs_lreserved_11_value_SHIFT 0
#define vdec_cs_lreserved_11_vdec_cs_lreserved_11_value_WIDTH 16

 vdec_cs_lreserved_11_value:16, /*[15:0] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_lreserved_10Reg {
 struct { uint32_t

 /* sorting 1 */
#define vdec_cs_lreserved_10_vdec_cs_lreserved_10_value_SHIFT 0
#define vdec_cs_lreserved_10_vdec_cs_lreserved_10_value_WIDTH 16

 vdec_cs_lreserved_10_value:16, /*[15:0] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_lreserved_1Reg {
 struct { uint32_t

 /* sorting 1 */
#define vdec_cs_lreserved_1_vdec_cs_lreserved_1_value_SHIFT 0
#define vdec_cs_lreserved_1_vdec_cs_lreserved_1_value_WIDTH 16

 vdec_cs_lreserved_1_value:16, /*[15:0] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_lreserved_0Reg {
 struct { uint32_t

 /* sorting 1 */
#define vdec_cs_lreserved_0_vdec_cs_lreserved_0_value_SHIFT 0
#define vdec_cs_lreserved_0_vdec_cs_lreserved_0_value_WIDTH 16

 vdec_cs_lreserved_0_value:16, /*[15:0] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_internal_intensity_edgeReg {
 struct { uint32_t

 /* sorting 1 */
#define vdec_cs_internal_intensity_edge_vdec_cs_internal_intensity_edge_value_SHIFT 0
#define vdec_cs_internal_intensity_edge_vdec_cs_internal_intensity_edge_value_WIDTH 16

 vdec_cs_internal_intensity_edge_value:16, /*[15:0]  */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_idct_wait_predReg {
 struct { uint32_t

 /* sorting 1 */
#define vdec_cs_idct_wait_pred_vdec_cs_idct_wait_pred_value_SHIFT 0
#define vdec_cs_idct_wait_pred_vdec_cs_idct_wait_pred_value_WIDTH 16

 vdec_cs_idct_wait_pred_value:16, /*[15:0]  */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_heightReg {
 struct { uint32_t

 /* sorting 1 */
#define vdec_cs_height_vdec_cs_height_value_SHIFT 0
#define vdec_cs_height_vdec_cs_height_value_WIDTH 13

 vdec_cs_height_value:13, /*[12:0]  */
 hole0:19;
 } bits;

 uint32_t value;
};

union vdec_cs_cwidth_9Reg {
 struct { uint32_t

 /* sorting 3 */
#define vdec_cs_cwidth_9_stride_SHIFT 0
#define vdec_cs_cwidth_9_stride_WIDTH 10
#define vdec_cs_cwidth_9_prep_SHIFT 14
#define vdec_cs_cwidth_9_prep_WIDTH 1
#define vdec_cs_cwidth_9_pad_SHIFT 15
#define vdec_cs_cwidth_9_pad_WIDTH 1

 stride:10, /*[9:0]  */
 hole0:4,
 prep:1, /*[14:14]  */
 pad:1, /*[15:15]  */
 hole1:16;
 } bits;

 uint32_t value;
};

union vdec_cs_cwidth_8Reg {
 struct { uint32_t

 /* sorting 3 */
#define vdec_cs_cwidth_8_stride_SHIFT 0
#define vdec_cs_cwidth_8_stride_WIDTH 10
#define vdec_cs_cwidth_8_prep_SHIFT 14
#define vdec_cs_cwidth_8_prep_WIDTH 1
#define vdec_cs_cwidth_8_pad_SHIFT 15
#define vdec_cs_cwidth_8_pad_WIDTH 1

 stride:10, /*[9:0]  */
 hole0:4,
 prep:1, /*[14:14]  */
 pad:1, /*[15:15]  */
 hole1:16;
 } bits;

 uint32_t value;
};

union vdec_cs_cwidth_7Reg {
 struct { uint32_t

 /* sorting 3 */
#define vdec_cs_cwidth_7_stride_SHIFT 0
#define vdec_cs_cwidth_7_stride_WIDTH 10
#define vdec_cs_cwidth_7_prep_SHIFT 14
#define vdec_cs_cwidth_7_prep_WIDTH 1
#define vdec_cs_cwidth_7_pad_SHIFT 15
#define vdec_cs_cwidth_7_pad_WIDTH 1

 stride:10, /*[9:0]  */
 hole0:4,
 prep:1, /*[14:14]  */
 pad:1, /*[15:15]  */
 hole1:16;
 } bits;

 uint32_t value;
};

union vdec_cs_cwidth_6Reg {
 struct { uint32_t

 /* sorting 3 */
#define vdec_cs_cwidth_6_stride_SHIFT 0
#define vdec_cs_cwidth_6_stride_WIDTH 10
#define vdec_cs_cwidth_6_prep_SHIFT 14
#define vdec_cs_cwidth_6_prep_WIDTH 1
#define vdec_cs_cwidth_6_pad_SHIFT 15
#define vdec_cs_cwidth_6_pad_WIDTH 1

 stride:10, /*[9:0]  */
 hole0:4,
 prep:1, /*[14:14]  */
 pad:1, /*[15:15]  */
 hole1:16;
 } bits;

 uint32_t value;
};

union vdec_cs_cwidth_5Reg {
 struct { uint32_t

 /* sorting 3 */
#define vdec_cs_cwidth_5_stride_SHIFT 0
#define vdec_cs_cwidth_5_stride_WIDTH 10
#define vdec_cs_cwidth_5_prep_SHIFT 14
#define vdec_cs_cwidth_5_prep_WIDTH 1
#define vdec_cs_cwidth_5_pad_SHIFT 15
#define vdec_cs_cwidth_5_pad_WIDTH 1

 stride:10, /*[9:0]  */
 hole0:4,
 prep:1, /*[14:14]  */
 pad:1, /*[15:15]  */
 hole1:16;
 } bits;

 uint32_t value;
};

union vdec_cs_cwidth_4Reg {
 struct { uint32_t

 /* sorting 3 */
#define vdec_cs_cwidth_4_stride_SHIFT 0
#define vdec_cs_cwidth_4_stride_WIDTH 10
#define vdec_cs_cwidth_4_prep_SHIFT 14
#define vdec_cs_cwidth_4_prep_WIDTH 1
#define vdec_cs_cwidth_4_pad_SHIFT 15
#define vdec_cs_cwidth_4_pad_WIDTH 1

 stride:10, /*[9:0]  */
 hole0:4,
 prep:1, /*[14:14]  */
 pad:1, /*[15:15]  */
 hole1:16;
 } bits;

 uint32_t value;
};

union vdec_cs_cwidth_3Reg {
 struct { uint32_t

 /* sorting 3 */
#define vdec_cs_cwidth_3_stride_SHIFT 0
#define vdec_cs_cwidth_3_stride_WIDTH 10
#define vdec_cs_cwidth_3_prep_SHIFT 14
#define vdec_cs_cwidth_3_prep_WIDTH 1
#define vdec_cs_cwidth_3_pad_SHIFT 15
#define vdec_cs_cwidth_3_pad_WIDTH 1

 stride:10, /*[9:0]  */
 hole0:4,
 prep:1, /*[14:14]  */
 pad:1, /*[15:15]  */
 hole1:16;
 } bits;

 uint32_t value;
};

union vdec_cs_cwidth_2Reg {
 struct { uint32_t

 /* sorting 3 */
#define vdec_cs_cwidth_2_stride_SHIFT 0
#define vdec_cs_cwidth_2_stride_WIDTH 10
#define vdec_cs_cwidth_2_prep_SHIFT 14
#define vdec_cs_cwidth_2_prep_WIDTH 1
#define vdec_cs_cwidth_2_pad_SHIFT 15
#define vdec_cs_cwidth_2_pad_WIDTH 1

 stride:10, /*[9:0]  */
 hole0:4,
 prep:1, /*[14:14]  */
 pad:1, /*[15:15]  */
 hole1:16;
 } bits;

 uint32_t value;
};

union vdec_cs_cwidth_16Reg {
 struct { uint32_t

 /* sorting 3 */
#define vdec_cs_cwidth_16_stride_SHIFT 0
#define vdec_cs_cwidth_16_stride_WIDTH 10
#define vdec_cs_cwidth_16_prep_SHIFT 14
#define vdec_cs_cwidth_16_prep_WIDTH 1
#define vdec_cs_cwidth_16_pad_SHIFT 15
#define vdec_cs_cwidth_16_pad_WIDTH 1

 stride:10, /*[9:0]  */
 hole0:4,
 prep:1, /*[14:14]  */
 pad:1, /*[15:15]  */
 hole1:16;
 } bits;

 uint32_t value;
};

union vdec_cs_cwidth_15Reg {
 struct { uint32_t

 /* sorting 3 */
#define vdec_cs_cwidth_15_stride_SHIFT 0
#define vdec_cs_cwidth_15_stride_WIDTH 10
#define vdec_cs_cwidth_15_prep_SHIFT 14
#define vdec_cs_cwidth_15_prep_WIDTH 1
#define vdec_cs_cwidth_15_pad_SHIFT 15
#define vdec_cs_cwidth_15_pad_WIDTH 1

 stride:10, /*[9:0]  */
 hole0:4,
 prep:1, /*[14:14]  */
 pad:1, /*[15:15]  */
 hole1:16;
 } bits;

 uint32_t value;
};

union vdec_cs_cwidth_14Reg {
 struct { uint32_t

 /* sorting 3 */
#define vdec_cs_cwidth_14_stride_SHIFT 0
#define vdec_cs_cwidth_14_stride_WIDTH 10
#define vdec_cs_cwidth_14_prep_SHIFT 14
#define vdec_cs_cwidth_14_prep_WIDTH 1
#define vdec_cs_cwidth_14_pad_SHIFT 15
#define vdec_cs_cwidth_14_pad_WIDTH 1

 stride:10, /*[9:0]  */
 hole0:4,
 prep:1, /*[14:14]  */
 pad:1, /*[15:15]  */
 hole1:16;
 } bits;

 uint32_t value;
};

union vdec_cs_cwidth_13Reg {
 struct { uint32_t

 /* sorting 3 */
#define vdec_cs_cwidth_13_stride_SHIFT 0
#define vdec_cs_cwidth_13_stride_WIDTH 10
#define vdec_cs_cwidth_13_prep_SHIFT 14
#define vdec_cs_cwidth_13_prep_WIDTH 1
#define vdec_cs_cwidth_13_pad_SHIFT 15
#define vdec_cs_cwidth_13_pad_WIDTH 1

 stride:10, /*[9:0]  */
 hole0:4,
 prep:1, /*[14:14]  */
 pad:1, /*[15:15]  */
 hole1:16;
 } bits;

 uint32_t value;
};

union vdec_cs_cwidth_12Reg {
 struct { uint32_t

 /* sorting 3 */
#define vdec_cs_cwidth_12_stride_SHIFT 0
#define vdec_cs_cwidth_12_stride_WIDTH 10
#define vdec_cs_cwidth_12_prep_SHIFT 14
#define vdec_cs_cwidth_12_prep_WIDTH 1
#define vdec_cs_cwidth_12_pad_SHIFT 15
#define vdec_cs_cwidth_12_pad_WIDTH 1

 stride:10, /*[9:0]  */
 hole0:4,
 prep:1, /*[14:14]  */
 pad:1, /*[15:15]  */
 hole1:16;
 } bits;

 uint32_t value;
};

union vdec_cs_cwidth_11Reg {
 struct { uint32_t

 /* sorting 3 */
#define vdec_cs_cwidth_11_stride_SHIFT 0
#define vdec_cs_cwidth_11_stride_WIDTH 10
#define vdec_cs_cwidth_11_prep_SHIFT 14
#define vdec_cs_cwidth_11_prep_WIDTH 1
#define vdec_cs_cwidth_11_pad_SHIFT 15
#define vdec_cs_cwidth_11_pad_WIDTH 1

 stride:10, /*[9:0]  */
 hole0:4,
 prep:1, /*[14:14]  */
 pad:1, /*[15:15]  */
 hole1:16;
 } bits;

 uint32_t value;
};

union vdec_cs_cwidth_10Reg {
 struct { uint32_t

 /* sorting 3 */
#define vdec_cs_cwidth_10_stride_SHIFT 0
#define vdec_cs_cwidth_10_stride_WIDTH 10
#define vdec_cs_cwidth_10_prep_SHIFT 14
#define vdec_cs_cwidth_10_prep_WIDTH 1
#define vdec_cs_cwidth_10_pad_SHIFT 15
#define vdec_cs_cwidth_10_pad_WIDTH 1

 stride:10, /*[9:0]  */
 hole0:4,
 prep:1, /*[14:14]  */
 pad:1, /*[15:15]  */
 hole1:16;
 } bits;

 uint32_t value;
};

union vdec_cs_cwidth_1Reg {
 struct { uint32_t

 /* sorting 3 */
#define vdec_cs_cwidth_1_stride_SHIFT 0
#define vdec_cs_cwidth_1_stride_WIDTH 10
#define vdec_cs_cwidth_1_prep_SHIFT 14
#define vdec_cs_cwidth_1_prep_WIDTH 1
#define vdec_cs_cwidth_1_pad_SHIFT 15
#define vdec_cs_cwidth_1_pad_WIDTH 1

 stride:10, /*[9:0]  */
 hole0:4,
 prep:1, /*[14:14]  */
 pad:1, /*[15:15]  */
 hole1:16;
 } bits;

 uint32_t value;
};

union vdec_cs_cwidth_0Reg {
 struct { uint32_t

 /* sorting 3 */
#define vdec_cs_cwidth_0_stride_SHIFT 0
#define vdec_cs_cwidth_0_stride_WIDTH 10
#define vdec_cs_cwidth_0_prep_SHIFT 14
#define vdec_cs_cwidth_0_prep_WIDTH 1
#define vdec_cs_cwidth_0_pad_SHIFT 15
#define vdec_cs_cwidth_0_pad_WIDTH 1

 stride:10, /*[9:0]  */
 hole0:4,
 prep:1, /*[14:14]  */
 pad:1, /*[15:15]  */
 hole1:16;
 } bits;

 uint32_t value;
};

union vdec_cs_cstartlow_9Reg {
 struct { uint32_t

 /* sorting 2 */
#define vdec_cs_cstartlow_9_x_offset_SHIFT 4
#define vdec_cs_cstartlow_9_x_offset_WIDTH 4
#define vdec_cs_cstartlow_9_tile_SHIFT 8
#define vdec_cs_cstartlow_9_tile_WIDTH 8

 hole0:4,
 x_offset:4, /*[7:4]  */
 tile:8, /*[15:8]  */
 hole1:16;
 } bits;

 uint32_t value;
};

union vdec_cs_cstartlow_8Reg {
 struct { uint32_t

 /* sorting 2 */
#define vdec_cs_cstartlow_8_x_offset_SHIFT 4
#define vdec_cs_cstartlow_8_x_offset_WIDTH 4
#define vdec_cs_cstartlow_8_tile_SHIFT 8
#define vdec_cs_cstartlow_8_tile_WIDTH 8

 hole0:4,
 x_offset:4, /*[7:4]  */
 tile:8, /*[15:8]  */
 hole1:16;
 } bits;

 uint32_t value;
};

union vdec_cs_cstartlow_7Reg {
 struct { uint32_t

 /* sorting 2 */
#define vdec_cs_cstartlow_7_x_offset_SHIFT 4
#define vdec_cs_cstartlow_7_x_offset_WIDTH 4
#define vdec_cs_cstartlow_7_tile_SHIFT 8
#define vdec_cs_cstartlow_7_tile_WIDTH 8

 hole0:4,
 x_offset:4, /*[7:4]  */
 tile:8, /*[15:8]  */
 hole1:16;
 } bits;

 uint32_t value;
};

union vdec_cs_cstartlow_6Reg {
 struct { uint32_t

 /* sorting 2 */
#define vdec_cs_cstartlow_6_x_offset_SHIFT 4
#define vdec_cs_cstartlow_6_x_offset_WIDTH 4
#define vdec_cs_cstartlow_6_tile_SHIFT 8
#define vdec_cs_cstartlow_6_tile_WIDTH 8

 hole0:4,
 x_offset:4, /*[7:4]  */
 tile:8, /*[15:8]  */
 hole1:16;
 } bits;

 uint32_t value;
};

union vdec_cs_cstartlow_5Reg {
 struct { uint32_t

 /* sorting 2 */
#define vdec_cs_cstartlow_5_x_offset_SHIFT 4
#define vdec_cs_cstartlow_5_x_offset_WIDTH 4
#define vdec_cs_cstartlow_5_tile_SHIFT 8
#define vdec_cs_cstartlow_5_tile_WIDTH 8

 hole0:4,
 x_offset:4, /*[7:4]  */
 tile:8, /*[15:8]  */
 hole1:16;
 } bits;

 uint32_t value;
};

union vdec_cs_cstartlow_4Reg {
 struct { uint32_t

 /* sorting 2 */
#define vdec_cs_cstartlow_4_x_offset_SHIFT 4
#define vdec_cs_cstartlow_4_x_offset_WIDTH 4
#define vdec_cs_cstartlow_4_tile_SHIFT 8
#define vdec_cs_cstartlow_4_tile_WIDTH 8

 hole0:4,
 x_offset:4, /*[7:4]  */
 tile:8, /*[15:8]  */
 hole1:16;
 } bits;

 uint32_t value;
};

union vdec_cs_cstartlow_3Reg {
 struct { uint32_t

 /* sorting 2 */
#define vdec_cs_cstartlow_3_x_offset_SHIFT 4
#define vdec_cs_cstartlow_3_x_offset_WIDTH 4
#define vdec_cs_cstartlow_3_tile_SHIFT 8
#define vdec_cs_cstartlow_3_tile_WIDTH 8

 hole0:4,
 x_offset:4, /*[7:4]  */
 tile:8, /*[15:8]  */
 hole1:16;
 } bits;

 uint32_t value;
};

union vdec_cs_cstartlow_2Reg {
 struct { uint32_t

 /* sorting 2 */
#define vdec_cs_cstartlow_2_x_offset_SHIFT 4
#define vdec_cs_cstartlow_2_x_offset_WIDTH 4
#define vdec_cs_cstartlow_2_tile_SHIFT 8
#define vdec_cs_cstartlow_2_tile_WIDTH 8

 hole0:4,
 x_offset:4, /*[7:4]  */
 tile:8, /*[15:8]  */
 hole1:16;
 } bits;

 uint32_t value;
};

union vdec_cs_cstartlow_16Reg {
 struct { uint32_t

 /* sorting 2 */
#define vdec_cs_cstartlow_16_x_offset_SHIFT 4
#define vdec_cs_cstartlow_16_x_offset_WIDTH 4
#define vdec_cs_cstartlow_16_tile_SHIFT 8
#define vdec_cs_cstartlow_16_tile_WIDTH 8

 hole0:4,
 x_offset:4, /*[7:4]  */
 tile:8, /*[15:8]  */
 hole1:16;
 } bits;

 uint32_t value;
};

union vdec_cs_cstartlow_15Reg {
 struct { uint32_t

 /* sorting 2 */
#define vdec_cs_cstartlow_15_x_offset_SHIFT 4
#define vdec_cs_cstartlow_15_x_offset_WIDTH 4
#define vdec_cs_cstartlow_15_tile_SHIFT 8
#define vdec_cs_cstartlow_15_tile_WIDTH 8

 hole0:4,
 x_offset:4, /*[7:4]  */
 tile:8, /*[15:8]  */
 hole1:16;
 } bits;

 uint32_t value;
};

union vdec_cs_cstartlow_14Reg {
 struct { uint32_t

 /* sorting 2 */
#define vdec_cs_cstartlow_14_x_offset_SHIFT 4
#define vdec_cs_cstartlow_14_x_offset_WIDTH 4
#define vdec_cs_cstartlow_14_tile_SHIFT 8
#define vdec_cs_cstartlow_14_tile_WIDTH 8

 hole0:4,
 x_offset:4, /*[7:4]  */
 tile:8, /*[15:8]  */
 hole1:16;
 } bits;

 uint32_t value;
};

union vdec_cs_cstartlow_13Reg {
 struct { uint32_t

 /* sorting 2 */
#define vdec_cs_cstartlow_13_x_offset_SHIFT 4
#define vdec_cs_cstartlow_13_x_offset_WIDTH 4
#define vdec_cs_cstartlow_13_tile_SHIFT 8
#define vdec_cs_cstartlow_13_tile_WIDTH 8

 hole0:4,
 x_offset:4, /*[7:4]  */
 tile:8, /*[15:8]  */
 hole1:16;
 } bits;

 uint32_t value;
};

union vdec_cs_cstartlow_12Reg {
 struct { uint32_t

 /* sorting 2 */
#define vdec_cs_cstartlow_12_x_offset_SHIFT 4
#define vdec_cs_cstartlow_12_x_offset_WIDTH 4
#define vdec_cs_cstartlow_12_tile_SHIFT 8
#define vdec_cs_cstartlow_12_tile_WIDTH 8

 hole0:4,
 x_offset:4, /*[7:4]  */
 tile:8, /*[15:8]  */
 hole1:16;
 } bits;

 uint32_t value;
};

union vdec_cs_cstartlow_11Reg {
 struct { uint32_t

 /* sorting 2 */
#define vdec_cs_cstartlow_11_x_offset_SHIFT 4
#define vdec_cs_cstartlow_11_x_offset_WIDTH 4
#define vdec_cs_cstartlow_11_tile_SHIFT 8
#define vdec_cs_cstartlow_11_tile_WIDTH 8

 hole0:4,
 x_offset:4, /*[7:4]  */
 tile:8, /*[15:8]  */
 hole1:16;
 } bits;

 uint32_t value;
};

union vdec_cs_cstartlow_10Reg {
 struct { uint32_t

 /* sorting 2 */
#define vdec_cs_cstartlow_10_x_offset_SHIFT 4
#define vdec_cs_cstartlow_10_x_offset_WIDTH 4
#define vdec_cs_cstartlow_10_tile_SHIFT 8
#define vdec_cs_cstartlow_10_tile_WIDTH 8

 hole0:4,
 x_offset:4, /*[7:4]  */
 tile:8, /*[15:8]  */
 hole1:16;
 } bits;

 uint32_t value;
};

union vdec_cs_cstartlow_1Reg {
 struct { uint32_t

 /* sorting 2 */
#define vdec_cs_cstartlow_1_x_offset_SHIFT 4
#define vdec_cs_cstartlow_1_x_offset_WIDTH 4
#define vdec_cs_cstartlow_1_tile_SHIFT 8
#define vdec_cs_cstartlow_1_tile_WIDTH 8

 hole0:4,
 x_offset:4, /*[7:4]  */
 tile:8, /*[15:8]  */
 hole1:16;
 } bits;

 uint32_t value;
};

union vdec_cs_cstartlow_0Reg {
 struct { uint32_t

 /* sorting 2 */
#define vdec_cs_cstartlow_0_x_offset_SHIFT 4
#define vdec_cs_cstartlow_0_x_offset_WIDTH 4
#define vdec_cs_cstartlow_0_tile_SHIFT 8
#define vdec_cs_cstartlow_0_tile_WIDTH 8

 hole0:4,
 x_offset:4, /*[7:4]  */
 tile:8, /*[15:8]  */
 hole1:16;
 } bits;

 uint32_t value;
};

union vdec_cs_cstarthigh_9Reg {
 struct { uint32_t

 /* sorting 2 */
#define vdec_cs_cstarthigh_9_tile_SHIFT 0
#define vdec_cs_cstarthigh_9_tile_WIDTH 15
#define vdec_cs_cstarthigh_9_msb_SHIFT 15
#define vdec_cs_cstarthigh_9_msb_WIDTH 1

 tile:15, /*[14:0]  */
 msb:1, /*[15:15] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_cstarthigh_8Reg {
 struct { uint32_t

 /* sorting 2 */
#define vdec_cs_cstarthigh_8_tile_SHIFT 0
#define vdec_cs_cstarthigh_8_tile_WIDTH 15
#define vdec_cs_cstarthigh_8_msb_SHIFT 15
#define vdec_cs_cstarthigh_8_msb_WIDTH 1

 tile:15, /*[14:0]  */
 msb:1, /*[15:15] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_cstarthigh_7Reg {
 struct { uint32_t

 /* sorting 2 */
#define vdec_cs_cstarthigh_7_tile_SHIFT 0
#define vdec_cs_cstarthigh_7_tile_WIDTH 15
#define vdec_cs_cstarthigh_7_msb_SHIFT 15
#define vdec_cs_cstarthigh_7_msb_WIDTH 1

 tile:15, /*[14:0]  */
 msb:1, /*[15:15] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_cstarthigh_6Reg {
 struct { uint32_t

 /* sorting 2 */
#define vdec_cs_cstarthigh_6_tile_SHIFT 0
#define vdec_cs_cstarthigh_6_tile_WIDTH 15
#define vdec_cs_cstarthigh_6_msb_SHIFT 15
#define vdec_cs_cstarthigh_6_msb_WIDTH 1

 tile:15, /*[14:0]  */
 msb:1, /*[15:15] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_cstarthigh_5Reg {
 struct { uint32_t

 /* sorting 2 */
#define vdec_cs_cstarthigh_5_tile_SHIFT 0
#define vdec_cs_cstarthigh_5_tile_WIDTH 15
#define vdec_cs_cstarthigh_5_msb_SHIFT 15
#define vdec_cs_cstarthigh_5_msb_WIDTH 1

 tile:15, /*[14:0]  */
 msb:1, /*[15:15] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_cstarthigh_4Reg {
 struct { uint32_t

 /* sorting 2 */
#define vdec_cs_cstarthigh_4_tile_SHIFT 0
#define vdec_cs_cstarthigh_4_tile_WIDTH 15
#define vdec_cs_cstarthigh_4_msb_SHIFT 15
#define vdec_cs_cstarthigh_4_msb_WIDTH 1

 tile:15, /*[14:0]  */
 msb:1, /*[15:15] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_cstarthigh_3Reg {
 struct { uint32_t

 /* sorting 2 */
#define vdec_cs_cstarthigh_3_tile_SHIFT 0
#define vdec_cs_cstarthigh_3_tile_WIDTH 15
#define vdec_cs_cstarthigh_3_msb_SHIFT 15
#define vdec_cs_cstarthigh_3_msb_WIDTH 1

 tile:15, /*[14:0]  */
 msb:1, /*[15:15] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_cstarthigh_2Reg {
 struct { uint32_t

 /* sorting 2 */
#define vdec_cs_cstarthigh_2_tile_SHIFT 0
#define vdec_cs_cstarthigh_2_tile_WIDTH 15
#define vdec_cs_cstarthigh_2_msb_SHIFT 15
#define vdec_cs_cstarthigh_2_msb_WIDTH 1

 tile:15, /*[14:0]  */
 msb:1, /*[15:15] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_cstarthigh_16Reg {
 struct { uint32_t

 /* sorting 2 */
#define vdec_cs_cstarthigh_16_tile_SHIFT 0
#define vdec_cs_cstarthigh_16_tile_WIDTH 15
#define vdec_cs_cstarthigh_16_msb_SHIFT 15
#define vdec_cs_cstarthigh_16_msb_WIDTH 1

 tile:15, /*[14:0]  */
 msb:1, /*[15:15] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_cstarthigh_15Reg {
 struct { uint32_t

 /* sorting 2 */
#define vdec_cs_cstarthigh_15_tile_SHIFT 0
#define vdec_cs_cstarthigh_15_tile_WIDTH 15
#define vdec_cs_cstarthigh_15_msb_SHIFT 15
#define vdec_cs_cstarthigh_15_msb_WIDTH 1

 tile:15, /*[14:0]  */
 msb:1, /*[15:15] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_cstarthigh_14Reg {
 struct { uint32_t

 /* sorting 2 */
#define vdec_cs_cstarthigh_14_tile_SHIFT 0
#define vdec_cs_cstarthigh_14_tile_WIDTH 15
#define vdec_cs_cstarthigh_14_msb_SHIFT 15
#define vdec_cs_cstarthigh_14_msb_WIDTH 1

 tile:15, /*[14:0]  */
 msb:1, /*[15:15] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_cstarthigh_13Reg {
 struct { uint32_t

 /* sorting 2 */
#define vdec_cs_cstarthigh_13_tile_SHIFT 0
#define vdec_cs_cstarthigh_13_tile_WIDTH 15
#define vdec_cs_cstarthigh_13_msb_SHIFT 15
#define vdec_cs_cstarthigh_13_msb_WIDTH 1

 tile:15, /*[14:0]  */
 msb:1, /*[15:15] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_cstarthigh_12Reg {
 struct { uint32_t

 /* sorting 2 */
#define vdec_cs_cstarthigh_12_tile_SHIFT 0
#define vdec_cs_cstarthigh_12_tile_WIDTH 15
#define vdec_cs_cstarthigh_12_msb_SHIFT 15
#define vdec_cs_cstarthigh_12_msb_WIDTH 1

 tile:15, /*[14:0]  */
 msb:1, /*[15:15] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_cstarthigh_11Reg {
 struct { uint32_t

 /* sorting 2 */
#define vdec_cs_cstarthigh_11_tile_SHIFT 0
#define vdec_cs_cstarthigh_11_tile_WIDTH 15
#define vdec_cs_cstarthigh_11_msb_SHIFT 15
#define vdec_cs_cstarthigh_11_msb_WIDTH 1

 tile:15, /*[14:0]  */
 msb:1, /*[15:15] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_cstarthigh_10Reg {
 struct { uint32_t

 /* sorting 2 */
#define vdec_cs_cstarthigh_10_tile_SHIFT 0
#define vdec_cs_cstarthigh_10_tile_WIDTH 15
#define vdec_cs_cstarthigh_10_msb_SHIFT 15
#define vdec_cs_cstarthigh_10_msb_WIDTH 1

 tile:15, /*[14:0]  */
 msb:1, /*[15:15] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_cstarthigh_1Reg {
 struct { uint32_t

 /* sorting 2 */
#define vdec_cs_cstarthigh_1_tile_SHIFT 0
#define vdec_cs_cstarthigh_1_tile_WIDTH 15
#define vdec_cs_cstarthigh_1_msb_SHIFT 15
#define vdec_cs_cstarthigh_1_msb_WIDTH 1

 tile:15, /*[14:0]  */
 msb:1, /*[15:15] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_cstarthigh_0Reg {
 struct { uint32_t

 /* sorting 2 */
#define vdec_cs_cstarthigh_0_tile_SHIFT 0
#define vdec_cs_cstarthigh_0_tile_WIDTH 15
#define vdec_cs_cstarthigh_0_msb_SHIFT 15
#define vdec_cs_cstarthigh_0_msb_WIDTH 1

 tile:15, /*[14:0]  */
 msb:1, /*[15:15] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_creserved_9Reg {
 struct { uint32_t

 /* sorting 1 */
#define vdec_cs_creserved_9_vdec_cs_creserved_9_value_SHIFT 0
#define vdec_cs_creserved_9_vdec_cs_creserved_9_value_WIDTH 16

 vdec_cs_creserved_9_value:16, /*[15:0] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_creserved_8Reg {
 struct { uint32_t

 /* sorting 1 */
#define vdec_cs_creserved_8_vdec_cs_creserved_8_value_SHIFT 0
#define vdec_cs_creserved_8_vdec_cs_creserved_8_value_WIDTH 16

 vdec_cs_creserved_8_value:16, /*[15:0] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_creserved_7Reg {
 struct { uint32_t

 /* sorting 1 */
#define vdec_cs_creserved_7_vdec_cs_creserved_7_value_SHIFT 0
#define vdec_cs_creserved_7_vdec_cs_creserved_7_value_WIDTH 16

 vdec_cs_creserved_7_value:16, /*[15:0] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_creserved_6Reg {
 struct { uint32_t

 /* sorting 1 */
#define vdec_cs_creserved_6_vdec_cs_creserved_6_value_SHIFT 0
#define vdec_cs_creserved_6_vdec_cs_creserved_6_value_WIDTH 16

 vdec_cs_creserved_6_value:16, /*[15:0] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_creserved_5Reg {
 struct { uint32_t

 /* sorting 1 */
#define vdec_cs_creserved_5_vdec_cs_creserved_5_value_SHIFT 0
#define vdec_cs_creserved_5_vdec_cs_creserved_5_value_WIDTH 16

 vdec_cs_creserved_5_value:16, /*[15:0] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_creserved_4Reg {
 struct { uint32_t

 /* sorting 1 */
#define vdec_cs_creserved_4_vdec_cs_creserved_4_value_SHIFT 0
#define vdec_cs_creserved_4_vdec_cs_creserved_4_value_WIDTH 16

 vdec_cs_creserved_4_value:16, /*[15:0] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_creserved_3Reg {
 struct { uint32_t

 /* sorting 1 */
#define vdec_cs_creserved_3_vdec_cs_creserved_3_value_SHIFT 0
#define vdec_cs_creserved_3_vdec_cs_creserved_3_value_WIDTH 16

 vdec_cs_creserved_3_value:16, /*[15:0] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_creserved_2Reg {
 struct { uint32_t

 /* sorting 1 */
#define vdec_cs_creserved_2_vdec_cs_creserved_2_value_SHIFT 0
#define vdec_cs_creserved_2_vdec_cs_creserved_2_value_WIDTH 16

 vdec_cs_creserved_2_value:16, /*[15:0] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_creserved_16Reg {
 struct { uint32_t

 /* sorting 1 */
#define vdec_cs_creserved_16_vdec_cs_creserved_16_value_SHIFT 0
#define vdec_cs_creserved_16_vdec_cs_creserved_16_value_WIDTH 16

 vdec_cs_creserved_16_value:16, /*[15:0] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_creserved_15Reg {
 struct { uint32_t

 /* sorting 1 */
#define vdec_cs_creserved_15_vdec_cs_creserved_15_value_SHIFT 0
#define vdec_cs_creserved_15_vdec_cs_creserved_15_value_WIDTH 16

 vdec_cs_creserved_15_value:16, /*[15:0] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_creserved_14Reg {
 struct { uint32_t

 /* sorting 1 */
#define vdec_cs_creserved_14_vdec_cs_creserved_14_value_SHIFT 0
#define vdec_cs_creserved_14_vdec_cs_creserved_14_value_WIDTH 16

 vdec_cs_creserved_14_value:16, /*[15:0] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_creserved_13Reg {
 struct { uint32_t

 /* sorting 1 */
#define vdec_cs_creserved_13_vdec_cs_creserved_13_value_SHIFT 0
#define vdec_cs_creserved_13_vdec_cs_creserved_13_value_WIDTH 16

 vdec_cs_creserved_13_value:16, /*[15:0] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_creserved_12Reg {
 struct { uint32_t

 /* sorting 1 */
#define vdec_cs_creserved_12_vdec_cs_creserved_12_value_SHIFT 0
#define vdec_cs_creserved_12_vdec_cs_creserved_12_value_WIDTH 16

 vdec_cs_creserved_12_value:16, /*[15:0] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_creserved_11Reg {
 struct { uint32_t

 /* sorting 1 */
#define vdec_cs_creserved_11_vdec_cs_creserved_11_value_SHIFT 0
#define vdec_cs_creserved_11_vdec_cs_creserved_11_value_WIDTH 16

 vdec_cs_creserved_11_value:16, /*[15:0] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_creserved_10Reg {
 struct { uint32_t

 /* sorting 1 */
#define vdec_cs_creserved_10_vdec_cs_creserved_10_value_SHIFT 0
#define vdec_cs_creserved_10_vdec_cs_creserved_10_value_WIDTH 16

 vdec_cs_creserved_10_value:16, /*[15:0] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_commandReg {
 struct { uint32_t

 /* sorting 1 */
#define vdec_cs_command_vdec_cs_status_SHIFT 0
#define vdec_cs_command_vdec_cs_status_WIDTH 16

 vdec_cs_status:16, /*[15:0]  */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_chroma_intensity_buffer_3Reg {
 struct { uint32_t

 /* sorting 1 */
#define vdec_cs_chroma_intensity_buffer_3_vdec_cs_intensity_1_bottom_2_SHIFT 0
#define vdec_cs_chroma_intensity_buffer_3_vdec_cs_intensity_1_bottom_2_WIDTH 16

 vdec_cs_intensity_1_bottom_2:16, /*[15:0]  */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_chroma_intensity_buffer_2Reg {
 struct { uint32_t

 /* sorting 1 */
#define vdec_cs_chroma_intensity_buffer_2_vdec_cs_intensity_0_bottom_2_SHIFT 0
#define vdec_cs_chroma_intensity_buffer_2_vdec_cs_intensity_0_bottom_2_WIDTH 16

 vdec_cs_intensity_0_bottom_2:16, /*[15:0]  */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_chroma_intensity_buffer_1Reg {
 struct { uint32_t

 /* sorting 1 */
#define vdec_cs_chroma_intensity_buffer_1_vdec_cs_intensity_1_bottom_1_SHIFT 0
#define vdec_cs_chroma_intensity_buffer_1_vdec_cs_intensity_1_bottom_1_WIDTH 16

 vdec_cs_intensity_1_bottom_1:16, /*[15:0]  */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_chroma_intensity_buffer_0Reg {
 struct { uint32_t

 /* sorting 1 */
#define vdec_cs_chroma_intensity_buffer_0_vdec_cs_intensity_0_bottom_1_SHIFT 0
#define vdec_cs_chroma_intensity_buffer_0_vdec_cs_intensity_0_bottom_1_WIDTH 16

 vdec_cs_intensity_0_bottom_1:16, /*[15:0]  */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_bottom_statusReg {
 struct { uint32_t

 /* sorting 1 */
#define vdec_cs_bottom_status_vdec_cs_bottom_status_value_SHIFT 0
#define vdec_cs_bottom_status_vdec_cs_bottom_status_value_WIDTH 16

 vdec_cs_bottom_status_value:16, /*[15:0]  */
 hole0:16;
 } bits;

 uint32_t value;
};

union vdec_cs_alpha_betaReg {
 struct { uint32_t

 /* sorting 3 */
#define vdec_cs_alpha_beta_beta_offset_SHIFT 0
#define vdec_cs_alpha_beta_beta_offset_WIDTH 5
#define vdec_cs_alpha_beta_alpha_offset_SHIFT 8
#define vdec_cs_alpha_beta_alpha_offset_WIDTH 5
#define vdec_cs_alpha_beta_dbk_en_SHIFT 15
#define vdec_cs_alpha_beta_dbk_en_WIDTH 1

 beta_offset:5, /*[4:0]  */
 hole0:3,
 alpha_offset:5, /*[12:8]  */
 hole1:2,
 dbk_en:1, /*[15:15]  */
 hole2:16;
 } bits;

 uint32_t value;
};

struct vdec_command_sequencer {
 union vdec_cs_lstartlow_0Reg vdec_cs_lstartlow_0; /* +0x00000000  */
 union vdec_cs_lstarthigh_0Reg vdec_cs_lstarthigh_0; /* +0x00000004  */
 union vdec_cs_lwidth_0Reg vdec_cs_lwidth_0; /* +0x00000008  */
 union vdec_cs_lreserved_0Reg vdec_cs_lreserved_0; /* +0x0000000c  */
 union vdec_cs_cstartlow_0Reg vdec_cs_cstartlow_0; /* +0x00000010  */
 union vdec_cs_cstarthigh_0Reg vdec_cs_cstarthigh_0; /* +0x00000014  */
 union vdec_cs_cwidth_0Reg vdec_cs_cwidth_0; /* +0x00000018  */
 union vdec_cs_rreserved_0Reg vdec_cs_rreserved_0; /* +0x0000001c  */
 union vdec_cs_lstartlow_1Reg vdec_cs_lstartlow_1; /* +0x00000020  */
 union vdec_cs_lstarthigh_1Reg vdec_cs_lstarthigh_1; /* +0x00000024  */
 union vdec_cs_lwidth_1Reg vdec_cs_lwidth_1; /* +0x00000028  */
 union vdec_cs_lreserved_1Reg vdec_cs_lreserved_1; /* +0x0000002c  */
 union vdec_cs_cstartlow_1Reg vdec_cs_cstartlow_1; /* +0x00000030  */
 union vdec_cs_cstarthigh_1Reg vdec_cs_cstarthigh_1; /* +0x00000034  */
 union vdec_cs_cwidth_1Reg vdec_cs_cwidth_1; /* +0x00000038  */
 union vdec_cs_rreserved_1Reg vdec_cs_rreserved_1; /* +0x0000003c  */
 union vdec_cs_lstartlow_2Reg vdec_cs_lstartlow_2; /* +0x00000040  */
 union vdec_cs_lstarthigh_2Reg vdec_cs_lstarthigh_2; /* +0x00000044  */
 union vdec_cs_lwidth_2Reg vdec_cs_lwidth_2; /* +0x00000048  */
 union vdec_cs_lreserved_2Reg vdec_cs_lreserved_2; /* +0x0000004c  */
 union vdec_cs_cstartlow_2Reg vdec_cs_cstartlow_2; /* +0x00000050  */
 union vdec_cs_cstarthigh_2Reg vdec_cs_cstarthigh_2; /* +0x00000054  */
 union vdec_cs_cwidth_2Reg vdec_cs_cwidth_2; /* +0x00000058  */
 union vdec_cs_creserved_2Reg vdec_cs_creserved_2; /* +0x0000005c  */
 union vdec_cs_lstartlow_3Reg vdec_cs_lstartlow_3; /* +0x00000060  */
 union vdec_cs_lstarthigh_3Reg vdec_cs_lstarthigh_3; /* +0x00000064  */
 union vdec_cs_lwidth_3Reg vdec_cs_lwidth_3; /* +0x00000068  */
 union vdec_cs_lreserved_3Reg vdec_cs_lreserved_3; /* +0x0000006c  */
 union vdec_cs_cstartlow_3Reg vdec_cs_cstartlow_3; /* +0x00000070  */
 union vdec_cs_cstarthigh_3Reg vdec_cs_cstarthigh_3; /* +0x00000074  */
 union vdec_cs_cwidth_3Reg vdec_cs_cwidth_3; /* +0x00000078  */
 union vdec_cs_creserved_3Reg vdec_cs_creserved_3; /* +0x0000007c  */
 union vdec_cs_lstartlow_4Reg vdec_cs_lstartlow_4; /* +0x00000080  */
 union vdec_cs_lstarthigh_4Reg vdec_cs_lstarthigh_4; /* +0x00000084  */
 union vdec_cs_lwidth_4Reg vdec_cs_lwidth_4; /* +0x00000088  */
 union vdec_cs_lreserved_4Reg vdec_cs_lreserved_4; /* +0x0000008c  */
 union vdec_cs_cstartlow_4Reg vdec_cs_cstartlow_4; /* +0x00000090  */
 union vdec_cs_cstarthigh_4Reg vdec_cs_cstarthigh_4; /* +0x00000094  */
 union vdec_cs_cwidth_4Reg vdec_cs_cwidth_4; /* +0x00000098  */
 union vdec_cs_creserved_4Reg vdec_cs_creserved_4; /* +0x0000009c  */
 union vdec_cs_lstartlow_5Reg vdec_cs_lstartlow_5; /* +0x000000a0  */
 union vdec_cs_lstarthigh_5Reg vdec_cs_lstarthigh_5; /* +0x000000a4  */
 union vdec_cs_lwidth_5Reg vdec_cs_lwidth_5; /* +0x000000a8  */
 union vdec_cs_lreserved_5Reg vdec_cs_lreserved_5; /* +0x000000ac  */
 union vdec_cs_cstartlow_5Reg vdec_cs_cstartlow_5; /* +0x000000b0  */
 union vdec_cs_cstarthigh_5Reg vdec_cs_cstarthigh_5; /* +0x000000b4  */
 union vdec_cs_cwidth_5Reg vdec_cs_cwidth_5; /* +0x000000b8  */
 union vdec_cs_creserved_5Reg vdec_cs_creserved_5; /* +0x000000bc  */
 union vdec_cs_lstartlow_6Reg vdec_cs_lstartlow_6; /* +0x000000c0  */
 union vdec_cs_lstarthigh_6Reg vdec_cs_lstarthigh_6; /* +0x000000c4  */
 union vdec_cs_lwidth_6Reg vdec_cs_lwidth_6; /* +0x000000c8  */
 union vdec_cs_lreserved_6Reg vdec_cs_lreserved_6; /* +0x000000cc  */
 union vdec_cs_cstartlow_6Reg vdec_cs_cstartlow_6; /* +0x000000d0  */
 union vdec_cs_cstarthigh_6Reg vdec_cs_cstarthigh_6; /* +0x000000d4  */
 union vdec_cs_cwidth_6Reg vdec_cs_cwidth_6; /* +0x000000d8  */
 union vdec_cs_creserved_6Reg vdec_cs_creserved_6; /* +0x000000dc  */
 union vdec_cs_lstartlow_7Reg vdec_cs_lstartlow_7; /* +0x000000e0  */
 union vdec_cs_lstarthigh_7Reg vdec_cs_lstarthigh_7; /* +0x000000e4  */
 union vdec_cs_lwidth_7Reg vdec_cs_lwidth_7; /* +0x000000e8  */
 union vdec_cs_lreserved_7Reg vdec_cs_lreserved_7; /* +0x000000ec  */
 union vdec_cs_cstartlow_7Reg vdec_cs_cstartlow_7; /* +0x000000f0  */
 union vdec_cs_cstarthigh_7Reg vdec_cs_cstarthigh_7; /* +0x000000f4  */
 union vdec_cs_cwidth_7Reg vdec_cs_cwidth_7; /* +0x000000f8  */
 union vdec_cs_creserved_7Reg vdec_cs_creserved_7; /* +0x000000fc  */
 union vdec_cs_lstartlow_8Reg vdec_cs_lstartlow_8; /* +0x00000100  */
 union vdec_cs_lstarthigh_8Reg vdec_cs_lstarthigh_8; /* +0x00000104  */
 union vdec_cs_lwidth_8Reg vdec_cs_lwidth_8; /* +0x00000108  */
 union vdec_cs_lreserved_8Reg vdec_cs_lreserved_8; /* +0x0000010c  */
 union vdec_cs_cstartlow_8Reg vdec_cs_cstartlow_8; /* +0x00000110  */
 union vdec_cs_cstarthigh_8Reg vdec_cs_cstarthigh_8; /* +0x00000114  */
 union vdec_cs_cwidth_8Reg vdec_cs_cwidth_8; /* +0x00000118  */
 union vdec_cs_creserved_8Reg vdec_cs_creserved_8; /* +0x0000011c  */
 union vdec_cs_lstartlow_9Reg vdec_cs_lstartlow_9; /* +0x00000120  */
 union vdec_cs_lstarthigh_9Reg vdec_cs_lstarthigh_9; /* +0x00000124  */
 union vdec_cs_lwidth_9Reg vdec_cs_lwidth_9; /* +0x00000128  */
 union vdec_cs_lreserved_9Reg vdec_cs_lreserved_9; /* +0x0000012c  */
 union vdec_cs_cstartlow_9Reg vdec_cs_cstartlow_9; /* +0x00000130  */
 union vdec_cs_cstarthigh_9Reg vdec_cs_cstarthigh_9; /* +0x00000134  */
 union vdec_cs_cwidth_9Reg vdec_cs_cwidth_9; /* +0x00000138  */
 union vdec_cs_creserved_9Reg vdec_cs_creserved_9; /* +0x0000013c  */
 union vdec_cs_lstartlow_10Reg vdec_cs_lstartlow_10; /* +0x00000140  */
 union vdec_cs_lstarthigh_10Reg vdec_cs_lstarthigh_10; /* +0x00000144  */
 union vdec_cs_lwidth_10Reg vdec_cs_lwidth_10; /* +0x00000148  */
 union vdec_cs_lreserved_10Reg vdec_cs_lreserved_10; /* +0x0000014c  */
 union vdec_cs_cstartlow_10Reg vdec_cs_cstartlow_10; /* +0x00000150  */
 union vdec_cs_cstarthigh_10Reg vdec_cs_cstarthigh_10; /* +0x00000154  */
 union vdec_cs_cwidth_10Reg vdec_cs_cwidth_10; /* +0x00000158  */
 union vdec_cs_creserved_10Reg vdec_cs_creserved_10; /* +0x0000015c  */
 union vdec_cs_lstartlow_11Reg vdec_cs_lstartlow_11; /* +0x00000160  */
 union vdec_cs_lstarthigh_11Reg vdec_cs_lstarthigh_11; /* +0x00000164  */
 union vdec_cs_lwidth_11Reg vdec_cs_lwidth_11; /* +0x00000168  */
 union vdec_cs_lreserved_11Reg vdec_cs_lreserved_11; /* +0x0000016c  */
 union vdec_cs_cstartlow_11Reg vdec_cs_cstartlow_11; /* +0x00000170  */
 union vdec_cs_cstarthigh_11Reg vdec_cs_cstarthigh_11; /* +0x00000174  */
 union vdec_cs_cwidth_11Reg vdec_cs_cwidth_11; /* +0x00000178  */
 union vdec_cs_creserved_11Reg vdec_cs_creserved_11; /* +0x0000017c  */
 union vdec_cs_lstartlow_12Reg vdec_cs_lstartlow_12; /* +0x00000180  */
 union vdec_cs_lstarthigh_12Reg vdec_cs_lstarthigh_12; /* +0x00000184  */
 union vdec_cs_lwidth_12Reg vdec_cs_lwidth_12; /* +0x00000188  */
 union vdec_cs_lreserved_12Reg vdec_cs_lreserved_12; /* +0x0000018c  */
 union vdec_cs_cstartlow_12Reg vdec_cs_cstartlow_12; /* +0x00000190  */
 union vdec_cs_cstarthigh_12Reg vdec_cs_cstarthigh_12; /* +0x00000194  */
 union vdec_cs_cwidth_12Reg vdec_cs_cwidth_12; /* +0x00000198  */
 union vdec_cs_creserved_12Reg vdec_cs_creserved_12; /* +0x0000019c  */
 union vdec_cs_lstartlow_13Reg vdec_cs_lstartlow_13; /* +0x000001a0  */
 union vdec_cs_lstarthigh_13Reg vdec_cs_lstarthigh_13; /* +0x000001a4  */
 union vdec_cs_lwidth_13Reg vdec_cs_lwidth_13; /* +0x000001a8  */
 union vdec_cs_lreserved_13Reg vdec_cs_lreserved_13; /* +0x000001ac  */
 union vdec_cs_cstartlow_13Reg vdec_cs_cstartlow_13; /* +0x000001b0  */
 union vdec_cs_cstarthigh_13Reg vdec_cs_cstarthigh_13; /* +0x000001b4  */
 union vdec_cs_cwidth_13Reg vdec_cs_cwidth_13; /* +0x000001b8  */
 union vdec_cs_creserved_13Reg vdec_cs_creserved_13; /* +0x000001bc  */
 union vdec_cs_lstartlow_14Reg vdec_cs_lstartlow_14; /* +0x000001c0  */
 union vdec_cs_lstarthigh_14Reg vdec_cs_lstarthigh_14; /* +0x000001c4  */
 union vdec_cs_lwidth_14Reg vdec_cs_lwidth_14; /* +0x000001c8  */
 union vdec_cs_lreserved_14Reg vdec_cs_lreserved_14; /* +0x000001cc  */
 union vdec_cs_cstartlow_14Reg vdec_cs_cstartlow_14; /* +0x000001d0  */
 union vdec_cs_cstarthigh_14Reg vdec_cs_cstarthigh_14; /* +0x000001d4  */
 union vdec_cs_cwidth_14Reg vdec_cs_cwidth_14; /* +0x000001d8  */
 union vdec_cs_creserved_14Reg vdec_cs_creserved_14; /* +0x000001dc  */
 union vdec_cs_lstartlow_15Reg vdec_cs_lstartlow_15; /* +0x000001e0  */
 union vdec_cs_lstarthigh_15Reg vdec_cs_lstarthigh_15; /* +0x000001e4  */
 union vdec_cs_lwidth_15Reg vdec_cs_lwidth_15; /* +0x000001e8  */
 union vdec_cs_lreserved_15Reg vdec_cs_lreserved_15; /* +0x000001ec  */
 union vdec_cs_cstartlow_15Reg vdec_cs_cstartlow_15; /* +0x000001f0  */
 union vdec_cs_cstarthigh_15Reg vdec_cs_cstarthigh_15; /* +0x000001f4  */
 union vdec_cs_cwidth_15Reg vdec_cs_cwidth_15; /* +0x000001f8  */
 union vdec_cs_creserved_15Reg vdec_cs_creserved_15; /* +0x000001fc  */
 union vdec_cs_lstartlow_16Reg vdec_cs_lstartlow_16; /* +0x00000200  */
 union vdec_cs_lstarthigh_16Reg vdec_cs_lstarthigh_16; /* +0x00000204  */
 union vdec_cs_lwidth_16Reg vdec_cs_lwidth_16; /* +0x00000208  */
 union vdec_cs_lreserved_16Reg vdec_cs_lreserved_16; /* +0x0000020c  */
 union vdec_cs_cstartlow_16Reg vdec_cs_cstartlow_16; /* +0x00000210  */
 union vdec_cs_cstarthigh_16Reg vdec_cs_cstarthigh_16; /* +0x00000214  */
 union vdec_cs_cwidth_16Reg vdec_cs_cwidth_16; /* +0x00000218  */
 union vdec_cs_creserved_16Reg vdec_cs_creserved_16; /* +0x0000021c  */
 union vdec_cs_commandReg vdec_cs_command; /* +0x00000220 ,NO_TEST */
 union vdec_cs_setupReg vdec_cs_setup; /* +0x00000224  */
 union vdec_cs_widthReg vdec_cs_width; /* +0x00000228  */
 union vdec_cs_heightReg vdec_cs_height; /* +0x0000022c  */
 union vdec_cs_luma_intensity_buffer_0Reg vdec_cs_luma_intensity_buffer_0; /* +0x00000230  */
 union vdec_cs_chroma_intensity_buffer_0Reg vdec_cs_chroma_intensity_buffer_0; /* +0x00000234  */
 union vdec_cs_luma_intensity_buffer_1Reg vdec_cs_luma_intensity_buffer_1; /* +0x00000238  */
 union vdec_cs_chroma_intensity_buffer_1Reg vdec_cs_chroma_intensity_buffer_1; /* +0x0000023c  */
 union vdec_cs_luma_intensity_buffer_2Reg vdec_cs_luma_intensity_buffer_2; /* +0x00000240  */
 union vdec_cs_chroma_intensity_buffer_2Reg vdec_cs_chroma_intensity_buffer_2; /* +0x00000244  */
 union vdec_cs_luma_intensity_buffer_3Reg vdec_cs_luma_intensity_buffer_3; /* +0x00000248  */
 union vdec_cs_chroma_intensity_buffer_3Reg vdec_cs_chroma_intensity_buffer_3; /* +0x0000024c  */
 union vdec_cs_top_statusReg vdec_cs_top_status; /* +0x00000250  */
 union vdec_cs_bottom_statusReg vdec_cs_bottom_status; /* +0x00000254  */
 union vdec_cs_alpha_betaReg vdec_cs_alpha_beta; /* +0x00000258  */
 union vdec_cs_internal_intensity_edgeReg vdec_cs_internal_intensity_edge; /* +0x0000025c ,NO_TEST */
 union vdec_cs_idct_wait_predReg vdec_cs_idct_wait_pred; /* +0x00000260  */
 union vdec_cs_pred_wait_idctReg vdec_cs_pred_wait_idct; /* +0x00000264  */
 union vdec_cs_no_allocateReg vdec_cs_no_allocate; /* +0x00000268  */
};
