/* autogenerated with parsecfg: do not edit. */

union vi_crc32_0_cmdReg {
 struct { uint32_t

 /* sorting 2 */
#define vi_crc32_0_cmd_fifo_number_SHIFT 0
#define vi_crc32_0_cmd_fifo_number_WIDTH 5
#define vi_crc32_0_cmd_data_width_SHIFT 5
#define vi_crc32_0_cmd_data_width_WIDTH 2

 fifo_number:5, /*[4:0]  */
 data_width:2, /*[6:5]  */
 hole0:25;
 } bits;

 uint32_t value;
};

struct vi_crc32_spy {
 uint32_t vi_crc32_0_crc32; /* +0x00000000  */
 uint32_t vi_crc32_0_count; /* +0x00000004  */
 union vi_crc32_0_cmdReg vi_crc32_0_cmd; /* +0x00000008  */
 uint32_t vi_crc32_0_mask; /* +0x0000000c  */
};
