/* autogenerated with parsecfg: do not edit. */

union vi_misc_selectReg {
 struct { uint32_t

 /* sorting 1 */
#define vi_misc_select_vi_misc_select_loopback_SHIFT 0
#define vi_misc_select_vi_misc_select_loopback_WIDTH 1

 vi_misc_select_loopback:1, /*[0:0]  */
 hole0:31;
 } bits;

 uint32_t value;
};

union vi_misc_mbus_alphaReg {
 struct { uint32_t

 /* sorting 2 */
#define vi_misc_mbus_alpha__0_SHIFT 0
#define vi_misc_mbus_alpha__0_WIDTH 8
#define vi_misc_mbus_alpha__1_SHIFT 16
#define vi_misc_mbus_alpha__1_WIDTH 8

 _0:8, /*[7:0]  */
 hole0:8,
 _1:8, /*[23:16]  */
 hole1:8;
 } bits;

 uint32_t value;
};

struct vi_misc {
 uint32_t vi_misc_reset_run; /* +0x00000000  */
 uint32_t vi_misc_reset_datapath; /* +0x00000004  */
 uint32_t vi_misc_reset_timing; /* +0x00000008  */
 uint32_t vi_misc_reset_config; /* +0x0000000c  */
 uint32_t pad0[0x0004/4];
 uint32_t vi_misc_reset_mode_0; /* +0x00000014  */
 uint32_t vi_misc_reset_mode_1; /* +0x00000018  */
 uint32_t vi_misc_reset_mbus_flush; /* +0x0000001c  */
 uint32_t vi_misc_mbus_xbar_select; /* +0x00000020  */
 union vi_misc_selectReg vi_misc_select; /* +0x00000024  */
 union vi_misc_mbus_alphaReg vi_misc_mbus_alpha; /* +0x00000028  */
};
