/* autogenerated with parsecfg: do not edit. */

union vo_bus_resize_modeReg {
 struct { uint32_t

 /* sorting 1 */
#define vo_bus_resize_mode_vo_bus_resize_mode_select_30bits_SHIFT 0
#define vo_bus_resize_mode_vo_bus_resize_mode_select_30bits_WIDTH 1

 vo_bus_resize_mode_select_30bits:1, /*[0:0]  */
 hole0:31;
 } bits;

 uint32_t value;
};

struct vo_bus_resize {
 union vo_bus_resize_modeReg vo_bus_resize_mode; /* +0x00000000  */
};
