/* autogenerated with parsecfg: do not edit. */

union vo_crc32_3_cmdReg {
 struct { uint32_t

 /* sorting 2 */
#define vo_crc32_3_cmd_fifo_number_SHIFT 0
#define vo_crc32_3_cmd_fifo_number_WIDTH 5
#define vo_crc32_3_cmd_data_width_SHIFT 5
#define vo_crc32_3_cmd_data_width_WIDTH 2

 fifo_number:5, /*[4:0]  */
 data_width:2, /*[6:5]  */
 hole0:25;
 } bits;

 uint32_t value;
};

union vo_crc32_2_cmdReg {
 struct { uint32_t

 /* sorting 2 */
#define vo_crc32_2_cmd_fifo_number_SHIFT 0
#define vo_crc32_2_cmd_fifo_number_WIDTH 5
#define vo_crc32_2_cmd_data_width_SHIFT 5
#define vo_crc32_2_cmd_data_width_WIDTH 2

 fifo_number:5, /*[4:0]  */
 data_width:2, /*[6:5]  */
 hole0:25;
 } bits;

 uint32_t value;
};

union vo_crc32_1_cmdReg {
 struct { uint32_t

 /* sorting 2 */
#define vo_crc32_1_cmd_fifo_number_SHIFT 0
#define vo_crc32_1_cmd_fifo_number_WIDTH 5
#define vo_crc32_1_cmd_data_width_SHIFT 5
#define vo_crc32_1_cmd_data_width_WIDTH 2

 fifo_number:5, /*[4:0]  */
 data_width:2, /*[6:5]  */
 hole0:25;
 } bits;

 uint32_t value;
};

union vo_crc32_0_cmdReg {
 struct { uint32_t

 /* sorting 2 */
#define vo_crc32_0_cmd_fifo_number_SHIFT 0
#define vo_crc32_0_cmd_fifo_number_WIDTH 5
#define vo_crc32_0_cmd_data_width_SHIFT 5
#define vo_crc32_0_cmd_data_width_WIDTH 2

 fifo_number:5, /*[4:0]  */
 data_width:2, /*[6:5]  */
 hole0:25;
 } bits;

 uint32_t value;
};

struct vo_crc32_spy {
 uint32_t vo_crc32_0_crc32; /* +0x00000000  */
 uint32_t vo_crc32_0_count; /* +0x00000004  */
 union vo_crc32_0_cmdReg vo_crc32_0_cmd; /* +0x00000008  */
 uint32_t vo_crc32_0_mask; /* +0x0000000c  */
 uint32_t vo_crc32_1_crc32; /* +0x00000010  */
 uint32_t vo_crc32_1_count; /* +0x00000014  */
 union vo_crc32_1_cmdReg vo_crc32_1_cmd; /* +0x00000018  */
 uint32_t vo_crc32_1_mask; /* +0x0000001c  */
 uint32_t vo_crc32_2_crc32; /* +0x00000020  */
 uint32_t vo_crc32_2_count; /* +0x00000024  */
 union vo_crc32_2_cmdReg vo_crc32_2_cmd; /* +0x00000028  */
 uint32_t vo_crc32_2_mask; /* +0x0000002c  */
 uint32_t vo_crc32_3_crc32; /* +0x00000030  */
 uint32_t vo_crc32_3_count; /* +0x00000034  */
 union vo_crc32_3_cmdReg vo_crc32_3_cmd; /* +0x00000038  */
 uint32_t vo_crc32_3_mask; /* +0x0000003c  */
};
