/* autogenerated with parsecfg: do not edit. */

union vo_dma2lbusconv_configReg {
 struct { uint32_t

 /* sorting 3 */
#define vo_dma2lbusconv_config_id_SHIFT 0
#define vo_dma2lbusconv_config_id_WIDTH 8
#define vo_dma2lbusconv_config_status_SHIFT 24
#define vo_dma2lbusconv_config_status_WIDTH 7
#define vo_dma2lbusconv_config_work_in_progress_SHIFT 31
#define vo_dma2lbusconv_config_work_in_progress_WIDTH 1

 id:8, /*[7:0]  */
 hole0:16,
 status:7, /*[30:24]  */
 work_in_progress:1; /*[31:31]  */
 } bits;

 uint32_t value;
};

struct vo_dma_to_lbus_converter {
 union vo_dma2lbusconv_configReg vo_dma2lbusconv_config; /* +0x00000000  */
 uint32_t vo_dma2lbusconv_byte_count; /* +0x00000004  */
 uint32_t vo_dma2lbusconv_last_add; /* +0x00000008  */
 uint32_t vo_dma2lbusconv_last_data; /* +0x0000000c  */
};
