/* autogenerated with parsecfg: do not edit. */

union vo_hard_cursor_size_ctrlReg {
 struct { uint32_t

 /* sorting 4 */
#define vo_hard_cursor_size_ctrl_xsize_SHIFT 0
#define vo_hard_cursor_size_ctrl_xsize_WIDTH 8
#define vo_hard_cursor_size_ctrl_ysize_SHIFT 16
#define vo_hard_cursor_size_ctrl_ysize_WIDTH 8
#define vo_hard_cursor_size_ctrl_parity_SHIFT 30
#define vo_hard_cursor_size_ctrl_parity_WIDTH 1
#define vo_hard_cursor_size_ctrl_interlacement_SHIFT 31
#define vo_hard_cursor_size_ctrl_interlacement_WIDTH 1

 xsize:8, /*[7:0]  */
 hole0:8,
 ysize:8, /*[23:16]  */
 hole1:6,
 parity:1, /*[30:30]  */
 interlacement:1; /*[31:31]  */
 } bits;

 uint32_t value;
};

union vo_hard_cursor_lut9Reg {
 struct { uint32_t

 /* sorting 4 */
#define vo_hard_cursor_lut9_Cb9_SHIFT 0
#define vo_hard_cursor_lut9_Cb9_WIDTH 8
#define vo_hard_cursor_lut9_Y9_SHIFT 8
#define vo_hard_cursor_lut9_Y9_WIDTH 8
#define vo_hard_cursor_lut9_Cr9_SHIFT 16
#define vo_hard_cursor_lut9_Cr9_WIDTH 8
#define vo_hard_cursor_lut9_A9_SHIFT 24
#define vo_hard_cursor_lut9_A9_WIDTH 8

 cb9:8, /*[7:0]  */
 y9:8, /*[15:8]  */
 cr9:8, /*[23:16]  */
 a9:8; /*[31:24]  */
 } bits;

 uint32_t value;
};

union vo_hard_cursor_lut8Reg {
 struct { uint32_t

 /* sorting 4 */
#define vo_hard_cursor_lut8_Cb8_SHIFT 0
#define vo_hard_cursor_lut8_Cb8_WIDTH 8
#define vo_hard_cursor_lut8_Y8_SHIFT 8
#define vo_hard_cursor_lut8_Y8_WIDTH 8
#define vo_hard_cursor_lut8_Cr8_SHIFT 16
#define vo_hard_cursor_lut8_Cr8_WIDTH 8
#define vo_hard_cursor_lut8_A8_SHIFT 24
#define vo_hard_cursor_lut8_A8_WIDTH 8

 cb8:8, /*[7:0]  */
 y8:8, /*[15:8]  */
 cr8:8, /*[23:16]  */
 a8:8; /*[31:24]  */
 } bits;

 uint32_t value;
};

union vo_hard_cursor_lut7Reg {
 struct { uint32_t

 /* sorting 4 */
#define vo_hard_cursor_lut7_Cb7_SHIFT 0
#define vo_hard_cursor_lut7_Cb7_WIDTH 8
#define vo_hard_cursor_lut7_Y7_SHIFT 8
#define vo_hard_cursor_lut7_Y7_WIDTH 8
#define vo_hard_cursor_lut7_Cr7_SHIFT 16
#define vo_hard_cursor_lut7_Cr7_WIDTH 8
#define vo_hard_cursor_lut7_A7_SHIFT 24
#define vo_hard_cursor_lut7_A7_WIDTH 8

 cb7:8, /*[7:0]  */
 y7:8, /*[15:8]  */
 cr7:8, /*[23:16]  */
 a7:8; /*[31:24]  */
 } bits;

 uint32_t value;
};

union vo_hard_cursor_lut6Reg {
 struct { uint32_t

 /* sorting 4 */
#define vo_hard_cursor_lut6_Cb6_SHIFT 0
#define vo_hard_cursor_lut6_Cb6_WIDTH 8
#define vo_hard_cursor_lut6_Y6_SHIFT 8
#define vo_hard_cursor_lut6_Y6_WIDTH 8
#define vo_hard_cursor_lut6_Cr6_SHIFT 16
#define vo_hard_cursor_lut6_Cr6_WIDTH 8
#define vo_hard_cursor_lut6_A6_SHIFT 24
#define vo_hard_cursor_lut6_A6_WIDTH 8

 cb6:8, /*[7:0]  */
 y6:8, /*[15:8]  */
 cr6:8, /*[23:16]  */
 a6:8; /*[31:24]  */
 } bits;

 uint32_t value;
};

union vo_hard_cursor_lut5Reg {
 struct { uint32_t

 /* sorting 4 */
#define vo_hard_cursor_lut5_Cb5_SHIFT 0
#define vo_hard_cursor_lut5_Cb5_WIDTH 8
#define vo_hard_cursor_lut5_Y5_SHIFT 8
#define vo_hard_cursor_lut5_Y5_WIDTH 8
#define vo_hard_cursor_lut5_Cr5_SHIFT 16
#define vo_hard_cursor_lut5_Cr5_WIDTH 8
#define vo_hard_cursor_lut5_A5_SHIFT 24
#define vo_hard_cursor_lut5_A5_WIDTH 8

 cb5:8, /*[7:0]  */
 y5:8, /*[15:8]  */
 cr5:8, /*[23:16]  */
 a5:8; /*[31:24]  */
 } bits;

 uint32_t value;
};

union vo_hard_cursor_lut4Reg {
 struct { uint32_t

 /* sorting 4 */
#define vo_hard_cursor_lut4_Cb4_SHIFT 0
#define vo_hard_cursor_lut4_Cb4_WIDTH 8
#define vo_hard_cursor_lut4_Y4_SHIFT 8
#define vo_hard_cursor_lut4_Y4_WIDTH 8
#define vo_hard_cursor_lut4_Cr4_SHIFT 16
#define vo_hard_cursor_lut4_Cr4_WIDTH 8
#define vo_hard_cursor_lut4_A4_SHIFT 24
#define vo_hard_cursor_lut4_A4_WIDTH 8

 cb4:8, /*[7:0]  */
 y4:8, /*[15:8]  */
 cr4:8, /*[23:16]  */
 a4:8; /*[31:24]  */
 } bits;

 uint32_t value;
};

union vo_hard_cursor_lut3Reg {
 struct { uint32_t

 /* sorting 4 */
#define vo_hard_cursor_lut3_Cb3_SHIFT 0
#define vo_hard_cursor_lut3_Cb3_WIDTH 8
#define vo_hard_cursor_lut3_Y3_SHIFT 8
#define vo_hard_cursor_lut3_Y3_WIDTH 8
#define vo_hard_cursor_lut3_Cr3_SHIFT 16
#define vo_hard_cursor_lut3_Cr3_WIDTH 8
#define vo_hard_cursor_lut3_A3_SHIFT 24
#define vo_hard_cursor_lut3_A3_WIDTH 8

 cb3:8, /*[7:0]  */
 y3:8, /*[15:8]  */
 cr3:8, /*[23:16]  */
 a3:8; /*[31:24]  */
 } bits;

 uint32_t value;
};

union vo_hard_cursor_lut2Reg {
 struct { uint32_t

 /* sorting 4 */
#define vo_hard_cursor_lut2_Cb2_SHIFT 0
#define vo_hard_cursor_lut2_Cb2_WIDTH 8
#define vo_hard_cursor_lut2_Y2_SHIFT 8
#define vo_hard_cursor_lut2_Y2_WIDTH 8
#define vo_hard_cursor_lut2_Cr2_SHIFT 16
#define vo_hard_cursor_lut2_Cr2_WIDTH 8
#define vo_hard_cursor_lut2_A2_SHIFT 24
#define vo_hard_cursor_lut2_A2_WIDTH 8

 cb2:8, /*[7:0]  */
 y2:8, /*[15:8]  */
 cr2:8, /*[23:16]  */
 a2:8; /*[31:24]  */
 } bits;

 uint32_t value;
};

union vo_hard_cursor_lut15Reg {
 struct { uint32_t

 /* sorting 4 */
#define vo_hard_cursor_lut15_Cb15_SHIFT 0
#define vo_hard_cursor_lut15_Cb15_WIDTH 8
#define vo_hard_cursor_lut15_Y15_SHIFT 8
#define vo_hard_cursor_lut15_Y15_WIDTH 8
#define vo_hard_cursor_lut15_Cr15_SHIFT 16
#define vo_hard_cursor_lut15_Cr15_WIDTH 8
#define vo_hard_cursor_lut15_A15_SHIFT 24
#define vo_hard_cursor_lut15_A15_WIDTH 8

 cb15:8, /*[7:0]  */
 y15:8, /*[15:8]  */
 cr15:8, /*[23:16]  */
 a15:8; /*[31:24]  */
 } bits;

 uint32_t value;
};

union vo_hard_cursor_lut14Reg {
 struct { uint32_t

 /* sorting 4 */
#define vo_hard_cursor_lut14_Cb14_SHIFT 0
#define vo_hard_cursor_lut14_Cb14_WIDTH 8
#define vo_hard_cursor_lut14_Y14_SHIFT 8
#define vo_hard_cursor_lut14_Y14_WIDTH 8
#define vo_hard_cursor_lut14_Cr14_SHIFT 16
#define vo_hard_cursor_lut14_Cr14_WIDTH 8
#define vo_hard_cursor_lut14_A14_SHIFT 24
#define vo_hard_cursor_lut14_A14_WIDTH 8

 cb14:8, /*[7:0]  */
 y14:8, /*[15:8]  */
 cr14:8, /*[23:16]  */
 a14:8; /*[31:24]  */
 } bits;

 uint32_t value;
};

union vo_hard_cursor_lut13Reg {
 struct { uint32_t

 /* sorting 4 */
#define vo_hard_cursor_lut13_Cb13_SHIFT 0
#define vo_hard_cursor_lut13_Cb13_WIDTH 8
#define vo_hard_cursor_lut13_Y13_SHIFT 8
#define vo_hard_cursor_lut13_Y13_WIDTH 8
#define vo_hard_cursor_lut13_Cr13_SHIFT 16
#define vo_hard_cursor_lut13_Cr13_WIDTH 8
#define vo_hard_cursor_lut13_A13_SHIFT 24
#define vo_hard_cursor_lut13_A13_WIDTH 8

 cb13:8, /*[7:0]  */
 y13:8, /*[15:8]  */
 cr13:8, /*[23:16]  */
 a13:8; /*[31:24]  */
 } bits;

 uint32_t value;
};

union vo_hard_cursor_lut12Reg {
 struct { uint32_t

 /* sorting 4 */
#define vo_hard_cursor_lut12_Cb12_SHIFT 0
#define vo_hard_cursor_lut12_Cb12_WIDTH 8
#define vo_hard_cursor_lut12_Y12_SHIFT 8
#define vo_hard_cursor_lut12_Y12_WIDTH 8
#define vo_hard_cursor_lut12_Cr12_SHIFT 16
#define vo_hard_cursor_lut12_Cr12_WIDTH 8
#define vo_hard_cursor_lut12_A12_SHIFT 24
#define vo_hard_cursor_lut12_A12_WIDTH 8

 cb12:8, /*[7:0]  */
 y12:8, /*[15:8]  */
 cr12:8, /*[23:16]  */
 a12:8; /*[31:24]  */
 } bits;

 uint32_t value;
};

union vo_hard_cursor_lut11Reg {
 struct { uint32_t

 /* sorting 4 */
#define vo_hard_cursor_lut11_Cb11_SHIFT 0
#define vo_hard_cursor_lut11_Cb11_WIDTH 8
#define vo_hard_cursor_lut11_Y11_SHIFT 8
#define vo_hard_cursor_lut11_Y11_WIDTH 8
#define vo_hard_cursor_lut11_Cr11_SHIFT 16
#define vo_hard_cursor_lut11_Cr11_WIDTH 8
#define vo_hard_cursor_lut11_A11_SHIFT 24
#define vo_hard_cursor_lut11_A11_WIDTH 8

 cb11:8, /*[7:0]  */
 y11:8, /*[15:8]  */
 cr11:8, /*[23:16]  */
 a11:8; /*[31:24]  */
 } bits;

 uint32_t value;
};

union vo_hard_cursor_lut10Reg {
 struct { uint32_t

 /* sorting 4 */
#define vo_hard_cursor_lut10_Cb10_SHIFT 0
#define vo_hard_cursor_lut10_Cb10_WIDTH 8
#define vo_hard_cursor_lut10_Y10_SHIFT 8
#define vo_hard_cursor_lut10_Y10_WIDTH 8
#define vo_hard_cursor_lut10_Cr10_SHIFT 16
#define vo_hard_cursor_lut10_Cr10_WIDTH 8
#define vo_hard_cursor_lut10_A10_SHIFT 24
#define vo_hard_cursor_lut10_A10_WIDTH 8

 cb10:8, /*[7:0]  */
 y10:8, /*[15:8]  */
 cr10:8, /*[23:16]  */
 a10:8; /*[31:24]  */
 } bits;

 uint32_t value;
};

union vo_hard_cursor_lut1Reg {
 struct { uint32_t

 /* sorting 4 */
#define vo_hard_cursor_lut1_Cb1_SHIFT 0
#define vo_hard_cursor_lut1_Cb1_WIDTH 8
#define vo_hard_cursor_lut1_Y1_SHIFT 8
#define vo_hard_cursor_lut1_Y1_WIDTH 8
#define vo_hard_cursor_lut1_Cr1_SHIFT 16
#define vo_hard_cursor_lut1_Cr1_WIDTH 8
#define vo_hard_cursor_lut1_A1_SHIFT 24
#define vo_hard_cursor_lut1_A1_WIDTH 8

 cb1:8, /*[7:0]  */
 y1:8, /*[15:8]  */
 cr1:8, /*[23:16]  */
 a1:8; /*[31:24]  */
 } bits;

 uint32_t value;
};

union vo_hard_cursor_lut0Reg {
 struct { uint32_t

 /* sorting 4 */
#define vo_hard_cursor_lut0_Cb0_SHIFT 0
#define vo_hard_cursor_lut0_Cb0_WIDTH 8
#define vo_hard_cursor_lut0_Y0_SHIFT 8
#define vo_hard_cursor_lut0_Y0_WIDTH 8
#define vo_hard_cursor_lut0_Cr0_SHIFT 16
#define vo_hard_cursor_lut0_Cr0_WIDTH 8
#define vo_hard_cursor_lut0_A0_SHIFT 24
#define vo_hard_cursor_lut0_A0_WIDTH 8

 cb0:8, /*[7:0]  */
 y0:8, /*[15:8]  */
 cr0:8, /*[23:16]  */
 a0:8; /*[31:24]  */
 } bits;

 uint32_t value;
};

struct vo_hard_cursor {
 union vo_hard_cursor_size_ctrlReg vo_hard_cursor_size_ctrl; /* +0x00000000  */
 uint32_t pad0[0x003c/4];
 union vo_hard_cursor_lut0Reg vo_hard_cursor_lut0; /* +0x00000040  */
 union vo_hard_cursor_lut1Reg vo_hard_cursor_lut1; /* +0x00000044  */
 union vo_hard_cursor_lut2Reg vo_hard_cursor_lut2; /* +0x00000048  */
 union vo_hard_cursor_lut3Reg vo_hard_cursor_lut3; /* +0x0000004c  */
 union vo_hard_cursor_lut4Reg vo_hard_cursor_lut4; /* +0x00000050  */
 union vo_hard_cursor_lut5Reg vo_hard_cursor_lut5; /* +0x00000054  */
 union vo_hard_cursor_lut6Reg vo_hard_cursor_lut6; /* +0x00000058  */
 union vo_hard_cursor_lut7Reg vo_hard_cursor_lut7; /* +0x0000005c  */
 union vo_hard_cursor_lut8Reg vo_hard_cursor_lut8; /* +0x00000060  */
 union vo_hard_cursor_lut9Reg vo_hard_cursor_lut9; /* +0x00000064  */
 union vo_hard_cursor_lut10Reg vo_hard_cursor_lut10; /* +0x00000068  */
 union vo_hard_cursor_lut11Reg vo_hard_cursor_lut11; /* +0x0000006c  */
 union vo_hard_cursor_lut12Reg vo_hard_cursor_lut12; /* +0x00000070  */
 union vo_hard_cursor_lut13Reg vo_hard_cursor_lut13; /* +0x00000074  */
 union vo_hard_cursor_lut14Reg vo_hard_cursor_lut14; /* +0x00000078  */
 union vo_hard_cursor_lut15Reg vo_hard_cursor_lut15; /* +0x0000007c  */
};
