/* autogenerated with parsecfg: do not edit. */

union vo_deint_multi_scaler_scale_factorReg {
 struct { uint32_t

 /* sorting 2 */
#define vo_deint_multi_scaler_scale_factor_x_scale_factor_SHIFT 0
#define vo_deint_multi_scaler_scale_factor_x_scale_factor_WIDTH 14
#define vo_deint_multi_scaler_scale_factor_y_scale_factor_SHIFT 16
#define vo_deint_multi_scaler_scale_factor_y_scale_factor_WIDTH 14

 x_scale_factor:14, /*[13:0]  */
 hole0:2,
 y_scale_factor:14, /*[29:16]  */
 hole1:2;
 } bits;

 uint32_t value;
};

union vo_deint_multi_scaler_phaseReg {
 struct { uint32_t

 /* sorting 4 */
#define vo_deint_multi_scaler_phase_lumax_SHIFT 0
#define vo_deint_multi_scaler_phase_lumax_WIDTH 5
#define vo_deint_multi_scaler_phase_chromax_SHIFT 8
#define vo_deint_multi_scaler_phase_chromax_WIDTH 5
#define vo_deint_multi_scaler_phase_lumay_SHIFT 16
#define vo_deint_multi_scaler_phase_lumay_WIDTH 5
#define vo_deint_multi_scaler_phase_chromay_SHIFT 24
#define vo_deint_multi_scaler_phase_chromay_WIDTH 5

 lumax:5, /*[4:0]  */
 hole0:3,
 chromax:5, /*[12:8]  */
 hole1:3,
 lumay:5, /*[20:16]  */
 hole2:3,
 chromay:5, /*[28:24]  */
 hole3:3;
 } bits;

 uint32_t value;
};

union vo_deint_multi_scaler_output_sizeReg {
 struct { uint32_t

 /* sorting 2 */
#define vo_deint_multi_scaler_output_size_xsize_SHIFT 0
#define vo_deint_multi_scaler_output_size_xsize_WIDTH 12
#define vo_deint_multi_scaler_output_size_ysize_SHIFT 16
#define vo_deint_multi_scaler_output_size_ysize_WIDTH 12

 xsize:12, /*[11:0]  */
 hole0:4,
 ysize:12, /*[27:16]  */
 hole1:4;
 } bits;

 uint32_t value;
};

union vo_deint_multi_scaler_formatReg {
 struct { uint32_t

 /* sorting 3 */
#define vo_deint_multi_scaler_format_sub_mode_SHIFT 0
#define vo_deint_multi_scaler_format_sub_mode_WIDTH 2
#define vo_deint_multi_scaler_format_c_SHIFT 4
#define vo_deint_multi_scaler_format_c_WIDTH 2
#define vo_deint_multi_scaler_format_ffl_SHIFT 8
#define vo_deint_multi_scaler_format_ffl_WIDTH 1

 sub_mode:2, /*[1:0]  */
 hole0:2,
 c:2, /*[5:4]  */
 hole1:2,
 ffl:1, /*[8:8]  */
 hole2:23;
 } bits;

 uint32_t value;
};

union vo_deint_multi_scaler_edgeReg {
 struct { uint32_t

 /* sorting 5 */
#define vo_deint_multi_scaler_edge_check_SHIFT 0
#define vo_deint_multi_scaler_edge_check_WIDTH 4
#define vo_deint_multi_scaler_edge_rf_SHIFT 7
#define vo_deint_multi_scaler_edge_rf_WIDTH 1
#define vo_deint_multi_scaler_edge_w0_SHIFT 8
#define vo_deint_multi_scaler_edge_w0_WIDTH 3
#define vo_deint_multi_scaler_edge_w1_SHIFT 12
#define vo_deint_multi_scaler_edge_w1_WIDTH 2
#define vo_deint_multi_scaler_edge_ae_SHIFT 18
#define vo_deint_multi_scaler_edge_ae_WIDTH 1

 check:4, /*[3:0]  */
 hole0:3,
 rf:1, /*[7:7]  */
 w0:3, /*[10:8]  */
 hole1:1,
 w1:2, /*[13:12]  */
 hole2:4,
 ae:1, /*[18:18]  */
 hole3:13;
 } bits;

 uint32_t value;
};

union vo_deint_multi_scaler_chroma_scale_factorReg {
 struct { uint32_t

 /* sorting 3 */
#define vo_deint_multi_scaler_chroma_scale_factor_hroma_x_scale_factor_SHIFT 0
#define vo_deint_multi_scaler_chroma_scale_factor_hroma_x_scale_factor_WIDTH 14
#define vo_deint_multi_scaler_chroma_scale_factor_hroma_y_scale_factor_SHIFT 16
#define vo_deint_multi_scaler_chroma_scale_factor_hroma_y_scale_factor_WIDTH 14
#define vo_deint_multi_scaler_chroma_scale_factor_se_SHIFT 31
#define vo_deint_multi_scaler_chroma_scale_factor_se_WIDTH 1

 hroma_x_scale_factor:14, /*[13:0]  */
 hole0:2,
 hroma_y_scale_factor:14, /*[29:16]  */
 hole1:1,
 se:1; /*[31:31]  */
 } bits;

 uint32_t value;
};

struct vo_multi_scaler {
 union vo_deint_multi_scaler_formatReg vo_deint_multi_scaler_format; /* +0x00000000  */
 union vo_deint_multi_scaler_output_sizeReg vo_deint_multi_scaler_output_size; /* +0x00000004  */
 union vo_deint_multi_scaler_scale_factorReg vo_deint_multi_scaler_scale_factor; /* +0x00000008  */
 union vo_deint_multi_scaler_phaseReg vo_deint_multi_scaler_phase; /* +0x0000000c  */
 union vo_deint_multi_scaler_edgeReg vo_deint_multi_scaler_edge; /* +0x00000010  */
 union vo_deint_multi_scaler_chroma_scale_factorReg vo_deint_multi_scaler_chroma_scale_factor; /* +0x00000014  */
};
