/* autogenerated with parsecfg: do not edit. */

union vo_post_process_sizeReg {
 struct { uint32_t

 /* sorting 2 */
#define vo_post_process_size_xsize_SHIFT 0
#define vo_post_process_size_xsize_WIDTH 12
#define vo_post_process_size_ysize_SHIFT 16
#define vo_post_process_size_ysize_WIDTH 11

 xsize:12, /*[11:0]  */
 hole0:4,
 ysize:11, /*[26:16]  */
 hole1:5;
 } bits;

 uint32_t value;
};

union vo_post_process_parameterReg {
 struct { uint32_t

 /* sorting 5 */
#define vo_post_process_parameter_quantizer_SHIFT 0
#define vo_post_process_parameter_quantizer_WIDTH 12
#define vo_post_process_parameter_interleaved_SHIFT 16
#define vo_post_process_parameter_interleaved_WIDTH 1
#define vo_post_process_parameter_quantizer_dram_SHIFT 17
#define vo_post_process_parameter_quantizer_dram_WIDTH 1
#define vo_post_process_parameter_microsoft_bug_SHIFT 18
#define vo_post_process_parameter_microsoft_bug_WIDTH 1
#define vo_post_process_parameter_disable_deringing_SHIFT 19
#define vo_post_process_parameter_disable_deringing_WIDTH 1

 quantizer:12, /*[11:0]  */
 hole0:4,
 interleaved:1, /*[16:16]  */
 quantizer_dram:1, /*[17:17]  */
 microsoft_bug:1, /*[18:18]  */
 disable_deringing:1, /*[19:19]  */
 hole1:12;
 } bits;

 uint32_t value;
};

struct vo_post_process {
 union vo_post_process_sizeReg vo_post_process_size; /* +0x00000000  */
 union vo_post_process_parameterReg vo_post_process_parameter; /* +0x00000004  */
};
