/* autogenerated with parsecfg: do not edit. */

union vo_slihdmi13t_video_setting2Reg {
 struct { uint32_t

 /* sorting 2 */
#define vo_slihdmi13t_video_setting2_set_SHIFT 6
#define vo_slihdmi13t_video_setting2_set_WIDTH 1
#define vo_slihdmi13t_video_setting2_clear_SHIFT 7
#define vo_slihdmi13t_video_setting2_clear_WIDTH 1

 hole0:6,
 set:1, /*[6:6]  */
 clear:1, /*[7:7]  */
 hole1:24;
 } bits;

 uint32_t value;
};

union vo_slihdmi13t_video_setting1Reg {
 struct { uint32_t

 /* sorting 3 */
#define vo_slihdmi13t_video_setting1_in_colorspace_SHIFT 0
#define vo_slihdmi13t_video_setting1_in_colorspace_WIDTH 1
#define vo_slihdmi13t_video_setting1_in_wdith_SHIFT 4
#define vo_slihdmi13t_video_setting1_in_wdith_WIDTH 2
#define vo_slihdmi13t_video_setting1_out_format_SHIFT 6
#define vo_slihdmi13t_video_setting1_out_format_WIDTH 2

 in_colorspace:1, /*[0:0]  */
 hole0:3,
 in_wdith:2, /*[5:4]  */
 out_format:2, /*[7:6]  */
 hole1:24;
 } bits;

 uint32_t value;
};

union vo_slihdmi13t_source_number_and_audio_word_lengthReg {
 struct { uint32_t

 /* sorting 2 */
#define vo_slihdmi13t_source_number_and_audio_word_length_audio_word_length_SHIFT 0
#define vo_slihdmi13t_source_number_and_audio_word_length_audio_word_length_WIDTH 4
#define vo_slihdmi13t_source_number_and_audio_word_length_source_number_SHIFT 4
#define vo_slihdmi13t_source_number_and_audio_word_length_source_number_WIDTH 4

 audio_word_length:4, /*[3:0]  */
 source_number:4, /*[7:4]  */
 hole0:24;
 } bits;

 uint32_t value;
};

union vo_slihdmi13t_i2s_audio_settingReg {
 struct { uint32_t

 /* sorting 2 */
#define vo_slihdmi13t_i2s_audio_setting_audio_mode_SHIFT 0
#define vo_slihdmi13t_i2s_audio_setting_audio_mode_WIDTH 2
#define vo_slihdmi13t_i2s_audio_setting_pin_enable_SHIFT 2
#define vo_slihdmi13t_i2s_audio_setting_pin_enable_WIDTH 4

 audio_mode:2, /*[1:0]  */
 pin_enable:4, /*[5:2]  */
 hole0:26;
 } bits;

 uint32_t value;
};

union vo_slihdmi13t_hdcp_controlReg {
 struct { uint32_t

 /* sorting 1 */
#define vo_slihdmi13t_hdcp_control_vo_slihdmi13t_hdcp_hdmi_mode_SHIFT 1
#define vo_slihdmi13t_hdcp_control_vo_slihdmi13t_hdcp_hdmi_mode_WIDTH 1

 hole0:1,
 vo_slihdmi13t_hdcp_hdmi_mode:1, /*[1:1]  */
 hole1:30;
 } bits;

 uint32_t value;
};

union vo_slihdmi13t_external_video_parameter_settingsReg {
 struct { uint32_t

 /* sorting 5 */
#define vo_slihdmi13t_external_video_parameter_settings_enable_SHIFT 0
#define vo_slihdmi13t_external_video_parameter_settings_enable_WIDTH 1
#define vo_slihdmi13t_external_video_parameter_settings_progressive_SHIFT 1
#define vo_slihdmi13t_external_video_parameter_settings_progressive_WIDTH 1
#define vo_slihdmi13t_external_video_parameter_settings_hsync_pol_SHIFT 2
#define vo_slihdmi13t_external_video_parameter_settings_hsync_pol_WIDTH 1
#define vo_slihdmi13t_external_video_parameter_settings_vsync_pol_SHIFT 3
#define vo_slihdmi13t_external_video_parameter_settings_vsync_pol_WIDTH 1
#define vo_slihdmi13t_external_video_parameter_settings_vsync_offset_SHIFT 4
#define vo_slihdmi13t_external_video_parameter_settings_vsync_offset_WIDTH 4

 enable:1, /*[0:0]  */
 progressive:1, /*[1:1]  */
 hsync_pol:1, /*[2:2]  */
 vsync_pol:1, /*[3:3]  */
 vsync_offset:4, /*[7:4]  */
 hole0:24;
 } bits;

 uint32_t value;
};

union vo_slihdmi13t_deep_color_modesReg {
 struct { uint32_t

 /* sorting 1 */
#define vo_slihdmi13t_deep_color_modes_vo_slihdmi13t_tdms_speed_select_SHIFT 6
#define vo_slihdmi13t_deep_color_modes_vo_slihdmi13t_tdms_speed_select_WIDTH 2

 hole0:6,
 vo_slihdmi13t_tdms_speed_select:2, /*[7:6]  */
 hole1:24;
 } bits;

 uint32_t value;
};

union vo_slihdmi13t_data_swap_control_and_20bit_audio_clockReg {
 struct { uint32_t

 /* sorting 2 */
#define vo_slihdmi13t_data_swap_control_and_20bit_audio_clock__20bit_audio_clock_regeneration_packet_msb_SHIFT 0
#define vo_slihdmi13t_data_swap_control_and_20bit_audio_clock__20bit_audio_clock_regeneration_packet_msb_WIDTH 4
#define vo_slihdmi13t_data_swap_control_and_20bit_audio_clock__data_swap_control_SHIFT 4
#define vo_slihdmi13t_data_swap_control_and_20bit_audio_clock__data_swap_control_WIDTH 4

 _20bit_audio_clock_regeneration_packet_msb:4, /*[3:0]  */
 _data_swap_control:4, /*[7:4]  */
 hole0:24;
 } bits;

 uint32_t value;
};

union vo_slihdmi13t_audio_status_bits_setting2Reg {
 struct { uint32_t

 /* sorting 5 */
#define vo_slihdmi13t_audio_status_bits_setting2_clock_accuracy_SHIFT 0
#define vo_slihdmi13t_audio_status_bits_setting2_clock_accuracy_WIDTH 2
#define vo_slihdmi13t_audio_status_bits_setting2_add_info_SHIFT 2
#define vo_slihdmi13t_audio_status_bits_setting2_add_info_WIDTH 3
#define vo_slihdmi13t_audio_status_bits_setting2_copyright_SHIFT 5
#define vo_slihdmi13t_audio_status_bits_setting2_copyright_WIDTH 1
#define vo_slihdmi13t_audio_status_bits_setting2_cs0_SHIFT 6
#define vo_slihdmi13t_audio_status_bits_setting2_cs0_WIDTH 1
#define vo_slihdmi13t_audio_status_bits_setting2_cs1_SHIFT 7
#define vo_slihdmi13t_audio_status_bits_setting2_cs1_WIDTH 1

 clock_accuracy:2, /*[1:0]  */
 add_info:3, /*[4:2]  */
 copyright:1, /*[5:5]  */
 cs0:1, /*[6:6]  */
 cs1:1, /*[7:7]  */
 hole0:24;
 } bits;

 uint32_t value;
};

union vo_slihdmi13t_audio_status_bits_setting1Reg {
 struct { uint32_t

 /* sorting 1 */
#define vo_slihdmi13t_audio_status_bits_setting1_vo_slihdmi13t_audio_status_original_sampling_freq_SHIFT 0
#define vo_slihdmi13t_audio_status_bits_setting1_vo_slihdmi13t_audio_status_original_sampling_freq_WIDTH 4

 vo_slihdmi13t_audio_status_original_sampling_freq:4, /*[3:0]  */
 hole0:28;
 } bits;

 uint32_t value;
};

union vo_slihdmi13t_audio_setting2Reg {
 struct { uint32_t

 /* sorting 3 */
#define vo_slihdmi13t_audio_setting2_channel_number_SHIFT 0
#define vo_slihdmi13t_audio_setting2_channel_number_WIDTH 4
#define vo_slihdmi13t_audio_setting2_internal_audio_clock_select_SHIFT 5
#define vo_slihdmi13t_audio_setting2_internal_audio_clock_select_WIDTH 1
#define vo_slihdmi13t_audio_setting2_acr_asp_priority_select_SHIFT 6
#define vo_slihdmi13t_audio_setting2_acr_asp_priority_select_WIDTH 1

 channel_number:4, /*[3:0]  */
 hole0:1,
 internal_audio_clock_select:1, /*[5:5]  */
 acr_asp_priority_select:1, /*[6:6]  */
 hole1:25;
 } bits;

 uint32_t value;
};

union vo_slihdmi13t_audio_setting1Reg {
 struct { uint32_t

 /* sorting 3 */
#define vo_slihdmi13t_audio_setting1_type_SHIFT 3
#define vo_slihdmi13t_audio_setting1_type_WIDTH 2
#define vo_slihdmi13t_audio_setting1_down_sampling_ratio_SHIFT 5
#define vo_slihdmi13t_audio_setting1_down_sampling_ratio_WIDTH 2
#define vo_slihdmi13t_audio_setting1_cts_source_SHIFT 7
#define vo_slihdmi13t_audio_setting1_cts_source_WIDTH 1

 hole0:3,
 type:2, /*[4:3]  */
 down_sampling_ratio:2, /*[6:5]  */
 cts_source:1, /*[7:7]  */
 hole1:24;
 } bits;

 uint32_t value;
};

union vo_slihdmi13t_audio_and_video_setting1Reg {
 struct { uint32_t

 /* sorting 3 */
#define vo_slihdmi13t_audio_and_video_setting1_video_de_select_SHIFT 0
#define vo_slihdmi13t_audio_and_video_setting1_video_de_select_WIDTH 1
#define vo_slihdmi13t_audio_and_video_setting1_video_in_format_SHIFT 1
#define vo_slihdmi13t_audio_and_video_setting1_video_in_format_WIDTH 3
#define vo_slihdmi13t_audio_and_video_setting1_audio_sample_freq_SHIFT 4
#define vo_slihdmi13t_audio_and_video_setting1_audio_sample_freq_WIDTH 4

 video_de_select:1, /*[0:0]  */
 video_in_format:3, /*[3:1]  */
 audio_sample_freq:4, /*[7:4]  */
 hole0:24;
 } bits;

 uint32_t value;
};

struct vo_slishdmi13t {
 uint32_t vo_slihdmi13t_system_control; /* +0x00000000  */
 union vo_slihdmi13t_data_swap_control_and_20bit_audio_clockReg vo_slihdmi13t_data_swap_control_and_20bit_audio_clock; /* +0x00000004  */
 uint32_t vo_slihdmi13t_20bit_audio_clock_regeneration_packet0; /* +0x00000008  */
 uint32_t vo_slihdmi13t_20bit_audio_clock_regeneration_packet1; /* +0x0000000c  */
 uint32_t vo_slihdmi13t_spdif_audio_sampling_frequency_and_internal_cts; /* +0x00000010  */
 uint32_t vo_slihdmi13t_internal_cts0; /* +0x00000014  */
 uint32_t vo_slihdmi13t_internal_cts1; /* +0x00000018  */
 uint32_t vo_slihdmi13t_external_cts0; /* +0x0000001c  */
 uint32_t vo_slihdmi13t_external_cts1; /* +0x00000020  */
 uint32_t vo_slihdmi13t_external_cts2; /* +0x00000024  */
 union vo_slihdmi13t_audio_setting1Reg vo_slihdmi13t_audio_setting1; /* +0x00000028  */
 union vo_slihdmi13t_audio_setting2Reg vo_slihdmi13t_audio_setting2; /* +0x0000002c  */
 union vo_slihdmi13t_i2s_audio_settingReg vo_slihdmi13t_i2s_audio_setting; /* +0x00000030  */
 uint32_t vo_slihdmi13t_dsd_audio_setting; /* +0x00000034  */
 uint32_t vo_slihdmi13t_debug_monitor1; /* +0x00000038  */
 uint32_t vo_slihdmi13t_debug_monitor2; /* +0x0000003c  */
 uint32_t vo_slihdmi13t_i2s_input_pin_swap; /* +0x00000040  */
 union vo_slihdmi13t_audio_status_bits_setting1Reg vo_slihdmi13t_audio_status_bits_setting1; /* +0x00000044  */
 union vo_slihdmi13t_audio_status_bits_setting2Reg vo_slihdmi13t_audio_status_bits_setting2; /* +0x00000048  */
 uint32_t vo_slihdmi13t_category_code; /* +0x0000004c  */
 union vo_slihdmi13t_source_number_and_audio_word_lengthReg vo_slihdmi13t_source_number_and_audio_word_length; /* +0x00000050  */
 union vo_slihdmi13t_audio_and_video_setting1Reg vo_slihdmi13t_audio_and_video_setting1; /* +0x00000054  */
 union vo_slihdmi13t_video_setting1Reg vo_slihdmi13t_video_setting1; /* +0x00000058  */
 union vo_slihdmi13t_deep_color_modesReg vo_slihdmi13t_deep_color_modes; /* +0x0000005c  */
 uint32_t vo_slihdmi13t_color_space_conversion_parameters00; /* +0x00000060  */
 uint32_t vo_slihdmi13t_color_space_conversion_parameters01; /* +0x00000064  */
 uint32_t vo_slihdmi13t_color_space_conversion_parameters02; /* +0x00000068  */
 uint32_t vo_slihdmi13t_color_space_conversion_parameters03; /* +0x0000006c  */
 uint32_t vo_slihdmi13t_color_space_conversion_parameters04; /* +0x00000070  */
 uint32_t vo_slihdmi13t_color_space_conversion_parameters05; /* +0x00000074  */
 uint32_t vo_slihdmi13t_color_space_conversion_parameters06; /* +0x00000078  */
 uint32_t vo_slihdmi13t_color_space_conversion_parameters07; /* +0x0000007c  */
 uint32_t vo_slihdmi13t_color_space_conversion_parameters08; /* +0x00000080  */
 uint32_t vo_slihdmi13t_color_space_conversion_parameters09; /* +0x00000084  */
 uint32_t vo_slihdmi13t_color_space_conversion_parameters10; /* +0x00000088  */
 uint32_t vo_slihdmi13t_color_space_conversion_parameters11; /* +0x0000008c  */
 uint32_t vo_slihdmi13t_color_space_conversion_parameters12; /* +0x00000090  */
 uint32_t vo_slihdmi13t_color_space_conversion_parameters13; /* +0x00000094  */
 uint32_t vo_slihdmi13t_color_space_conversion_parameters14; /* +0x00000098  */
 uint32_t vo_slihdmi13t_color_space_conversion_parameters15; /* +0x0000009c  */
 uint32_t vo_slihdmi13t_color_space_conversion_parameters16; /* +0x000000a0  */
 uint32_t vo_slihdmi13t_color_space_conversion_parameters17; /* +0x000000a4  */
 uint32_t vo_slihdmi13t_color_space_conversion_parameters18; /* +0x000000a8  */
 uint32_t vo_slihdmi13t_color_space_conversion_parameters19; /* +0x000000ac  */
 uint32_t vo_slihdmi13t_color_space_conversion_parameters20; /* +0x000000b0  */
 uint32_t vo_slihdmi13t_color_space_conversion_parameters21; /* +0x000000b4  */
 uint32_t vo_slihdmi13t_color_space_conversion_parameters22; /* +0x000000b8  */
 uint32_t vo_slihdmi13t_color_space_conversion_parameters23; /* +0x000000bc  */
 union vo_slihdmi13t_external_video_parameter_settingsReg vo_slihdmi13t_external_video_parameter_settings; /* +0x000000c0  */
 uint32_t vo_slihdmi13t_external_horizontal_total_lsb; /* +0x000000c4  */
 uint32_t vo_slihdmi13t_external_horizontal_total_msb; /* +0x000000c8  */
 uint32_t vo_slihdmi13t_external_horizontal_blank_lsb; /* +0x000000cc  */
 uint32_t vo_slihdmi13t_external_horizontal_blank_msb; /* +0x000000d0  */
 uint32_t vo_slihdmi13t_external_horizontal_delay_lsb; /* +0x000000d4  */
 uint32_t vo_slihdmi13t_external_horizontal_delay_msb; /* +0x000000d8  */
 uint32_t vo_slihdmi13t_external_horizontal_duration_lsb; /* +0x000000dc  */
 uint32_t vo_slihdmi13t_external_horizontal_duration_msb; /* +0x000000e0  */
 uint32_t vo_slihdmi13t_external_vertical_total_lsb; /* +0x000000e4  */
 uint32_t vo_slihdmi13t_external_vertical_total_msb; /* +0x000000e8  */
 uint32_t vo_slihdmi13t_audio_and_video_setting2; /* +0x000000ec  */
 uint32_t vo_slihdmi13t_reserved_00h; /* +0x000000f0  */
 uint32_t vo_slihdmi13t_external_vertical_blank; /* +0x000000f4  */
 uint32_t vo_slihdmi13t_external_vertical_delay; /* +0x000000f8  */
 uint32_t vo_slihdmi13t_external_vertical_duration; /* +0x000000fc  */
 uint32_t vo_slihdmi13t_control_packet_manual_send_control; /* +0x00000100  */
 uint32_t vo_slihdmi13t_control_packet_auto_send_with_vsync_control; /* +0x00000104  */
 uint32_t vo_slihdmi13t_auto_checksum_option; /* +0x00000108  */
 uint32_t vo_slihdmi13t_reserved_01h; /* +0x0000010c  */
 uint32_t vo_slihdmi13t_reserved_02h; /* +0x00000110  */
 union vo_slihdmi13t_video_setting2Reg vo_slihdmi13t_video_setting2; /* +0x00000114  */
 uint32_t vo_slihdmi13t_reserved_03h; /* +0x00000118  */
 uint32_t vo_slihdmi13t_reserved_04h; /* +0x0000011c  */
 uint32_t vo_slihdmi13t_reserved_05h; /* +0x00000120  */
 uint32_t vo_slihdmi13t_reserved_06h; /* +0x00000124  */
 uint32_t vo_slihdmi13t_reserved_07h; /* +0x00000128  */
 uint32_t vo_slihdmi13t_reserved_08h; /* +0x0000012c  */
 uint32_t vo_slihdmi13t_reserved_09h; /* +0x00000130  */
 uint32_t vo_slihdmi13t_reserved_0ah; /* +0x00000134  */
 uint32_t vo_slihdmi13t_reserved_0bh; /* +0x00000138  */
 uint32_t vo_slihdmi13t_reserved_0ch; /* +0x0000013c  */
 uint32_t vo_slihdmi13t_reserved_0dh; /* +0x00000140  */
 uint32_t vo_slihdmi13t_reserved_0eh; /* +0x00000144  */
 uint32_t vo_slihdmi13t_hsync_placement_at_embedded_sync_lsb; /* +0x00000148  */
 uint32_t vo_slihdmi13t_hsync_placement_at_embedded_sync_msb; /* +0x0000014c  */
 uint32_t vo_slihdmi13t_vsync_placement_at_embedded_sync_lsb; /* +0x00000150  */
 uint32_t vo_slihdmi13t_vsync_placement_at_embedded_sync_msb; /* +0x00000154  */
 uint32_t vo_slihdmi13t_sliphdmit_parameter_settings1; /* +0x00000158  */
 uint32_t vo_slihdmi13t_sliphdmit_parameter_settings2; /* +0x0000015c  */
 uint32_t vo_slihdmi13t_sliphdmit_parameter_settings3; /* +0x00000160  */
 uint32_t vo_slihdmi13t_sliphdmit_parameter_settings5; /* +0x00000164  */
 uint32_t vo_slihdmi13t_sliphdmit_parameter_settings6; /* +0x00000168  */
 uint32_t vo_slihdmi13t_sliphdmit_parameter_settings7; /* +0x0000016c  */
 uint32_t vo_slihdmi13t_sliphdmit_parameter_settings8; /* +0x00000170  */
 uint32_t vo_slihdmi13t_sliphdmit_parameter_settings9; /* +0x00000174  */
 uint32_t vo_slihdmi13t_sliphdmit_parameter_settings10; /* +0x00000178  */
 uint32_t vo_slihdmi13t_control_packet_buffer_index; /* +0x0000017c  */
 uint32_t vo_slihdmi13t_control_packet_data_buffer_access_window_hb0; /* +0x00000180  */
 uint32_t vo_slihdmi13t_control_packet_data_buffer_access_window_hb1; /* +0x00000184  */
 uint32_t vo_slihdmi13t_control_packet_data_buffer_access_window_hb2; /* +0x00000188  */
 uint32_t vo_slihdmi13t_control_packet_data_buffer_access_window_pb0; /* +0x0000018c  */
 uint32_t vo_slihdmi13t_control_packet_data_buffer_access_window_pb1; /* +0x00000190  */
 uint32_t vo_slihdmi13t_control_packet_data_buffer_access_window_pb2; /* +0x00000194  */
 uint32_t vo_slihdmi13t_control_packet_data_buffer_access_window_pb3; /* +0x00000198  */
 uint32_t vo_slihdmi13t_control_packet_data_buffer_access_window_pb4; /* +0x0000019c  */
 uint32_t vo_slihdmi13t_control_packet_data_buffer_access_window_pb5; /* +0x000001a0  */
 uint32_t vo_slihdmi13t_control_packet_data_buffer_access_window_pb6; /* +0x000001a4  */
 uint32_t vo_slihdmi13t_control_packet_data_buffer_access_window_pb7; /* +0x000001a8  */
 uint32_t vo_slihdmi13t_control_packet_data_buffer_access_window_pb8; /* +0x000001ac  */
 uint32_t vo_slihdmi13t_control_packet_data_buffer_access_window_pb9; /* +0x000001b0  */
 uint32_t vo_slihdmi13t_control_packet_data_buffer_access_window_pb10; /* +0x000001b4  */
 uint32_t vo_slihdmi13t_control_packet_data_buffer_access_window_pb11; /* +0x000001b8  */
 uint32_t vo_slihdmi13t_control_packet_data_buffer_access_window_pb12; /* +0x000001bc  */
 uint32_t vo_slihdmi13t_control_packet_data_buffer_access_window_pb13; /* +0x000001c0  */
 uint32_t vo_slihdmi13t_control_packet_data_buffer_access_window_pb14; /* +0x000001c4  */
 uint32_t vo_slihdmi13t_control_packet_data_buffer_access_window_pb15; /* +0x000001c8  */
 uint32_t vo_slihdmi13t_control_packet_data_buffer_access_window_pb16; /* +0x000001cc  */
 uint32_t vo_slihdmi13t_control_packet_data_buffer_access_window_pb17; /* +0x000001d0  */
 uint32_t vo_slihdmi13t_control_packet_data_buffer_access_window_pb18; /* +0x000001d4  */
 uint32_t vo_slihdmi13t_control_packet_data_buffer_access_window_pb19; /* +0x000001d8  */
 uint32_t vo_slihdmi13t_control_packet_data_buffer_access_window_pb20; /* +0x000001dc  */
 uint32_t vo_slihdmi13t_control_packet_data_buffer_access_window_pb21; /* +0x000001e0  */
 uint32_t vo_slihdmi13t_control_packet_data_buffer_access_window_pb22; /* +0x000001e4  */
 uint32_t vo_slihdmi13t_control_packet_data_buffer_access_window_pb23; /* +0x000001e8  */
 uint32_t vo_slihdmi13t_control_packet_data_buffer_access_window_pb24; /* +0x000001ec  */
 uint32_t vo_slihdmi13t_control_packet_data_buffer_access_window_pb25; /* +0x000001f0  */
 uint32_t vo_slihdmi13t_control_packet_data_buffer_access_window_pb26; /* +0x000001f4  */
 uint32_t vo_slihdmi13t_control_packet_data_buffer_access_window_pb27; /* +0x000001f8  */
 uint32_t vo_slihdmi13t_reserved_0fh; /* +0x000001fc  */
 uint32_t vo_slihdmi13t_edid_and_ksv_buffer_access_window; /* +0x00000200  */
 uint32_t vo_slihdmi13t_ddc_bus_access_frequency_control_lsb; /* +0x00000204  */
 uint32_t vo_slihdmi13t_ddc_bus_access_frequency_control_msb; /* +0x00000208  */
 uint32_t vo_slihdmi13t_reserved_10h; /* +0x0000020c  */
 uint32_t vo_slihdmi13t_reserved_11h; /* +0x00000210  */
 uint32_t vo_slihdmi13t_reserved_12h; /* +0x00000214  */
 uint32_t vo_slihdmi13t_reserved_13h; /* +0x00000218  */
 uint32_t vo_slihdmi13t_reserved_14h; /* +0x0000021c  */
 uint32_t vo_slihdmi13t_reserved_15h; /* +0x00000220  */
 uint32_t vo_slihdmi13t_reserved_16h; /* +0x00000224  */
 uint32_t vo_slihdmi13t_reserved_17h; /* +0x00000228  */
 uint32_t vo_slihdmi13t_reserved_18h; /* +0x0000022c  */
 uint32_t vo_slihdmi13t_reserved_19h; /* +0x00000230  */
 uint32_t vo_slihdmi13t_reserved_1ah; /* +0x00000234  */
 uint32_t vo_slihdmi13t_reserved_1bh; /* +0x00000238  */
 uint32_t vo_slihdmi13t_reserved_1ch; /* +0x0000023c  */
 uint32_t vo_slihdmi13t_reserved_1dh; /* +0x00000240  */
 uint32_t vo_slihdmi13t_reserved_1eh; /* +0x00000244  */
 uint32_t vo_slihdmi13t_interrupt_mask1; /* +0x00000248  */
 uint32_t vo_slihdmi13t_interrupt_mask2; /* +0x0000024c  */
 uint32_t vo_slihdmi13t_interrupt_status1; /* +0x00000250  */
 uint32_t vo_slihdmi13t_interrupt_status2; /* +0x00000254  */
 uint32_t vo_slihdmi13t_interrupt_mask3; /* +0x00000258  */
 uint32_t vo_slihdmi13t_interrupt_mask4; /* +0x0000025c  */
 uint32_t vo_slihdmi13t_interrupt_status3; /* +0x00000260  */
 uint32_t vo_slihdmi13t_interrupt_status4; /* +0x00000264  */
 uint32_t vo_slihdmi13t_software_hdcp_control1; /* +0x00000268  */
 uint32_t vo_slihdmi13t_reserved_1fh; /* +0x0000026c  */
 uint32_t vo_slihdmi13t_frame_counter; /* +0x00000270  */
 uint32_t vo_slihdmi13t_frame_counter_for_ri_check; /* +0x00000274  */
 uint32_t vo_slihdmi13t_ddc_i2c_access_length_for_hdcp; /* +0x00000278  */
 uint32_t vo_slihdmi13t_reserved_20h; /* +0x0000027c  */
 uint32_t vo_slihdmi13t_ddc_i2c_offset_for_hdcp; /* +0x00000280  */
 uint32_t vo_slihdmi13t_ddc_i2c_control_for_hdcp; /* +0x00000284  */
 uint32_t vo_slihdmi13t_ddc_i2c_read_buffer0; /* +0x00000288  */
 uint32_t vo_slihdmi13t_ddc_i2c_read_buffer1; /* +0x0000028c  */
 uint32_t vo_slihdmi13t_ddc_i2c_read_buffer2; /* +0x00000290  */
 uint32_t vo_slihdmi13t_ddc_i2c_read_buffer3; /* +0x00000294  */
 uint32_t vo_slihdmi13t_ddc_i2c_read_buffer4; /* +0x00000298  */
 uint32_t vo_slihdmi13t_ddc_i2c_write_buffer0; /* +0x0000029c  */
 uint32_t vo_slihdmi13t_ddc_i2c_write_buffer1; /* +0x000002a0  */
 uint32_t vo_slihdmi13t_ddc_i2c_write_buffer2; /* +0x000002a4  */
 uint32_t vo_slihdmi13t_ddc_i2c_write_buffer3; /* +0x000002a8  */
 uint32_t vo_slihdmi13t_ddc_i2c_write_buffer4; /* +0x000002ac  */
 uint32_t vo_slihdmi13t_ddc_i2c_write_buffer5; /* +0x000002b0  */
 uint32_t vo_slihdmi13t_ddc_i2c_write_buffer6; /* +0x000002b4  */
 uint32_t vo_slihdmi13t_ddc_i2c_write_buffer7; /* +0x000002b8  */
 union vo_slihdmi13t_hdcp_controlReg vo_slihdmi13t_hdcp_control; /* +0x000002bc  */
 uint32_t vo_slihdmi13t_reserved_21h; /* +0x000002c0  */
 uint32_t vo_slihdmi13t_reserved_22h; /* +0x000002c4  */
 uint32_t vo_slihdmi13t_ri_frame_count_register; /* +0x000002c8  */
 uint32_t vo_slihdmi13t_reserved_23h; /* +0x000002cc  */
 uint32_t vo_slihdmi13t_reserved_24h; /* +0x000002d0  */
 uint32_t vo_slihdmi13t_reserved_25h; /* +0x000002d4  */
 uint32_t vo_slihdmi13t_reserved_26h; /* +0x000002d8  */
 uint32_t vo_slihdmi13t_ddc_bus_control; /* +0x000002dc  */
 uint32_t vo_slihdmi13t_hdcp_status; /* +0x000002e0  */
 uint32_t vo_slihdmi13t_sha0; /* +0x000002e4  */
 uint32_t vo_slihdmi13t_sha1; /* +0x000002e8  */
 uint32_t vo_slihdmi13t_sha2; /* +0x000002ec  */
 uint32_t vo_slihdmi13t_sha3; /* +0x000002f0  */
 uint32_t vo_slihdmi13t_sha4; /* +0x000002f4  */
 uint32_t vo_slihdmi13t_bcaps; /* +0x000002f8  */
 uint32_t vo_slihdmi13t_aksv_and_bksv_7_to_0_monitor; /* +0x000002fc  */
 uint32_t vo_slihdmi13t_aksv_and_bksv_15_to_8_monitor; /* +0x00000300  */
 uint32_t vo_slihdmi13t_aksv_and_bksv_23_to_16_monitor; /* +0x00000304  */
 uint32_t vo_slihdmi13t_aksv_and_bksv_31_to_24_monitor; /* +0x00000308  */
 uint32_t vo_slihdmi13t_aksv_and_bksv_39_to_32_monitor; /* +0x0000030c  */
 uint32_t vo_slihdmi13t_edid_segment_pointer; /* +0x00000310  */
 uint32_t vo_slihdmi13t_edid_word_address; /* +0x00000314  */
 uint32_t vo_slihdmi13t_reserved_27h; /* +0x00000318  */
 uint32_t vo_slihdmi13t_number_of_hdmi_devices; /* +0x0000031c  */
 uint32_t vo_slihdmi13t_hdcp_error_code; /* +0x00000320  */
 uint32_t vo_slihdmi13t_100ms_timer_setting; /* +0x00000324  */
 uint32_t vo_slihdmi13t_5sec_timer_setting; /* +0x00000328  */
 uint32_t vo_slihdmi13t_ri_read_count; /* +0x0000032c  */
 uint32_t vo_slihdmi13t_an_seed; /* +0x00000330  */
 uint32_t vo_slihdmi13t_maximum_number_of_receivers_allowed; /* +0x00000334  */
 uint32_t vo_slihdmi13t_hdcp_memory_access_control1; /* +0x00000338  */
 uint32_t vo_slihdmi13t_hdcp_memory_access_control2; /* +0x0000033c  */
 uint32_t vo_slihdmi13t_hdcp_control_2; /* +0x00000340  */
 uint32_t vo_slihdmi13t_reserved_28h; /* +0x00000344  */
 uint32_t vo_slihdmi13t_hdcp_key_memory_control; /* +0x00000348  */
 uint32_t vo_slihdmi13t_color_space_conversion_configuration1; /* +0x0000034c  */
 uint32_t vo_slihdmi13t_video_setting3; /* +0x00000350  */
 uint32_t vo_slihdmi13t_ri_7_to_0; /* +0x00000354  */
 uint32_t vo_slihdmi13t_ri_15_to_8; /* +0x00000358  */
 uint32_t vo_slihdmi13t_pj; /* +0x0000035c  */
 uint32_t vo_slihdmi13t_sha_rd; /* +0x00000360  */
 uint32_t vo_slihdmi13t_ri_7_to_0_saved; /* +0x00000364  */
 uint32_t vo_slihdmi13t_ri_15_to_8_saved; /* +0x00000368  */
 uint32_t vo_slihdmi13t_pj_saved; /* +0x0000036c  */
 uint32_t vo_slihdmi13t_number_of_devices; /* +0x00000370  */
 uint32_t vo_slihdmi13t_reserved_29h; /* +0x00000374  */
 uint32_t vo_slihdmi13t_reserved_2ah; /* +0x00000378  */
 uint32_t vo_slihdmi13t_hot_plug_and_msens_status; /* +0x0000037c  */
 uint32_t vo_slihdmi13t_bcaps2; /* +0x00000380  */
 uint32_t vo_slihdmi13t_bstat_7_to_0; /* +0x00000384  */
 uint32_t vo_slihdmi13t_bstat_15_to_8; /* +0x00000388  */
 uint32_t vo_slihdmi13t_bksv_7_to_0; /* +0x0000038c  */
 uint32_t vo_slihdmi13t_bksv_15_to_8; /* +0x00000390  */
 uint32_t vo_slihdmi13t_bksv_23_to_16; /* +0x00000394  */
 uint32_t vo_slihdmi13t_bksv_31_to_24; /* +0x00000398  */
 uint32_t vo_slihdmi13t_bksv_39_to_32; /* +0x0000039c  */
 uint32_t vo_slihdmi13t_an_7_to_0; /* +0x000003a0  */
 uint32_t vo_slihdmi13t_an_15_to_8; /* +0x000003a4  */
 uint32_t vo_slihdmi13t_an_23_to_16; /* +0x000003a8  */
 uint32_t vo_slihdmi13t_an_31_to_24; /* +0x000003ac  */
 uint32_t vo_slihdmi13t_an_39_to_32; /* +0x000003b0  */
 uint32_t vo_slihdmi13t_an_47_to_40; /* +0x000003b4  */
 uint32_t vo_slihdmi13t_an_55_to_48; /* +0x000003b8  */
 uint32_t vo_slihdmi13t_an_63_to_56; /* +0x000003bc  */
 uint32_t vo_slihdmi13t_product_id; /* +0x000003c0  */
 uint32_t vo_slihdmi13t_revision_id; /* +0x000003c4  */
 uint32_t vo_slihdmi13t_reserved_2bh; /* +0x000003c8  */
 uint32_t vo_slihdmi13t_reserved_2ch; /* +0x000003cc  */
 uint32_t vo_slihdmi13t_reserved_2dh; /* +0x000003d0  */
 uint32_t vo_slihdmi13t_reserved_2eh; /* +0x000003d4  */
 uint32_t vo_slihdmi13t_reserved_2fh; /* +0x000003d8  */
 uint32_t vo_slihdmi13t_reserved_30h; /* +0x000003dc  */
 uint32_t vo_slihdmi13t_reserved_31h; /* +0x000003e0  */
 uint32_t vo_slihdmi13t_reserved_32h; /* +0x000003e4  */
 uint32_t vo_slihdmi13t_reserved_33h; /* +0x000003e8  */
 uint32_t vo_slihdmi13t_reserved_34h; /* +0x000003ec  */
 uint32_t vo_slihdmi13t_reserved_35h; /* +0x000003f0  */
 uint32_t vo_slihdmi13t_reserved_36h; /* +0x000003f4  */
 uint32_t vo_slihdmi13t_test_mode; /* +0x000003f8  */
 uint32_t vo_slihdmi13t_reserved_37h; /* +0x000003fc  */
};
