/* autogenerated with parsecfg: do not edit. */

union vo_sboxmbusrd_disconnect_cmdReg {
 struct { uint32_t

 /* sorting 2 */
#define vo_sboxmbusrd_disconnect_cmd_id_SHIFT 0
#define vo_sboxmbusrd_disconnect_cmd_id_WIDTH 3
#define vo_sboxmbusrd_disconnect_cmd_type_SHIFT 8
#define vo_sboxmbusrd_disconnect_cmd_type_WIDTH 2

 id:3, /*[2:0]  */
 hole0:5,
 type:2, /*[9:8]  */
 hole1:22;
 } bits;

 uint32_t value;
};

union vo_sboxmbusrd_connect_cmdReg {
 struct { uint32_t

 /* sorting 2 */
#define vo_sboxmbusrd_connect_cmd_dest_SHIFT 0
#define vo_sboxmbusrd_connect_cmd_dest_WIDTH 3
#define vo_sboxmbusrd_connect_cmd_source_SHIFT 8
#define vo_sboxmbusrd_connect_cmd_source_WIDTH 3

 dest:3, /*[2:0]  */
 hole0:5,
 source:3, /*[10:8]  */
 hole1:21;
 } bits;

 uint32_t value;
};

struct vo_switchbox_mbus_read {
 union vo_sboxmbusrd_connect_cmdReg vo_sboxmbusrd_connect_cmd; /* +0x00000000  */
 union vo_sboxmbusrd_disconnect_cmdReg vo_sboxmbusrd_disconnect_cmd; /* +0x00000004  */
 uint32_t vo_sboxmbusrd_source_0; /* +0x00000008  */
 uint32_t vo_sboxmbusrd_source_1; /* +0x0000000c  */
 uint32_t vo_sboxmbusrd_source_2; /* +0x00000010  */
 uint32_t vo_sboxmbusrd_source_3; /* +0x00000014  */
 uint32_t vo_sboxmbusrd_dest_0; /* +0x00000018  */
 uint32_t vo_sboxmbusrd_dest_1; /* +0x0000001c  */
 uint32_t vo_sboxmbusrd_dest_2; /* +0x00000020  */
 uint32_t vo_sboxmbusrd_dest_3; /* +0x00000024  */
};
