/* autogenerated with parsecfg: do not edit. */

union vp_main_mixer_indexReg {
 struct { uint32_t

 /* sorting 8 */
#define vp_main_mixer_index__0_SHIFT 0
#define vp_main_mixer_index__0_WIDTH 3
#define vp_main_mixer_index__1_SHIFT 4
#define vp_main_mixer_index__1_WIDTH 3
#define vp_main_mixer_index__2_SHIFT 8
#define vp_main_mixer_index__2_WIDTH 3
#define vp_main_mixer_index__3_SHIFT 12
#define vp_main_mixer_index__3_WIDTH 3
#define vp_main_mixer_index__4_SHIFT 16
#define vp_main_mixer_index__4_WIDTH 3
#define vp_main_mixer_index__5_SHIFT 20
#define vp_main_mixer_index__5_WIDTH 3
#define vp_main_mixer_index__6_SHIFT 24
#define vp_main_mixer_index__6_WIDTH 3
#define vp_main_mixer_index__7_SHIFT 28
#define vp_main_mixer_index__7_WIDTH 3

 _0:3, /*[2:0]  */
 hole0:1,
 _1:3, /*[6:4]  */
 hole1:1,
 _2:3, /*[10:8]  */
 hole2:1,
 _3:3, /*[14:12]  */
 hole3:1,
 _4:3, /*[18:16]  */
 hole4:1,
 _5:3, /*[22:20]  */
 hole5:1,
 _6:3, /*[26:24]  */
 hole6:1,
 _7:3, /*[30:28]  */
 hole7:1;
 } bits;

 uint32_t value;
};

union vp_main_mixer_frame_sizeReg {
 struct { uint32_t

 /* sorting 2 */
#define vp_main_mixer_frame_size_xsize_SHIFT 0
#define vp_main_mixer_frame_size_xsize_WIDTH 12
#define vp_main_mixer_frame_size_ysize_SHIFT 16
#define vp_main_mixer_frame_size_ysize_WIDTH 12

 xsize:12, /*[11:0]  */
 hole0:4,
 ysize:12, /*[27:16]  */
 hole1:4;
 } bits;

 uint32_t value;
};

union vp_main_mixer_depthReg {
 struct { uint32_t

 /* sorting 8 */
#define vp_main_mixer_depth_r0_depth_SHIFT 0
#define vp_main_mixer_depth_r0_depth_WIDTH 2
#define vp_main_mixer_depth_r1_depth_SHIFT 4
#define vp_main_mixer_depth_r1_depth_WIDTH 2
#define vp_main_mixer_depth_r2_depth_SHIFT 8
#define vp_main_mixer_depth_r2_depth_WIDTH 2
#define vp_main_mixer_depth_r3_depth_SHIFT 12
#define vp_main_mixer_depth_r3_depth_WIDTH 2
#define vp_main_mixer_depth_r4_depth_SHIFT 16
#define vp_main_mixer_depth_r4_depth_WIDTH 2
#define vp_main_mixer_depth_r5_depth_SHIFT 20
#define vp_main_mixer_depth_r5_depth_WIDTH 2
#define vp_main_mixer_depth_r6_depth_SHIFT 24
#define vp_main_mixer_depth_r6_depth_WIDTH 2
#define vp_main_mixer_depth_r7_depth_SHIFT 28
#define vp_main_mixer_depth_r7_depth_WIDTH 2

 r0_depth:2, /*[1:0]  */
 hole0:2,
 r1_depth:2, /*[5:4]  */
 hole1:2,
 r2_depth:2, /*[9:8]  */
 hole2:2,
 r3_depth:2, /*[13:12]  */
 hole3:2,
 r4_depth:2, /*[17:16]  */
 hole4:2,
 r5_depth:2, /*[21:20]  */
 hole5:2,
 r6_depth:2, /*[25:24]  */
 hole6:2,
 r7_depth:2, /*[29:28]  */
 hole7:2;
 } bits;

 uint32_t value;
};

union vp_main_mixer_background_yReg {
 struct { uint32_t

 /* sorting 1 */
#define vp_main_mixer_background_y_vp_main_mixer_back_ground_color_y_SHIFT 0
#define vp_main_mixer_background_y_vp_main_mixer_back_ground_color_y_WIDTH 12

 vp_main_mixer_back_ground_color_y:12, /*[11:0]  */
 hole0:20;
 } bits;

 uint32_t value;
};

union vp_main_mixer_background_crReg {
 struct { uint32_t

 /* sorting 1 */
#define vp_main_mixer_background_cr_vp_main_mixer_back_ground_color_cr_SHIFT 0
#define vp_main_mixer_background_cr_vp_main_mixer_back_ground_color_cr_WIDTH 12

 vp_main_mixer_back_ground_color_cr:12, /*[11:0]  */
 hole0:20;
 } bits;

 uint32_t value;
};

union vp_main_mixer_background_cbReg {
 struct { uint32_t

 /* sorting 2 */
#define vp_main_mixer_background_cb_back_ground_color_cb_SHIFT 0
#define vp_main_mixer_background_cb_back_ground_color_cb_WIDTH 12
#define vp_main_mixer_background_cb_fb_SHIFT 16
#define vp_main_mixer_background_cb_fb_WIDTH 1

 back_ground_color_cb:12, /*[11:0]  */
 hole0:4,
 fb:1, /*[16:16]  */
 hole1:15;
 } bits;

 uint32_t value;
};

union vp_main_mixer_7_posReg {
 struct { uint32_t

 /* sorting 3 */
#define vp_main_mixer_7_pos_xpos_SHIFT 0
#define vp_main_mixer_7_pos_xpos_WIDTH 13
#define vp_main_mixer_7_pos_ypos_SHIFT 16
#define vp_main_mixer_7_pos_ypos_WIDTH 13
#define vp_main_mixer_7_pos_en_SHIFT 31
#define vp_main_mixer_7_pos_en_WIDTH 1

 xpos:13, /*[12:0]  */
 hole0:3,
 ypos:13, /*[28:16]  */
 hole1:2,
 en:1; /*[31:31]  */
 } bits;

 uint32_t value;
};

union vp_main_mixer_6_posReg {
 struct { uint32_t

 /* sorting 3 */
#define vp_main_mixer_6_pos_xpos_SHIFT 0
#define vp_main_mixer_6_pos_xpos_WIDTH 13
#define vp_main_mixer_6_pos_ypos_SHIFT 16
#define vp_main_mixer_6_pos_ypos_WIDTH 13
#define vp_main_mixer_6_pos_en_SHIFT 31
#define vp_main_mixer_6_pos_en_WIDTH 1

 xpos:13, /*[12:0]  */
 hole0:3,
 ypos:13, /*[28:16]  */
 hole1:2,
 en:1; /*[31:31]  */
 } bits;

 uint32_t value;
};

union vp_main_mixer_5_posReg {
 struct { uint32_t

 /* sorting 3 */
#define vp_main_mixer_5_pos_xpos_SHIFT 0
#define vp_main_mixer_5_pos_xpos_WIDTH 13
#define vp_main_mixer_5_pos_ypos_SHIFT 16
#define vp_main_mixer_5_pos_ypos_WIDTH 13
#define vp_main_mixer_5_pos_en_SHIFT 31
#define vp_main_mixer_5_pos_en_WIDTH 1

 xpos:13, /*[12:0]  */
 hole0:3,
 ypos:13, /*[28:16]  */
 hole1:2,
 en:1; /*[31:31]  */
 } bits;

 uint32_t value;
};

union vp_main_mixer_4_posReg {
 struct { uint32_t

 /* sorting 3 */
#define vp_main_mixer_4_pos_xpos_SHIFT 0
#define vp_main_mixer_4_pos_xpos_WIDTH 13
#define vp_main_mixer_4_pos_ypos_SHIFT 16
#define vp_main_mixer_4_pos_ypos_WIDTH 13
#define vp_main_mixer_4_pos_en_SHIFT 31
#define vp_main_mixer_4_pos_en_WIDTH 1

 xpos:13, /*[12:0]  */
 hole0:3,
 ypos:13, /*[28:16]  */
 hole1:2,
 en:1; /*[31:31]  */
 } bits;

 uint32_t value;
};

union vp_main_mixer_3_posReg {
 struct { uint32_t

 /* sorting 3 */
#define vp_main_mixer_3_pos_xpos_SHIFT 0
#define vp_main_mixer_3_pos_xpos_WIDTH 13
#define vp_main_mixer_3_pos_ypos_SHIFT 16
#define vp_main_mixer_3_pos_ypos_WIDTH 13
#define vp_main_mixer_3_pos_en_SHIFT 31
#define vp_main_mixer_3_pos_en_WIDTH 1

 xpos:13, /*[12:0]  */
 hole0:3,
 ypos:13, /*[28:16]  */
 hole1:2,
 en:1; /*[31:31]  */
 } bits;

 uint32_t value;
};

union vp_main_mixer_2_posReg {
 struct { uint32_t

 /* sorting 3 */
#define vp_main_mixer_2_pos_xpos_SHIFT 0
#define vp_main_mixer_2_pos_xpos_WIDTH 13
#define vp_main_mixer_2_pos_ypos_SHIFT 16
#define vp_main_mixer_2_pos_ypos_WIDTH 13
#define vp_main_mixer_2_pos_en_SHIFT 31
#define vp_main_mixer_2_pos_en_WIDTH 1

 xpos:13, /*[12:0]  */
 hole0:3,
 ypos:13, /*[28:16]  */
 hole1:2,
 en:1; /*[31:31]  */
 } bits;

 uint32_t value;
};

union vp_main_mixer_1_posReg {
 struct { uint32_t

 /* sorting 3 */
#define vp_main_mixer_1_pos_xpos_SHIFT 0
#define vp_main_mixer_1_pos_xpos_WIDTH 13
#define vp_main_mixer_1_pos_ypos_SHIFT 16
#define vp_main_mixer_1_pos_ypos_WIDTH 13
#define vp_main_mixer_1_pos_en_SHIFT 31
#define vp_main_mixer_1_pos_en_WIDTH 1

 xpos:13, /*[12:0]  */
 hole0:3,
 ypos:13, /*[28:16]  */
 hole1:2,
 en:1; /*[31:31]  */
 } bits;

 uint32_t value;
};

union vp_main_mixer_0_posReg {
 struct { uint32_t

 /* sorting 3 */
#define vp_main_mixer_0_pos_xpos_SHIFT 0
#define vp_main_mixer_0_pos_xpos_WIDTH 13
#define vp_main_mixer_0_pos_ypos_SHIFT 16
#define vp_main_mixer_0_pos_ypos_WIDTH 13
#define vp_main_mixer_0_pos_en_SHIFT 31
#define vp_main_mixer_0_pos_en_WIDTH 1

 xpos:13, /*[12:0]  */
 hole0:3,
 ypos:13, /*[28:16]  */
 hole1:2,
 en:1; /*[31:31]  */
 } bits;

 uint32_t value;
};

struct vp_main_mixer {
 union vp_main_mixer_0_posReg vp_main_mixer_0_pos; /* +0x00000000  */
 union vp_main_mixer_1_posReg vp_main_mixer_1_pos; /* +0x00000004  */
 union vp_main_mixer_2_posReg vp_main_mixer_2_pos; /* +0x00000008  */
 union vp_main_mixer_3_posReg vp_main_mixer_3_pos; /* +0x0000000c  */
 union vp_main_mixer_4_posReg vp_main_mixer_4_pos; /* +0x00000010  */
 union vp_main_mixer_5_posReg vp_main_mixer_5_pos; /* +0x00000014  */
 union vp_main_mixer_6_posReg vp_main_mixer_6_pos; /* +0x00000018  */
 union vp_main_mixer_7_posReg vp_main_mixer_7_pos; /* +0x0000001c  */
 union vp_main_mixer_indexReg vp_main_mixer_index; /* +0x00000020  */
 union vp_main_mixer_frame_sizeReg vp_main_mixer_frame_size; /* +0x00000024  */
 union vp_main_mixer_background_cbReg vp_main_mixer_background_cb; /* +0x00000028  */
 union vp_main_mixer_background_yReg vp_main_mixer_background_y; /* +0x0000002c  */
 union vp_main_mixer_background_crReg vp_main_mixer_background_cr; /* +0x00000030  */
 union vp_main_mixer_depthReg vp_main_mixer_depth; /* +0x00000034  */
};
