/* autogenerated with parsecfg: do not edit. */

union misc_timer_divReg {
 struct { uint32_t

 /* sorting 1 */
#define misc_timer_div_misc_timer_div_value_SHIFT 0
#define misc_timer_div_misc_timer_div_value_WIDTH 16

 misc_timer_div_value:16, /*[15:0]  */
 hole0:16;
 } bits;

 uint32_t value;
};

union misc_sbox_write_totalbytesReg {
 struct { uint32_t

 /* sorting 2 */
#define misc_sbox_write_totalbytes_value_SHIFT 0
#define misc_sbox_write_totalbytes_value_WIDTH 11
#define misc_sbox_write_totalbytes_zero_SHIFT 11
#define misc_sbox_write_totalbytes_zero_WIDTH 5

 value:11, /*[10:0]  */
 zero:5, /*[15:11] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union misc_sbox_write_pmembytesReg {
 struct { uint32_t

 /* sorting 2 */
#define misc_sbox_write_pmembytes_value_SHIFT 0
#define misc_sbox_write_pmembytes_value_WIDTH 11
#define misc_sbox_write_pmembytes_zero_SHIFT 11
#define misc_sbox_write_pmembytes_zero_WIDTH 5

 value:11, /*[10:0]  */
 zero:5, /*[15:11] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union misc_sbox_write_currentReg {
 struct { uint32_t

 /* sorting 2 */
#define misc_sbox_write_current_value_SHIFT 0
#define misc_sbox_write_current_value_WIDTH 11
#define misc_sbox_write_current_zero_SHIFT 11
#define misc_sbox_write_current_zero_WIDTH 5

 value:11, /*[10:0]  */
 zero:5, /*[15:11] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union misc_sbox_read_totalbytesReg {
 struct { uint32_t

 /* sorting 2 */
#define misc_sbox_read_totalbytes_value_SHIFT 0
#define misc_sbox_read_totalbytes_value_WIDTH 11
#define misc_sbox_read_totalbytes_zero_SHIFT 11
#define misc_sbox_read_totalbytes_zero_WIDTH 5

 value:11, /*[10:0]  */
 zero:5, /*[15:11] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union misc_sbox_read_pmembytesReg {
 struct { uint32_t

 /* sorting 2 */
#define misc_sbox_read_pmembytes_value_SHIFT 0
#define misc_sbox_read_pmembytes_value_WIDTH 11
#define misc_sbox_read_pmembytes_zero_SHIFT 11
#define misc_sbox_read_pmembytes_zero_WIDTH 5

 value:11, /*[10:0]  */
 zero:5, /*[15:11] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union misc_sbox_read_currentReg {
 struct { uint32_t

 /* sorting 2 */
#define misc_sbox_read_current_value_SHIFT 0
#define misc_sbox_read_current_value_WIDTH 11
#define misc_sbox_read_current_zero_SHIFT 11
#define misc_sbox_read_current_zero_WIDTH 5

 value:11, /*[10:0]  */
 zero:5, /*[15:11] ,RO */
 hole0:16;
 } bits;

 uint32_t value;
};

union misc_sbox_modeReg {
 struct { uint32_t

 /* sorting 1 */
#define misc_sbox_mode_misc_sbox_mode_value_SHIFT 0
#define misc_sbox_mode_misc_sbox_mode_value_WIDTH 3

 misc_sbox_mode_value:3, /*[2:0]  */
 hole0:29;
 } bits;

 uint32_t value;
};

union misc_dw_modeReg {
 struct { uint32_t

 /* sorting 2 */
#define misc_dw_mode_mode_SHIFT 0
#define misc_dw_mode_mode_WIDTH 2
#define misc_dw_mode_priority_SHIFT 8
#define misc_dw_mode_priority_WIDTH 1

 mode:2, /*[1:0]  */
 hole0:6,
 priority:1, /*[8:8]  */
 hole1:23;
 } bits;

 uint32_t value;
};

union misc_dw_addressReg {
 struct { uint32_t

 /* sorting 1 */
#define misc_dw_address_misc_dw_address_value_SHIFT 0
#define misc_dw_address_misc_dw_address_value_WIDTH 15

 misc_dw_address_value:15, /*[14:0]  */
 hole0:17;
 } bits;

 uint32_t value;
};

union misc_dr_modeReg {
 struct { uint32_t

 /* sorting 2 */
#define misc_dr_mode_mode_SHIFT 0
#define misc_dr_mode_mode_WIDTH 2
#define misc_dr_mode_priority_SHIFT 8
#define misc_dr_mode_priority_WIDTH 1

 mode:2, /*[1:0]  */
 hole0:6,
 priority:1, /*[8:8]  */
 hole1:23;
 } bits;

 uint32_t value;
};

union misc_dr_addressReg {
 struct { uint32_t

 /* sorting 1 */
#define misc_dr_address_misc_dr_address_value_SHIFT 0
#define misc_dr_address_misc_dr_address_value_WIDTH 15

 misc_dr_address_value:15, /*[14:0]  */
 hole0:17;
 } bits;

 uint32_t value;
};

union misc_codec_typeReg {
 struct { uint32_t

 /* sorting 1 */
#define misc_codec_type_misc_codec_type_value_SHIFT 0
#define misc_codec_type_misc_codec_type_value_WIDTH 16

 misc_codec_type_value:16, /*[15:0]  */
 hole0:16;
 } bits;

 uint32_t value;
};

struct vtsc_misc {
 uint32_t misc_counter_lo; /* +0x00000000 ,NO_MEM */
 uint32_t misc_counter_hi; /* +0x00000004 ,NO_MEM */
 uint32_t pad0[0x0078/4];
 uint32_t misc_semaphore_0; /* +0x00000080 ,NO_TEST */
 uint32_t misc_semaphore_1; /* +0x00000084 ,NO_TEST */
 union misc_sbox_read_totalbytesReg misc_sbox_read_totalbytes; /* +0x00000088  */
 union misc_sbox_read_pmembytesReg misc_sbox_read_pmembytes; /* +0x0000008c  */
 union misc_sbox_read_currentReg misc_sbox_read_current; /* +0x00000090  */
 union misc_sbox_write_totalbytesReg misc_sbox_write_totalbytes; /* +0x00000094  */
 union misc_sbox_write_pmembytesReg misc_sbox_write_pmembytes; /* +0x00000098  */
 union misc_sbox_write_currentReg misc_sbox_write_current; /* +0x0000009c  */
 uint32_t pad1[0x0010/4];
 uint32_t misc_dsp_irq_extend; /* +0x000000b0 ,RO */
 uint32_t misc_dsp_irq_extend_mask; /* +0x000000b4 ,NO_MEM */
 uint32_t misc_reset2; /* +0x000000b8 ,NO_MEM */
 uint32_t pad2[0x0004/4];
 union misc_dr_modeReg misc_dr_mode; /* +0x000000c0  */
 uint32_t misc_dr_length; /* +0x000000c4 ,NO_TEST */
 union misc_dr_addressReg misc_dr_address; /* +0x000000c8  */
 union misc_sbox_modeReg misc_sbox_mode; /* +0x000000cc  */
 union misc_dw_modeReg misc_dw_mode; /* +0x000000d0  */
 uint32_t misc_dw_length; /* +0x000000d4 ,NO_TEST */
 union misc_dw_addressReg misc_dw_address; /* +0x000000d8  */
 union misc_codec_typeReg misc_codec_type; /* +0x000000dc  */
 uint32_t misc_reset0; /* +0x000000e0 ,NO_MEM */
 uint32_t misc_reset1; /* +0x000000e4 ,NO_MEM */
 uint32_t misc_interrupt; /* +0x000000e8 ,NO_MEM */
 union misc_timer_divReg misc_timer_div; /* +0x000000ec  */
 uint32_t misc_timer_cnt; /* +0x000000f0 ,NO_TEST */
 uint32_t pad3[0x0008/4];
 uint32_t misc_version_revision; /* +0x000000fc ,RO */
};
