/* autogenerated with parsemap: do not edit. */
struct vtsc_dbus_address_decoder_dbus {
                              uint32_t pad0[14336/4];
#define vtsc_dbus_address_decoder_dbus_mbus_interface_wr_OFF 0x00003800
/* [0x00003800,0x00003880[ */ struct { struct mbus_interface_wr_det d; uint32_t w[(0x00000080-sizeof(struct mbus_interface_wr_det))/4]; } _mbus_interface_wr;
#define vtsc_dbus_address_decoder_dbus_mbus_interface_rd_OFF 0x00003880
/* [0x00003880,0x00003900[ */ struct { struct mbus_interface_rd_det d; uint32_t w[(0x00000080-sizeof(struct mbus_interface_rd_det))/4]; } _mbus_interface_rd;
#define vtsc_dbus_address_decoder_dbus_cme_OFF 0x00003900
/* [0x00003900,0x00003920[ */ struct { struct cme_det d; uint32_t w[(0x00000020-sizeof(struct cme_det))/4]; } _cme;
                              uint32_t pad1[64/4];
#define vtsc_dbus_address_decoder_dbus_scaler_OFF 0x00003960
/* [0x00003960,0x00003980[ */ struct { struct scaler_det d; uint32_t w[(0x00000020-sizeof(struct scaler_det))/4]; } _scaler;
                              uint32_t pad2[64/4];
#define vtsc_dbus_address_decoder_dbus_gbus_interface_OFF 0x000039c0
/* [0x000039c0,0x00003a00[ */ struct { struct gbus_interface_det d; uint32_t w[(0x00000040-sizeof(struct gbus_interface_det))/4]; } _gbus_interface;
#define vtsc_dbus_address_decoder_dbus_lcg_OFF 0x00003a00
/* [0x00003a00,0x00003a80[ */ struct { struct lcg_det d; uint32_t w[(0x00000080-sizeof(struct lcg_det))/4]; } _lcg;
                              uint32_t pad3[384/4];
#define vtsc_dbus_address_decoder_dbus_mvp_OFF 0x00003c00
/* [0x00003c00,0x00003d00[ */ struct { struct mvp_det d; uint32_t w[(0x00000100-sizeof(struct mvp_det))/4]; } _mvp;
#define vtsc_dbus_address_decoder_dbus_pmem_OFF 0x00003d00
/* [0x00003d00,0x00003d80[ */ struct { struct pmem_det d; uint32_t w[(0x00000080-sizeof(struct pmem_det))/4]; } _pmem;
                              uint32_t pad4[384/4];
#define vtsc_dbus_address_decoder_dbus_residual_OFF 0x00003f00
/* [0x00003f00,0x00003f20[ */ struct { struct residual_det d; uint32_t w[(0x00000020-sizeof(struct residual_det))/4]; } _residual;
                              uint32_t pad5[112/4];
#define vtsc_dbus_address_decoder_dbus_crc32_spy_OFF 0x00003f90
/* [0x00003f90,0x00003f98[ */ struct { struct crc32_spy_det d; uint32_t w[(0x00000008-sizeof(struct crc32_spy_det))/4]; } _crc32_spy;
                              uint32_t pad6[8/4];
#define vtsc_dbus_address_decoder_dbus_clock_gate_top_OFF 0x00003fa0
/* [0x00003fa0,0x00003fa2[ */ struct { struct clock_gate_top_det d; uint32_t w[(0x00000002-sizeof(struct clock_gate_top_det))/4]; } _clock_gate_top;
                              uint32_t pad7[30/4];
#define vtsc_dbus_address_decoder_dbus_misc_OFF 0x00003fc0
/* [0x00003fc0,0x00004000[ */ struct { struct misc_det d; uint32_t w[(0x00000040-sizeof(struct misc_det))/4]; } _misc;
};
