/* autogenerated with parsecfg: do not edit. */

/* gotta drop sp_read_add_zero@sp_read_address: 0x00017fff [1:0] */
union sp_write_modeReg {
 struct { uint32_t

 /* sorting 1 */
#define sp_write_mode_sp_write_mode_value_SHIFT 0
#define sp_write_mode_sp_write_mode_value_WIDTH 1

 sp_write_mode_value:1, /*[0:0]  */
 hole0:31;
 } bits;

 uint32_t value;
};

union sp_write_addressReg {
 struct { uint32_t

 /* sorting 3 */
#define sp_write_address_zero_SHIFT 0
#define sp_write_address_zero_WIDTH 2
#define sp_write_address_value_SHIFT 2
#define sp_write_address_value_WIDTH 13
#define sp_write_address_sel_SHIFT 16
#define sp_write_address_sel_WIDTH 1

 zero:2, /*[1:0] ,NO_MEM */
 value:13, /*[14:2]  */
 hole0:1,
 sel:1, /*[16:16]  */
 hole1:15;
 } bits;

 uint32_t value;
};

union sp_read_modeReg {
 struct { uint32_t

 /* sorting 1 */
#define sp_read_mode_sp_read_mode_value_SHIFT 0
#define sp_read_mode_sp_read_mode_value_WIDTH 1

 sp_read_mode_value:1, /*[0:0]  */
 hole0:31;
 } bits;

 uint32_t value;
};

union sp_read_addressReg {
 struct { uint32_t

 /* sorting 2 */
#define sp_read_address_value_SHIFT 0
#define sp_read_address_value_WIDTH 15
#define sp_read_address_sel_SHIFT 16
#define sp_read_address_sel_WIDTH 1

 value:15, /*[14:0]  */
 hole0:1,
 sel:1, /*[16:16]  */
 hole1:15;
 } bits;

 uint32_t value;
};

union sp_arbiter_cfgReg {
 struct { uint32_t

 /* sorting 1 */
#define sp_arbiter_cfg_sp_arbiter_cfg_value_SHIFT 0
#define sp_arbiter_cfg_sp_arbiter_cfg_value_WIDTH 2

 sp_arbiter_cfg_value:2, /*[1:0]  */
 hole0:30;
 } bits;

 uint32_t value;
};

union sbox_routeReg {
 struct { uint32_t

 /* sorting 4 */
#define sbox_route_SHA1_SHIFT 0
#define sbox_route_SHA1_WIDTH 4
#define sbox_route_w0_SHIFT 4
#define sbox_route_w0_WIDTH 4
#define sbox_route_write_SHIFT 8
#define sbox_route_write_WIDTH 4
#define sbox_route_ciphers_SHIFT 12
#define sbox_route_ciphers_WIDTH 4

 sha1:4, /*[3:0] ,NO_MEM */
 w0:4, /*[7:4] ,NO_MEM */
 write:4, /*[11:8] ,NO_MEM */
 ciphers:4, /*[15:12] ,NO_MEM */
 hole0:16;
 } bits;

 uint32_t value;
};

struct xpu_misc {
 union sbox_routeReg sbox_route; /* +0x00000000  */
 uint32_t sbox_route_hi; /* +0x00000004 ,NO_MEM */
 uint32_t sbox_reset_in; /* +0x00000008 ,NO_MEM */
 uint32_t sbox_reset_out; /* +0x0000000c ,NO_MEM */
 union sp_read_addressReg sp_read_address; /* +0x00000010  */
 uint32_t sp_read_size; /* +0x00000014 ,NO_TEST */
 union sp_read_modeReg sp_read_mode; /* +0x00000018  */
 uint32_t pad0[0x0004/4];
 union sp_write_addressReg sp_write_address; /* +0x00000020  */
 uint32_t sp_write_size; /* +0x00000024 ,NO_TEST */
 union sp_write_modeReg sp_write_mode; /* +0x00000028  */
 uint32_t pad1[0x0004/4];
 union sp_arbiter_cfgReg sp_arbiter_cfg; /* +0x00000030  */
};
