/* autogenerated with parsecfg: do not edit. */

union kl_config_control_regReg {
 struct { uint32_t

 /* sorting 3 */
#define kl_config_control_reg_config_SHIFT 0
#define kl_config_control_reg_config_WIDTH 2
#define kl_config_control_reg_level_SHIFT 2
#define kl_config_control_reg_level_WIDTH 2
#define kl_config_control_reg_cipher_select_SHIFT 5
#define kl_config_control_reg_cipher_select_WIDTH 2

 config:2, /*[1:0]  */
 level:2, /*[3:2] ,NO_MEM */
 hole0:1,
 cipher_select:2, /*[6:5]  */
 hole1:25;
 } bits;

 uint32_t value;
};

union kl_config_access_regReg {
 struct { uint32_t

 /* sorting 7 */
#define kl_config_access_reg_go_enable_SHIFT 0
#define kl_config_access_reg_go_enable_WIDTH 1
#define kl_config_access_reg_status_oib_err_SHIFT 1
#define kl_config_access_reg_status_oib_err_WIDTH 1
#define kl_config_access_reg_status_oib_num_objects_SHIFT 2
#define kl_config_access_reg_status_oib_num_objects_WIDTH 3
#define kl_config_access_reg_check_data_flags_SHIFT 25
#define kl_config_access_reg_check_data_flags_WIDTH 4
#define kl_config_access_reg_check_kl_level_flag_SHIFT 29
#define kl_config_access_reg_check_kl_level_flag_WIDTH 1
#define kl_config_access_reg_check_access_flag_SHIFT 30
#define kl_config_access_reg_check_access_flag_WIDTH 1
#define kl_config_access_reg_done_SHIFT 31
#define kl_config_access_reg_done_WIDTH 1

 go_enable:1, /*[0:0]  */
 status_oib_err:1, /*[1:1] ,RO */
 status_oib_num_objects:3, /*[4:2] ,RO */
 hole0:20,
 check_data_flags:4, /*[28:25] ,RO */
 check_kl_level_flag:1, /*[29:29] ,RO */
 check_access_flag:1, /*[30:30] ,RO */
 done:1; /*[31:31] ,RO */
 } bits;

 uint32_t value;
};

struct xpu_keyladder {
 uint32_t kl_load_data0; /* +0x00000000 ,NO_MEM */
 uint32_t kl_load_data1; /* +0x00000004 ,NO_MEM */
 uint32_t kl_load_data2; /* +0x00000008 ,NO_MEM */
 uint32_t kl_load_data3; /* +0x0000000c ,NO_MEM */
 union kl_config_control_regReg kl_config_control_reg; /* +0x00000010  */
 union kl_config_access_regReg kl_config_access_reg; /* +0x00000014 ,NO_TEST */
};
