/* autogenerated with parsecfg: do not edit. */

union des_config_regReg {
 struct { uint32_t

 /* sorting 12 */
#define des_config_reg_mode_triple_des_SHIFT 0
#define des_config_reg_mode_triple_des_WIDTH 1
#define des_config_reg_mode_decryption_SHIFT 1
#define des_config_reg_mode_decryption_WIDTH 1
#define des_config_reg_mode_ofb_SHIFT 2
#define des_config_reg_mode_ofb_WIDTH 1
#define des_config_reg_mode_cbc_SHIFT 3
#define des_config_reg_mode_cbc_WIDTH 1
#define des_config_reg_kl_select_SHIFT 4
#define des_config_reg_kl_select_WIDTH 1
#define des_config_reg_residual_bytes_SHIFT 5
#define des_config_reg_residual_bytes_WIDTH 3
#define des_config_reg_counter_cycles_SHIFT 8
#define des_config_reg_counter_cycles_WIDTH 8
#define des_config_reg_alt_key_SHIFT 16
#define des_config_reg_alt_key_WIDTH 3
#define des_config_reg_status_cpu_keyopt3_flag_SHIFT 28
#define des_config_reg_status_cpu_keyopt3_flag_WIDTH 1
#define des_config_reg_status_kl_keyopt3_flag_SHIFT 29
#define des_config_reg_status_kl_keyopt3_flag_WIDTH 1
#define des_config_reg_status_keyopt3_flag_SHIFT 30
#define des_config_reg_status_keyopt3_flag_WIDTH 1
#define des_config_reg_done_SHIFT 31
#define des_config_reg_done_WIDTH 1

 mode_triple_des:1, /*[0:0]  */
 mode_decryption:1, /*[1:1]  */
 mode_ofb:1, /*[2:2]  */
 mode_cbc:1, /*[3:3]  */
 kl_select:1, /*[4:4] ,NO_MEM */
 residual_bytes:3, /*[7:5] ,NO_MEM */
 counter_cycles:8, /*[15:8] ,NO_MEM */
 alt_key:3, /*[18:16] ,NO_MEM */
 hole0:9,
 status_cpu_keyopt3_flag:1, /*[28:28] ,NO_MEM */
 status_kl_keyopt3_flag:1, /*[29:29] ,NO_MEM */
 status_keyopt3_flag:1, /*[30:30] ,NO_MEM */
 done:1; /*[31:31] ,RO */
 } bits;

 uint32_t value;
};

struct xpu_cipher_des {
 uint32_t des_key_1[2]; /* +0x00000000 [63:0] */
 uint32_t des_key_2[2]; /* +0x00000008 [63:0] */
 uint32_t des_key_3[2]; /* +0x00000010 [63:0] */
 uint32_t des_iv[2]; /* +0x00000018 [63:0] */
 union des_config_regReg des_config_reg; /* +0x00000020  */
};
