/* autogenerated with parsecfg: do not edit. */

union cipher_rst_regReg {
 struct { uint32_t

 /* sorting 4 */
#define cipher_rst_reg_des_rst_SHIFT 0
#define cipher_rst_reg_des_rst_WIDTH 1
#define cipher_rst_reg_aes_rst_SHIFT 1
#define cipher_rst_reg_aes_rst_WIDTH 1
#define cipher_rst_reg_rc4_rst_SHIFT 2
#define cipher_rst_reg_rc4_rst_WIDTH 1
#define cipher_rst_reg_sha_rst_SHIFT 3
#define cipher_rst_reg_sha_rst_WIDTH 1

 des_rst:1, /*[0:0]  */
 aes_rst:1, /*[1:1]  */
 rc4_rst:1, /*[2:2]  */
 sha_rst:1, /*[3:3]  */
 hole0:28;
 } bits;

 uint32_t value;
};

struct xpu_cipher_rst {
 union cipher_rst_regReg cipher_rst_reg; /* +0x00000000 ,NO_TEST */
};
