/* autogenerated with parsecfg: do not edit. */

union tm_valueReg {
 struct { uint32_t

 /* sorting 1 */
#define tm_value_timer_value_SHIFT 0
#define tm_value_timer_value_WIDTH 16

 timer_value:16, /*[15:0] ,NO_MEM */
 hole0:16;
 } bits;

 uint32_t value;
};

union tm_loadReg {
 struct { uint32_t

 /* sorting 1 */
#define tm_load_timer_load_SHIFT 0
#define tm_load_timer_load_WIDTH 16

 timer_load:16, /*[15:0]  */
 hole0:16;
 } bits;

 uint32_t value;
};

union tm_ctrlReg {
 struct { uint32_t

 /* sorting 1 */
#define tm_ctrl_timer_ctrl_SHIFT 0
#define tm_ctrl_timer_ctrl_WIDTH 8

 timer_ctrl:8, /*[7:0]  */
 hole0:24;
 } bits;

 uint32_t value;
};

struct xpu_timer {
 union tm_loadReg tm_load; /* +0x00000000  */
 union tm_valueReg tm_value; /* +0x00000004  */
 union tm_ctrlReg tm_ctrl; /* +0x00000008  */
};
