/* autogenerated with parsecfg: do not edit. */

/* gotta drop aes_light_mode@aes_config_reg: 0x8007fff0 [7:7] */
union aes_config_regReg {
 struct { uint32_t

 /* sorting 6 */
#define aes_config_reg_size_of_block_SHIFT 0
#define aes_config_reg_size_of_block_WIDTH 2
#define aes_config_reg_size_of_key_SHIFT 2
#define aes_config_reg_size_of_key_WIDTH 2
#define aes_config_reg_mode_SHIFT 4
#define aes_config_reg_mode_WIDTH 4
#define aes_config_reg_counter_cycles_SHIFT 8
#define aes_config_reg_counter_cycles_WIDTH 8
#define aes_config_reg_key_select_SHIFT 16
#define aes_config_reg_key_select_WIDTH 3
#define aes_config_reg_end_SHIFT 31
#define aes_config_reg_end_WIDTH 1

 size_of_block:2, /*[1:0]  */
 size_of_key:2, /*[3:2]  */
 mode:4, /*[7:4] ,NO_MEM */
 counter_cycles:8, /*[15:8] ,NO_MEM */
 key_select:3, /*[18:16]  */
 hole0:12,
 end:1; /*[31:31] ,RO */
 } bits;

 uint32_t value;
};

struct xpu_cipher_aes {
 uint32_t aes_key_0; /* +0x00000000 ,NO_MEM */
 uint32_t aes_key_1; /* +0x00000004 ,NO_MEM */
 uint32_t aes_key_2; /* +0x00000008 ,NO_MEM */
 uint32_t aes_key_3; /* +0x0000000c ,NO_MEM */
 uint32_t aes_key_4; /* +0x00000010 ,NO_MEM */
 uint32_t aes_key_5; /* +0x00000014 ,NO_MEM */
 uint32_t aes_key_6; /* +0x00000018 ,NO_MEM */
 uint32_t aes_key_7; /* +0x0000001c ,NO_MEM */
 union aes_config_regReg aes_config_reg; /* +0x00000020  */
 uint32_t aes_iv_0; /* +0x00000024  */
 uint32_t aes_iv_1; /* +0x00000028  */
 uint32_t aes_iv_2; /* +0x0000002c  */
 uint32_t aes_iv_3; /* +0x00000030  */
 uint32_t aes_iv_4; /* +0x00000034  */
 uint32_t aes_iv_5; /* +0x00000038  */
 uint32_t aes_iv_6; /* +0x0000003c  */
 uint32_t aes_iv_7; /* +0x00000040  */
};
